portal/models/intervention_strategies.py

* add extra check to see if due_date has passed when generating questionnaire status display text for patient dashboard

TN-289 Add extra checks to questionnaire dashboard display text

---

bin/deploy.sh

* Do not change branch unless specified (`-b "branch"` or `BRANCH="branch"`
* Reset local branch state to match remote branch when updating
* **NB** Discards ALL local changes
* Add logging/comments

Fixup deploy script

---

portal/static/js/main.js
portal/templates/profile/profile_base.html
portal/templates/profile/profile_macros.html

fix issue when user timezone is America/Chicago - not selected because it is missing from the timezone dropdown list
TODO - ask Paul about possible service for returning timezone list that frontend can make use of to dynamically populate the dropdown.

TN-504 missing timezone fix

---

portal/static/js/initialQueries.js

TN-534 terms scrolling follow up fixes

---

portal/templates/profile/profile_macros.html

add missing European timezones

TN-504 followup fix - add European timezones

---

portal/static/js/main.js

follow-up fix to this story:  
https://jira.movember.com/browse/TN-553
- add check for existence of notification before deleting it - covering use case where multiple windows containing notification are open

TN-398 - follow up fix to check for existing notification before

---

portal/static/js/accountCreation.js
portal/static/js/main.js

fix for: 
https://jira.movember.com/browse/TN-536
https://jira.movember.com/browse/TN-563
remove code that modify identifier of practice/region

TN-562 frontend dups region submission fix

---

portal/exercise_diet/static/css/styles.css
portal/exercise_diet/static/js/exercise_diet.js
portal/exercise_diet/templates/exercise_diet/base.html
portal/exercise_diet/templates/exercise_diet/exercise-diet_portal.html
portal/exercise_diet/views.py

TN-531: https://jira.movember.com/browse/TN-531
im ple ment e & d u n a thenticated p a ge
ad d responsiveness css

TN-531 exercise and diet unauthenticated page

---

portal/exercise_diet/static/css/styles.css
portal/exercise_diet/static/js/exercise_diet.js

made the fix to allow the display of recipe images transition more smoothly in exercise and diet

fix recipie image transition display issue in exercise and diet

---

portal/static/js/main.js

fix the issue in staging -
putting acceptance date back as one of the parameters for setting consent
fix references of this

TN-537 fix reference of self, move acceptance date back as param

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-571
I think we're planning to *not* merge until this has been reviewed on the eproms test system.

TN-571 Adds UW org to IRONMAN

---

portal/exercise_diet/static/css/styles.css

address https://jira.movember.com/browse/TN-560
fix the issue that close button in modal is not working in firefox

TN-560 exercise and diet close button in modal not working in firefox

---

portal/models/intervention_strategies.py

* Add translation call
* Fix typos/docstrings

i18n fixups

---

portal/static/js/initialQueries.js

finding this issue while testing:
correcting flaw in logic - initializing data for still needed data **prior** to setting incomplete fields information

fix data initailization in initial queries

---

bin/build-frontend-translations.sh
bin/deploy.sh

* Add new `node_env` virtual environment for NodeJS
* Created if not present
* Update frontend translations on deploy
* Transform PO file translations to JSON for i18next consumption
* Merge backend translations into frontend

Update frontend translations on deploy

---

portal/exercise_diet/templates/exercise_diet/exercise-diet_portal.html

follow-up fix to this story:  https://jira.movember.com/browse/TN-531
"start" button on unauthenticated e&d page should point to registration modal

TN-531 follow-up fix - point start buttons to registration model

---

portal/static/js/initialQueries.js

address issue mentioned by Diana in this story:
https://jira.movember.com/browse/TN-534
- add missing "," in element selector
- add detection for mouse movements when stopping scrolling animation in progress

TN-534 follow-up fix - add detection for mouse movement, fix missing ,

---

portal/exercise_diet/static/css/styles.css
portal/exercise_diet/static/js/exercise_diet.js
portal/exercise_diet/templates/exercise_diet/exercise-diet_portal.html
portal/exercise_diet/views.py
portal/gil/templates/gil/base.html

followup fixes to story: https://jira.movember.com/browse/TN-532
for exercise and diet page
fix menu item to point to portal exercise and diet page
add footer, was previously missing
fix video display - still having issue with the layout - may need to create story to address it

TN-532 exercise and diet video styling fixes, nav menu fix, footer fix

---

portal/exercise_diet/templates/exercise_diet/exercise-diet_portal.html
portal/static/js/gil.js

address this story: https://jira.movember.com/browse/TN-629
fix start button link to point to correct exercise and diet path

TN-629 fix exercise and diet links

---

portal/models/reporting.py

* added 'Partially Completed' to list of statuses _not_ to include in overdue questionnaire counts for site summary emails

TN-447 Filter 'Partially Completed' status from overdue counts

---

portal/migrations/versions/124cffb0fc6f_.py
portal/models/encounter.py
portal/models/role.py
portal/views/portal.py
portal/views/user.py
tests/test_access_on_verify.py
tests/test_access_url.py

Fix for TN-602, TN-603 and TN-604 - namely, full implementation for MUSIC's needs of an access_on_verify role.

Fix for TN-602, TN-603 and TN-604  implement access_on_verify role

---

portal/models/reporting.py
tests/test_reporting.py

* updated order of orgs in site summary email to alphabetical (by name)
* added unit test check for org order

TN-637 Sort orgs alphabetically in site summary email

---

portal/static/js/main.js

address TN-615:
allow study id and site id to be changed back to empty value:
https://jira.movember.com/browse/TN-615

TN-615 allow empty study id && site id

---

portal/gil/templates/gil/index.html

neglect to include new index js file in GIL index page

add js file to GIL index page

---

portal/eproms/views.py
portal/gil/views.py

* fixed `url_for` calls for research dashboard on home page load

Fixing research dashboard url calls

---

portal/models/reference.py
portal/system_uri.py
tests/test_reference.py

Minor bug in practitioner reference regex - need non characters in expected system URLs.

fix TN-660

---

portal/config/eproms/ScheduledJob.json
portal/config/gil/ScheduledJob.json
portal/config/model_persistence.py
portal/migrations/versions/84d8d857c2c6_.py
portal/tasks.py
tests/test_tou.py

To clear up confusion and simplify process when new ToUs are available, we'll now combine the `deactivate` and `notify` steps into a single scheduled job.
See the applicable list of scheduled jobs in https://jira.movember.com/browse/TN-535?focusedCommentId=134356&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-134356

Fix for TN-659, which should resolve parent issue TN-535

---

portal/gil/templates/gil/base.html
portal/templates/portal_wrapper.html

* fixed check/push for User Organizations in piwik data push (now use `user.organizations.first()`)

TN-631 Fix piwik user org push

---

portal/config/eproms/ScheduledJob.json
portal/config/gil/Notification.json
portal/config/gil/ScheduledJob.json
portal/models/tou.py
portal/tasks.py
tests/test_tou.py

One more round of task renaming and refactoring to fit the spec.  See description in https://jira.movember.com/browse/TN-659 (which I've been vetting w/ Diana as of late).

TN-659 take 3

---

portal/views/assessment_engine.py

* Wrap extensions in outer list if need be, for QNR answers

Wrap extensions in QNRs

---

portal/static/js/main.js

followup fix to this:
https://jira.movember.com/browse/TN-553
remove the 'Pending notification requiring your attention' message and just display the actual notification text

TN-553 follow up minor fixes to text display in banner

---

portal/views/assessment_engine.py

* Return lists of due assessments; partial and full

TN-617 Granular assessment status

---

portal/models/assessment_status.py
portal/tasks.py
portal/views/assessment_engine.py
portal/views/portal.py

Extended /api/patient/<patient_id>/assessment-status to return completed_ids and qb_name
Extended /communicate to take id in place of email for easier access

TN-696 improve assessment-status and communicate APIs for debugging

---

portal/models/fhir.py
portal/views/assessment_engine.py

* Add missing `resource` element for DSTU2 compliance, when `patch_dstu2=true` is passed to `/api/patient/assessment`

TN-685 Conditionally patch QNR Bundles

---

portal/models/assessment_status.py

Need to handle multiple indefinite QBs - overlooked till now as one needed to be `in-progress` with new RP3 indefinite onboard.

TN-440 Hotfix/handle multi indefs

---

portal/eproms/templates/eproms/base.html
portal/templates/layout.html

fix src attribute for promise polyfill external file

fix js attribute for promise polyfill file

---

portal/config/eproms/ScheduledJob.json
portal/config/gil/ScheduledJob.json
portal/models/auth.py
portal/tasks.py

New scheduled job (on both systems) to run a daily check for expired tokens (deletes stale) and nearly expired service tokens (emails sponsor).

TN-713 service token management

---

portal/models/reference.py
portal/views/organization.py
tests/test_organization.py
tests/test_reference.py

Address bugs in PR #1895 including handling hyphens in identifier values.

Finish TN-731

---

portal/static/js/initialQueries.js
portal/static/js/main.js
portal/templates/initial_queries.html
portal/templates/patient_profile_create.html
portal/templates/profile/patient_profile.html
portal/templates/profile/profile_base.html
portal/templates/staff_profile_create.html
portal/views/portal.py

followup clean-up of profile and initial queries js - 
remove references to global variables
retrieve config variables via ajax 
fix code indentations
fix references to this

clean up profile and initial queries js

---

portal/views/portal.py

followup fix from last refactoring PR -
simplify code in api/settings

refactor/simplify code in api/settings function

---

portal/models/assessment_status.py
portal/models/questionnaire_bank.py
tests/test_assessment_status.py
tests/test_questionnaire_bank.py

Correctly handle old resource protocols & indefinite questionnaires.

Fix TN-752 & TN-754

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-753

TN-753 TNGR Alfred organization addition

---

portal/config/eproms/Intervention.json

* Remove filler text on AE card, match AE card in TrueNTH USA

Remove AE filler text

---

portal/gil/templates/gil/base.html
portal/static/js/gil.js

address TN-751:
https://jira.movember.com/browse/TN-751
password reset modal not appearing in GIL page because flash message html code is missing from template

TN-751 add missing flash message html code in GIL

---

portal/static/js/gil.js

js error causing fix to fail for this story:
https://jira.movember.com/browse/TN-751

TN-751 follow up js error fix

---

portal/config/eproms/Organization.json

@ivan-c  Mo wants the orgs that we recently merged into master to go live on prod by mid this week (before next Monday's update). I asked them to look into the future a bit to include as many other orgs as possible with this update, thus this PR.

tn-762 2 new ironman orgs

---

portal/config/eproms/AppText.json
portal/config/eproms/site_persistence_file.json
portal/models/app_text.py
portal/models/message.py
portal/models/organization.py
portal/views/portal.py
portal/views/user.py
tests/test_organization.py

Adding new API endpoint for service token access - will enable MUSIC (and others) to trigger email invitation to user.
NB - expected we'll go through rounds of debugging yet.  Did shallow, initial testing via test-intervention code.

TN-568, TN-612 invite email api 

---

portal/config/eproms/Organization.json

* Keep v3 protocol change in `develop` branch

Use IRONMAN v2 protocol on prod

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-811

TN-811 ePROMs - IRONMAN Duke to v3 protocol

---

portal/templates/flask_user/register.html

hiding fb UI on registration page

hotfix - hide fb UI on registration page

---

tests/test_questionnaire_bank.py

Test fix for: Remove outer "questionnaire" wrap as it's breaking MUSIC's parser.

Fix test broken in PR #1964

---

portal/models/communication.py
portal/static/js/main.js
portal/templates/profile/profile_macros.html

followup fixes to TN-609
https://jira.movember.com/browse/TN-609
- fix typo
- fix button display issue in reminder email

TN-609 fix typo and button issue in email

---

portal/models/communication.py

per convo with justin, remove the last change relating to class="btn" to ae_link

TN-609 remove class btn from ae_link

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-883 ePROMs - org protocol v3 changes for late March release (late-breaking)

TN-883-IRONMAN-orgs-v3

---

docker/docker-compose.yaml

* Use YAML anchors to move common service elements to base service

Refactor docker-compose YAML

---

portal/config/config.py

* Read mail configuration from environment variables, if set ([see flask-mail config](https://flask-mail.readthedocs.io/en/latest/#configuring-flask-mail))

Set mail config from environment variables

---

docker/docker-compose.yaml
tox.ini

* Fix port YAML syntax
* Pin version of docker-compose used during artifact-building, testing ([fixes part of above issues](https://github.com/docker/compose/pull/5291))

Fix docker-compose YAML

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-941
https://jira.movember.com/browse/TN-942

TN-941-TN-942-IRONMAN-UofM-V3

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-941 ePROMs - org changes for 6th April 2018 (IRONMAN v3, etc)
https://jira.movember.com/browse/TN-950 IRONMAN remove es_ES from USA

TN-941-remove-es_ES-from-usa

---

portal/models/intervention_strategies.py

needed when persistence for a strategy changes (which I ran into on my local eproms build).

AccessStrategy was missing the update_from pattern

---

portal/config/eproms/Intervention.json
portal/config/gil/Intervention.json
portal/models/intervention.py

Part of the PSA Tracker stories - need an intervention to work with for starters.

https://jira.movember.com/browse/TN-935 Add PSA Tracker intervention

---

portal/eproms/templates/eproms/portal.html
portal/gil/templates/gil/portal.html
portal/models/user.py
portal/static/js/main.js
portal/templates/portal_wrapper.html
portal/templates/profile/profile_macros.html
tests/__init__.py
tests/test_user.py

fix registration status display on profile page
add check for registration status on whether to display reset password UI
remove unused/unnecessary code

TN-944 fix registration status display on UI

---

.travis.yml
portal/config/config.py
tox.ini

* Expose LR config variables
* Remove default `SECRET_KEY`
* NB: existing checkouts that do not have `SECRET_KEY` will error until set
* Cleanup config vars

Expose config vars as environment variables

---

.gitignore
bin/deploy-docker.sh
docker/default.env
docker/docker-compose.yaml
docker/portal.env.default

* Do not mount `instance/` as volume into container
* Fix DB backup

Docker prod fixups

---

portal/config/eproms/Organization.json

[See](https://jira.movember.com/browse/TN-965)

TN-965 Update BC Cancer Agency to IRONMAN v3

---

bin/deploy-docker.sh
docs/source/docker.rst
portal/config/config.py

* Fix docker DB backup
* Add docs on bootstrapping an admin account

Docker docs

---

portal/static/js/psaTracker.js

as per feedback from justin (note, rotating 180 degrees = 270 degrees in a 3d perspective)

TN-581 followup fix

---

portal/models/user.py
portal/views/auth.py
portal/views/user.py

Few bugs fixed:
1. include email on redirect to user.register, so it's correctly pre populated
2. exclude ALL the special roles when promoting the account.

TN-979 take 3

---

portal/static/js/i18next-config.js
portal/static/js/main.js

fix default locale selection for i18next
linting some JS issues (e.g. unnecessary comma, etc., single quotes)
move document ready block to bottom
for this release

TN-983 fix locale selection for i18next config

---

portal/static/js/main.js
portal/templates/patients_by_org.html
portal/templates/staff_by_org.html

fix translation issue for side pagination text on patient/staff list
bug fix - remove extraneous declaration of self variable

fix pagination side info translation issue in patients/staff list

---

portal/static/js/admin.js
portal/static/js/i18next-config.js

add i18next tag to one untagged text
add checks before setting session storage var for source data

add one more missing i18next tag, add checks before setting session var

---

portal/templates/initial_queries_macros.html

as per https://jira.movember.com/browse/TN-981

TN-981 update acknowledgment verbiage for music

---

portal/templates/initial_queries_macros.html

https://jira.movember.com/browse/TN-981
made verbiage change at the wrong place in the last PR
@ivan-c Ivan FYI

music terms verbiage fix

---

portal/static/js/main.js

- bug fix to not use subject's locale for current user's

frontend translation followup fix

---

portal/static/js/main.js

fixed undefined js error raised when choosing an org.

fix self reference error

---

portal/views/staff.py

https://jira.movember.com/browse/TN-1009

TN-1009 Fix typo - 'locale_code', not 'local_code'

---

portal/models/communication_request.py
portal/models/questionnaire_bank.py

see https://jira.movember.com/browse/TN-1031 for details.  in local debugging, this looks to resolve the issue.

TN-1031 sort in-progress qbs

---

portal/views/organization.py
tests/__init__.py
tests/test_organization.py
tests/test_reference.py

As a workaround to PUT /api/demographics, this PR enables POSTing additional orgs on user.

TN-1027 org post

---

portal/models/user.py
portal/views/patient.py
tests/test_patient.py

Added workaround POST for users needing to update a patient's deceased status, whom can't PUT to /api/demographics

TN-1040 Feature/deceased api

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-1021
@pbugni  following earlier org additions/mods, I'm having children inherit protocol, but neither language nor timezone (since we're not clear that those are inherited across all functionality)

TN-1021-IRONMAN-orgs-QUT

---

portal/static/js/main.js

https://jira.movember.com/browse/TN-1025 biopsy date display issue for musica patients
https://jira.movember.com/browse/TN-1035 pagination text fixes for email log and patient report tables
add time interval between initializing sections (dealing with number of ajax calls handled by the browser)

TN-1025 & TN-1035 fixes

---

portal/config/eproms/Organization.json

* Temporarily add Spanish as a language to Baylor and UCSD
* **Revert before finalizing RC**

Add Spanish ePROMs orgs for testing

---

portal/config/eproms/AppText.json

* Use approved ePROMs email for reminder (from patient profile page)

Fix Reminder Email

---

portal/config/eproms/Organization.json

Reverts uwcirg/true_nth_usa_portal#2098
**Only merge immediately before RC finalization**

Revert "Add Spanish ePROMs orgs for testing"

---

portal/static/js/admin.js
portal/templates/patients_by_org.html
portal/templates/staff_by_org.html

address this story:  https://jira.movember.com/browse/TN-1134

TN-1134 fix frontend translation issues in patients/staff list table

---

portal/static/js/initialQueries.js
portal/static/js/profile.js
portal/templates/initial_queries_macros.html
portal/templates/profile/profile_macros.html

- add translation fixes to tables in profile
- fix display and un-complicate event logics in clinical questions section

TN-1108 refinements

---

portal/templates/challenge_identity.html

address TN-1132:
https://jira.movember.com/browse/TN-1132

TN-1132 add translation tags for validation error messages on challenge

---

portal/static/js/initialQueries.js
portal/static/js/main.js
portal/static/js/profile.js
portal/templates/initial_queries.html

- remove unused argument from getRoles method, remove unused method in main.js
- move document ready block from initial queries template to js file

TN-1108 initial queries refinements

---

portal/templates/flask_user/login_or_register.html
portal/templates/flask_user/register.html
portal/views/portal.py

* Tag error messages
* Move identity challenge to [guard](https://en.wikipedia.org/wiki/Guard_(computer_science)) [clause](https://refactoring.guru/replace-nested-conditional-with-guard-clauses)

TN-1132 & TN-1130 i18n error messages

---

portal/models/reporting.py

* `force_locale()` when generating report HTML

TN-1127 Fix Site Summary i18n

---

portal/config/config.py
portal/factories/app.py
portal/logs.py

* Expose email settings to SMTPHandler
* Override `SMTPHandler` as `SSLSMTPHandler`
* Allow SSL connection
* More straightforward initialization

Expose email settings to error email logging

---

portal/models/i18n.py

* Rewrite string extraction for easy extension
* Extract organization names for translation

TN-1133 Extract DB Content - Organization names

---

portal/static/js/main.js
portal/static/js/profile.js
portal/templates/profile/profile_macros.html

TN-1107:  https://jira.movember.com/browse/TN-1107

TN-1107 disable send email button(s) for not email-ready users

---

portal/factories/app.py
portal/views/patch_flask_user.py

Customize flask-user forgot_password function to replace messaging as requested.

TN-1030, TN-1161 Update password reset messaging

---

portal/config/config.py

* Remove default error email address
* Logging workaround until underlying issue fixed

TN-1190 Remove default error email

---

portal/templates/profile/profile_macros.html

address TN-1202 https://jira.movember.com/browse/TN-1202  feedback from diana
fix css class placement on element - wrong placement was hiding the entire cell.

TN-1202 consent list display fix

---

portal/eproms/templates/eproms/base.html
portal/static/js/main.js
portal/templates/layout.html

address TN-1198 https://jira.movember.com/browse/TN-1198
fix untranslated copyright text before authentication

TN-1198 copyright translation fix

---

portal/config/eproms/Organization.json

Reverts uwcirg/true_nth_usa_portal#2128
*Do not merge until before RC finalization*

Revert "Re-add Spanish ePROMs orgs for testing"

---

portal/templates/flask_user/reset_password.html

add missing translation tags to password reset template

add translation tags to reset password error/info messages

---

portal/models/i18n.py
portal/models/questionnaire_bank.py
tests/test_questionnaire_bank.py

@ivan-c this should resolve #TN-1176 (sorry for the 3 PRs, that started when working on the front end w/ Amy...)  I rebased the other two into here for one final PR.

TN-1176 qb display name

---

portal/dict_tools.py
tests/test_dict_tools.py

- added tests for dict_tools.py

TN-1163 Added new tests for dict_tools.py

---

portal/models/intervention_strategies.py
portal/models/tou.py
portal/views/portal.py
portal/views/user.py
tests/test_assessment_status.py
tests/test_coredata.py
tests/test_intervention.py
tests/test_organization.py
tests/test_procedure.py
tests/test_questionnaire_bank.py

* Run 2to3 [`set_literal` ruleset](https://docs.python.org/2/library/2to3.html#2to3fixer-set_literal)

Fixup 2to3 set_literal

---

portal/config/model_persistence.py
portal/models/app_text.py
portal/models/fhir.py
portal/models/intervention_strategies.py
portal/views/demographics.py
portal/views/organization.py
portal/views/practitioner.py

* Run 2to3 [`except` ruleset](https://docs.python.org/2/library/2to3.html#2to3fixer-except)

Fixup 2to3 exceptions

---

docs/source/conf.py
portal/dict_tools.py
portal/models/address.py
portal/models/app_text.py
portal/models/assessment_status.py
portal/models/coredata.py
portal/models/extension.py
portal/models/fhir.py
portal/models/i18n.py
portal/models/organization.py
portal/models/telecom.py
portal/models/user_document.py
portal/views/assessment_engine.py
portal/views/auth.py
portal/views/organization.py
portal/views/patient.py
tests/test_audit.py
tests/test_i18n.py
tests/test_organization.py
tests/test_telecom.py
tests/test_user.py
tests/test_user_document.py

* Run 2to3 [`metaclass` ruleset](https://docs.python.org/2/library/2to3.html#2to3fixer-metaclass)
* Run 2to3 [`ws_comma` ruleset](https://docs.python.org/2/library/2to3.html#2to3fixer-ws_comma)
* Run 2to3 [`paren` ruleset](https://docs.python.org/2/library/2to3.html#2to3fixer-paren)
* Run 2to3 [`funcattrs` ruleset](https://docs.python.org/2/library/2to3.html#2to3fixer-funcattrs)

Misc 2to3 fixers

---

portal/static/js/psaTracker.js

date/time interval needs to account for re-calculated max-date.

TN-932 minor bug fix

---

portal/models/i18n.py
portal/views/patients.py

* Explicitly add assessment status strings for extraction
* Add translation call to assessment status in `/patients` list
* Minor code cleanup

TN-1210 Fix assessment status i18n

---

portal/static/js/psaTracker.js
portal/templates/psa_tracker.html

fix y-scale based on highest result.
add loading indicator when saving result (as there is a delay)

TN-932 fix Y-axis to scale based on highest result, add loading

---

portal/models/i18n.py
portal/models/questionnaire_bank.py

* Add `classification_types_enum` to manual string extraction

TN-1210 Patient list "Visit" column i18n

---

portal/config/eproms/CommunicationRequest.json

@pbugni  before you merge... noting that we should really go ahead and add all these at this point:
9 | 12 | 15 | 18 | 21 | 24 | 30 | 36
... per https://docs.google.com/spreadsheets/d/1oJ8HKfMHOdXkSshjRlr8lFXxT4aUHX5ntxnKMgf50wE/edit#gid=1339608238
And, that as it stands this will make this file quite verbose...
Are you adding QB's for the above at this point?

TN-1243 Adding CommunicationRequest records for IRONMAN 9 mo assessment

---

portal/views/clinical.py
portal/views/patient.py
requirements.txt

* Fix errors in swagger spec surfaced in newer version of module

Fix swagger docs for update

---

portal/static/js/admin.js

- allow user with admin role in patients list to have access to create account button

in patients list - allow user with admin role to create account

---

portal/static/js/clientIntervention.js
portal/templates/client_edit.html

fix runtime error encountered when deleting a client application on client application edit page - removing inline script as it was invoked before Jquery is loaded

fix clients application edit page js runtime error

---

portal/static/js/psaTracker.js

followup fixes to my last PR:
found that y axis labels were not displayed correctly, made fix for that, also linting/simply code

psa tracker follow y axis label rendering fix

---

portal/static/js/psaTracker.js

remove unnecessary cast from loop
@ivan-c Ivan, thank you for catching that.

remove unnecessary cast

---

portal/static/js/profile.js

found this issue when testing - excessive calls to check consent status
remove extra call to check consent status in consent modal code and streamline the code

ui consent modal code fix

---

README.rst
tests/__init__.py
tox.ini

* Use `py.test` to run all tests
* Use `pytest-cov` plugin for coverage calculation

Replace nosetest with py.test as test runner

---

portal/static/js/main.js

part of fixes for TN-1258:
https://jira.movember.com/browse/TN-1258
clear cached data when updating/deleting user roles

TN-1258 remove cached data when updating user roles

---

portal/factories/app.py
portal/logs.py

* Only use SSL when configured
* Default email settings use local email server, without SSL
* Mail relay requires SSL

TN-1264 Fix email config issue

---

portal/models/i18n.py

* Add browser fallback for locale configuration
* If no explicit locale preferred (set in /profile)
* If not logged in

TN-1201 Respect browser locale preferences

---

portal/config/eproms/QuestionnaireBank.json

https://jira.movember.com/browse/TN-1266

TN-1266 IRONMAN 12 month QB fixes order

---

portal/config/eproms/AccessStrategy.json

PSA Strategy now:
if (TNG Patients AND localized PCa AND Tx Started) OR (TNG Patients AND w/o positive PCa dx)

Corrected PSA strategy as per TN-1262

---

portal/static/js/profile.js
portal/templates/profile/profile_macros.html

follow issues when testing: https://jira.movember.com/browse/TN-1265
fix display of messages when user changes the email
put code back for disabling send email button when user isn't email ready - accidentally removed from last PR.
linting code

Email invite button followup fixes

---

portal/static/js/profile.js
portal/templates/profile/profile_macros.html

https://jira.movember.com/browse/TN-1239
followup fix to account for consent with status of deleted in history

Tn-1239 Consent History Modal followup fix

---

README.rst

Update readme to include add_user

---

portal/models/questionnaire_bank.py

Discovered when importing the altered order of the annual QB - now correctly removing conflicting rows before integrity error is raised.

TN-1276 Correctly handle changing the order of preexisting qbq's

---

portal/static/js/main.js
portal/static/js/profile.js

address 404 JS error generated when submitting duplicating withdrawn consent request via UI (as probably when user clicking on the radio button multiple times)

withdraw consent 404 js error fix

---

portal/models/assessment_status.py
portal/views/assessment_engine.py
tests/test_assessment_status.py
tests/test_questionnaire_bank.py

Sloppy check for presence of iteration failed for iteration ZERO.

TN-1286 Hotfix/recurring in process qbs

---

bin/deploy.sh

* Create default `venv/` virtual environment on first deploy if not present

Create venv on first deploy

---

portal/config/gil/Organization.json

including this in next regular schedule TN USA prod release is soon enough

TN-1287 add MUSIC orgs "wave 2"

---

.travis.yml
setup.cfg
tox.ini

* Use single `py.test` command for py2/3 unit tests
* Update py.test defaults
* Verbose
* Color logging, no progress

Cleanup test invocation

---

setup.cfg
setup.py

* Move more `setup.py` sections to `setup.cfg` ([including versioning logic](https://github.com/pypa/setuptools/pull/1150#issuecomment-330719468))
* Fix identation

Cleanup setup.py

---

portal/static/js/profile.js

https://jira.movember.com/browse/TN-1309
-  use acceptance_date for display signed date of consent
- remove the sorting code as the API already sorted the items
- use recorded by information to list last updated user and date

TN-1309 UI consent diplay changes based on API

---

portal/config/eproms/Intervention.json

per feedback from https://jira.movember.com/browse/TN-60
fix verbiage for Symptom Tracker and PSA Tracker tiles.

TN-60 fix descriptions for Symptom Tracker and PSA Tracker tiles for

---

portal/static/js/profile.js

noticing this issue when testing on ipad: event fired on each touch - made fix so it will only fire on change (keyboard key enter).

bug fix - fix mobile event listener

---

portal/static/js/admin.js

found this issue while testing - filtering by text in input raised JS runtime error
Fix by initializing filtering event after table configuration has done (e.g. get table preferences, etc)

patients filtering bug fix

---

portal/static/js/ajaxWorker.js
portal/static/js/main.js
portal/static/js/profile.js
portal/static/js/utility.js

issues seen in **IE** when testing - stale demo data displayed after updating, portal wrapper not displaying menu - as evident when issues are gone upon opening developer tool (which prevents caching of data)
Fixes are - 
make sure ajax calls are made with no caching parameter
add call to Vue nextTick helper function to ensure callback is executed after the next DOM update cycle

IE UI caching issue fixes

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-1312

TN-1312 Adds IRONMAN org Juravinski

---

portal/migrations/versions/b4dcf331317e_.py
portal/migrations/versions/ed70c144ae46_.py
portal/models/assessment_status.py
portal/models/user.py
portal/views/clinical.py

Now using the user_observation status to determine if a user has PCa_localized.

TN-1269 Feature/pca localized 4 assessment status

---

portal/static/js/ajaxWorker.js
portal/static/js/main.js
portal/static/js/profile.js
portal/static/js/utility.js

Followup fixes to PR:  https://github.com/uwcirg/true_nth_usa_portal/pull/2403
set the HTTP response headers to disallow caching
address 400 errors from retrieving optional core data for user

followup fixes to PR #2401 set response header for no caching

---

portal/exercise_diet/static/css/styles.css

followup styling fixes to this story:
https://jira.movember.com/browse/TN-1328
adjust main content padding
fix image styling in mobile view

TN-1328 styling followup fixes

---

portal/static/css/orgTreeView.css
portal/static/js/orgTreeView.js

address this story:  https://jira.movember.com/browse/TN-1324
add link to view JSON for each org

TN-1324 add link to view json for each org

---

portal/models/user.py
portal/type_tools.py
portal/views/assessment_engine.py
portal/views/notification.py
portal/views/patients.py
portal/views/portal.py
portal/views/practitioner.py
portal/views/scheduled_job.py
portal/views/user.py

Cleaning up old work, found in branch feature/deactivate-staff-account 
NB - that branch included work to move the admin views to their own branch, but too many changes have happened since - we'll redo that when necessary.

refactor check_int to common module

---

portal/static/js/profile.js
portal/templates/profile/profile_macros.html

saw this issue while testing this story:  https://jira.movember.com/browse/TN-1348
- add loading indicator when pressing send email button in patient profile - especially for the case when error has occurred as there would be a longer delay when request is re-trying.

TN-1234 add indicator after pressiong sending invite email button in

---

portal/exercise_diet/views.py
portal/views/portal.py

* Move JSON decoding to single location
* Use builtin JSON methods

Fixup Liferay URL generation;JSON decoding

---

bin/docker-login.sh
bin/docker-push.sh

* Handle docker.io image repository specially
* Remove old conditional code

Docker-push fixup

---

portal/config/gil/Organization.json

Request from Stephanie Ferrante

Fixes a mis-named MUSIC org

---

.travis.yml
bin/docker-push.sh
docker/docker-compose.yaml
docs/source/docker.rst

* Switch from Artifactory to Docker Hub/Cloud
* Update default image name

Update default docker image repository

---

portal/views/portal.py

address: https://jira.movember.com/browse/TN-1389
fix blank due date in manually triggered reminder email

TN-1389 fix due date in manually triggered reminder email

---

tests/test_recur.py

Simple cherry-pick of fix already applied to develop
```git cherry-pick d44a935a07d8026733b90f15c22bcb1823d29dd3```

Patch failing tests in master.

---

portal/config/config.py
portal/static/js/sessionMonitor.js
portal/templates/portal_wrapper.html
portal/views/auth.py
portal/views/portal.py
portal/views/truenth.py
tests/test_timeout.py

See details in document https://docs.google.com/document/d/1LAXMyS0M4ttlArIhPQc6fVuB3oXN_XAI0HqCsSa2VdE/edit#
@achen2401 I think (given the complexity of http cookies) we might want to set `data-cookie-timeout` to the template variable `{{ expires_in }}` in `portal_wrapper.html` ??

TN-662 refactor inactivity timeout

---

portal/factories/app.py
portal/sql_logging.py

Same LOG_SQL config var controls this option - but now includes time to run queries and uses cleaner interface.

Enhance SQL logging including time to run queries

---

portal/views/user.py
tests/test_user.py

addressing TN 1418: https://jira.movember.com/browse/TN-1418
fix unique email API check to ignore case
*think* this is a right fix, but feedback on this is appreciated

TN-1418 fix unique email check to ignore case

---

portal/config/gil/site_persistence_file.json

for https://jira.movember.com/browse/TN-1252
As per sprint discussion, hide feature for deactivating patient account from this coming release.

TN-1252 remove config for deactivating patient for TruenthUSA

---

manage.py

Stumbled on this problem debugging another.  Adding case insensitive search in the manage.py CLI commands

Case insensitive search for emails from manage.py CLI

---

portal/templates/flask_user/register.html

This reverts commit feecc8e8135da16d2b8d45001e4bc807197c5446.
Don't merge until just before RC finalization

Disable FB Registration on prod

---

instance/application.cfg.default
portal/config/config.py
portal/models/user.py
portal/views/auth.py
portal/views/extend_flask_user.py
tests/test_auth.py

These changes add lockout variables (i.e. lockout period and # of failed attempts) to config to make them easier to change/update.
I also updated the names of a few variables to make the logic easier to follow (I confused myself).

Add lockout variables to config

---

portal/templates/initial_queries_macros.html

* [Strip leading whitespace](http://jinja.pocoo.org/docs/dev/templates/#whitespace-control)
* Causing issue in back-translation workflow
* Remove line break

TN-1473 Fix translation whitespace

---

portal/eproms/static/js/websiteConsentScript.js
portal/static/js/initialQueries.js
portal/static/js/main.js
portal/static/js/profile.js

followup fix to this story:  https://jira.movember.com/browse/TN-1447
fix broken initial queries work flow for MUSIC after UI refactor

TN-1447 fix music initial queries flow

---

README.rst
portal/config/config.py
portal/tasks.py
portal/views/portal.py

The big celery tasks that loop over all necessary patients have been refactored to a classic producer / consumer model, to massively shorten the time to wait when shutting down celery, and create a more efficient asynchronous system where multiple workers can in parallel work on a number of tasks at a time.

Refactor long running celery tasks

---

portal/config/config.py
portal/gil/templates/gil/macros.html
portal/static/js/main.js
portal/templates/flask_user/_macros.html
portal/views/portal.py

* Move copyright year to config value
* Use placeholder in translations

TN-1445 Update Copyright; add config

---

portal/templates/profile/profile_macros.html

address: https://jira.movember.com/browse/TN-1313
followup verbiage fix

TN-1313 followup verbiage fix

---

portal/static/js/main.js

frontend fix related to this story:
https://jira.movember.com/browse/TN-1418
- display appropriate message if unique email API check returned server error - and stop proceeding with email update

TN-1418 frontend error display fix when check unique API check failed

---

portal/templates/profile/profile_macros.html

followup fix to this story: https://jira.movember.com/browse/TN-1313
- use double quotes to enclose text - remove slashes

TN-1313 verbiage fix - use double quotes

---

portal/templates/admin/staff_by_org.html

https://jira.movember.com/browse/TN-1253
allow reactivation of staff account on staffs list

TN-1253 allow reactivation of staff account

---

portal/static/js/main.js
portal/static/js/profile.js
portal/views/user.py

manual entry questionnaire entry date - frontend fix 
use - GMT noon date/time + user(subject) timezone for checking questionnaire window
format is fixed to be in "YYYY-MM-DDTHH:MM:SSZ" format

manual entry questionnaire date front end fix

---

docs/source/index.rst
docs/source/testing.rst

Adding this documentation to share with Warren and others.

Add testing page to documentation, including special views

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-1522

TN-1522 ironman v3 2018-09

---

portal/static/js/main.js

https://jira.movember.com/browse/TN-1445
bug fix related to setting copyright text by user locale, I neglect to think this through but I think this should fix the issue.
- locale is prematurely set to sessionStorage value (the value is set to that before authentication - which is incorrect)
- fix to set text after configuration callback
@ivan-c Ivan, please feel free to fix anything I change that you think is incorrect.

TN-1445 copyright locale text fix

---

portal/config/eproms/AppText.json

https://jira.movember.com/browse/TN-1484
add missing . to the title text

TN-1484 title text fix

---

docker/docker-compose.prod.yaml

* Increase from 1 to 8 ([recommended 2x number of CPUs](http://docs.gunicorn.org/en/stable/settings.html#workers))

Set number of gunicorn workers in prod

---

portal/config/eproms/site_persistence_file.json
portal/templates/profile/profile_macros.html

found when testing this story:  https://jira.movember.com/browse/TN-1498
- add config defaults related to MedidataRave Integration in eproms config json file

TN-1498 add MedidataRave config var to eproms config json

---

docker/Dockerfile
docker/docker-compose.yaml
manage.py
portal/config/config.py

Not certain this is perfect, or where to best set variables such as PERSISTENCE_EXCLUSIONS_DIR.

TN-1251 writable tmp dir for exclusions via docker

---

portal/static/js/initialQueries.js

fix issues found when testing MUSIC patient initial queries issue:
- display appropriate error on submission for acceptance on next
- do not display modal reminder for checking terms checkbox for acceptance on next

initial queries error display fix

---

docker/Dockerfile
docker/docker-compose.yaml
portal/config/config.py

* Consolidate folder operations in Dockerfile
* Sort `ENV` lines for consistency
* Add docker volume for user uploads

TN-1560 Store user documents on docker volume

---

portal/static/js/main.js

Logging data being sent for frontend ajax requests - making it easier for debugging

Fe error data logging

---

portal/config/eproms/QuestionnaireBank.json

RELATED TO https://github.com/uwcirg/true_nth_usa_portal/pull/2663/files

TN-1490 IRONMAN ALL RECURRING OVERDUE EARLIER

---

portal/static/js/initialQueries.js

followup fix for initial queries - remove check for organization id as a user may not be affiliated with one yet

remove errorneous check

---

portal/migrations/versions/883fd1095361_.py

messy problems from altering query data mid loop - capture details needing attention in query loop, then execute in a separate loop.

TN-1601 patch broken migration

---

docker/docker-compose.yaml
portal/config/config.py
portal/config/eproms/site_persistence_file.json

* Allow configuration of `MEDIDATA_RAVE_ORG` by env var
* Remove site-persistence default
* Rearrange config/env vars

Expose Medidata configuration

---

portal/static/js/CookieMonster.js

Address part of this story:
https://jira.movember.com/browse/TN-1602
modal not appearing after resetting password
- remove global modal selectors from cookie checking js

TN-1602 fix modal not appearing issue after resetting password

---

portal/views/portal.py

* Fix HTTP scheme to match what's actually supported by current flask config

Dynamically set Swagger scheme from flask configuration

---

portal/celery_worker.py

Untested. Having trouble starting celery beat. It just hangs. I've had this problem before; I don't think it's due to my changes.

Ensure scheduled jobs have the appropriate scheduled_task decorator

---

portal/celery_worker.py

Reverts uwcirg/true_nth_usa_portal#2764
Somehow was preventing Scheduled Jobs from being added to celery beat

Revert "Ensure scheduled jobs have the appropriate scheduled_task decorator"

---

portal/config/gil/AccessStrategy.json

https://jira.movember.com/projects/TN/issues/TN-1632

TN-1632 USA PSA Tracker for patients only

---

portal/static/js/utility.js

story: https://jira.movember.com/browse/TN-1234
add timezone info to date/time in system outage message display

TN-1234 add timezone info to system outage info

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-1734

tn-1734-ironman-org-protocols

---

portal/models/qb_status.py
portal/views/reporting.py
tests/__init__.py
tests/test_assessment_status.py
tests/test_reporting.py

API specialized for MVP, now includes `csv` format option.

TN-1617 qb status API

---

portal/models/user.py
portal/views/portal.py

Sanely handle bogus dates.  Now treated like any /challenge mismatch, user gets 3 tries to get it right.

TN-1684 handle bogus dates in /challenge

---

portal/config/gil/Organization.json

https://jira.movember.com/browse/TN-1744

TN-1744 music-org-name

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-1737

TN-1737-IRONMAN-South-Africa-Orgs

---

portal/templates/profile/profile_macros.html

https://jira.movember.com/browse/TN-1756
Add African/Jo timezone

TN-1756 add African/Jo timezone

---

portal/views/reporting.py
tests/test_questionnaire_bank.py
tests/test_reporting.py

now staff can only view patients for which a like consent is in place.  tests included.

TN-1752 protect /api/report/questionnaire_status from unauthorized views

---

bin/build-frontend-translations.sh
bin/gulp-wrapper.sh
tox.ini

* Standardize on `gulp-wrapper.sh` to run gulp i18n tasks with `node_env`
* Installs necessary virtual environments if not present

TN-1762 Refactor front-end wrappers

---

portal/static/js/coredata.js
portal/templates/coredata.html
portal/views/portal.py

address https://jira.movember.com/browse/TN-1760
in coredata JS
- remove global functions - use methods of object instead
- add error message display
- provide default footer, retrieve GIL footer based on configuration

TN-1760 fix TODO - refactor coredata JS file

---

debian/rules
setup.cfg

* Add translation files to `portal` `package_data`
* Workaround oddity with `root_path`

Fixup docker i18n issues

---

setup.cfg

* Correct generated files list (to add to `portal` python module)

Fixup docker front-end file generation

---

docker/portal.env.default
portal/config/eproms/site_persistence_file.json
portal/config/gil/site_persistence_file.json
portal/models/questionnaire.py
portal/templates/research.html
portal/views/assessment_engine.py
portal/views/portal.py

* Remove old email configs
* `MAIL_SENDER_DEFAULT` dynamically generated now
* Remove old assessment engine configs (replaced with Questionnaire resource stubs)

Cleanup project configuration

---

portal/models/communication.py
portal/models/coredata.py
portal/models/questionnaire_bank.py
portal/models/reporting.py
portal/models/user.py
portal/models/user_consent.py
portal/views/patients.py
portal/views/portal.py
portal/views/reporting.py
portal/views/staff.py
portal/views/user.py
tests/__init__.py
tests/test_assessment_status.py
tests/test_audit.py
tests/test_consent.py
tests/test_coredata.py
tests/test_demographics.py
tests/test_intervention.py
tests/test_organization.py
tests/test_qb_timeline.py
tests/test_questionnaire_bank.py
tests/test_reporting.py
tests/test_tou.py
tests/test_user.py

Use common query function `active_patients` in view code.

TN-1788 active patient query refactor

---

portal/static/js/src/accountCreation.js
portal/static/js/src/profile.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/profile/profile_macros.html

Followup fixes/bug fixes when testing this story:  https://jira.movember.com/browse/TN-1769
- add setting property to account creation object for use internally (as setting is referenced multiple times)
- fixed typo that prevented sorting of option list in alphabetical order for the state select element (i.e. as seen in selecting state in patient's organization in Truenth USA)
- add missing email log to staff profile page to allow displaying of emails sent to staff account
- update email log after sending invite/reminder emails in profile page
- fix toggle behavior of accordion element in Communication section - show/hide content when clicking on label
- fix accordion element styling

TN-1769 followup fixes

---

portal/config/eproms/Organization.json

site not yet recruiting, can go live w/ upcoming release

TN-1806 IRONMAN org (Tygerberg) fix MR org ID

---

portal/static/less/eproms.less
portal/templates/admin/patients_by_org.html

followup UI fixes based on Diana's feedback:
https://jira.movember.com/browse/TN-1802
Change text and Fix button position

TN-1802 followup UI fixes per feedback

---

portal/templates/flask_user/emails/eproms_password_changed_message.html

fixes exception seen when attempting to send password reset email

len() not available in templates - use correct jinja syntax.

---

requirements.txt

Reverts #2913 
* Pin flask-dance version until oauthlib version upgraded
* flask-dance references new method
See
```
Exception on /facebook/authorized [GET]
File "/srv/www/demo.us.truenth.org/portal/env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
File "/srv/www/demo.us.truenth.org/portal/env/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
File "/srv/www/demo.us.truenth.org/portal/env/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
File "/srv/www/demo.us.truenth.org/portal/env/local/lib/python2.7/site-packages/flask/app.py", line 1813, in …
```

Revert flask-dance upgrade; pin version

---

portal/static/js/src/accountCreation.js
portal/static/js/src/mixins/CurrentUser.js

restore the ability of admin user to create ironman patient when MedidataRave configuration is set (i.e. production)

allow admin staff to create ironman patient - for testing purpose

---

portal/templates/flask_user/emails/eproms_password_changed_message.txt

This time, tested on user with a single org.

TN-1830 password changed template overlooked in joined query

---

portal/static/js/src/admin.js
portal/static/js/src/mixins/CurrentUser.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/admin/admin_base.html
portal/templates/admin/patients_by_org.html
portal/templates/admin/staff_by_org.html
portal/views/patients.py
portal/views/staff.py

https://jira.movember.com/browse/TN-1586
adding UI checkbox to allow admin user to toggle inclusion of test accounts
- UI accessible only to Admin staff only
- test accounts are excluded by default and will be included only requested (via post)
- styling fixes
- refactor admin JS code to allow role based events
@pbugni Paul, it will be great if you can review the changes  (especially the backend ones) I had made

TN-1586 allow admin staff to toggle the inclusion of test accounts in

---

debian/control
docker/Dockerfile.build
requirements.txt

* Use pre-buildt binaries when possible
* Add notes about binary wheels

Cleanup build dependencies

---

portal/models/identifier.py
portal/models/user.py
portal/static/js/src/modules/Validator.js
portal/static/js/src/profile.js
portal/templates/profile/patient_profile_create.html
portal/templates/profile/profile_macros.html
portal/views/identifier.py
portal/views/patient.py
tests/test_identifier.py

Don't merge yet - pending @achen2401 sub-task TN-1853

TN-1613 Enforce unique user_identifiers on restricted systems.

---

portal/static/js/flask_user/register.js

address duplicate posts initial on registration page:
hitting enter key will create duplicate post calls due to extraneous code to trigger submit event.
Fix is to remove the culprit code

bugfix - address duplicate register posts from front end

---

portal/static/js/src/admin.js
portal/views/reporting.py

https://jira.movember.com/browse/TN-1754
Per specs for the story:
Fix export reporting title as specified in the story
Also hide hide export reporting UI element if no relevant configuration found (e.g. config variable of status)

TN-1754 fix reporting title per specs

---

portal/migrations/versions/55469bdd181f_.py

The run time is down to about 30 seconds.

TN-1824 migration to patch incorrect QB (wrong RP) on several QNRs.

---

portal/migrations/versions/55469bdd181f_.py

Same migration as PR #2983 , but the audit comment now includes the visit_name for the affected QNR/QB.

Add visit name to audit log

---

portal/static/js/src/modules/OrgTool.js

add more details/context to error generated when making ajax call to initializing organizations in the UI.

add more information to error generated in org UI ajax call

---

portal/static/js/src/coredata.js
portal/static/js/src/modules/Procedures.js
portal/templates/coredata.html

https://jira.movember.com/browse/TN-1835
Display error message on UI when failing to save/update treatment for a user
Fixes include:
- adding error message display
- disabling continued button until treatment update has been completed via ajax

TN-1878 display error message when failing to update treatment/procedure

---

portal/static/js/flask_user/base.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/challenge_identity.html
portal/templates/flask_user/register.html

Server errors reported when performing multiple clicks on the submission button during registration or identity challenge, as reported in this story:  
https://jira.movember.com/browse/TN-1883
Fixes include:
Displaying spinner loading indicator and hiding submission button when submission button is clicked
Adding styling for the new spinner loader icon and containing element

TN-1883 add UI changes to prevent multiple clicks of submission button

---

debian/changelog
debian/control
debian/default
debian/postinst
docker/Dockerfile
docker/Dockerfile.build

* Move writable file location configs to package defaults
* Remove unnecessary env vars
* Use [standard `GUNICORN_CMD_ARGS`](http://docs.gunicorn.org/en/stable/settings.html) for gunicorn options

Debian-ize configuration

---

portal/migrations/versions/a1de3ab4d050_.py
portal/models/identifier.py
portal/models/questionnaire_response.py
portal/views/assessment_engine.py
tests/test_assessment_engine.py

Post review, this should now be ready to merge.
@ivan-c you should probably also check out the comments in TN-1882 detailing the issues found from the respective production dbs.

TN-1839 enforce unique constraint on QNR.identifier

---

portal/exercise_diet/templates/exercise_diet/base.html

https://jira.movember.com/browse/TN-1895

TN-1895 fix exercise and diet style reference

---

portal/static/js/src/components/PsaTracker.vue

Fix build error raised when parsing PsaTracker.vue - may have been stemming from malformed html - I am not quite sure why it wasn't caught before - perhaps the latest version of vue-loader package added the check for that.

fix build error in PsaTracker vue

---

portal/config/config.py

Retire old stg-lr7 domain in favor of cms-stage

Update default (development) Liferay config values

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-1913

TN-1913-2orgsV3AndSimplify

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-1886

TN-1886 new IRONMAN org Epworth

---

requirements.txt

* Cleanup [Flask-User fork](https://github.com/uwcirg/Flask-User)
* Remove unused branches
* Add git tags for each minor version added to fork
* Add [git tag to fork](https://github.com/uwcirg/Flask-User/releases/tag/0.6.21.2), reference in requirements.txt

Fixup flask-user fork version

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-1935

TN-1935-IRONMAN-TEST-ORG

---

portal/config/config.py
portal/migrations/versions/1d84237ed07c_.py
portal/models/intervention.py
portal/models/user.py
portal/static/js/src/admin.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/admin/patients_by_org.html
portal/views/patients.py
tests/test_portal.py

Rework `/patients` logic, for more predictable consumption by admins, intervention_staff and staff.
See #TN-1835 for details.

TN-1835 RCT patients

---

docker/Dockerfile
docker/Dockerfile.build
docker/docker-compose.flower.yaml
docker/docker-compose.prod.yaml
docker/docker-compose.yaml
docs/source/docker.rst

* Squelch superfluous messages from package manager (`apt-get`)
* Removed noise from build logs
* Errors still written to stderr
* Refactor service base for new docker-compose file format
* Update docs

Docker cleanup

---

portal/migrations/versions/0b4e7a8a7e64_.py
portal/models/qb_status.py
portal/models/user_consent.py
portal/views/patient.py
tests/test_qb_timeline.py

Changes to QB timeline / status processing, so patients have history up to the point of withdrawal.

TN-1871 include QB's pre subject withdrawal

---

portal/models/auth.py

include the intervention name (if applicable) in subject and body of expired token email.
example before:
```
subj: 'WARNING: Service Token Expiration'
body: 'The service token in use at TrueNTH expires 2019-04-24 21:09:14.747944.  Please renew at <SERVER>/client/NREmkT2Ww9x8WofWni8Sd9jF5IHFu9UYK55L9o1u'
```
example after:
```
subj: 'WARNING: Service Token Expiration for music (MUSIC Integration)'
body: 'The service token in use at TrueNTH for music (MUSIC Integration) expires 2019-04-24 21:09:14.747944.  Please renew at <SERVER>/client/NREmkT2Ww9x8WofWni8Sd9jF5IHFu9UYK55L9o1u'
```

enhance expired token email

---

portal/views/patients.py

The restriction for users having a consent with an organization only makes sense if the /patients list is filtered by org, which happens always for staff, and anytime intervention_staff or admins apply the UI filter by org.

TN-1835 hotfix

---

portal/static/js/src/components/PsaTracker.vue

https://jira.movember.com/browse/TN-1945
minor followup fix:  use the correct property of data object to display tooltip label

TN-1914 followup fix - fix tooltip label

---

portal/static/js/src/admin.js
portal/static/js/src/mixins/CurrentUser.js

https://jira.movember.com/browse/TN-1961
hide account creation button on patients list from MUSIC staff
will **not** hide the button for staff that has top org affiliation other than MUSIC

TN-1961 hide account creation button from MUSIC staff on patients' list

---

portal/config/eproms/Coding.json
portal/config/eproms/Organization.json

Poorly names branch, no longer a WIP

TN-1948 test ironman org i18n & add es_ES

---

portal/static/js/src/profile.js

temporarily comments out code that disables manual entry button on profile page

hotfix - commented out code to disable manual entry button on profile

---

portal/migrations/versions/1e09e871fb65_.py
portal/static/js/src/modules/OrgTool.js
portal/static/less/portal.less

https://jira.movember.com/browse/TN-408
Correctly display legend containing parent organization name when a parent organization do not have any affiliated child clinics.
Fixes include:
- adding legend display for parent organization that fits the above criterion
- simplify code that filters the relevant orgs
- styling fixes

TN-498 correctly display parent organization for organizations that do

---

portal/models/i18n.py
portal/models/i18n_utils.py
tox.ini

* Fix upload condition check
* Fix unicode upload issues

i18n utility fixups

---

portal/translations/af_ZA/LC_MESSAGES/flask_user.po
portal/translations/af_ZA/LC_MESSAGES/messages.po
portal/translations/de_CH/LC_MESSAGES/flask_user.po
portal/translations/de_CH/LC_MESSAGES/messages.po
portal/translations/es_ES/LC_MESSAGES/flask_user.po
portal/translations/es_ES/LC_MESSAGES/messages.po
portal/translations/es_US/LC_MESSAGES/flask_user.po
portal/translations/es_US/LC_MESSAGES/messages.po
portal/translations/fr_CA/LC_MESSAGES/flask_user.po
portal/translations/fr_CA/LC_MESSAGES/messages.po
portal/translations/pt_BR/LC_MESSAGES/flask_user.po
portal/translations/pt_BR/LC_MESSAGES/messages.po
portal/translations/sv_SE/LC_MESSAGES/flask_user.po
portal/translations/sv_SE/LC_MESSAGES/messages.po
portal/translations/xh_ZA/LC_MESSAGES/flask_user.po
portal/translations/xh_ZA/LC_MESSAGES/messages.po
portal/translations/zu_ZA/LC_MESSAGES/flask_user.po
portal/translations/zu_ZA/LC_MESSAGES/messages.po

* Update back-end translations from Smartling
* Add flask-user translations

TN-1973 Update Backend Translations

---

portal/models/questionnaire_response.py
portal/views/assessment_engine.py
tests/test_assessment_engine.py

TN-1969 is now in question, at least by me.  I'd like to see this change go out regardless.

TN-1976 maintain QNR questionnaire bank association on state change

---

portal/config/gil/Organization.json

per convo related to this story:
https://jira.movember.com/browse/TN-408
Fix organization JSON for UCSF Urologic Surgical Oncology Clinic so it is the child clinic of UCSF.

TN-408 fix organization JSON for UCSF urologic clinic

---

portal/config/eproms/CommunicationRequest.json
portal/config/eproms/QuestionnaireBank.json

https://jira.movember.com/browse/TN-1979 impl
https://jira.movember.com/browse/TN-1953 spike

WIP TN-1953-IRONMAN-widen-QB-windows

---

portal/migrations/versions/687dd856dc5e_.py

Need to reset cache for all IRONMAN patients following change of assessment window (see PR #3108)

TN-1979 Migration for expanding assessment window

---

portal/models/questionnaire.py
portal/models/questionnaire_response.py
portal/views/assessment_engine.py

* Add convenience property (`QuestionnaireResponse.document_answered`) for getting QNRs with dynamically populated answers
* Lookup option text from Questionnaire resource referenced in QuestionnaireResponse, if available
* Override default behavior until migration removes superfluous `valueString` answers added by AE

TN-1946 Dynamically lookup option text from Questionnaires

---

.travis.yml

* Remove references to removed debian package upload functionality

Remove debian deployment from TravisCI

---

bin/deploy.sh
portal/models/i18n_utils.py

* Add flask-user translation files to PO to MO compilation step

TN-1934 Compile flask-user translation files

---

portal/views/staff.py

address https://jira.movember.com/browse/TN-1426
remove admin users from staff list of staff/staff-admin users
changes include:
simply code to exclude admin users in query
remove previous code that did not exclude admin users as it should

TN-1426 remove users with admin role from staff list

---

portal/static/js/src/CookieMonster.js
portal/static/js/src/profile.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/profile/profile_macros.html
portal/templates/require_cookies.html

found issues related to loading indicator when testing: https://jira.movember.com/browse/TN-1426
address issue that loading indicator not showing when send registration email to staff button is pressed, i.e. limit the scope of loading indicator css class selector in CookieMonster object
fix styling and positioning of loading indicator so pressing of send registration email won't result in jumpiness of UI

send email loading indicator styling fixes

---

portal/static/less/eproms.less

https://jira.movember.com/browse/TN-2020
Fix styling of account creation button in Portuguese

TN-2020 portuguese UI fix - fix create account button styling

---

portal/eproms/templates/eproms/contact.html
portal/static/js/src/profile.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/challenge_identity.html

minor styling fixes made while testing other stories:
move inline styling from identity challenge form to less file
add loading indicator for loading audit log in profile
contact form responsive styling fix

minor styling fixes - move inline styling in challenge form to less

---

portal/migrations/versions/4ea2b79957f3_.py

Use alembic op.bind mechanism to create session and make more robust (any piece of the new identifier or links may be missing, adding only what is needed).

TN-1941 2nd pass at adding IRONMAN 3 digit identifiers

---

portal/translations/af_ZA/LC_MESSAGES/messages.po
portal/translations/de_CH/LC_MESSAGES/messages.po
portal/translations/es_ES/LC_MESSAGES/messages.po
portal/translations/es_US/LC_MESSAGES/messages.po
portal/translations/fr_CA/LC_MESSAGES/messages.po
portal/translations/pt_BR/LC_MESSAGES/messages.po
portal/translations/sv_SE/LC_MESSAGES/messages.po
portal/translations/xh_ZA/LC_MESSAGES/messages.po
portal/translations/zu_ZA/LC_MESSAGES/messages.po

* Update backend translations (`flask download-translations`)
* Add new email footers
* Remove translations for strings that are no longer present

TN-2022 Update Backend Translations

---

portal/i18next_gulpfile.js

address issue where frontend tranlation json files were not being converted to pot files
- fix is to wait for i18next scanner to finish extracting json text before conversion.  
@ivan-c ivan, let me know if you see issue, it worked in my instance after I made the fixes.

i18next script bug fix

---

portal/migrations/versions/ee3a3a61484f_.py

3rd try, simple SQL expression.  What could be easier?

flush qb_timeline cache for all suspended patients

---

portal/static/js/src/profile.js

Fix comment referencing medidata rave fields that require disabling.

fix comment for mr disable fields

---

portal/static/js/src/modules/Procedures.js
portal/templates/profile/profile_macros.html
portal/translations/af_ZA/LC_MESSAGES/frontend.po
portal/translations/af_ZA/LC_MESSAGES/messages.po
portal/translations/de_CH/LC_MESSAGES/frontend.po
portal/translations/de_CH/LC_MESSAGES/messages.po
portal/translations/es_ES/LC_MESSAGES/frontend.po
portal/translations/es_ES/LC_MESSAGES/messages.po
portal/translations/es_US/LC_MESSAGES/frontend.po
portal/translations/es_US/LC_MESSAGES/messages.po
portal/translations/fr_CA/LC_MESSAGES/frontend.po
portal/translations/fr_CA/LC_MESSAGES/messages.po
portal/translations/pt_BR/LC_MESSAGES/frontend.po
portal/translations/pt_BR/LC_MESSAGES/messages.po
portal/translations/sv_SE/LC_MESSAGES/frontend.po
portal/translations/sv_SE/LC_MESSAGES/messages.po
portal/translations/xh_ZA/LC_MESSAGES/frontend.po
portal/translations/xh_ZA/LC_MESSAGES/messages.po
portal/translations/zu_ZA/LC_MESSAGES/frontend.po
portal/translations/zu_ZA/LC_MESSAGES/messages.po

* Update back-end and front-end translations
* Fixup inconsistent substitutions
NB: string ordering is arbitrary; check overall line additions/deletions

TN-2022 Update translations

---

bin/backup-docker.sh
bin/deploy-docker.sh
bin/docker-build.sh

* Move pre-deploy backup to separate script
* Use system-wide `/var/opt/portal` directory for pre-deploy backups, if able

Stand-alone Backup Script

---

portal/static/js/src/admin.js

Part of fix for https://jira.movember.com/browse/TN-1807
Noting that ajax requests are still being sent for report status **even after** the export report popover has been closed.
Fix is to property store the timeout interval id for each ajax request and clear each when popover dialog is closed.

TN-1807 frontend export request cleanup fix

---

portal/config/eproms/Organization.json
tests/test_assessment_status.py

https://jira.movember.com/browse/TN-2071

TN-2071-New-IRONMAN-UK-org

---

portal/migrations/versions/458e56eedb92_.py

Confronts migration problems seen on truenth systems.

Make IRONMAN specific migration tolerant of non IRONMAN systems.

---

portal/celery_worker.py

* Restore original behavior before #3209

Hotfix scheduled job load

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2096

TN-2096 IRONMAN add Spain and Spanish org

---

portal/models/auth.py
portal/models/user.py
tests/test_user.py

Handle migration of auth_providers when merging accounts (temporary auth into invited user).

TN-2054 handle 3rd party auth_providers in user.merge_with()

---

portal/config/gil/Organization.json

https://jira.movember.com/browse/TN-2113

TN-2113-new-music-orgs

---

portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/profile/patient_profile.html

Finding this while testing:
In patient profile page, patient name title is cut off when name is long.  
Added styling fixes to address that.

profile patient name header styling fix

---

portal/views/auth.py

Attempt minor code change for google auth scopes as per warning message.

TN-2130 fix google auth

---

portal/config/gil/Organization.json

https://jira.movember.com/browse/TN-2166 2 new orgs alongside existing Johns Hopkins children

TN-2166-New-TN-USA-orgs

---

portal/static/less/eproms.less
portal/static/less/gil.less
portal/static/less/portal.less
portal/templates/flask_user/_macros.html
portal/templates/flask_user/login.html
portal/templates/flask_user/register.html
portal/templates/initial_queries.html
portal/templates/initial_queries_macros.html
portal/templates/profile/profile_macros.html

making styling fixes after testing in mobile devices:
minor responsive styling fixes, i.e. spacing/margin and font consistency, for the following pages:
registration/login 
initial queries
profile

responsive styling fixes

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2167

TN-2167-IRONMAN-orgs for OOB release 2019-08-02

---

portal/exercise_diet/static/css/styles.css
portal/exercise_diet/templates/exercise_diet/base.html

Per feedback from Rob:
Show the acknowledgement section on the Exercise and Diet pre-authenticated page as well.
https://jira.movember.com/browse/TN-2107
@mcjustin JUSTIN, FYI

TN-2107 show acknowledgement on pre-authenticated ED page

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2212

TN-2212-IRONMAN-add-3-orgs

---

portal/static/js/src/profile.js

https://jira.movember.com/browse/TN-2215
correctly display GMT date/time for entries in email log

TN-2215 fix display date/time for email log, in GMT

---

.travis.yml

* Also build docker images for branches prefixed with `test/`
* Move TravisCI defaults into appropriate job
* Update python version on TravisCI

Build docker images for more branches; cleanup CI

---

.gitlab-ci.yml

* update to version in debian stable

Update unit test python3 version

---

README.rst

* Update package names
* Update virtual environment setup example

Update docs for python3

---

portal/config/gil/Questionnaire.json
portal/static/js/src/modules/TnthAjax.js
portal/views/portal.py

NB - we're pushing the async behavior of /research into the next sprint (issue TN-2235)

TN-2199 add missing Questionnaires to /research exports

---

portal/exercise_diet/templates/exercise_diet/base.html
portal/gil/templates/gil/macros.html
portal/static/less/exerciseDiet.less
portal/static/less/gil.less

Address:
https://jira.movember.com/browse/TN-2219
https://jira.movember.com/browse/TN-2250
Both stories share the same stylesheet.  Changes included:
- remove redundant links from TruenthUSA footer; fix layout of the footer element, and elements in relation to it (e.g. Exercise Diet acknowledgement section)
- address truncated text issue in patient portal home page; add responsive fixes to the page

TruenthUSA footer & homepage layout styling updates

---

portal/gil/templates/gil/macros.html
portal/static/less/gil.less

per feedback for this story: https://jira.movember.com/browse/TN-2250
moving truenth logo to same row at bottom as the Movember logo per feedback

TN-2250 move logo to bottom to align with movember logo per feedback

---

manage.py
portal/models/user.py

Robust, careful process won't allow merge unless several criteria are met.  Asks admin user to verify each step of the process.

TN-2274 CLI to merge duplicate users as described in TN-2240

---

portal/gil/templates/gil/macros.html

fix typo per feedback for this:
https://jira.movember.com/browse/TN-2250

TN-2250 fix typo

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2275 This commit adds Yale University. 4 more orgs still to come

TN-2275-add-ironman-orgs

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2296

TN-2296-2-new-ironman-orgs

---

manage.py
portal/config/eproms/QuestionnaireBank.json
portal/config/gil/QuestionnaireBank.json
portal/migrations/versions/da6506c5899a_.py
portal/models/qb_status.py
portal/models/qb_timeline.py
portal/models/questionnaire_bank.py
portal/models/questionnaire_response.py
portal/models/reporting.py
portal/views/patient.py
tests/__init__.py
tests/test_assessment_engine.py
tests/test_qb_timeline.py
tests/test_questionnaire_bank.py

Add "none of the above" Questionnaire Bank, and extended classification enum with "other".
TN-2303 Prevent repeated QNR->QB lookup with marker for n/a.
TN-2304 Add indefinite to adherence report

TN-2193 indefinite QB in adherence report

---

.travis.yml

* Remove parallel job execution config
* Only attempt to create DB in jobs configured with postgres addon

Fixup TravisCI DB Errors

---

portal/config/eproms/Intervention.json

https://jira.movember.com/browse/TN-2251

TN-2251-eproms-analytics-intervention

---

portal/gil/static/js/lived_experience.js
portal/gil/templates/gil/lived-experience.html
portal/gil/templates/gil/lived_experience_base.html
portal/static/less/gil.less

https://jira.movember.com/browse/TN-2298
On LE main page:
hide home link using css
adjust button size for buttons at footer so they are equal in sizes

TN-2298 follow fixes

---

portal/static/js/src/components/PsaTracker.vue
portal/static/js/src/data/gil/PsaTrackerData.js
portal/static/less/psaTracker.less

Referencing https://jira.movember.com/browse/TN-2282
add login/register prompt in modal for PSA Tracker page per feedback

TN-2282 login verbiage update

---

portal/models/questionnaire_response.py
portal/views/assessment_engine.py
tests/test_assessment_engine.py

Report error w/ 400 status on authored validation exception.
Also, give 1 min buffer for external system clock drift

TN-2330 catch use of future dates in QNR submission

---

portal/models/user.py
portal/views/auth.py
portal/views/user.py

Modified audit for new account and registration to capture initial email settings.

TN-1469 Include initial email address in audit 

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2360

TN-2360-NewIronmanOrgsUK

---

portal/gil/templates/gil/what-is-prostate-cancer.html

https://jira.movember.com/browse/TN-2362

TN-2362-gil-minor-edit-movember-2019

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2380 Hospital Provincial de Castellón

TN-2380-add-ironman-org

---

portal/factories/app.py
requirements.txt
wsgi.py

Replacing deprecated code! mostly coming from werkzeug.contrib

Update deprecated werkzeug code

---

requirements.txt
tests/test_scheduled_job.py

will look at other places to see if deprecated code still exist

Update deprecated sqlalchemy code

---

portal/static/less/psaTracker.less
portal/templates/psa_tracker.html

update PsaTracker Footer as per:  https://jira.movember.com/browse/TN-2388

TN-2388 update footer for PSA Tracker

---

portal/config/eproms/Organization.json

TN-2411 https://jira.movember.com/browse/TN-2411

TN-2411-add-ironman-org

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2420

TN-2420-2NewIronmanOrgs

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2420

TN-2420-3rdof3NewIronmanOrgs

---

portal/migrations/script.py.mako
portal/migrations/versions/df233cc6fa8a_.py
portal/models/message.py

Also capturing exceptions when attempting email send, to include in audit row.

TN-2425 capture EmailMessage.recipient_id for pre-registered users.

---

manage.py
portal/usage_monitor.py
portal/views/truenth.py

Implement simple usage tracker to simplify checks since last call to /ping was recorded.

Seconds since last /ping

---

portal/config/eproms/CommunicationRequest.json
portal/config/eproms/Organization.json
portal/config/eproms/Questionnaire.json
portal/config/eproms/QuestionnaireBank.json
portal/config/eproms/ResearchProtocol.json
portal/models/organization.py
portal/models/reference.py

https://jira.movember.com/browse/TN-2407

WIP TN-2407-IRONMAN-V5-Add-Configs-RPs-QBs-etc

---

portal/migrations/versions/4737a563e3f9_.py

this broke on my system as well.  does this guard alter your expected migration?

guard against missing keys in migration

---

bin/deploy-docker.sh
portal/config/config.py
tests/test_deploy.sh

* Add inactivity check to deploy script by default
* Override with new force (`-f`) flag
* Allow configuration of `LOG_LEVEL` by environment variable

Deploy Script Activity Check

---

portal/cache.py
portal/config/config.py
portal/database.py
portal/factories/app.py
portal/models/app_text.py
portal/models/i18n.py
portal/models/qb_timeline.py
portal/models/questionnaire_bank.py
portal/models/user.py
portal/views/assessment_engine.py
portal/views/organization.py
portal/views/portal.py
tests/__init__.py
tests/test_questionnaire_bank.py

Profiling /patients, found some low hanging fruit to cache.  Took relatively low risk options only to avoid need to invalidate on data changes (i.e. organizations, questionnaire banks, research protocols)

leverage caching

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2462
May also need to delete org 21700 - TBD.  <= WE DID DECIDE TO DO THIS 2019-01-17

TN-2462-MoveRoyalBrisbaneToOtherParent

---

portal/translations/messages.pot

* Run `dc exec web flask extract-i18n` to extract portal strings to POT for translation
* Give up using links in POT files
* Workaround disutils exceptions by installing module system-wide:
`dc exec -u root web apt install python3-distutils`

Update Extracted Strings

---

portal/config/eproms/Organization.json

* TN-2462-MoveRoyalBrisbaneToOtherParent
https://jira.movember.com/browse/TN-2462
* TN-2462 - Removes org 21700
https://jira.movember.com/browse/TN-2462

TN-2462-MoveRoyalBrisbaneToOtherParent (#3623)

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2487

Add 3 IRONMAN orgs (Spain)

---

.gitlab-ci.yml
docker/docker-compose.yaml

* Add required password for postgres docker image

Configure Password for Dockerized Postgres

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2526

TN-2526-3-new-ironman-uk-orgs

---

portal/static/js/src/gil.js
portal/static/less/gil.less

https://jira.movember.com/browse/TN-2558
Address issue where side slide-in menu for Truenth USA site is not scrollable on mobile devices preventing user from selecting items that are hidden from view.
- Add CSS changes to allow side slide-in menu to be scrollable 
- Add JS code to prevent triggering of onclick event when menu it being scrolled

TN-2558 allow side menu to be scrollable on mobile device

---

portal/config/eproms/CommunicationRequest.json
portal/config/eproms/QuestionnaireBank.json

https://jira.movember.com/browse/TN-2556

TN-2556-v5-shift-WIP

---

portal/migrations/versions/f93d9608c372_.py

Should correct https://jira.movember.com/browse/TN-2594, but we still don't know "where they went"?
NB - this takes probably a good 10 mins to run, as it purges and updates QB data for > 1000 patients.

TN-2594 Migration to clean up missing 6 month QBs.

---

portal/models/qb_timeline.py

This isn't necessarily needed as a hotfix - as only test has this protocol on prod, but to test the hotfix on test, you'll need it!

Found another exception needed for v5 date changes.

---

portal/eproms/templates/eproms/resources.html
portal/eproms/views.py

address: https://jira.movember.com/browse/TN-2600
adding IRONMAN v5 training resource to the IRONMAN staff resources page (note, the pdf has been been uploaded to Liferay)

TN-2600 adding v5 training PDF to IRONMAN staff resources page

---

portal/static/js/src/modules/Global.js
portal/templates/portal_wrapper.html

address : https://jira.movember.com/browse/TN-2645
- frontend code change to check authentication method via which user is authenticated
- disabling UI elements, i.e. profile menu links and links with css class, 'portal-weak-auth-disabled', if user encounter indicates a "url_authenticated" auth method
**NOTE:** This is dependent on changes in this PR: #3693

URL-authenticated - disabling relevant frontend elements

---

portal/eproms/templates/eproms/base.html
portal/static/js/src/modules/Global.js
portal/views/auth.py

address https://jira.movember.com/browse/TN-2645
prompting url-authenticated user to login to continue when accessing protected link
waiting on Cam's feedback on verbiage, will likely have another PR related to this

TN-2645 add login confirmation when clicking on disabled link

---

portal/views/assessment_engine.py

https://jira.movember.com/browse/TN-2627 url_authenticated permit PUT patient/n/assessment

TN-2627 url_authenticated allow PUT ... assessment

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2666

TN-2666 IRONMAN first 2 orgs transitioned to v5

---

portal/templates/confirm_identity.html

per comment in this story: https://jira.movember.com/browse/TN-2628

update url-authenticated consent text

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2686

TN-2686 IRONMAN one org to v5

---

portal/config/eproms/Questionnaire.json

https://jira.movember.com/browse/TN-2650 . Same as existing qnrs in this file; will need other things added (eg Observations, SDC itemContext extension)

TN-2650-Adds-ironman_ss-qnr

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2696

TN-2696 IRONMAN orgs to v5 batch 3 (3 US orgs)

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2704

TN-2704 one ironman org to v5 (batch 4)

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2714

TN-2714-ironman-4-orgs-to-v5

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2710

TN-2710-ironman-2-new-orgs

---

portal/translations/messages.pot

* Call `flask extract-i18n` to update string template file

TN-2706 Update Source Translation Strings

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2729

TN-2729-1-IRONMAN-org-to-v5 (Yale)

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2741

TN-2741-ironman-v5-batch-8 2 orgs

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2754

TN-2754-Chesapeake-v3-retro-fix

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2750

TN-2750-v5-batch9

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2753

TN-2753-add-ironman-org-maccallum

---

portal/config/eproms/Questionnaire.json

https://jira.movember.com/browse/TN-2670 - removes two questions near the end; note that this results in the final question's index being decremented by 2.

TN-2670-ironman_ss-qnr-edit-2

---

portal/models/qb_status.py
portal/models/questionnaire_response.py

The indefinite case it special - we need to consider any work done on previous research protocols which may come from a different questionnaire bank.

TN-2747 completed or in-process indefinite overlooked on RP change

---

portal/config/eproms/ResearchStudy.json
portal/static/js/src/data/common/consts.js

per feedback on https://jira.movember.com/browse/TN-2634
update update sub-study title displayed in consent history table

TN-2634 update substudy name title

---

portal/static/js/src/profile.js

remove duplicate method defined:
see https://github.com/uwcirg/truenth-portal/blob/1f914396d3a9e8a812955c07f143015f5bbd8dde/portal/static/js/src/profile.js#L2488

remove duplicate method definition in profile JS

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2782

TN-2782-ironman-v5-migration-batch10

---

portal/eproms/templates/eproms/portal.html

This is the source of the problem Diana reported on https://mo-programs.slack.com/archives/G3Z4E7B55/p1602554301003800

Obsolete code fragment left behind caused stack

---

portal/config/eproms/Organization.json
portal/config/eproms/Questionnaire.json

https://jira.movember.com/browse/TN-2670

TN-2670 empro patient qnr: add observation coding

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2809

TN-2809-IRONMAN-v5-migration-11

---

portal/eproms/templates/eproms/resources.html
portal/eproms/views.py

Hotfix version of #3812
---
* TN-2813 address incorrect link urls on eproms staff resources page
* fix comment
Co-authored-by: Amy Chen <clone@cesium.cirg.washington.edu>

Bug fix for eproms staff resources page links

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2801

TN-2801 Add 2 new IRONMAN orgs (1st to use it_IT)

---

portal/eproms/templates/eproms/assessment_engine/ae_macros.html
portal/eproms_substudy_tailored_content/src/js/Base.js
portal/static/js/src/empro.js

Per convo with Paul,  frontend code changes are necessary in anticipation to the JSON format update for triggers API in this PR:  https://github.com/uwcirg/truenth-portal/pull/3814
- update frontend code that displays domain(s) based on triggers in the thank you modal on the patient home page
- update frontend code that displayed tailored domain content based on triggers

update frontend code that reads response data from triggers API

---

portal/config/eproms/Organization.json

v5 batch 12: https://jira.movember.com/browse/TN-2828
New org: https://jira.movember.com/browse/TN-2820

TN-2828-TN-2820-org-changes

---

portal/config/eproms/Coding.json

* Add Italian language coding (already enabled on select orgs)

TN-2801 Add Italian language coding

---

portal/config/eproms/CommunicationRequest.json

https://jira.movember.com/browse/TN-2690

TN-2690-empro-patient-qnr-reminder-emails

---

portal/eproms_substudy_tailored_content/package-lock.json
portal/eproms_substudy_tailored_content/src/data/data.js
portal/eproms_substudy_tailored_content/src/js/Base.js
portal/eproms_substudy_tailored_content/src/js/Utility.js
portal/eproms_substudy_tailored_content/src/js/Video.js
portal/eproms_substudy_tailored_content/src/style/app.less

address https://jira.movember.com/browse/TN-2830
Updates to retrieval of resources and video content for sub-study tailored content
- update frontend code to retrieve sub-study tailored resources content by country code - noting that each content item is tagged with the country code
- update frontend code to accommodate retrieval of video content dynamically as some tailored content items shared the same video
- styling updates for resources section

Retrieve resources by country code for sub-study tailored content

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2833

TN-2833-ironman-v5-batch13

---

portal/eproms_substudy_tailored_content/src/components/DebugSection.vue
portal/eproms_substudy_tailored_content/src/data/data.js
portal/eproms_substudy_tailored_content/src/js/Base.js
portal/eproms_substudy_tailored_content/src/js/Utility.js
portal/eproms_substudy_tailored_content/src/style/app.less

Address link:
https://jira.movember.com/browse/TN-2815
- update code to accommodate additional tailored video content 
- update code to show/hide certain sections based on triggers
- minor styling updates
- add debugging code to test triggers

TN-2815 sub-study tailored content - finalized video tailored content

---

portal/eproms/templates/eproms/assessment_engine/ae_complete.html
portal/eproms/templates/eproms/assessment_engine/ae_due.html
portal/eproms/templates/eproms/assessment_engine/ae_indefinite_due.html
portal/eproms/templates/eproms/assessment_engine/ae_macros.html
portal/eproms/views.py
portal/models/qb_status.py
portal/models/research_study.py

```python
patient_research_study_status()
```
brings together business rules and complexity of checking if user is "ready" to do respective study work.
returns: ordered list of applicable research studies.  Each contains a dictionary with keys:
- research_study_id: integer value of research study
- ready: set True or False based on complex rules.  True means pending work user can immediately do
- errors: list of strings detailing anything preventing user from being "ready"

added function `patient_research_study_status()`

---

portal/eproms/templates/eproms/assessment_engine/ae_macros.html
portal/static/less/eproms.less

address https://jira.movember.com/browse/TN-2786
update text and layout of EMPRO patient home page based on here:  https://movember.app.box.com/s/hgor94odhfwfooib3bhfrtg0b2tgyh91

TN-2786 update substudy patient home page tiles text based on final prototype copy

---

portal/eproms_substudy_tailored_content/src/components/DomainSection.vue
portal/eproms_substudy_tailored_content/src/components/Error.vue
portal/eproms_substudy_tailored_content/src/data/data.js
portal/eproms_substudy_tailored_content/src/js/Base.js
portal/eproms_substudy_tailored_content/src/js/Utility.js
portal/eproms_substudy_tailored_content/src/js/Video.js
portal/eproms_substudy_tailored_content/src/style/app.less

Address: https://jira.movember.com/browse/TN-2811
Allow access to sub-study resources library content via self-managed landing page
- allow staff/clinician to access the page without querying for triggers
- dynamically populate the resources library page with resources and videos from all domain topics
- styling updates of the resources library page based on final design in Figma

Substudy tailored content -  resources library

---

docker/docker-compose.yaml
portal/config/config.py
portal/config/eproms/Questionnaire.json
portal/models/observation.py
portal/models/questionnaire_response.py
portal/tasks.py
portal/views/assessment_engine.py

TN-2781
* Integrate SDC at service level

TN-2781 Integrate SDC service

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2851

TN-2851 ironman v5 transitions - batch 14

---

portal/config/gil/Organization.json

https://jira.movember.com/browse/TN-2846

TN-2846 add music org/site

---

portal/eproms/templates/eproms/assessment_engine/ae_macros.html
portal/static/js/src/empro.js
portal/static/less/eproms.less

Address https://jira.movember.com/browse/TN-2644
Update displayed text in sub-study thank you modal based on latest web copy here: 
https://movember.app.box.com/s/0piyxgkynlyan6oa1weg39vpqtql1x5y  as per story

Update text in sub-study thank you modal based on final web copy

---

portal/config/eproms/Questionnaire.json
portal/config/eproms/QuestionnaireBank.json
portal/config/eproms/ResearchProtocol.json

Initial take at the RP, QB and Questionnaire needed for post-intervention.
The questionnaire doesn't yet have any of the question structure - @mcjustin is this something you'd be willing to fill in?

TN-2849 RP, QB and Questionnaire for post-intervention.

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2862

TN-2862 ironman v5 orgs batch15

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2832

TN-2832 ironman add Memphis VA

---

tox.ini

* Use [deprecated pip resolver](https://discuss.python.org/t/announcement-pip-20-2-release/4863)
* Add TODO

Revert to deprecated pip resolver

---

portal/config/eproms/ScheduledJob.json
portal/tasks.py
portal/trigger_states/empro_states.py

Add scheduled job to send staff trigger reminders.
Fix bug where email_message wasn't being persisted.

TN-2866 schedule trigger reminders

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2870

TN-2870 ironman v5 batch 16 - one org

---

portal/static/js/flask_user/urlAuthenticatedModal.js
portal/static/js/src/empro.js
portal/static/js/src/profile.js
portal/static/less/eproms.less
portal/templates/profile/profile_macros.html

Address https://jira.movember.com/browse/TN-2873, display email log for non-patient user
- Fix faulty logic that prevents displaying email log for a staff user
- bugfix for accessing sub-study longitudinal report link via url authentication
- styling updates

TN-2873 staff email log fix, url-authenticated longitudinal report link fix 

---

portal/static/js/src/CookieMonster.js

sub-task for : https://jira.movember.com/browse/TN-2577
When frontend is testing if cookies are enabled in a browser, add secure cookie attribute to test cookie so that it won't be rejected by the browser.

TN-2577 update frontend cookie testing code

---

portal/models/qb_timeline.py
portal/templates/admin/patients_substudy.html
portal/trigger_states/empro_states.py

per https://jira.movember.com/browse/TN-2771
Update column name and order for sub-study patient list.
Fix clinician action status from "due" to "required" as per specs.
See final specs here:  https://movember.app.box.com/s/fv78bk00lpru8scm99fex1ec09ocbtlv

TN-2771 update sub-study patient list column names and order

---

portal/templates/admin/admin_base.html
portal/templates/admin/patients_substudy.html

per feedback in the story: https://jira.movember.com/browse/TN-2771
Update sub-study text and study selector text as per updated specs.

TN-2771 fix sub-study text displays

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2889

TN-2889 v5 ironman migration batch 17

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2896

TN-2896-new-ironman-org-florida

---

portal/eproms/views.py
portal/models/coredata.py
portal/models/qb_status.py
portal/models/qb_timeline.py
portal/views/patients.py
tests/conftest.py
tests/test_intervention.py

return type from patient_research_study_status() changed so the results may reliably be indexed by research_study_id

fix return type from

---

portal/static/js/src/profile.js
portal/static/less/eproms.less
portal/templates/profile/profile_macros.html

Fixes based on feedback from this story:
https://jira.movember.com/browse/TN-2798
For EMPRO post intervention questionnaire UI:
- update section title
- update date field placeholder text
- specify GMT for the date/time updated for clarity

TN-2798 update text on post txt questionnaire UI per feedback

---

portal/static/js/src/profile.js
portal/static/less/eproms.less
portal/templates/admin/admin_base.html
portal/templates/admin/patients_substudy.html
portal/templates/profile/profile_macros.html
portal/trigger_states/empro_messages.py

https://jira.movember.com/browse/TN-2898
https://jira.movember.com/browse/TN-2835
EMPRO UI & email text updates
UI text updates include:
- EMPRO welcome email text in dropdown
- placeholder text for Post Intervention questionnaire date field
- Adherence report hover over text & icon updates
-  text updates in EMPRO longitudinal report section in profile
Email text update:
- triggered domain(s) displayed in the email (as per spec, domains delimited by comma and bolded)
also minor styling updates

Feature/empro UI email updates

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2908
(the "NewYork" is intentional here)

TN-2908-add-ironman-org NewYork-Presbyterian Brooklyn Methodist Hospital

---

tests/test_assessment_engine.py

presumably an old cut&paste error, found two tests duplicated.

removed two duplicated/identical tests

---

.gitlab-ci.yml
docker/docker-compose.yaml

* Use postgres 13 as default version in docker-compose and Gitlab CI

Update default postgresql version

---

portal/models/questionnaire_bank.py
portal/models/reporting.py
portal/models/research_study.py
portal/templates/admin/admin_base.html
portal/templates/admin/patients_substudy.html
portal/trigger_states/models.py

TN-2912: Specialized visit name for EMPRO: no baseline visible in reports, etc.  1 based month counts 1-12.
TN-2642: Specialized EMPRO adherence report as per issue, including clinician columns and removing consent date and entry method.

TN-2912, TN-2642 EMPRO visit name and adherence report

---

manage.py

corrected CLI `update_qnr_authored()` to work with single authored field and research_study IDs.

TN-2921 patch update_qnr_authored()

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2903

TN-2903-ironman-2-orgs-to-v5

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2915

TN-2915 IRONMAN add Nigeria and 4 sites there (en_GB only)

---

portal/trigger_states/empro_states.py

on discovery of a withdrawn EMPRO user, update the `action_state` to withdrawn as well, so the reports display the desired Clinician Status.

TN-2932 action_state should reflect 'withdrawn'

---

portal/eproms/templates/eproms/assessment_engine/ae_due.html
portal/eproms/templates/eproms/assessment_engine/ae_indefinite_due.html

per slack convo  https://cirg.slack.com/archives/C5MH9NVKQ/p1613093708018600
Fix "Completed Questionnaires" display text on patient home page

fix completed questionnaire display strings on patient home page

---

portal/config/eproms/site_persistence_file.json
portal/eproms/views.py

https://jira.movember.com/browse/TN-2913
Add EMPRO inquiry type and its associated contact email to Contact Page
Change includes:
Adding EMPRO contact via configuration variable (others come from contact emails retrieve via Organization json)

TN-2913 add EMPRO contact inquiry type to contact page

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2938

TN-2938 IRONMAN Migrate 2 orgs to V5 (batch 19)

---

portal/models/organization.py

Adding a redis lock around the OrgTree initializer eliminated the notorious and illusive mysterious situation where organizations in the tree would lose their parents.
During one of those rare windows when the symptom of this issue (would raise as `OrgTree.at_and_above_ids()` would find a node that had lost its parent) was reliably reproducible unless flask was run `--without-threads`, opted to try a redis lock around the initializer and found it was no longer reproducible.  The reproduction would happen when viewing /patients/substudy as a JS request starts a new thread that somehow exposed an internal shared resource that is apparently not thread safe.  Probably a SQLAlchemy pool or the like.
I should note we haven't seen this on a test or prod system, only in development (both …

Patch orgtree threading issue

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2949  i18n

TN-2949 ironman ottawa clinic add fr_CA option

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2961

TN-2961-ironman-2-new-orgs (v3 intentionally)

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2981

TN-2981 ironman-v5-3orgs brazilian

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-2999

TN-2999-IRONMAN-add-swedish-org

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-3000

TN-3000-ironman-2-orgs-to-v5

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-3011

TN-3011-one-ironman-org-to-v5

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-3010

TN-3010-ironman-2-new-orgs

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-3019

TN-3019 Add ironman org VA of Western New York Healthcare System

---

portal/config/eproms/Organization.json
portal/migrations/versions/49d13048e7a7_.py

* Remove Zulu language from South Africa region
* Use migration to cleanup DB

TN-2874 Remove Zulu language

---

portal/config/config.py
portal/models/login.py
portal/static/js/flask_user/2fa.js
portal/templates/flask_user/second_factor.html
portal/views/auth.py

User can now [resend validation code] from the 2FA verify form.
Manage complexity of changing passwords and 2FA integration by forcing a login with freshly changed password.

TN-3016, TN-3022 resend 2fa validation code

---

portal/eproms/templates/eproms/assessment_engine/ae_macros.html

https://jira.movember.com/browse/TN-3021
Update text presented in EMPRO thank you modal.

TN-3021 update text related to description for trigger domains

---

portal/config/eproms/Coding.json
portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-3023

TN-3023 enable norwegian (nb_NO). Add country and site orgs.

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-3034

TN-3034 Add site & country (Jamaica) to IRONMAN

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-3023

TN-3023 add Norwegian to test sites

---

portal/config/eproms/Coding.json
portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-3039

TN-3039 ironman i18n add Canadian English coding en_CA

---

bin/deploy-docker.sh

Switch default backup path to match CIRG backup circuit

TN-2992 Update default backup path

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-3041

TN-3041-add-ironman-org-umiss

---

portal/static/less/eproms.less

https://jira.movember.com/browse/TN-3038
Update action required link in the Clinician Action Status column in the Patient List to red as requested.

TN-3038 update link color for the clinician action status column

---

portal/models/login.py
portal/static/js/flask_user/2fa.js
portal/templates/flask_user/second_factor.html
portal/views/auth.py

address https://jira.movember.com/browse/TN-3036
Update 2FA UI text displays as per updated web copy
** these changes are needed for the upcoming release

TN-3036 2fa UI text updates

---

portal/templates/flask_user/second_factor.html

address: https://jira.movember.com/browse/TN-3050
as per email thread from Marie.

fix typo in 2FA template

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-3060

TN-3060 add ironman org William Jennings Bryan Dorn VAMC

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-3059

TN-3059-org-to-v5-epworth

---

portal/eproms/static/js/emproResources.js
portal/eproms/templates/eproms/empro_resources.html
portal/eproms/views.py
portal/static/less/eproms.less
portal/templates/portal_wrapper.html

Address: https://jira.movember.com/browse/TN-3061
EMPRO training material
changes include
- add new endpoint for accessing the EMPRO training material
- a new template for the training material content, which is fetched from LR

TN-3061 EMPRO training material

---

portal/models/login.py

https://jira.movember.com/browse/TN-3036 & https://jira.movember.com/browse/TN-3036

TN-3066-2FA-email-content-revision

---

portal/config/eproms/site_persistence_file.json

per https://jira.movember.com/browse/TN-3067

TN-3067 update empro contact email address

---

portal/eproms/static/js/emproResources.js
portal/eproms/templates/eproms/empro_resources.html
portal/static/less/eproms.less

address https://jira.movember.com/browse/TN-3073
update layout for the EMPRO training material page

TN-3073 EMPRO training material page layout updates

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-3076

TN-3076 First site to use EMPRO (Macquarie)

---

portal/config/eproms/Organization.json

Reverts uwcirg/truenth-portal#4142

Revert "TN-3076 First site to use EMPRO (Macquarie)"

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-3075

TN-3075-empro-first-org-macquarie

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-3043
No migration for existing users as there is no effect on what they'll see in content anywhere.

TN-3043-switch-canadian-sites-i18n-2

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-3081

TN-3081 EMPRO go live at MSK

---

portal/templates/admin/admin.html

https://jira.movember.com/browse/TN-3107
restore deactivation UI for non-patient account on admin page -  allowing a user with admin role to deactivate any non-patient account

TN-3107 restore deactivate UI for non-patient accounts on admin page

---

portal/models/questionnaire_response.py

log error but continue, when more than a single in-progress QNR is located.
@mcjustin I also verified with this in place:
- we will get (a lot) of error messages when this situation is present
- the staff user can view the respective QNR results from the patient's profile.

TN-3109 relax assertion for single in-process QNR

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-3093

TN-3093 empro enabled at cornell

---

portal/models/reporting.py

If the pre-started EMPRO user has a clinician, include in the adherence report.

TN-3101 include clinician even pre-started for EMPRO

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-3089

TN-3089 - EMPRO enabled for Cross Cancer Institute

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-3128

TN-3128 IRONMAN v5 1 org Guys

---

portal/date_tools.py
portal/models/qbd.py
portal/models/reporting.py

Look for the extension within QuestionnaireResponses defining the "actual" completion date, and if found, use in the adherence report in a new "oow_completion_date".

TN-3125 oow_completion_date in adherence report

---

portal/models/reporting.py
portal/trigger_states/models.py

Added a new column `intervention_questionnaire_completion_date` which will show the date-time of the clinician/staff filed intervention questionnaire, if one is found.
NB, this PR includes a significant refactor to internals for adherence report generation, to eliminate duplicate, fragile code and replace it with more maintainable generators and reusable functions.

TN-3169 EMPRO adherence new column for intervention response time

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/IRONN-79 . This is not the first site in Switzerland, and the languages are used at other Swiss sites.

IRONN-79 Add a new site in Switzerland

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/TN-3088 "EMPRO go live - (Eastern Health) Fri 12 Aug"

TN-3088 empro go-live Eastern Health

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/IRONN-88

IRONN-88 Morecambe Bay to v5

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/IRONN-96

IRONN-96 IRONMAN New Site Morehouse School of Medicine

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/IRONN-95

IRONN-95 Sligo University to v5

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/IRONN-98 .
Please include in this Friday's monthly release.

IRONN-98 Add country Barbados and a site therein

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/IRONN-92

IRONN-92 Add V3->V5 transition for Onkozentrum Zürich

---

requirements.txt

request a compatible version of `importlib-metadata`

Pin Importlib Version

---

portal/config/eproms/Organization.json

https://jira.movember.com/projects/IRONN/issues/IRONN-102

IRONN-102 3 VA orgs to v5

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/IRONN-103

IRONN-103 add Nairobi and site

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/IRONN-109 and  https://jira.movember.com/browse/IRONN-110

IRONN-109-IRONN-110-4-orgs-to-v5

---

portal/config/eproms/Organization.json

https://jira.movember.com/projects/IRONN/issues/IRONN-111

IRONN-111 add another Brazilian site

---

portal/static/js/src/profile.js
portal/static/less/eproms.less
portal/templates/profile/profile_macros.html

see https://jira.movember.com/browse/TN-3199
- remove delete icon button from PI on the assigned clinician list in patient profile (see screenshot):
- disabled clinicians selector element _while_ a selected clinician is being added/removed to ensure that data is updated before another selection occurs.

TN-3198 prevent PI from being removed from patient's assigned clinician list

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/IRONN-114
Add new IRONMAN site to TrueNTH (Steve Biko Academic Hospital) The 2nd site in South Africa.

IRONN-114 add org Steve Biko Academic Hospital

---

portal/models/questionnaire_bank.py

if subsequent global visit has become due after user started EMPRO work (and previously there wasn't a global completed within 4 weeks of EMPRO consent).
very isolated change - only impacts EMPRO trigger-date[1] calculations, and then only if all of the above criteria are met.
See comments in code.
[1] trigger-date: term for the initial start of the study, not related to an EMPRO "triggered status"

TN-3202 fix for complicated EMPRO trigger dates moving

---

portal/config/eproms/AppText.json

- Update EMPRO report content ID to match existing Liferay content ID

Update EMPRO report Liferay content ID

---

portal/static/less/eproms.less
portal/static/less/topnav.less
portal/templates/portal_wrapper.html
portal/templates/profile/profile_macros.html

https://jira.movember.com/browse/TN-3209
Fix display of post intervention questionnaire in profile page and user name in header.
- update css for displaying checkbox and text in the post intervention questionnaire UI
- add helper css classes and update css to responsively display portal wrapper content, including user name
Example screenshots after the fixes are applied:

TN-3209 profile display styling fixes

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/IRONN-139

IRONN-139 add Rosebank org

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/IRONN-141

Add org Groote Schuur Hospital, 1st site using zulu

---

manage.py

generate a summary report after running `preview-site-update` including changes in QNRs assigned to a QB and how many QBs are completed before and after the change.
see also conversation in PR #4279 
example summary from a preview-site-update run:
```
52 QuestionnaireResponses for all patients in organization 146180
Hospital Universitario Miguel Servet (Zaragoza)
Patients in organization: 5
Patients negatively affected by change: 5
Number of those QNRs assigned to a QB before RP change: 52
Number of those QNRs assigned to a QB after RP change: 38
Number of QuestionnaireBanks completed before RP change: 14
Number of QuestionnaireBanks completed after RP change: 0
```

add summary report to `preview-site-update`

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/IRONN-158

IRONN-158 add org University of Massachusetts Memorial Medical Center

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/IRONN-160

IRONN-160 add ironman org baptist

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/IRONN-164

IRONN-164 EMPRO for Southampton

---

portal/models/clinical_constants.py

Update broken codesystem URL to include FHIR version

Update broken codesystem URL

---

docker/docker-compose.prod.yaml

Add healthcheck to sdc service

TN-3232 Add healthcheck to sdc service

---

portal/migrations/versions/2f125954b69a_.py

use `pop()` rather than attempting to index a set (failed to look at

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/IRONN-185

IRONN-185 add alfred org for ironman

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/IRONN-186

IRONN-186 Add IRONMAN org Howard Univ

---

portal/models/login.py

previous design spread confusion and missed a call.

Move 2FA cookie check within `user_requires_2fa()`

---

portal/config/eproms/Organization.json

https://jira.movember.com/browse/IRONN-197

IRONN-197 Brooklyn on EMPRO

---

portal/models/qb_status.py

add guard and premature exit should adherence cache be working on timeline data purged in another thread.

threaded adherence cache production error

---

portal/views/assessment_engine.py

When a questionnaire response is UPDATED (via PUT from the assessment engine), make a note of the situation in the audit log, and log a warning as per TN-3184.
Example audit generated when testing:
```
410347 |     128 |       4032 | assessment     | 2023-08-28 23:15:56.849448 | 2
3.7.24.3.dev4+g5b2dcee5.d20161205 | updated QuestionnaireResponse 4175 for user
4032 completed 2023-01-08T20:00:00Z UNEXPECTED authored change; was previously 2
023-01-04T20:00:00Z
```

TN-3184, report any in-process QNRs attempting to change authored dates

---

bin/deploy-docker.sh

after the 2nd time of needing to look this up, figured it was worth documenting...

Add doc for `-f` (force) flag to deploy-docker.sh

---

portal/models/communication.py

part of https://movember.atlassian.net/browse/TN-3271
Add main study registry link as email variable that can be referenced in the Liferay email items.
Note: once this is approved and merged, I will add reference to this variable in relevant Life email items
example screenshot when testing:

TN-3271 : add main study registry link email variable

---

portal/config/eproms/Questionnaire.json

TN-3264 Adds 6 new options to irondemog_v3.26 (ethnic group)

TN-3264 Add options to irondemog_v3

---

portal/config/eproms/Organization.json

https://movember.atlassian.net/browse/IRONN-236

IRONN-236 V5 for Lister & Clatterbridge

---

.editorconfig
.pep8speaks.yml

- Increase max line length allowed by linting tools
[Some precedents established by others](https://knox.codes/posts/line-length-limits)

Increase max line length for linters

---

portal/static/js/src/empro.js
portal/static/js/src/mixins/CurrentUser.js
portal/static/js/src/profile.js
portal/templates/profile/profile_macros.html
portal/views/portal.py

Add frontend check to determine whether user's org is in the list of orgs that do not allow OPT OUT feature yet, i.e. via config variable, `OPT_OUT_DISABLED_ORG_IDS`

Opt out feature - add frontend check for whether opt out is disabled for user org

---

portal/static/js/src/empro.js
portal/static/js/src/profile.js
portal/static/less/eproms.less
portal/templates/profile/patient_profile.html
portal/templates/profile/profile_macros.html

part of https://movember.atlassian.net/browse/TN-3284
address OPT OUT requirement: `A patient can choose to opt out a maximum of 3 times for a single domain`
Frontend will now check triggers history to ensure that user had not chosen to opt out of a domain at least 3 times in the past, i.e. check `_total_opted_out` of the domain property.
If so, it will not present the domain as an opt out option on UI.

OPT OUT frontend changes - check for max opt out limit

---

bin/nodejs-wrapper.sh

Pin NodeJS version used to build frontend

Pin NodeJS version

---

portal/config/eproms/Organization.json

…This date was chosen based on Paul's analysis at https://movember.atlassian.net/browse/IRONN-245?focusedCommentId=317102

IRONN-245 Move Velindre to V5

---

portal/config/eproms/Organization.json

https://movember.atlassian.net/browse/IRONN-247

IRONN-247 add org Univ Alabama Tuscaloosa

---

portal/eproms/templates/eproms/assessment_engine/ae_macros.html
portal/static/js/src/empro.js

https://movember.atlassian.net/browse/TN-3243 see [google doc](https://docs.google.com/document/d/1bpTGL7cJA9AcAx8ww1D1cneyTFxIbnpdCNj6JnPGS6k/edit?disco=AAABPlHTByk)
- remove Dismiss button and close button (X at top right corner) (see screenshot after changes)
- made Optout modal un-dismissable
- allow the user to continue (by clicking on the submit button) without selecting any option
screenshot

Feature/optout UI updates

---

portal/static/js/src/empro.js

https://movember.atlassian.net/browse/TN-3306
Followup fix to #4389 
address issue: not seeing EMPRO thank you modal following closing out of opt out modal by clicking on "X"

add EMPRO OPTOUT close button click event

---

docker/docker-compose.yaml

upgrade default postgresql version from 13 to 16

upgrade default postgresql version

---

portal/config/eproms/site_persistence_file.json

Enable EMPRO Opt-out for Guys St. Thomas NHS Foundation Trust

Enable EMPRO Opt-out for GSST

---

portal/config/eproms/Organization.json

https://movember.atlassian.net/browse/IRONN-260

IRONN-260 Add new IRONMAN org, needs to be live before 2024-09-09.

---

portal/config/eproms/site_persistence_file.json

Enable EMPRO for UK Site South Hampton

TN-3315 Enable EMPRO for UK South Hampton Site

---

portal/static/js/src/admin.js
portal/templates/admin/patients_by_org.html

accidentally merged [this](https://github.com/uwcirg/truenth-portal/pull/4413) into Master, reverted that.  Will merge this into the `develop` branch.

fix frontend error handing of patient list ajax error

---

tests/test_exclusion_persistence.py

Fixup email test
