portal/models/auth.py

Overrides the library default token expiration time (1 hour) to 4 hours

Override default OAuth token timeout

---

portal/models/auth.py

This fixes a bug I introduced earlier that caused service token expiration time to be set to 4 hours instead of the intended value of 365 days.

Fix overridden service token expiration time

---

portal/tasks.py

Nagios checks fill logs with redundant info - remove logging from the

---

portal/audit.py
portal/views/portal.py

events from landing in the error emails.  This means the audit log will
now include logging to levels ERROR and CRITICAL (which were previously
NOT part of the audit log).

Revised logging level AUDIT to be less than ERROR to prevent auditable

---

portal/models/auth.py

This will allow redirections to shared services without having to add an additional entry to `clients._redirect_uris`

Whitelist shared services URL for redirections

---

portal/config.py
portal/models/auth.py

This sets all instances of the token expiration time to 4 hours

Change default token expiration time to 4 hours

---

.travis.yml
portal/config.py

These changes reduce the complexity of the TravisCI database initialization by using the default database user present in the [build environment](https://docs.travis-ci.com/user/database-setup#using-postgresql-in-your-builds) instead of creating a new one.

TravisCI DB config refactor

---

.travis.yml
portal/config.py
tests/test_integration.py

These changes allow [TravisCI to run Selenium tests on Sauce Labs infrastructure](https://docs.travis-ci.com/user/sauce-connect/).
If tests are run on a local VM Sauce Labs infrastructure will not be used
Some Sauce Labs test metadata is not yet populated from TravisCI (eg [test status](https://wiki.saucelabs.com/display/DOCS/Test+Configuration+Options#TestConfigurationOptions-Pass/FailStatus))

Run Selenium tests on Sauce Labs

---

portal/views/user.py

This should fix the swagger documentation for the PUT `/user/<int:user_id>/groups` endpoint.

Group endpoint spec

---

portal/views/user.py
tests/test_consent.py

submitted data - the path value is adequate.

For POSTing user consents, don't expect a redundant user_id in the

---

portal/templates/challenge_identity.html
portal/views/portal.py

Fix the datepicker field format to mm-dd-yyyy in boostrap datepicker object as well as in portal.py where birthdate field is now a Flask-WTF String Field - and converted to datetime field before the fuzzy match comparison.

fix datepicker format in challenge form to mm-dd-yyyy

---

portal/models/fhir.py

During db seeding, #fetch_HL7_V3_Namespace seems to fail on certain machines with a socket error (errno 104), because of the use of urllib. Switching from urllib to requests, which seems to resolve the issue.

Use requests for HL7 namespace fetch

---

portal/static/js/main.js
portal/static/js/procedures.js
portal/templates/coredata.html

Changing the remaining mm/dd/yyyy datetimes to dd/mm/yyyy format. Includes date-modifying methods in main.js (changeFormat, convertDate, etc), which should now be expecting the new dt format.

Switching remaining mm/dd/yyyy datetimes to dd/mm/yyyy format

---

portal/templates/profile_macros.html
portal/templates/profile_test.html

Changing any instances of 'cell' in the template files to an app_text call, where the custom_text can be modified to 'Cell' or 'Mobile' depending on if the instance is TrueNTH (USA) or ePROMS (AU). 
This is just temporary, until we have a functional i18n system in place.

Changing cell/mobile in templates to apptext

---

portal/app.py
portal/views/auth.py

The default login and register view functions (in flask-user) fail to capture
the next parameter in a reliable fashion.  Using a simple closure
capture 'next' before redirecting to the real view function to
manage the flask-user business logic

Wire up flask-user to always capture 'next'

---

portal/app.py
portal/templates/about.html

* Make the last git commit hash available for display in views and templates
* Use above functionality to generate direct link to current version on github (only for development versions, not whole releases)

Add Github link to version if available

---

portal/templates/profile_macros.html

Getting rid of 'Default' option for locale select, which doesn't actually give any info to the user re: what locale they're using. Instead, " (Default)" will appear after the language option that's the current site default. Also, if the user has no locale set, that default option will be the one displayed in the Language field of their profile.

More intuitive language select

---

portal/models/intervention_strategies.py

This change adds the ePROMs additional questions for a patient to answer (after the epic26) after they have clicked the associated card. The ePROMs additional questions are implemented as a separate instrument (coded `eproms_add`).
@pbugni I'd like this to only apply to ePROMs (will it?). What's the easiest way to tell if a rule/strategy is being used on an intervention?

ePROMs Additional Questions

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/profile_create.html

- remove previous consent agreements upon selecting no organization afilliation (e.g. None of the above)
- add check to make sure no additional consent agreement added if previously added for the same top level organization
- prompt user to select organization in account creation page, remove None of the above as the option
- remove/comment out obsolete code
- minor css fixes

front end consent fixes

---

portal/templates/profile_macros.html

- restrict visibility of pca-localized section (i.e. clinical question inquired of the patient at account creation) in profile to only users having role of provider
- pca-localized section is currently visible in EPROMs, hidden in Truenth

fix permission for pca-localized section in profile - only visible to users with role of provider

---

portal/models/user.py
portal/models/user_consent.py
portal/views/user.py
tests/test_consent.py

GET /api/user/<id>/consent now returns all consents with deleted and

---

migrations/versions/4da6791b4a10_.py
portal/models/fhir.py
portal/models/intervention_strategies.py
portal/templates/profile.html
portal/templates/profile_macros.html
portal/views/assessment_engine.py
tests/test_fhir.py
tests/test_intervention.py

These changes allow staff members to queue and complete QuestionnaireResponses (through `present-assessment`) on a patient's ([FHIR `subject`](http://hl7.org/implement/standards/fhir/DSTU2/questionnaireresponse-definitions.html#QuestionnaireResponse.subject)) behalf by specifying the optional querystring parameter `subject_id` eg:
https://portal.example/api/present-assessment?instrument_id=epic26&subject_id=4
See [PT#132707403](https://www.pivotaltracker.com/story/show/132707403)

Assess Patient as Staff

---

portal/models/user.py
portal/models/user_document.py
portal/views/user.py
tests/test_user_document.py

Adding in GET endpoint for user documents. Note that this only provides an informative list of the user documents for the given user, including filename/type, document type, ID, etc. Does NOT include the actual file - that shouldn't be available in list format, but rather through a separate user_documents/<id>/download endpoint (which will be in a separate commit).

User Document GET

---

portal/models/user.py
portal/views/portal.py
tests/test_user.py

Modifying our identity challenge logic - now we still allow for fuzzy matching of firstname and lastname (average of the two fuzzy match ratios must be above configurable threshold, default 85%), but DOB must be a strict match.

Fuzzy match name only, DOB strict match

---

portal/views/patients.py

- making calls for user's assessment status conditionally based on config variable,PATIENTS_BY_PROVIDER_ADDL_FIELDS ('status' key)
Assessment Status is specific to Eproms, so no need to make those functional calls in Truenth
reduce performance hits that way as well

make loading of assessment status in patients list based on config variable

---

portal/static/css/portal.css
portal/static/less/portal.less

- fix syntax error (i.e. at media query for screen with 1300px) that prevented the rest of css from being read by the browser
- this will fix the facebook/google icon rendering issue

fix syntax errors in portal.css/less

---

portal/views/portal.py

- redirecting un-aunthenticated user back to landing page on attempting to access /home
Paul,  this fix is to address this story:
https://www.pivotaltracker.com/story/show/137493505
Let me know if you see any issue with this fix.

add fix for accessing /home on unauthenticated attempt

---

portal/static/css/gil.css
portal/static/less/gil.less
portal/templates/gil/base.html

- add fix so clicking on button(s) in GIL that display modal will not invoke loading indicator display

add fix to not show indicator for modal displays in GIL

---

portal/models/message.py

Adding in a 180-char wordwrap (only breaks between words) when setting message html, to avoid any potential issues with overly-long (>900 char) lines.

Fix email formatting issues with long lines

---

portal/templates/layout.html

- remove javascript code referencing URL object in layout.html 
- get the portal hostname using native javascript method

remove URL object javascript code - as it is not supported by all browsers

---

portal/models/organization.py
portal/models/user.py
tests/test_organization.py

Can now get all leaf nodes from any user's current set of organization
associations via user.leaf_organizations() or if needed for the whole
system, call OrgTree().all_leaf_ids()

Extend OrgTree to support leaf organization needs.

---

manage.py
portal/app.py
portal/models/i18n.py
portal/models/user.py
portal/translations/messages.pot
tests/test_i18n.py

* Created a new i18n module, which contains:
* the babel.localeselector method (moved from app.py)
* upsert method to add translatable strings from db to pot file if they don't already exist (and add new ref comments if they do, and said comments don't already exist)
* Added 'translations' option to manage.py, which runs i18n upsert method
* Fixed user locale setter function
* Created test suite for i18n module

I18n Module

---

portal/models/lazy.py

SQLAlchemy objects across thread boundaries.

include thread id in cache key - fixes problems with caching

---

portal/templates/gil/index.html
portal/views/portal.py

- looking for session variable instead to initiate login modal for entries to SS via intervention(s)

fix initialization of login modal for interventions on landing page

---

portal/templates/gil/base.html

clicking on the login link in the login/register modal should now pop up the login modal instead of directing the user to the older login page.

fix login link to popup login modal in the login/register modal in GIL

---

portal/templates/profile_macros.html

remove the show_macro filter for consents section as the section is now needed in both Eproms and Truenth.

remove show macro filter for consents section

---

portal/static/js/main.js
portal/templates/patients_by_org.html

fix the issue of loading indicator not displaying when patients list was initially loaded while ajax calls were being made to get assessment data. (stemming from timing issue - after wrapper is loaded, a call was made to hide the loading indicator).

UI Fix - to showing loading indicator when patients list first loaded

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/patients_by_org.html

- this allows users with applicable permission to select leaf orgs
- css fixes for orgs UI
- found a bug in patients_by_org.html - should hide loading div if there isn't any user consented to the same org as to the provider

Front-end Fix allowing leaf orgs to be selected when applicable

---

portal/app.py

localeselector function seems to not be working in some instances. Adding import line to app.py, so that it works as previously (before we moved localeselector out of app.py and into the new i18n model)

Properly implement localeselector function

---

portal/templates/gil/base.html

- add Symptom Tracker and Decision Support as sub-menu items under My Dashboard GIL menu item

additional items for Gil's dashboard menu item

---

portal/templates/profile_create.html

In account creation page, remove validation error message that was previous shown if no email checkbox is selected

remove error message requiring email if no email checkbox is checked

---

portal/migrations/versions/4b1e5b7b69eb_.py

In the audit subject_id/context migration, after extracting user id from comments, query users by id to confirm said user exists before using it for subject_id.

Confirm user exists before setting subject_id

---

portal/static/js/main.js
portal/templates/profile_create.html

- remove extraneous assigner parameter in the ajax call when setting study ID in call to demographics API
Paul, thank you very much for the API changes.  I tested and I see that study Id is now correctly saved.

remove assigner parameter in call to set study Id

---

portal/templates/profile_macros.html

- in Eproms, made the fix so that in patient's view of organizations, display only their org(s) (and no others)

fix patient's view of organizations (read-only view only)

---

portal/static/js/gil.js
portal/templates/gil/base.html
portal/templates/gil/decision-support.html
portal/templates/gil/symptom-tracker.html

- In GIL's decision-support and symptom-tracker pages, after registration, direct user to appropriate DSP site.
addressing this story:
https://www.pivotaltracker.com/story/show/139485009

IN GIL, direct user to appropriate DSP site after registration

---

portal/models/coredata.py
portal/models/fhir.py
tests/test_assessment_status.py

New coredata option 'localized' split off from 'clinical' to control
the display of the localized question in initial_queries.
See https://www.pivotaltracker.com/n/projects/1225464/stories/138544113

Localized now determined by org affiliation on ePROMs.

---

portal/templates/initial_queries.html
portal/templates/initial_queries_macros.html

- need to check for 'localized' in still_needed list now that pca_localized question is its own entity in core data
- use solely 'localized' in still_needed to determine presentation of question in initial queries
- use config variable, LOCALIZED_AFFILIATE_ORG in template to determine rendering of the question

pca localized fix in initial queries

---

portal/static/css/gil.css
portal/static/less/gil.less

- fix card css on GIL home page in smaller browser size and on mobile devices (e.g. adjust button appearance, allowing text to wrap in each card)

GIL mobile, smaller browser fixes

---

portal/site_persistence.py

Reports just the changed details when include_interventions is not
set (the default) for `seed`.  Reduce noise from matching cases.

Make tracking intervention changes easier.

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/initial_queries.html
portal/templates/initial_queries_macros.html
portal/templates/profile_macros.html

Addressing this story:  https://www.pivotaltracker.com/story/show/140101679
- display user-friendly error message if ajax call fails
- remove unused code (e.g. consent modal code, console.log code, etc)

add front-end error message display, remove unused code

---

portal/models/fhir.py

* Implicitly preserve instrument presentation order, in the order originally given in [`AssessmentStatus.__obtain_status_details()`](https://github.com/uwcirg/true_nth_usa_portal/blob/develop/portal/models/fhir.py#L683)
* May eventually need to explicitly maintain order in instrument sequences
See:
[PT#140370423](https://www.pivotaltracker.com/story/show/140370423)
[PT#140142961](https://www.pivotaltracker.com/story/show/140142961)

Preserve Instrument Presentation Order

---

portal/models/intervention_strategies.py
tests/test_intervention.py

need only confirm we don't have a procedure indicating real treatment.
Fix for [P3P should be available if the patient has 0 procedures](https://www.pivotaltracker.com/n/projects/1225464/stories/137643897)

As per issue #137643897 - the strategies that look for TX not started

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/portal_wrapper.html
portal/views/auth.py
portal/views/truenth.py

address this story: https://www.pivotaltracker.com/story/show/140106033
- temporary fix to allow user logging as patient to see profile menu item in banner
- made use of session variable to keep track of login-as scenario
- add css fixes for mobile view of patients list
The fix for login-as is needed for today, hence temporary in nature, will have a longer term fix for this

temporary fix for showing profile menu for login-as user

---

portal/models/app_text.py
portal/views/portal.py
tests/test_app_text.py

* Modified fetch_elements
* Now works with both versioned and non-versioned content
* Now has better error handling, and returns an error message for content instead of raising an exception
* Now logs error messages
* Modified existing non-fetch_elements requests.get() calls, to instead use fetch_elements

Remote server content error handling

---

portal/templates/profile_macros.html

fixing a bug I saw while testing in eproms-demo
- fix clinical data section display so when its content is hidden, the header for the section should also be hidden as well
- encapsulate the entire content to hide/display based on show macro filter

fix clinical data section display based on show_macro filter

---

portal/views/auth.py

Fix for [Deleted user error at registration](https://www.pivotaltracker.com/n/projects/1225464/stories/140962473)
We were not logging out the newly registered user and logging back in the invited one (whom picked up the newly registered user's auth details).

refactor err, failed to retain logout of registered and login of invited

---

portal/models/role.py
portal/templates/intervention_admin.html
portal/templates/portal_wrapper.html
portal/views/portal.py

* Adding intervention_staff role (https://www.pivotaltracker.com/story/show/120211029)
* Creating /admin/intervention page (https://www.pivotaltracker.com/story/show/136277925)
* Only accessible (and viewable in dropdown menu) to those with intervention_staff role
* Shows all patients who are related to any of the same interventions as the current intervention_staff user (i.e. who have user_interventions where the intervention_id matches any of the current user's user_intervention intervention_ids)
* List is searchable, sortable, etc.

Intervention_staff role & admin page

---

docs/source/organizations.txt

https://www.pivotaltracker.com/story/show/139052395
Fixing the formatting on the race/ethnicity/indigenous coding information in the organization documentation.

Fixing org r/e/i coding docs

---

portal/templates/flask_user/register.html
portal/templates/flask_user/reset_password.html

https://www.pivotaltracker.com/story/show/141050411
Increasing the minimum password length requirement from 6 to 8 characters.
Note that previously, we were not imposing _any_ of our password requirement rules (min chars, must include certain chars, password and password retype must match) on the Password Reset page. Adding those requirements in, including the new min length.

Min pass length 6->8 chars

---

portal/templates/profile_macros.html

https://www.pivotaltracker.com/story/show/141275823
- add filter to allow language section be visible in Eproms only
**Note**  this needs to go out in tandem to the change in persistence file for Eproms in this PR:  https://github.com/uwcirg/ePROMs-site-config/pull/17

add show macro filter to language section in profile

---

portal/templates/patients_by_org.html

address this story: https://www.pivotaltracker.com/story/show/141277807
- fix the issue by adding scroll-to-top code to on page change event listener of the patients list table

allow patients list to scroll to top when changing pages

---

portal/static/css/portal.css
portal/static/js/main.js
portal/static/js/procedures.js
portal/static/less/portal.less
portal/templates/profile_macros.html
tests/test_audit.py
tests/test_clinical.py
tests/test_procedure.py

address this story: https://www.pivotaltracker.com/story/show/141245875
- remove duplicate display of treatment entries from initial queries in procedures section in profile
- delete treatment when user toggles between treatment options in initial queries
- remove localized cancer question from Clinical Questions section in profile, and minor verbiage fix
- css fixes
- display staff name using name/email provided by procedures api

profile procedures section fixes

---

portal/templates/profile_macros.html

address this story:  
https://www.pivotaltracker.com/story/show/141256785
- allow gender section to display only in Truenth
**Note**  This change will need to go out in tandem of this PR of persistence file change:  https://github.com/uwcirg/TrueNTH-USA-site-config/pull/25

add show macro filter to gender section in Profile

---

portal/views/portal.py

When users are invited that are already fully registered in the system, email link (access token url) now redirects to the login page, with email field pre-populated (unless the user uses an alternative auth method).

Redirect invited pre-existing users to login page

---

manage.py

* Always update intervention data on development systems when seeding
* Will never automatically happen on demo or prod systems
* Prevents changes made from web interface from being overwritten

Update interventions on development systems when seeding

---

portal/templates/gil/portal.html

address this issue: https://www.pivotaltracker.com/story/show/141834163
- display disabled link for intervention tile only if the associated link label is present

fix portal link issue when disabled

---

portal/templates/profile_macros.html

fix bug I saw when testing:
- persist state selection if the relevant clinic for the state has been selected (this applies to users now in staging environment, i.e. stg.us.truenth.org) since their clinics are already selected)

clinics selector fix

---

portal/static/js/main.js

Part of https://www.pivotaltracker.com/story/show/141833645
Adding postBiopsy method, which should allow templates to send in biopsy info to our existing clinical observations API endpoint.
Note that this call uses '111' default code, per comments in PT story above. If we can find a suitable replacement code, we can update this later with a migration.

Adding biopsy post method

---

portal/templates/gil/base.html
portal/templates/portal_wrapper.html
portal/views/portal.py

Fixing minor issues as part of https://www.pivotaltracker.com/story/show/141449331
* Adding /patients link to main menu (was previously just in the gil wrapper) for intervention_staff
* Setting /home redirect to /patients page for intervention_staff (same as it currently is for staff)

int_staff should have patients list as home + in menu

---

portal/models/user.py
portal/views/patients.py

Adding permissions checks to allow users with only the intervention_staff role to access patient profiles from their relevant intervention patients

Allow intervention_staff to access patient profiles

---

portal/models/fhir.py
portal/views/clinical.py
tests/test_clinical.py
tests/test_fhir.py

* Adding update_from_fhir method to Observation model
* Only updates fields specified in incoming data; other fields are left the same
* Adding PUT endpoint to access update method
* Adding test for new endpoint + method logic

Observation PUT endpoint

---

portal/models/user.py

Non-admins with the staff_admin role should not be able to change their own organization information (same restrictions that are currently on staff role users).

staff_admin can't change their own orgs

---

portal/models/user.py

https://www.pivotaltracker.com/story/show/142722845
Unclear how we got them, but some users are ending up with email addresses containing both preset prefixes (INVITE_PREFIX + NO_EMAIL_PREFIX).
Modifying the email call to handle these cases, so that we no longer see `'__no_email__'`.

Handle cases with both email prefixes

---

portal/app.py

As per decision during stand-up on 4/4/17, reduce the requests-cache timeout to 10 seconds.

Reduce requests-cache to 10 seconds for easier content editing w/ LR

---

portal/models/user.py

Users w/o email see an empty string in demographics.  When this is PUT to the /api/demographics endpoint, we need to not replace the `__no_email__1491500775.8` like value with an empty string.

Catch case for users w/o email - demographics PUT shouldn't reset to ""

---

app.json
docker/Dockerfile
docker/docker-compose.yaml
portal/config.py

* Allow Flask SERVER_NAME config to be set by env var
* Required to correctly render portal wrapper (URL, including domain needed)
* Use SERVER_NAME env var to set Apache ServerName in Docker container

SERVER_NAME env var

---

docs/source/index.rst
docs/source/user_experience.rst

* Adds some documentation about how session timeouts occur on the frontend and backend
* Minor details about intervention client token expiration time
Let me know if I should add any details or have something wrong

Session Timeout Documentation

---

portal/models/user.py

Reverts uwcirg/true_nth_usa_portal#743
This fixed the symptom, not the problem :)
We should *never* have both invite and no_email prefixes on a user.  PR #786 fixes the root problem.

Revert "Handle cases with both email prefixes"

---

portal/templates/profile_macros.html

https://www.pivotaltracker.com/story/show/143212197
made the fix in the orgs UI in profile so that - 
In EPROMs where staff is allowed to edit patient's clinic, staff should only be able to select/edit one affiliated clinic for the patient.

orgs UI fix in profile 

---

setup.py

* Use `setuptools.find_packages()` to install `portal` package submodules (eg models/views)

Automatically Install Submodules

---

portal/static/js/main.js
portal/templates/profile_macros.html

Fixes to address this story:
https://www.pivotaltracker.com/story/show/143463375
- make consent associated with a fake agreement_url to be not editable (no link url is rendered for fake agreement url)
- allow state from a parent org that has no children to be selectable
- render consent modal only if agreement asset is present

orgs ui fixes

---

portal/views/portal.py

As needed for issue https://www.pivotaltracker.com/story/show/143463375
This can be referenced from any template via:
{{ url_for('portal.stock_consent', org_name='An Example', _external=True) }}

Adding simple view for stock consent agreements.

---

portal/static/js/main.js
portal/templates/initial_queries.html
portal/templates/profile_macros.html

address this story:  
https://www.pivotaltracker.com/story/show/143463375
- added the consent modal for org(s) that does not have consent agreement on file.  The modal will be presented to user upon selection of corresponding org.

add default consent modal for org(s) not having consent agreement

---

portal/static/js/main.js
portal/templates/initial_queries.html
portal/templates/profile_macros.html

address the issues from UI caused by no presence of consent text for any organization
- add fixes to remove dependence of UI on the existence of a consent text - the container div that houses the default consent modals is rendered independently

fix UI issues when no consent text is found for any org

---

docker/Dockerfile
requirements.txt
setup.py

* Install [Gunicorn WSGI webserver](http://gunicorn.org/) by default
* Already being used in [Heroku and Datica buildpack deployments](https://github.com/uwcirg/true_nth_usa_portal/tree/develop/Procfile#L4)
* Use Gunicorn as webserver inside Docker images (replaces Apache)
[Gunicorn in the context of serving a webapp](https://serverfault.com/questions/331256/why-do-i-need-nginx-and-something-like-gunicorn/331263#331263)

Replace Apache with Gunicorn

---

portal/models/user.py

https://www.pivotaltracker.com/story/show/143695513
Bug fix, to no longer throw an error when a user inputs a birthyear < 1900 during identity verification. Instead, verification just fails as normal (since no users can have birthyears < 1900 in the first place).

On identity verification, don't throw error if year < 1900

---

.travis.yml
app.json
docker/Dockerfile
portal/app.py
portal/audit.py
portal/config.py
tox.ini

* No longer require `LOG_FOLDER` config variable
* Write all logs to stdout if unconfigured
**NB: Will required `LOG_FOLDER` to be explicitly set in `application.cfg` for existing deployments**

Log to stdout by default

---

portal/templates/patients_by_org.html

https://www.pivotaltracker.com/story/show/144338151
- allow bigger clickable area for export checkbox in patients list
@ivan-c Ivan, this is a simple fix,  would be good to be included in tomorrow's release branch

increase click area in export checkbox in patients list page

---

manage.py
portal/models/organization.py
portal/models/user.py
setup.py

* Replace Flask-Script commands in manage.py with built-in [Flask CLI](http://flask.pocoo.org/docs/0.12/cli/) (based on [click module](/pallets/click))
* Allows running commands independent of current path (eg `flask initdb`), after setting `FLASK_APP`
* `FLASK_APP` can be set in venv activate script ie `FLASK_APP='/path/to/manage.py'`

Replace Flask-Script with builtin Flask.cli

---

portal/views/portal.py

fix for the TemplateNotFound server exception raised in stg.us - side effect of shared view template for lived experience stories.  Attempts to specify page path (e.g. /stories/blah/)  containing page name string not matching any template name will raise this exception.
I am not sure if this is the best fix.  Review and comment(s) on this is much appreciated.

fix template not found server error related to stories

---

portal/models/user.py
portal/templates/profile_macros.html

https://www.pivotaltracker.com/story/show/141258425
* added a new property to user model, which returns a set of that user's orgs' locales
* modified the locale section in profile_macros, to only display each locale if it (a) is in that user's org locale list, or (b) if it is the system default

Only display locale options valid for user's orgs

---

portal/models/organization.py
tests/test_organization.py

https://www.pivotaltracker.com/story/show/141258425
* changed org's `locales` db relationship to `_locales`
* created `organization.locales` property, which returns the union of the org's `_locales` and its parent's `locales` (if a parent exists).
* added test for this inheritance to `test_organization`

Org locale inheritance + test

---

portal/models/reference.py
portal/views/organization.py
tests/test_demographics.py
tests/test_organization.py

https://www.pivotaltracker.com/story/show/143697363
* modified Reference model, so that Organizations can be referenced from within other fhir api calls (e.g. `User.update_from_fhir`) via an external identifier
* format: instead of `{'reference': 'api/organization/<id>'}` (or variants), expects` {'reference': 'api/organization/<identifier_system>/<identifier_value>'}` (or variants)
* as with normal org reference, throws an error if no org is found; however, _also_ throws an error if more than one org is found (reference can only be used with unique identifiers)
* added test for org external identifier reference to test_demographics
* added GET api endpoint at `/api/organization/<identifier_system>/<identifier_value>`
* added test for GET endpoint

Demographics org reference can use external identifier

---

portal/views/portal.py

https://www.pivotaltracker.com/story/show/144709337
Looks like there's some strange issue where, when the app is running via apache, babel doesn't notice our override of `get_locale` in the i18n.py module. Adding this import line to the portal.py view seems to resolve the problem.

Making sure localeselector override function is used

---

portal/models/user.py
portal/templates/patients_by_org.html

https://www.pivotaltracker.com/story/show/144890987
* added study_id to the patients list
* searchable and sortable
* only appears if 'study_id' is added to the PATIENT_LIST_ADDL_FIELDS config
* added external_study_id property to the User model, which returns the value(s) of any external study identifiers (joined by commas if >1)

Adding study_id to patients list + relevant user property

---

portal/views/demographics.py

Found when debugging a bad request call with Martin - now clearly returning the details when a user forgets the `Content-Type: application/json` header.

Correct error text for demographics PUT when missing json header.

---

portal/models/assessment_status.py
tests/test_assessment_status.py

@achen2401 This will provide you with a 'by_date' field for every questionnaire the user hasn't completed, unless it has expired.
AssessmentStatus populates a list of questionnaires assigned to a user (associated by clinic).
You can now reference the 'by_date' for any questionnaire in the `AssessmentStatus.instrument_status` OrderedDictionary using the `by_date` key.
NB - 'by_date' will be `None` for `Completed` and `Expired` questionnaires.

Retain 'by_date' for incomplete questionnaires in AssessmentStatus.

---

portal/models/organization.py

Results in exception related to DB session:
sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <Organization at 0x7f8743fdfd50> is not bound to a Session, and no contextual session is established; lazy load operation of attribute '_locales' cannot proceed

Temporarily disable union behavior of Organization.locales

---

portal/models/organization.py
portal/models/user.py
tests/test_organization.py
tests/test_user.py

* removed `locales` organization property method (which returned the union of the org's `_locales` and its parent's `locales`), because it was causing an error during data seed (see https://github.com/uwcirg/true_nth_usa_portal/pull/871 )
* changed `_locales` db relationship back to `locales`
* removed inheritance test, added explicit locale check during org from_fhir test
* added logic to `user.locale_display_options`, to also grab locales from user's locale's parents (and their parents, continue recursively)
* added test for `locale_display_options` to test_user

Move locale inheritence check to user method

---

portal/views/user.py

* per Martin's input, expanding upon the 'no file found' error message for /patient_report POSTs to add more clarity

Expanding on 'no file found' error msg

---

portal/models/intervention.py

Generally, site_persistence ignores the link_url for interventions, as
it's unique per install.  This default behavior can be overriden by
using defining a `static_link_url` in the persistence file.

Add `static_link_url` option for pulling in intervention URLs

---

portal/views/user.py

Another detail found from Martin's use of the api.

Improve error text when given a bogus organization id.

---

portal/templates/gil/portal.html

as per conversation with Justin - 
remove LE information link from partner user's dashboard.
**NOTE**  needed for this release

remove LE link from partner's dashboard

---

portal/templates/gil/alonzo_mccann_story.html
portal/templates/gil/hirsch_brothers_story.html
portal/templates/gil/lived_experience_base.html

Found this while testing lived experience page:
- consolidate code for LE video on click event (remove duplicate code)
- add safari fix to force reload of video on window resizing as the video has background black bar on top and bottom without re-loading
**Note**
This should be included for the release as it contains styling fix for Safari when viewing LE videos

consolidate code for video onclick event, add video fix for safari

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/less/eproms.less
portal/static/less/portal.less

address this story: https://www.pivotaltracker.com/story/show/144338151
fix the issue of checkbox not clickable in export list by decreasing the z-index of absolute positioned loading div
**not**  needed for this release, can just be merged into develop upon review

fix checkbox unclickable issue

---

portal/templates/flask_user/emails/eproms_base_message.html
portal/templates/flask_user/emails/eproms_base_message.txt
portal/templates/flask_user/emails/eproms_forgot_password_message.html
portal/templates/flask_user/emails/eproms_forgot_password_message.txt
portal/templates/flask_user/emails/eproms_forgot_password_subject.txt
portal/templates/flask_user/emails/eproms_password_changed_message.html
portal/templates/flask_user/emails/eproms_password_changed_message.txt
portal/templates/flask_user/emails/eproms_password_changed_subject.txt

https://www.pivotaltracker.com/story/show/144890865
* new 'forgot password' and 'password_changed' email templates (to be used for eproms sites), with word choice specified by eproms

Change password reset email verbiage (eproms)

---

portal/models/organization.py

* modified the `organization.default_locale` property, so that if the org has no default_locale_id, it will instead use its parent's default_locale_id, continuing recursively until no more parents are found (in which case nothing is returned).
* should help Amy to avoid org tree traversal within the UI

Add inheritance to org default_locale property

---

portal/models/user.py

* adding the user's locale code to their locale display options, so we avoid scenarios where a user has a locale that doesn't show up in their locale list (e.g. if their orgs change)

Add user's locale code to their locale display options

---

portal/templates/gil/base.html
portal/templates/portal_footer.html
portal/views/portal.py

found this bug when testing portal footer html API
- made fixes to allow links in the footer to be appropriately disabled/enabled by allowing crossdomain call to gil-intervention-items API call
- In the context of crossdomain call,  allow a user object to be appropriately referenced by passing in user id parameter (otherwise a 401 error would be raised)

GIL intervention menu filtering check fix

---

portal/models/intervention_strategies.py

* broke out translatable strings from `intervention_strategy` html blocks, so that they could be wrapped with gettext ( `_( )` )
* note that translatable strings still contain some variable format brackets (e.g. "Hello {},"), so those will need to be translated around

Translating strings within strategy html

---

portal/models/organization.py
tests/test_organization.py

Don't consider org `none of the above` when looking up staff/admin
user's list of visible_patients.

Fix for https://www.pivotaltracker.com/story/show/145878341

---

portal/models/coredata.py
portal/views/coredata.py
tests/test_coredata.py

Refactored coredata to separate 'required' data from what is
'still_needed'.  Previously these were poorly coupled in the hasdata
method for each data point class.  More logical grouping, enables front
end developers to determine which controls should be available to a user
(list of required options) versus the ones for which we have yet to
gather any data (still_needed).
Backend changes needed for issue https://www.pivotaltracker.com/story/show/144417951

Coredata API includes still_needed and required endpoints.

---

portal/static/js/main.js
portal/templates/profile_macros.html

address server errors for staff having no organization affiliation
- add UI check for existence of organization affiliation if the user has the role of STAFF or STAFF_ADMIN

enforce UI check for existence of organization for staff/staff admin user

---

portal/static/css/eproms.css
portal/static/js/admin.js
portal/static/less/eproms.less
portal/templates/patients_by_org.html

address this story: https://www.pivotaltracker.com/story/show/142739321
allowing consent date field in the patients list table sortable
sorting of consent date is based on raw consent (e.g. 11-11-1980T00:00:00) but will display using the format, d M yyyy, as requested

make consent date field in patients table sortable

---

portal/models/questionnaire_bank.py

A questionnaire:rank may be duplicated between banks, where the correct constraint needs to prevent duplicate ranks on a single questionnaire_bank.
This should fix the failing test.

Fix constraint in error on questionnaire_bank_questionnaires

---

portal/templates/patients_by_org.html

* change the links for PatientReport entries in the Reports column of the /patients table
* instead of a d/l link, now redirects to the user's profile page, specifically the PatientReports section (via `#patientReportsLoc`)

Change PatientReport link in patients list

---

portal/models/user.py

* noticed that `user.merge_with()` was still looking for old `phone` field; updating to look for the new `phone_id` & `alt_phone_id` fields

Adding new phone fields to user.merge_with

---

portal/models/questionnaire_bank.py

https://www.pivotaltracker.com/story/show/145948501
* change `QuestionnaireBankQuestionnaire.add_if_not_found()` query to look up existing QBQs based on `questionnaire_id` and `questionnaire_bank_id`, rather than using all QBQ attributes
* should fix the db `seed()` issue

Fix qb site persistence issue

---

portal/models/user.py

Based on @pbugni 's comment in https://github.com/uwcirg/true_nth_usa_portal/pull/975
* modified db column attribute selection logic in `user.merge_with()` to be exclusionary (just ignore `['id', 'email', 'reset_password_token']`) rather than inclusionary (which requires manually adding fields to the attr list in `merge_with()` every time a new column is added to the model)

Change user.merge_with attr selection logic

---

portal/models/user.py

Should fix failing tests and issue https://www.pivotaltracker.com/story/show/146408767

Oversight from PR #976, the email field to ignore is spelled '_email'.

---

portal/models/user.py

Also, don't generate a stack, but log the error and march on.

Improve error details for strange multi-active encounter situation.

---

portal/models/fhir.py
portal/models/procedure.py
portal/models/user.py
portal/models/user_consent.py
portal/views/procedure.py
tests/__init__.py
tests/procedure2-example.json
tests/test_user.py

* added `cascade='delete'` to:
* UserObservation.encounter
* QuestionnaireResponse.encounter
* Procedure.audit
* Procedure.encounter
* User.user_audits (new relationship)
* User.subject_audits (new relationship)
* User.auth_providers
* User._consents
* User.encounters
* User.questionnaire_responses
* User.procedures
* User.documents
* User._phone
* User._alt_phone
(note that any relationship with a `secondary` table, automatically handles cascading deletes for that secondary table, and so needs no explicit `cascade='delete'` addition)
* removed most of `purge_user()` logic, as that's mostly all handled by the cascades now (besides a few unique cases)
* created fairly extensive test for `permanently_delete_user()`

Add missing delete orphan cascades

---

portal/templates/flask_user/_macros.html

found this issue when i was changing the links in the footer yesterday -
correct the element container in which the updated copyright text should be injected

copyright text container element fix

---

portal/models/user.py

https://www.pivotaltracker.com/story/show/146126053
(from testing of https://github.com/uwcirg/true_nth_usa_portal/pull/998 with copies of truenth and eproms stg instance data)
* Just as we currently modify observations' audit's user_ids when they reference the deleted user, also adding logic to modify observations' audit's subject_ids when they reference said user
* Note that this is just a temporary fix, until we move audit refs off of Observations and onto UserObservations (as detailed in https://www.pivotaltracker.com/story/show/146721583 ) - after which, all this Observation Audit logic in purge_user can and will be removed

Additional purge_user changes from stg data testing

---

portal/views/tou.py

*fixed swagger docs for tou apis
* removed extraneous `produces:` entries on same level
* changed duplicate `operationId:` on `get_tou_by_type()`
* fixed `properties:` double-embedding for `get_tou_by_type()`
* corrected description for `get_tou_by_type()`

Fixing swagger docs for ToU api endpoints

---

portal/migrations/versions/38cfbd643c73_.py

* fixed migration to allow for differently named foreign key constraints (`observations_audit_id_fkey` vs `observations_audit_fk`)

Fixing migration issue with different fkeys

---

portal/views/user.py

* on `POST /user/<user_id>/patient_report`, when attempting to determine the Token to subsequently determine the relevant Intervention, now use the access token from the request headers (if they exist) to locate the Token. If no access token found, instead find the first Token where `Token.user_id==current_user().id` (as we were doing before).

UserDoc POST - get token from headers when possible

---

portal/templates/profile_macros.html

* added column for `contributor` (i.e. Intervention description) to PatientReport list on the user profile page

Add contributor column to PR list

---

portal/models/user.py

This should fix the error emails just seen:
```
Exception on /api/patient/127/assessment [POST]
File "/srv/www/stg-eproms.us.truenth.org/portal/env/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
File "/srv/www/stg-eproms.us.truenth.org/portal/env/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
File "/srv/www/stg-eproms.us.truenth.org/portal/env/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
File "/srv/www/stg-eproms.us.truenth.org/portal/env/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File …
```

Typo - in user class, obviously doesn't have a user attribute.

---

portal/config.py
portal/templates/flask_user/_macros.html
portal/views/portal.py

* 'Terms' link in footer should only appear when logged in, or when `SHOW_PUBLIC_TERMS` config is `True` (which is the default)
* fixed typo in terms render method

Toggle-able public terms link in footer

---

portal/templates/settings.html
portal/views/portal.py

Fix for issue https://www.pivotaltracker.com/story/show/147238077
Adds to /settings:
- top level orgs & linked consents
- all app text strings (linked to LR if applicable)
- all application configuration values

Expand /settings for admins

---

portal/models/procedure.py

* removed `'delete'` cascade from `Procedure.encounter` relationship, which should fix the error when the UI attempts to delete a Procedure

Fix Proc DELETE issue

---

requirements.txt

Reverting this to confirm a hunch. See below email thread for context
---
Looks like the python requests module is looking for the cert bundle in the wrong module. This file may have been [formerly included in the requests module](https://github.com/requests/requests/commit/e41c2c2d965f6afb908c5acb595234d2bc5d2fe1), but now is part of the [certifi module](https://github.com/certifi/python-certifi/blob/master/certifi/cacert.pem).
I tested the (logout) eventcallback functionality on [demo.us.truenth.org](http://demo.us.truenth.org/) and was successfully logged out of [demo-dsp.us.truenth.org](http://demo-dsp.us.truenth.org/) so I don't think it's having any noticeable effect. Using the requests module directly from the [demo.us](http://demo.us/) virtual environment also worked.
I'll write …

Revert "Update requests to 2.18.1"

---

portal/templates/gil/base.html

address this issue:
https://www.pivotaltracker.com/story/show/147480971
fix role check for client application menu item in GIL menu
@pbugni Paul, I also did a scan of role checks for other items in the GIL menu, but let me know if you see any issue.

fix GIL menu permission issue

---

portal/views/portal.py
tests/test_portal.py

Added missing test to confirm parameters sent to the /report-error API land in the correct log and will therefore be included in error emails.

The report-error API was writing to STDOUT rather than the log.

---

portal/views/portal.py
tests/test_portal.py

* added api endpoint for getting specific config values in json format (/settings/<config_value>)
* currently only returns LR_ORIGIN or LR_GROUP config settings, otherwise returns a 400
* added tests for new endpoint

API endpoint for config settings (currently LR configs only)

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/initial_queries_macros.html
portal/views/portal.py

address story: 
https://www.pivotaltracker.com/story/show/147719465
- correct verbiage for consent terms read to patient (remove extra text, retrieving correct content for patient/org)
- styling fixes for terms checkboxes

eproms website content fixes

---

portal/views/auth.py

https://www.pivotaltracker.com/story/show/135168829
* modified browser timeout logic:
* when using the kiosk (aka `login-as`) functionality, browser timeout gets set to 5 minutes (via cookies, just as we do in the /settings page
* if admin user already had a custom browser timeout set (via /settings), that value is stored in another temporary cookie
* when logging back in normally (not using `login-as`), the 5 minute timeout either gets replaced with the previous value (via the temporary cookie), or if there was no previous value, just gets removed (and the system will use the app default)
* at this time, the temporary cookie is removed (if it exists)

Kiosk mode 5 minute browser timeout

---

portal/static/js/main.js

noticed this when testing:
add more descriptive text for items listed in Consent History section for EPROMs (i.e. which type of consent terms the subject agreed to)

add more informative text for items in consent list for EPROMs

---

portal/templates/flask_user/_macros.html

Sie-ce found this issue while testing:
Remove direct link from Truenth logo in footer; this includes preventing opening of page in a new tab.

remove direct link from Truenth log - for EPROMs

---

portal/models/user.py

https://www.pivotaltracker.com/story/show/147975625
* added proper API error handling for when fields are missing from the `identifiers` array within ` PUT /demographics` data.

Error handling for missing key (demographics/identifiers)

---

portal/templates/website_consent_script.html

Found this while testing:
When staff agreed to terms of use **on behalf of** subject as during manual entry, parent organization id should also be submitted when updating terms (as terms are different between CRV and IRONMAN).

submit organization id when updating terms via manual entry

---

portal/views/clinical.py
portal/views/group.py
portal/views/intervention.py
portal/views/procedure.py
portal/views/truenth.py
portal/views/user.py

Replaced generic `response` with distinct names so the resulting swagger
reports the desired return description.
Fix for https://www.pivotaltracker.com/story/show/148112793

Swagger requires unique symbols for return ids.

---

portal/templates/initial_queries_macros.html

found this while testing - clicking on terms or privacy links with the text of terms checkbox will automatically check the checkbox itself
fix is to prevent click event attached to links from bubbling up to parent element

prevent event propagation on embedded links for terms checkbox

---

portal/static/js/main.js
portal/templates/flask_user/_macros.html
portal/templates/initial_queries.html
portal/templates/initial_queries_macros.html
portal/templates/privacy.html
portal/templates/terms.html

found some issues with initial queries page when testing:
- when opening new browse tabs on clicking on terms or privacy link, disable links (EXCEPT for home and logout links) on ensuing page to prevent navigation to other pages
- no need to render content IF there is no as needed items return from API call

fix initial queries links, content rendering on as needed

---

portal/static/js/main.js
portal/templates/initial_queries.html
portal/templates/initial_queries_macros.html
portal/templates/portal_wrapper.html

address a couple of issues that were found when testing:
- remove code that does not work across browser (i.e. In IE, the event listener, window.focus, does not work as expected)
- enable home links on initial queries (allow users to navigate back when viewing privacy and terms pages)
- add code to get user organization via ajax if UI for organizations is not present

initial queries orgs for website terms, links fixes

---

portal/views/user.py

https://www.pivotaltracker.com/story/show/148440349
* when attempting to reset password, first check and confirm that the provided email address contains a domain (aka includes an '@' symbol)

Adding checks for email address on pw reset

---

portal/static/js/main.js
portal/templates/profile_macros.html

found issues while testing editing consent date/time for a patient:
- add validation check for empty date/time submission
- allow entry, "00", for hour, minute and second fields
allow consent date/time of patients in system other than "production" system be editable by staff.  (see story: https://www.pivotaltracker.com/story/show/148621337)

consent date/time validation fixes

---

portal/models/user.py

* when 'identifier' is included in the incoming demographics json, capture (and abort on) `TypeError` exceptions (aka situations where the identifier is not defined with a dict, as expected).

Capture type error on when reading Identifier from fhir

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less

address this story: https://www.pivotaltracker.com/story/show/147655813
hide agreed initial consent terms from user during initial queries, EPROMS specific.
hide terms via css

hide agreed terms in initial queries for EPROMs

---

portal/config.py

https://www.pivotaltracker.com/story/show/148387559
* Identified issue with `RECAPTCHA_ENABLED` config, where it was always reading as `False` when casting as a bool from the `RECAPTCHA_SITE_KEY` value.
* Just changing to a straight `True` value for now instead (we already have checks in place, that hide + ignore the recaptcha verification if the config values aren't properly set)

Change recaptcha_enabled config to True

---

portal/tasks.py
portal/views/portal.py

For debugging problems on demo, which we don't want to upgrade, backport the celery-info task and endpoint.
NB - off the release/v17.6.15 branch.

Add the celery-info task and endpoint for verification.

---

portal/config.py

Only set cookies over "secure" channels (HTTPS) for non-dev deployments
See [rfc6265](https://tools.ietf.org/html/rfc6265#section-4.1.2.5)

Only set cookies over "secure" channels (HTTPS) for non-dev deployments

---

portal/views/portal.py

Looks like this line somehow got removed...
Note that we NEED this line for translations to work properly in the portal. For whatever reason, when instances are deployed through apache, our replacement `locale_selector` method isn't registered (and therefore doesn't get used). This import line assures that our method gets pulled in.

Import locale selector method

---

portal/views/assessment_engine.py
portal/views/patients.py
portal/views/portal.py
portal/views/user.py

(for relevant stories, see commit msgs)
* add helper method to check int-casting of expected int inputs
* abort on a `ValueError`, with a relevant 400 error msg
* add above int-casting check to consent-assessment-status API
* add above int-casting check to patient search API
* add above int-casting check to unique_email API

Check int inputs for API endpoints

---

portal/models/user_consent.py
tests/test_user.py

https://www.pivotaltracker.com/story/show/148701941
* we're already capturing and aborting on `ValueError`s in `set_valid_consents()` in the user API; however, we weren't properly throwing `ValueErrors` on bad data in `UserConsent.from_json()`. Modified the logic slightly and added some extra error handling, so we can avoid SQL exceptions (see PT story).

Properly handle edgecases and throw ValueErrors for org_id

---

portal/models/auth.py
portal/views/auth.py
portal/views/portal.py
tests/test_auth.py
tests/test_portal.py

https://www.pivotaltracker.com/story/show/149043973
* added validation checks on client redirect URLs (using `validate_client_origin()`) for:
* `/website-consent-script/<int:patient_id>` [GET] - check `redirect_url`
* `/login/<provider_name>` [GET] - check optional `next` param
* created new `validate_local_origin()` method to check if given URL is "local" (netloc matches server name, or the URL is just a relative path)
* added validation checks on local redirect URLS (using new `validate_local_origin()`) for:
* `/challenge` [POST] - check `form.next_url`
* `capture_next_view_function` - check `next`
* created tests for generate origin validation methods + specific endpoint redirect scenarios

Validate redirect URLs

---

portal/config.py

https://www.pivotaltracker.com/story/show/149172459
After trying a couple different approaches (including extending out a whole new LoginForm class), I found that there's actually a simple config change for this :)
* set `USER_SHOW_USERNAME_EMAIL_DOES_NOT_EXIST = False`, which turns off specific error messages for invalid email vs. invalid password, and just shows one message ('Incorrect Email and/or Password') instead.

Show same error message for invalid email & invalid password

---

portal/static/js/main.js

found this while testing - email field being validated twice
- turn off on change validation event  (valid only on on-blur event)

fix input validation (e.g. email field)

---

portal/models/organization.py

https://www.pivotaltracker.com/story/show/148436359
* when comparing org levels (e.g. comparing staff and patient orgs during `check_role()`), properly handle `ValueError`s, so that, among other things, we properly handle patients who just belong to org id=0 ('None of the above').

Handle ValueErrors in when comparing org trees

---

portal/templates/contact.html
portal/templates/gil/contact.html
portal/views/portal.py

https://www.pivotaltracker.com/story/show/149275507
* added length limits to the Name/Subject fields (on GIL contact form) and FirstName/LastName/Subject fields (on non-GIL contact form), so that we wouldn't exceed db field length limits
* added similar limits on the backend (throughs 400 error when exceeded), in case of any direct POST contact request attempts

Length limits on contact sender/email (front- and back-end)

---

portal/views/auth.py
tests/test_auth.py

https://www.pivotaltracker.com/story/show/149047283
* added new `Client.callback_url` validation on `/client/<client_id> [POST]`
* `callback_url`'s `{scheme}://{netloc}` must match that of any of the provided `redirect_urls`
* only triggers if `callback_url` is provided (i.e. the field is still optional)
* modified `test_auth.test_client_edit`, so that client's new `callback_url` is also present in its list of `redirect_urls`

Validate Client callback_url against Client redirect_uris

---

portal/models/user.py

https://www.pivotaltracker.com/story/show/149043645
* added `cgi.escape()` to `User.display_name` return, so that when said `display_name` is pulled for `intervention_strategy` strings, etc, we pre-escape potentially dangerous HTML entity tags ('<', '>', and '&').

Escape HTML entities in user.display_name

---

portal/views/auth.py

https://www.pivotaltracker.com/story/show/148694671
https://www.pivotaltracker.com/story/show/148455555
* added check for NUL (`\0`) char in request form fields for `oauth/token' endpoint
This is a tricky situation, because our code in `auth.access_token()` is wrapped by the actual built-in flask oauth token_handler functionality; prior to this in fact, our `access_token()` method did nothing but `return None`. So we can't just wrap it in a try/except and handle the `ValueError`, because the sqlalchemy logic is happening outside of what we can control. We also can't modify the `request.form` fields (and just convert the data into something acceptable), because the object's immutable.
Current approach is just to straight-up check for the invalid NUL char in all the fields before continuing …

Check for NUL in access_token request form

---

portal/static/css/eproms.css
portal/static/css/gil.css
portal/static/less/eproms.less
portal/static/less/gil.less
portal/templates/contact.html
portal/templates/gil/contact.html
portal/views/portal.py

https://www.pivotaltracker.com/story/show/148387559
* modified `/contact` [POST] API endpoint logic:
* abort 400 on unverified recaptcha during POST (instead of previous page reload)
* on success, just return json containing the `msgid: <email.id>`
* modified contact.html page (both gil and non-gil)
* changed 'Submit' button press logic from submission + page load, to an ajax call
* on button press, hide button (to prevent multiple resubmissions) and show loading message
* on failed response, display error message and re-show button
* on successful response, load contact_sent.html page (using returned `msgid` as url param)

Show error msg, and don't load next page, on failed contact request

---

portal/templates/staff_profile_create.html

found this while testing:
display error message for required field(s) that are yet to be filled in.  (I saw that Sie-ce wasn't aware that she neglected to enter some required fields when she showed me her testing results).

display error message for empty required field in staff creation page

---

portal/static/css/eproms.css
portal/static/less/eproms.less

found this while testing-
remove opacity:0 css from next button, otherwise it won't be visible.
**not** for this release, can be merged back to develop upon review

remove opacity property from next button in eproms

---

portal/models/auth.py
portal/views/assessment_engine.py
portal/views/auth.py
portal/views/coredata.py
portal/views/crossdomain.py
portal/views/intervention.py
portal/views/portal.py
portal/views/truenth.py
tests/test_auth.py

* added local validations (origin's netloc matches the server_name, or origin is a local path) to `validate_client_origin()`
* removed `validate_local_origin()`
* changed calls of `validate_local_origin()` to `validate_client_origin()`
* updated tests
There are some cases popping up where we use the `next=` redirect for either local OR client origins. For example, with `/user/register?next=...`, we sometimes pass a local URL, sometimes a client, depending on how the user was sent to the register page.
As far as I am aware, there are no cases where we want to allow client origins but specifically _exclude_ local origins (or vice versa). So, rather than create a _third_ origin validation method for situations allowing both client and local origins (to handle the likes of `/user/register`), …

Fold validate_local_origin into validate_client_origin

---

portal/static/js/admin.js
portal/static/js/main.js
portal/templates/admin.html
portal/templates/layout.html
portal/templates/patients_by_org.html
portal/views/portal.py

https://www.pivotaltracker.com/story/show/149756859
* updated version of bootstrap-table from 1.10.1 to 1.11.1
* added bootstrap-table-export and bootstrap-table-filter-control extensions
* added table export functionality to /admin table
* added table filter functionality (for certain fields) to /admin table
* updated /admin API, to allow for `org_list` url param (to filter users in table based on org)
* added groundwork for `FILTER LIST BY SITE` button, including generifying the `initOrgsList()` function

Enhance admin table

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/profile.html
portal/templates/profile_macros.html

miscellaneous minor fixes made while testing:
- remove sync attribute from a couple ajax calls in profile (they should be non-blocking, asynchronous)
- loading indicator fixes (css and fadeout timing)
- remove unused code (i.e. showWrapper, not called anywhere)
- move email field specific event and attribute to email profile template

remove sync ajax calls from profile, loading spinner css fixes and timing fixes

---

portal/views/portal.py

https://www.pivotaltracker.com/story/show/147783817
* when gathering user stats for reporting dashboard, skip any user with `ROLE.TEST` in their roles list

Exclude users with the 'test' role from reporting stats

---

portal/static/js/admin.js
portal/templates/patients_by_org.html

found these issues while testing:
- shorten the terribly long timeout (2 minutes) to 3 seconds for each ajax call for assessment status in patients list.  The long timeout was accidentally left behind while testing.
- shorten the timeout duration for aborted ajax call (so the callback can be called in due speed)
- fixed so that loading spinner will display before (instead of during) user is redirected to next page (e.g. profile or account creation page

timeout duration fix for patients list

---

portal/models/app_text.py
tests/test_app_text.py

https://www.pivotaltracker.com/story/show/148510441
* modified `VersionedResource` and `UnversionedResource` classes, to allow for optional `variables` param
* when returning a resource's asset, now attempts formats asset with provided `variables` (or returns an error if a requested asset variable is missing from the provided `variables` dict)
* added unit tests

Replace variables in incoming LR content

---

portal/static/js/admin.js
portal/static/js/main.js
portal/templates/profile_macros.html

found these issues while testing:
- performing the following on **callback** of retrieving roles list (otherwise they don't happen since the call is now asynchronous):
-  attach on-click event for role checkbox
-  display indication for when role is being saved
- a minor fix to not show toolbar (e.g. filtering, search) on patients list table when there is no patient.

roles saving fixes

---

portal/templates/portal_wrapper.html

* added links to `/settings` and `/reporting` to the portal wrapper's mini-menu (i.e. the version of the menu that's used when the window is small)

Adding missing Settings and Reporting options to mini-menu

---

docker/Dockerfile
docker/remap_envvars.py

* Define PG* env vars from all possible URL-formatted env vars (`DATABASE_URL`, `DATABASE_1_URL`)
* Don't override existing values

Remap DB env vars to standardized PG values

---

portal/templates/reporting_dashboard.html
portal/views/portal.py

https://www.pivotaltracker.com/story/show/150063689
* added Usage Statistics section to Reporting Dashboard
* includes registrations and logins (incl. intervention breakdowns)
* currently displays by day, month, year, and all time
* eventual implementation will be a filterable graph - this is more a data POC
* added Encounter and user registration data collection to backend, for new Usage Stats section
* added 'Unspecified' option for orgs, for users with no orgs yet (different from users with 'none of the above' org)

Reporting dashboard v2

---

portal/views/scheduled_job.py
tests/test_scheduled_job.py

* cleaned up code for ScheduledJob tests and views (fixed description text, removed unnecessary imports, pep8-ified it, etc)
* singularized the API endpoints (`/api/scheduled_job` instead of `/api/scheduled_jobs`), to be more in line with our other views
* note that the user-facing page path (`/scheduled_jobs`) remains pluralized (similar to `/settings`, `/patients`, etc)

Cleaning up ScheduledJob code

---

portal/views/user.py

* added STAFF_ADMIN to list of allowed roles for `/account [POST]`
* users with STAFF_ADMIN should have account creation access, for when they're creating new accounts via the `/staff-profile-create` page (currently throws an API permissions error when they attempt to save, if they don't also have the STAFF role)

STAFF_ADMIN should have account POST permission

---

portal/models/app_text.py
portal/templates/profile.html
portal/templates/profile_macros.html
portal/views/patients.py
portal/views/portal.py
tests/test_app_text.py

https://www.pivotaltracker.com/story/show/150369091
* added new MailResource class in app_text module
* instead of `.asset`, has `.subject` and `.body`
* both fields have variable fields replaced
* `.body` field is rendered in a specific way, as to not destroy html formatting
* added UserInviteEmail_ATMA class for 'profileSendEmail invite email' in app_text module
* in `render_template()` calls of 'profile.html', create and pass through MailResource object for invite email info
* properly pass through and use info from invite email MailResource object in profile template (incl. 'profile_macros.html')
Note: This will also require new app_text entry for ('profileSendEmail invite email', '{config[LR_ORIGIN]}/c/portal/truenth/asset/mail?version=latest&uuid=32a6713e-5051-8079-0ed3-0a7eeb607c03' …

MailResource class, implemented with user invite email

---

portal/static/js/main.js
portal/templates/initial_queries.html
portal/templates/initial_queries_macros.html

found this issue when testing, in particular, patients (e.g. older testing patients) missing privacy policy in EPROMs:
- fix check for required terms of use items other than general website terms of use (e.g. including privacy)

initial queries - fix for check for required terms other than general website terms of use

---

portal/models/encounter.py
portal/models/organization.py
portal/models/user.py
portal/tasks.py
portal/views/patients.py
portal/views/portal.py

SQLAlchemy uses operator overloading in filter statements, but one can't
overload the is operator.
As of SQLAlechemy 0.7.9 the is_() and isnot() functions became
available.
http://docs.sqlalchemy.org/en/rel_1_0/core/sqlelement.html#sqlalchemy.sql.operators.ColumnOperators.is_

Use pep8 complaint operators for SQL null checks.

---

portal/templates/admin.html
portal/templates/patients_by_org.html

* when exporting tables, export _all_ rows (after filtering), not just the current page

Ignore pagination during table export

---

portal/templates/profile.html

Reverts last commit of #1264
The `user_email` template var is only in scope inside the trans block. 
It isn't strictly required to include the user's email as a template variable, but doing so gives the translator a little more context as to what the text *Profile for* refers to. 
Ideally when we mark strings for translation they should represent (as closely as possible) a complete sentence, thought or element. This is a little more of a grey area since it's just a heading, but the id/email are implied to be part of the heading and should be included if possible.

Revert "remove trans tag from email"

---

portal/templates/staff_by_org.html

* added field filtering and table export functionality to /staff table
* includes 'export all table' setting from PR #1273 
* includes Amy's filler text (e.g. "Enter Text") for the filter textboxes, as used on the /patients table

Add filter & export functionality to Staff table

---

portal/templates/gil/base.html
portal/templates/portal_wrapper.html
portal/templates/research.html

https://www.pivotaltracker.com/story/show/150112113/comments/178719590
* changed `/research` display name (in menus and on page) to "Research Data"
* added `/research` link to small-window version of dropdown menu

Rename Research Dashboard to Research Data

---

portal/templates/profile_macros.html

related to this story: 
https://www.pivotaltracker.com/story/show/150303132
allow intervention staff to have access to audit logs
missed checking for the role previously when including the audits section

intervention staff role check added to include audits section

---

portal/templates/reporting_dashboard.html

https://www.pivotaltracker.com/story/show/150063689
* added text descriptions for each table in /reporting
* note that these descriptions are VERY rough and technical; will require input from Justin and/or Paul to rewrite in a more user-friendly format

Add textual descriptions to reporting dashboard tables

---

portal/models/app_text.py
portal/templates/profile_macros.html

* move 'string-escape' formatting from `MailResource.body` to the actual template
* formatting is only an issue when the body html is pulled into the template (and causes issues other places if it's always assumed), so we should _only_ format as-needed

Fix MailResource.body formatting issue

---

portal/templates/profile_macros.html
portal/views/patients.py
portal/views/portal.py

* Use `return_url` for the access URL, rather than the current (incorrect) URL, in the invite email

Use proper access URL in invite email

---

portal/views/portal.py

Note this requires two config params, such as:
```
SQLALCHEMY_RECORD_QUERIES = True
DATABASE_QUERY_TIMEOUT = 0.05
```

Adding mechanism to report slow database queries.

---

portal/models/app_text.py
portal/views/patients.py
portal/views/portal.py

* add logic to pull specific invite email templates from LR if user's top org is CRV or IRONMAN
* see https://github.com/uwcirg/ePROMs-site-config/pull/55 for specific LR url vals
* added and populated MailResource variables for new template

Use new email templates for CRV & IRONMAN

---

portal/templates/gil/index.html

fix GIL home page title to "TrueNTH Home"
can be merged into the develop branch upon review

correct title on gil index page

---

portal/models/app_text.py
tests/test_app_text.py

https://www.pivotaltracker.com/story/show/148510441
* added `variable_list` to `MailResource`, which provides a list of all requested variables from the LR content
* updated `MailResource` tests

Add variable list to MailResource

---

portal/models/user.py
tests/test_user.py

https://www.pivotaltracker.com/story/show/150502476
* fixed logic to set `User.registered` to the current time when a non-registered user account is promoted to registered
* added tests

Update User.registered on promote

---

portal/app.py

Disabled unless configuration is added - shows significant detail on *every* request in the logs.

Add configurable profiler to assist in tracking down bottlenecks

---

portal/models/user.py
tests/__init__.py

Noticed incorrect lookup for biopsy trigger date.  Was using the time of entry, not the user provided date of observation.

Observation.issued, not Observation.audit.timestamp defines event date

---

portal/models/user.py
portal/views/procedure.py

* added assessment cache invalidation to procedure POST and DELETE
* moved shared code from `User.add_observation()` and `User.save_constrained_observation()` into new `User.save_observation()` method
* new method also includes assessment cache invalidation

Invalidate assessment cache on Procedure & Observation updates

---

portal/date_tools.py
portal/models/communication_request.py
portal/models/questionnaire_bank.py
portal/models/recur.py
tests/test_communication.py

We needed to check site_persistence imports - syntax errors slipped by creating an upgrade mess.
See also site persistence correction:  https://github.com/uwcirg/ePROMs-site-config/pull/59

Make imports of RelativeDelta strings more robust.

---

portal/models/reporting.py

@OptimusRhine @mcjustin Can you check if this is the desired behavior?
This change will restrict the lookup for intervention access and intervention reports to only patients.
(it should also significantly cut down on the noise in the error logs)

intervention access checks only apply to patients.

---

portal/migrations/versions/8ffec90e68a7_.py
portal/models/assessment_status.py
portal/models/communication_request.py
portal/models/questionnaire_bank.py
portal/tasks.py
portal/templates/patients_by_org.html
portal/views/assessment_engine.py
portal/views/patients.py
tests/test_communication.py
tests/test_questionnaire_bank.py

https://www.pivotaltracker.com/story/show/150112352
* added new namedtuple object `QBD` to QuestionnaireBank module
* modified `QB.calculated_start()` and `QB.most_current_qb()` to return `QBD` namedtuple
* updated existing calls to handle new return object properly
* added `QBD` info to assessment cache
* added display version of current QB to patient information for /patients list
* display version is a combination of the QB name prefix (e.g. 'IRONMAN'), the classification (e.g. 'Baseline', 'Recurring'), and if recurring, the month total, tabulated through a combination of the current Recur attributes and the iteration count
* added new 'Visit' column to /patients page table, which contains the display version of the current QB (per above)

Current QB in /patients list

---

portal/views/patients.py

* convert `Recur.start` and `Recur.cycle_length` to `RelativeDelta` objects, rather than just (incorrectly) assuming they're dicts/json
* better logic when calculating months (no longer assumes "months" OR "years", now checks and totals "months" AND/OR "years")

Properly handle Recur.start and Recur.cycle_length

---

portal/models/intervention.py
portal/models/intervention_strategies.py
portal/models/questionnaire_bank.py
portal/models/reporting.py
tests/test_intervention.py

* turned off InterventionStrategy logging by default, unless turned on via config setting
* added new `Intervention.quick_access_check(user)` function
* returns `True` as soon as access is confirmed (or `False` if no access confirmed), rather than making additional checks and/or building a `DisplayDetails` object
* skips html-generating strategies (they normally just return `True` anyway)
* modified reporting stats function to use new `quick_access_check()`
* added to existing InterventionStrategy-related Intervention tests, to confirm that `Intervention.quick_access_check(user)` acts the same as `Intervention.display_for_user(user).access`
Before these changes, reporting dashboard took 13min to load with truenth stg data.
After these changes, reporting dashboard took ~8min~ (7min with …

Quicker & quieter intervention access check

---

portal/models/app_text.py
tests/test_app_text.py

* modified `MailResource` object to include optional footer from LR json
* return as part of `MailResource.body`, if present (separated by newline)
* format with variables, same as subject and body
* include footer variables in `MailResource.variable_list`
* updated tests to check footer (incl. with vars)

Add footer to MailResource

---

portal/views/portal.py
tests/test_access_url.py

* modified `access_via_token()`, so that when the embedded `verify_token()` fails, we actually redirect to the returned redirect, rather than treating it as a `user_id`
* added test for bogus token (confirm redirect to landing)

Properly handle bad access tokens

---

docs/source/portal.rst
manage.py
portal.wsgi
portal/celery_worker.py
portal/extensions.py
portal/factories/app.py
portal/factories/celery.py
portal/models/auth.py
portal/models/scheduled_job.py
portal/site_persistence.py
portal/tasks.py
portal/views/portal.py
portal/views/scheduled_job.py
requirements.txt
setup.py
tests/__init__.py
tests/test_scheduled_job.py
wsgi.py

* Move app and celery initialization into separate module (`factories`)
* Initialize celery from a factory function
* Name tasks and call by name (with `celery.send_task()`) to prevent cyclic imports
Adapted from:
* [Configuring Celery](http://flask.pocoo.org/docs/0.12/patterns/celery/)
* [Using Celery with Flask Factories](https://citizen-stig.github.io/2016/02/17/using-celery-with-flask-factories.html)
See also:
* [Celery and the Flask Application Factory Pattern](https://blog.miguelgrinberg.com/post/celery-and-the-flask-application-factory-pattern)
* [Celery integration with Flask](http://shulhi.com/celery-integration-with-flask/)

Celery init factory

---

portal/templates/initial_queries_macros.html

found this while testing - placeholder for the day field of birthdate field is missing in initial queries page
- fix is to add the closing quotation mark to the aria label attribute

add closing quote to aria label for initial queries birthdate field

---

portal/models/app_text.py
tests/test_app_text.py

* fixed issue with str conversion, which was causing `None` footers to appear in emails as a line of `'None'`
* added new test for footer optionality

Fix MailResource footer

---

portal/models/communication.py
portal/trace.py

This should restart the trace on each user when called from the celery task - therefore the trace (stack) you see in the email should only pertain to the given user.

Reset the trace for each call to generate_and_send() if in celery loop

---

portal/views/assessment_engine.py

* Require staff or patient role to trigger an assessment
* Redirect to assessment after successful login

Require role for patient assessment and redirect

---

portal/date_tools.py
portal/models/communication.py
tests/__init__.py
tests/test_communication.py

https://www.pivotaltracker.com/story/show/151540337
* modified `questionnaire_due_date` for LR-generated Communication emails, to convert from UTC to the user's TZ (as that may modify the due date by +/- 1), if user TZ is set
* added tests for `questionnaire_due_date` (without and with user TZ)
* added new `setdate` param to `bless_with_basics()`, to make sure we can test a time where converting to another timezone would affect the day

Convert communication q_due_date to user's TZ

---

portal/date_tools.py
tests/test_date_tools.py

https://www.pivotaltracker.com/story/show/151539979
* modified RelativeDelta to raise `ValueError` if any keys are singular (we don't want to support absolute delta dates, just relative ones - [see here for more info](http://dateutil.readthedocs.io/en/stable/relativedelta.html) )
* added test

Raise exception on singular noun param in RelativeDelta

---

portal/models/intervention_strategies.py
tests/test_assessment_status.py
tests/test_communication.py
tests/test_intervention.py

https://www.pivotaltracker.com/story/show/151666519
* populate assessment_status card_html dates (due date, completion date, etc) based on user's local timezone, not just always UTC
* add tests for above display dates
* includes update to `test_assessment_status.mock_qr()`, to add a timestamp param

Localize AssessmentStatus card_html display dates

---

portal/models/communication.py
tests/test_communication.py

https://www.pivotaltracker.com/story/show/151704843
* modified due_date logic for Communications emails, to show the relative_start date (instead of the relative_start + overdue)
* updated tests to reflect new expected logic

Fix displayed due_date day in Communications emails

---

portal/templates/patient_profile_create.html
portal/templates/profile_macros.html

- fixed error messaged logged to the server during account creation - the response text that was supposed to be sent back was erroneously removed
- remove duplicator validator() call on account creation form - this was preventing custom duplicate email check from occurring
- remove aria label on hidden link

fix error message logged for account creation error, validator fixes

---

portal/templates/profile_macros.html
portal/views/portal.py

* modified `/staff-registration-email/<int:user_id>` call to return `{"subject": MailResource.subject, "body":MailResource.body}`, instead of a non-mail asset
* updated profile_macros code accordingly (no longer need to generate most of the html in the profile)

Use MailResource for staff registration email, update profile call accordingly

---

portal/models/questionnaire_bank.py
tests/test_questionnaire_bank.py

https://www.pivotaltracker.com/story/show/150112352
* exclude org name (IRONMAN, CRV) from QB visit status
* flip month display around ('X Month' -> 'Month X')
* updated tests to look for new visit name display format

Exclude org name from QB visit status

---

portal/config.py
portal/factories/app.py
portal/models/communication.py
portal/models/message.py

* Use standard `MAIL_DEFAULT_SENDER` config value (Flask-Mail, Flask-User)
* Remove explicit configuration (Flask-Mail, Flask-User fallback to `MAIL_DEFAULT_SENDER`)
* Set "from" address from existing config values (`SERVER_NAME`)
* Remove bad defaults
* `DEFAULT_MAIL_SENDER ` (typo of `MAIL_DEFAULT_SENDER`)
* Blackhole/unchecked email addresses
* `MAIL_USERNAME ` (SMTP config)

Cleanup email config

---

portal/models/assessment_status.py
portal/tasks.py
portal/views/user.py

Add more trace details when looking up QuestionnaireBank status.

Clean up duplicate methods - correct one instance w/ bad call.

---

portal/static/js/main.js
portal/templates/initial_queries.html
portal/templates/profile_macros.html

@mcjustin Justin, I stumbled upon this,  when I was in the initial queries page.   It seemed I couldn't check the 'no' or 'unknown' option for the biopsy question anymore.
I traced back and found the culprit code - that was added in this PR that addressed Firefox specific behavior a little while ago:
https://github.com/uwcirg/true_nth_usa_portal/pull/1475/files
This PR should fix the issue.  And I think this should be added as a hotfix. I see this is affecting demo and production.
The fixes are:
- instead of setting "checked" property of biopsy question to false, simply display the biopsy date input fields if the biopsy question is checked.
- allow data-trigger-event attribute, if specified, to be used to specify event type that triggers an event
- remove white spaces in comments

fix biopsy q ui issue - allowing checking of no/unknown questions

---

portal/models/intervention_strategies.py

https://jira.movember.com/browse/TN-282
* updated the questionnaire due date displayed in the AccessStrategy HTML, to use the same logic as the communication emails.

pull more relevant due date for IntervStrat html

---

portal/templates/staff_profile_create.html

noticed loading spinner not showing when staff account is created.
- fixed typo of the button class that caused this.

fix typo in button class in staff account creation page

---

portal/templates/contact.html
portal/templates/gil/contact.html
portal/views/portal.py

https://jira.movember.com/browse/TN-261
* added `types` as input array on `contact.html` (both gil and non-gil) template render
* pulls in any `Organization.email` with a valid email address
* added 'Enquiry Type' dropdown to `contact.html` (both gil and non-gil)
* only appears if `types > 0` (aka, if there are actual options to choose from besides just the default
* always includes, and starts selected as, 'Other' option (which is the same as the configured default)
* modified `/contact [POST]` to grab the recipient from the `type` field on form from `contact.html` (or, if nothing found, use the configured default)
* throws an error if no `type` value found in the form AND no configured default value
* only uses `type` from form, if it matches an existing `Organization.email` (otherwise, …

TN-156 TN-263 display recipient types on form; pull recipient for msg

---

portal/static/js/main.js

address the erroneous error messages generated by recent get-portal-footer-html calls
- add dataType of "html" to the get portal footer call
- add text in error message to specify that this is a front end error

fix error reporting for get portal footer call, fix error reporting content

---

bin/docker-push.sh
bin/utils.sh

* Switch delimiter used by `get_docker_tags` from space to newline to avoid word-splitting ([common Bash Pitfall](http://mywiki.wooledge.org/BashPitfalls))

Switch delimiter

---

portal/tasks.py

* added invalidation step to `cache_assessment_status()`, on top of the refresh (refresh only works if the cache is already invalidated or expired)

Invalidate overall_assessment_status on task run

---

portal/gil/templates/gil/about.html

address story:  https://jira.movember.com/browse/TN-177
- enable links for Lived Experience and Exercise and Diet pages on GIL About page

fix inactive LE and E&D links on GIL about page

---

portal/static/js/main.js

address frontend errors generated by timed out ajax calls:
- specify default timeout period (5 seconds)
- add retry attempts (maximum 3 times) after failed attempt

specify timeout for ajax call and add retry attempts

---

portal/eproms/views.py

https://jira.movember.com/browse/TN-327
* brought back in code that got dropped during the blueprint refactoring, so that when logged in, ePROMs users see `/about` content that's specific to their user and org (if Patient or Staff)

TN-327 Fixing ePROMs terms

---

portal/static/js/gil.js

per comment from Rob in this story:
https://jira.movember.com/browse/TN-278
remove capitalize css from element containing intervention text in GIL side bar as the text itself is already capitalized where applicable.

text fix for exercise and diet text on gil sidebar

---

portal/models/reporting.py

* adding check for case where `qb.trigger_date(user) == None`

TN-136 Properly handle cases where no trigger_date found for user

---

portal/models/assessment_status.py

* adding check for case where `qb.trigger_date(user) == None` (this time, in the assessment_status, which is called as part of the LR variable generation model)

TN-136 Properly handle cases where no trigger_date found for user (again)

---

portal/templates/profile.html
portal/templates/profile_macros.html
portal/views/patients.py
portal/views/portal.py

https://jira.movember.com/browse/TN-335
* added API for generating Patient invite email content (only accessible to Staff, StaffAdmin, and Admin)
* modified profile logic
* no longer generates invite_email content before loading patient profile, which means...
* invite_email errors won't prevent the profile from loading
* the profile won't need to wait for the content to be pulled from LR and generated before loading
* the template code is _much_ cleaner (no longer need to pass the invite_email param through 10 different macros)
* now just makes a separate API call to new API endpoint when button is clicked (same as we're already doing for Staff registration emails)

TN-335 Move Patient invite email to API GET

---

portal/models/message.py
tests/test_portal.py

https://jira.movember.com/browse/TN-348
* removed extraneous `<!DOCTYPE html><html>` from header and `</html>` from footer in email body
* flask_mail Message (which we convert our EmailMessages to) already adds outside html tags to the body. Our current setup was causing the tags to get repeated, which was causing formatting issues within the email
* tested to confirm that (a) the bug was fixed (see TN-348 for full description of issue), and (b) the rest of the email rendered as expected
* updated unit tests to reflect lack of declaration in `EmailMessage.body`

TN-348 Fix email HTML formatting bug

---

portal/models/questionnaire_bank.py
tests/__init__.py
tests/test_questionnaire_bank.py

https://jira.movember.com/browse/TN-352
* changed `QB.trigger_date(user)` logic
* now always checks for (and returns, if found) the user's latest TX_date, before triaging based on QB type (org- or intervention-based) and looking for other potential trigger dates
* added robust unit tests for `QB.trigger_date(user)`
* also updated `add_procedure()` and `consent_with_org()` test methods, to include a `setdate` param (for when the tests require an exact date)

TN-185 TN-352 Use TX date for trigger date on org QBs as well

---

portal/templates/profile_macros.html

saw this in safari when testing:
hide the manual entry modal on leaving the profile page.

hide manual entry modal on page change

---

portal/factories/app.py
portal/models/organization.py
portal/views/patch_flask_user.py
tests/test_patch_flask_user.py

the make_safe_url function in flask_user to correctly reassemble
the url after stripping out the scheme and net location.
NB - I will also file a bug/PR with flask_user so this gets fixed upstream.

Fix for https://jira.movember.com/browse/TN-384 - patch

---

portal/static/js/admin.js
portal/views/patients.py

https://jira.movember.com/browse/TN-392
* if Staff User has a preference list (aka, have used the 'Filter list by site' dropdown in the UI), selected orgs should now be restricted based on user's orgs (and children).

TN-392 Fix org access of staff using preference list

---

portal/gil/templates/gil/decision-support.html

https://jira.movember.com/browse/TN-331
* update Decision Support START button behavior when not logged in on /decision-support page
* no longer shows as inactivate (dull)
* now has same logic as the START button at the top of the page (brings up registration modal)

TN-331 Activate Decision Support START button for non-users

---

portal/views/user.py
tests/test_questionnaire_bank.py

https://jira.movember.com/browse/TN-399
* added new GET endpoint for retrieving user's most current QuestionnaireBank data (including iteration #, recur JSON, and relative start date, when available)
* includes optional `?as_of_date=%Y-%m-%d` param, for checking past QB situations based on specific backdates
* added unit tests (and made minor pep8 fixes to some existing tests)

TN-333 TN-399 API endpoint for current user QB

---

portal/templates/initial_queries.html

saw footer content rendered before the main content in initial queries:
fix is to increase the timeout period a few milliseconds more

add timeout to allow document DOM to load in initial queries

---

portal/eproms/views.py
portal/gil/views.py

https://jira.movember.com/browse/TN-403
* updated /terms logic (for both ePROMs and TNUSA/GIL), so that StaffAdmin users are shown the 'staff' terms

TN-280 TN-403 Staff terms for StaffAdmins

---

portal/views/assessment_engine.py

* Allow `QuestionnaireResponse.authored` to be overridden with `authored` QS param passed to `present-assessment` API
See [TN-387](https://jira.movember.com/browse/TN-387)
Merge before #1626

Expose QuestionnaireResponse.authored as QS param

---

portal/templates/coredata.html

saw this when testing
on coredata page 
- add loading indicator when continued button it is clicked
- disabled the continue button when it is clicked (was hidden)

fix display of continue button

---

portal/migrations/versions/9e5c1c6c4d64_.py
portal/models/user.py
portal/models/user_consent.py
portal/static/js/main.js
portal/views/patients.py
portal/views/user.py
tests/test_consent.py

https://jira.movember.com/browse/TN-342
* added 'status' field to UserConsent model
* restricted to `('consented', 'suspended', 'deleted')` values
* required; defaults to 'consented'
* added to JSON methods
* migration for new UserConsent.status field
* defaults to 'consented'; sets to 'suspended' or 'deleted' depending on `UserConsent.options` or `UserConsent.deleted_id`
* added new `/user/<user_id>/consent/withdraw [PUT, POST]` endpoint
* only requires user_id (in path) and organization_id (in JSON) - similar to consent [DELETE]
* replaces existing valid user/org consent with a matching one, minus the following changes:
* status = 'withdrawn'
* include_in_reports = True
* send_reminders = False
* staff_editable = False IF config['GIL'], else True
* updated patients list to only include …

TN-342 Update UserConsent model/api; omit withdrawn from TNUSA staff patients

---

portal/models/reporting.py

https://jira.movember.com/browse/TN-396
* modified overdue questionnaire reporting logic, so that we ONLY count users with the Patient role (while still ignoring any Patients that also have the Test role)

TN-396 Only count patients for overdue stats

---

portal/models/communication.py

* added exception handling to `Communication.generate_and_send()` function
Discovered issue during testing on https://stg-eproms.us.truenth.org for TN-369 (same issue, but for site summary email) - malformed email addresses cause the entire `send_queued_communications` task to break (see current status of that job in /scheduled_jobs ).
Modified the process, so that a malformed email address is properly caught and won't break the entire task. Note that when a Communication encounters this error, it will:
* log an error
* write an audit entry (to replace the one normally created by `Message.send_message()` after a successful send) showing the error
* set the Communication status to 'aborted' (so we don't continue to send erroneous emails)

Properly Handle RecipientsRefused error in Communication model

---

portal/templates/profile_macros.html

address: https://jira.movember.com/browse/TN-419
fix instruments list passed to assessment engine for backdated eproms paper entry.
@ivan-c Ivan, let me know if you see any issue with assessment link I built.  I was trying to address Diana's comment:  _"..was expecting to see all IRONMAN instruments for a 'date of completion' within a PROMs window."_  I passed in all questionnaires listed in the current questionnaire bank in format "instrument_id=[q]".

fix instruments list in assessment link for paper entry

---

portal/config/eproms/Coding.json

For ePROMs, need the 'Other primary treatment' option - was mislabeled.
Fix for detail in https://jira.movember.com/browse/TN-185?focusedCommentId=115022&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-115022

Corrected mislabled 'Other primary treatment' option in ePROMs.

---

portal/models/reporting.py

https://jira.movember.com/browse/TN-393
* modified intervention reporting, so that 'community_of_wellness' intervention shows up as 'Community of Wellness' (instead of the actual description 'Exercise and Diet')

TN-393 Use unique name for CoM intervention reporting

---

portal/models/assessment_status.py
portal/templates/profile_macros.html
portal/views/assessment_engine.py
tests/test_assessment_status.py

Adding new /present-needed API endpoint to dynamically compute which instruments a user needs to complete, and which are partially complete.
Using this endpoint for manual entry to get the correct set of instruments regardless of users completion status, etc.
Hopefully, the final detail for https://jira.movember.com/browse/TN-333

Present needed assessments

---

portal/static/js/accountCreation.js

fix recent returned errors when reporting error
- fix the context of "this" when reporting user id in an ajax callback

fix this context in account creation JS

---

portal/config/eproms/Coding.json
portal/config/gil/Coding.json
portal/migrations/versions/875b743d457f_.py
tests/test_communication.py

https://jira.movember.com/browse/TN-436
* remove the Default Coding object from config files
* migration to remove existing Default Coding objects from DBs
* removes Default Coding object + related CodeableConcept object
* sets any `Organization.default_locale_id` that pointed to the Default Coding, to `None`
* sets any `User.locale_id` that pointed to the Default Coding, to `None`
* downgrade restores the Default Coding/CodeableConcept (but does _not_ point any user/org locales back at Default, as we have no way of differentiating between user/org locales that were always `None`)
**NOTE: Please allow for unit tests to completely finish before merging**

TN-436 cleanup Default Coding

---

portal/views/user.py
tests/test_assessment_status.py

Need as_of_date (when not none/now) to accurately calculate the expiry.

One more case where we need to include as_of_date in expiry lookup.

---

portal/models/fhir.py

Using logger.warn for a minor issue being actively addressed.

Logging errors during site_persistence causes deploy problems.

---

portal/date_tools.py
portal/models/assessment_status.py
portal/models/communication.py
portal/models/communication_request.py
portal/models/intervention_strategies.py
portal/models/questionnaire_bank.py
portal/models/recur.py
portal/models/reporting.py
portal/tasks.py
portal/views/assessment_engine.py
portal/views/user.py
tests/test_assessment_status.py
tests/test_fhir.py
tests/test_questionnaire_bank.py
tests/test_recur.py

Require as_of_date in assessment status calculation methods
(Found several occurances where it wasn't being passed through as needed)
Fixed bug this demonstrated from the tests WRT timezone aware dates (after parsing with FHIR_datetime.parse they should be forced to UTC and timezone unaware).

When entering backdated assessments, treat in_process as new.

---

portal/models/user.py
tests/test_user.py

established during the original account promotion.
Fix for https://jira.movember.com/browse/TN-423

During account promotion, exclude timezone so we retain the one

---

portal/models/assessment_status.py
tests/test_assessment_status.py
tests/test_communication.py
tests/test_intervention.py

https://jira.movember.com/browse/TN-298
* updated AssessmentStatus lookup of QuestionnaireResponses, to query based on the relevant QB (we're already assigning QNRs to QBs, just weren't utilizing that info in the lookup)
* updated unit tests to properly test QNR-QB assignment/lookup (e.g. `mock_qr()` now actually sets a QB for the QNR, so the lookup mechanism actually has something to query against)
* cleaned up unit tests (e.g. `mock_qr()` had a user_id param, but in 100% of cases was just using `TEST_USER_ID`, so param wasn't actually needed)

Use QB to pull QNR for AssessmentStatus

---

portal/models/fhir.py
portal/models/intervention_strategies.py
portal/views/assessment_engine.py
tests/test_assessment_status.py

Provide the assessment engine with the actual identifier value from the QuestionnaireResponse for more reliable session behavior.

Fix for TN-453 - `resume_identifier` rather than `resume_id`

---

portal/celery_worker.py
portal/models/scheduled_job.py
portal/static/js/scheduledJobs.js
portal/tasks.py
portal/templates/scheduled_jobs_list.html
portal/views/scheduled_job.py
tests/test_scheduled_job.py

https://jira.movember.com/browse/TN-337
* major modifications to the `/scheduled_jobs` UI
* cleaner formatting
* new 'active' toggle, to easily activate/inactive jobs
* entries will now fade out and disable after being run/modified, until API response is returned (to avoid multiple triggers)
* moved all scheduled task logic to decorator (`@scheduled_task`)
* updated existing tasks to use new decorator (now _much_ cleaner/simpler)
* added `ScheduledJob.active` check logic
* Celery will still "run" inactive jobs, but (a) the actual task functionality won't kick off, and (b) the `last_runtime` and `last_status` fields won't be updated. Instead, Celery will just log that the task ran, but nothing happened, as the job was marked as inactive.
* updated tasks to take `job_id` as a kwarg, instead …

TN-337 ScheduledJob 'active' check & additional enhancements

---

portal/models/questionnaire_bank.py
tests/test_questionnaire_bank.py

https://jira.movember.com/browse/TN-491
* updated `QB.trigger_date` logic so that, per Mo request, for ResearchProtocol-based QBs the treatment date (TX) is only used if the QB recurs
* updated relevant unit tests accordingly
* cleaned up `QB.trigger_date` structure & comments to improve readability

TN-491 Only use TX for RP QB triggerdate if QB recurs

---

portal/migrations/versions/ffc71c89282f_.py

* added migration to assign existing indefinite IRONMAN QNRs to the corresponding QB (via `QuestionnaireResponse.questionnaire_bank_id`)

Assign existing indefinite IRONMAN QNRs to corresponding QB

---

portal/models/assessment_status.py
portal/models/questionnaire_bank.py
portal/views/assessment_engine.py

Previously, we were only matching up QNR submissions that fit within the "most_current_qb" - adding logic for the indefinite case.

Handle QNR -> QB for the indefinite case

---

portal/models/auth.py
portal/views/assessment_engine.py

* Log current_user() out of Assessment Engine on survey completion (`/complete-assessment`)
* Also applies when "Take a Break" is used (follows same flow through `/complete-assessment`)

Log out of AE after assessment completion

---

portal/views/assessment_engine.py

* Redirect to `/` (from `/api/present-needed`) if no assessments needed

Present Nothing Needed - TN-434

---

portal/migrations/versions/59be0e4b2171_.py
portal/models/user.py
tests/test_consent.py

https://jira.movember.com/browse/TN-451
* updated consent audit logic
* existing consent audit comment changed from "Adding consent agreement" to "Consent agreement <consent_id> signed". Audit is otherwise unchanged (including timestamp)
* new audit (NOT pointed at by the consent) created on consent create, with a timestamp of `datetime.utcnow()`, and a comment of "Consent agreement <consent_id> registered".
* created migration to change existing consent audit messages to match the new message
* added new and updated existing audit unit tests

TN-451 Modify consent audit logic

---

portal/views/assessment_engine.py

Should fix latest symptom in https://jira.movember.com/browse/TN-434
Previously, suspending work on the irondemog assessment would cause an error on session ID lookup, as we were looking in the users "current_qb", and the indefinite case is special

Lookup the indefinite QB when said assessment is being resumed.

---

portal/models/intervention_strategies.py

https://jira.movember.com/browse/TN-289
* changed the reminder text for the QB dashboard `intro_html`, depending on the `overall_status`
* 'Due' or 'In Progress' QBs still display same text as before, still using `calculated_due` for the date
* 'Overdue' QBs now display new text, using `calculated_expiry` for the date (see linked jira for details)
* fixed some minor existing pep8 formatting issues

TN-289 Update dashboard display for overdue QuestionnaireBanks

---

portal/static/js/initialQueries.js

address TN-534: https://jira.movember.com/browse/TN-534
allows user to scroll up/down after viewing terms 
Issue stemmed from animation in queue still resulted from invoking jquery's animate function. calling stop() function will clear it.

TN-534 fix scrolling issue on initial queries page

---

bin/deploy.sh
manage.py

* Only download Smartling translations during deployment if configured
* Add `flask config` command for printing Flask configuration values

Conditional Translation Download

---

portal/models/notification.py

* Do not set `Notification.created_at` in `as_json()` unless already saved in DB
* `Notification.created_at` defaults to GMT now, and cannot be `null`
* Returning `None` in `as_json()` when creating the empty/template JSON caused `null` to be saved to DB field

Fix Notification persistence issue

---

portal/static/js/main.js

I think I found the culprit - the call to get notifications on window.focus event in IE seems to execute in infinite loop

remove ajax call for notification on window unload/focus - this creates

---

portal/views/organization.py
tests/test_organization.py

As identifier.systems frequently use URLs, we must consume them properly (was generating a 404).  Extended test to catch this case.

API to lookup organization by identifier must allow path expressions

---

portal/static/js/main.js

remove duplicate keys when sending post data to set consent
@pbugni paul, per our cha t, this should fix the issue that you and justi n saw in the client side's post call to set consent

remove duplicate keys for consent post ajax call

---

portal/config/eproms/QuestionnaireBank.json

Note the same typo was found on both the `IRONMAN_recurring_6mo_pattern` and the `IRONMAN_recurring_annual_pattern` recurring questionnaire banks.

Fix for TN-544 fix typo s/months/days/ in IRONMAN recurring QB expiry

---

portal/views/organization.py

Both Apache and WSGI are getting in the way of passing `path:` parameters in the route.  Removing this error prone endpoint in favor of the organization search API where the `system` variable can reliably be encoded.
For context, see https://github.com/pallets/flask/issues/900

Remove `path:` parameters from route

---

portal/static/js/main.js

following up fix to https://jira.movember.com/browse/TN-573
address symptom of real issue:
Make sure the fade class is removed from modal when it is hidden (fade class is absolute-positioned occupying the entire screen - resulting in the screen unclickable).

TN-573 follow up fix to consent model fading issue

---

portal/static/js/gil.js

found this issue while testing - able to click on create account button when access code has been entered successfully and awaiting redirection to registration page..
Fix is to disable create account button to prevent race condition where pre-existing clinic is not properl y se t.

disable create account button when access code has been successfully

---

portal/models/reporting.py
tests/test_reporting.py

* added extra filters to Questionnaire summary report count functions, as to not include users with 'Expired' or 'Completed' as their `AssessmentStatus.overall_status`
* added unit tests for the above filter logic

TN-447 Filter QN summary report counts on overall_status

---

portal/config/eproms/ScheduledJob.json
portal/tasks.py
tests/test_tou.py

Eliminate confusion - use orgs not research protocol for selecting set of users for which to deactivate a terms of use agreement.
Addresses problem raised in https://jira.movember.com/browse/TN-535

orgs not research protocol for deactivate filter

---

portal/exercise_diet/views.py

found this issue while testing - 
menu items were off due to the absence of user parameter.
@ivan-c Ivan, another one for this release

exercise and diet portal page - need to pass in user parameter

---

portal/models/user.py
portal/views/demographics.py
tests/test_demographics.py

MUSIC reported they couldn't alter email via /api/demographics.
Confusion surrounds the two places where this appears - in `identifiers` and in `telecom`.
Now documented (in swagger) and reports usage error if such change is attempted in `identifiers`.
`telecom` has always worked - added test to prove it.

Fix for TN-648

---

portal/views/practitioner.py
tests/test_practitioner.py

* resolved issue on practitioner PUT, where updating with the same external identifier info was returning a duplicate identifier error (now works as expected)
* added unit test for the above scenario

Fix practitioner PUT issue

---

portal/gil/templates/gil/base.html
portal/templates/portal_wrapper.html

* added user role (codified/simplified to 'test', 'staff', or 'patient', or nothing) + org (in case of multiple orgs, just the first one found) to piwik push, using CustomDimensions

TN-631 Track Role & Org data in piwik

---

portal/views/assessment_engine.py
tests/test_assessment_engine.py

* added check to QNR POST endpoint, to abort (400) if the request json is missing the `questionnaire` element
* added unit test for above scenario

QNR POST - Abort on missing `questionnaire` element

---

portal/models/user.py
portal/views/clinical.py
tests/__init__.py
tests/test_assessment_status.py
tests/test_clinical.py
tests/test_communication.py
tests/test_intervention.py
tests/test_questionnaire_bank.py
tests/test_site_persistence.py

Previously, the shortcuts were overlooking this detail, and although the value
quantity would return the set value, the status value of `unknown`
needs to be respected for when the user's value isn't yet known.
Was previously only working when setting the observation by id.
Extensive test coverage.  Will be further tested by CofW integration folks on the test system once rolled out.

TN-666 Include status in observation handling for all APIs. 

---

portal/models/user.py

Ran into this when using the pca_localized shorthand API:
```
Exception on /api/patient/10800/clinical/pca_localized [POST]
File "/srv/www/truenth-test.cirg.washington.edu/portal/env/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
File "/srv/www/truenth-test.cirg.washington.edu/portal/env/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
File "/srv/www/truenth-test.cirg.washington.edu/portal/env/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
File "/srv/www/truenth-test.cirg.washington.edu/portal/env/local/lib/python2.7/site-packages/flask/app.py", line …
```

Fix minor typo in Observation model

---

portal/models/assessment_status.py
portal/models/questionnaire_bank.py
tests/test_questionnaire_bank.py
tests/test_reporting.py

* updated `QuestionnaireBank.qbs_for_user()` logic
* if a user has an _open_ QuestionnaireResponse (meaning, not 'Completed', 'Expired', or 'Partially Completed') for a QuestionnaireBank/ResearchProtocol, even if that QB/RP is not active for the user's org (aka the org has moved on to a newer QB/RP), `qbs_for_user()` will still return the outdated QB/RP until the QNR is closed
* general cleanup of method code
* added optional `qb` param to `QuestionnaireBankDetails` init, to allow `qbs_for_user()` to check the overall_status without cyclical calls
* pep8 fixes for assessment_status and questionnaire_bank models
* extensive unit tests for new QB/RP/QNR logic
* minor fix for issue in reporting unit test

TN-440 Proper handling of outdated yet in-progress ResearchProtocols

---

portal/templates/portal_wrapper.html

seeing a "trueNTHHeader.js:60 Uncaught ReferenceError: truenth_authenticated is not defined" js error in staging Liferay 
made the fix to put the variable back so it is available to LR

add back js variable needed by LR

---

portal/models/assessment_status.py
portal/models/intervention_strategies.py

* resolved an issue with `card_html` generation when `AssessmentStatus.top_organization == None`
* this is only an issue now because of the recent changes to the `most_current_qb()` logic, where a user with an open QNR for a QB can stay on that QB even after it's no longer referenced by an org

Fix TN-678 issue with card_html generation when no top_org found

---

portal/models/assessment_status.py

Inadvertently removed the top-level lookup when patching TN-678
This fixes the bug that created, TN-690

Fix TN-690 - show top level org on patient dashboard

---

portal/models/questionnaire_bank.py

this will resolve the production emails from the `prepare_communications` task.
(I'll subsequently add unit tests to confirm this case doesn't regress its way back in)

Safeguard intervention associated qbs from duplicate inclusion

---

portal/models/questionnaire_bank.py
tests/test_questionnaire_bank.py

This slipped through testing mostly due to alert fatigue.  Removed check to only log error on prod so this is seen earlier - in fact if it happens in testing, we'll now get an exception and therefore a failed test.

TN-717 fix to avoid duplicate qb by intervention

---

portal/factories/app.py
portal/models/reporting.py
portal/tasks.py
portal/views/reporting.py
tests/test_reporting.py

Refactored reporting methods out of tasks module.
Added view for custom one off code previously being run by developers anytime we needed to verify counts.  Also added view to see email content generated by scheduled job.
Log in as admin to generate cvs data previously generated by hand:
`GET /admin/overdue-numbers`  # generates a csv download - slow!
Admin, staff or staff admin can see email content - will restrict output
counts to user's orgs:
`GET /admin/overdue-table?org_id=20000`  # for IRONMAN
`GET /admin/overdue-table?org_id=10000`  # for TNGR

TN-761 Adding reporting views.  

---

portal/eproms/templates/eproms/resources.html

use title of LR item instead of tag to display the name for the resource item
@mcjustin Justin, as per today's demo, we use **title** of LR item to identify each item on the resources page so Diana/Kelly can change as they see fit.
Example json returned from Liferay for resources items:
https://stg-lr7.us.truenth.org//c/portal/truenth/asset/query?anyTags=ironman%20work%20instruction

TN-529 use title to list resource items

---

portal/models/user.py
tests/test_user.py

As part of the `get_user_or_abort` refactor, handle null inputs.
This addresses server error log emails such as the following stack:
```
Exception on /challenge [GET]
File "/srv/www/stg-eproms.us.truenth.org/portal/env/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
File "/srv/www/stg-eproms.us.truenth.org/portal/env/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
File "/srv/www/stg-eproms.us.truenth.org/portal/env/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
File "/srv/www/stg-eproms.us.truenth.org/portal/env/local/lib/python2.7/site-packages/flask/ …
```

handle nulls in user lookup

---

portal/models/identifier.py
tests/test_demographics.py

Confronting error email - this minor error leads to locking out subsequent demographic updates.
Error email example:
```
Received error {'actor': 'user 12236',
'message': u'Error generated in JS - [Error occurred processing request]  status - 400, response text - <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>400 Bad Request</title>\n<h1>Bad Request</h1>\n<p>\'value\' field not found for identifier</p>\n',
'page_url': u'/api/demographics/12236',
'subject_id': u'12236'}
```

Safeguard from empty string insertion in identifiers (leads to locking

---

portal/config/eproms/Intervention.json
portal/config/gil/Intervention.json
portal/models/intervention.py
portal/views/intervention.py
tests/test_intervention.py

In order to control which interventions and on which set of users to send expanded event for user_docuements, we need a MUSIC intervention.

TN-796 fix.  Need music intervention for event push.

---

portal/static/js/main.js

re-worked front-end logic so that empty strings won't be saved for identifiers (e.g. study id, site id

Frontend identifiers saving fix

---

portal/date_tools.py
tests/test_clinical.py
tests/test_demographics.py
tests/test_fhir.py
tests/test_tou.py
tests/test_user_document.py

Although the [FHIR spec](https://www.hl7.org/fhir/datatypes.html#dateTime) seems to imply the timezone portion of a datetime string is optional, this is giving integrators (such as MUSIC) trouble.
We'll now always include time zone info, it'll always be in UTC, and it'll always be in ISO FORMAT.
NB - this will affect ALL APIs producing datetime strings in their output, and this change should clearly be communicated to all API consumers.
This should resolve https://jira.movember.com/browse/TN-810

TN-810 fhir datetime output includes time zone

---

portal/date_tools.py
tests/test_fhir.py
tests/test_tou.py

ArborMetrix is using a parser that can't handle more than 3 digits of accuracy, and w/o valid need for this level of precision, we opted to remove from display alone - microseconds continue to be persisted if provided.

Drop microseconds from FHIR datetime output

---

portal/config/eproms/AppText.json
portal/config/eproms/site_persistence_file.json
portal/config/gil/AppText.json
portal/config/gil/site_persistence_file.json

Obviously, these belong in the GIL config - moving over.
@mcjustin Sorry for this oversight - I believe I had run my tests from an eproms config (and therefore hit MUSIC config values), but this would mean we were not accessing the correct email content on stg.us.

MUSIC config settings belong in Truenth (GIL) config, not eproms.

---

portal/models/auth.py

Missed a detail in the client refactor out of auth.  This will resolve the error email such as:
```
File "portal/tasks.py", line 60, in call_and_update
output = func(*args, **kwargs)
File "portal/tasks.py", line 285, in token_watchdog
error_emails = token_janitor()
File "portal/models/auth.py", line 261, in token_janitor
'auth.client_edit', client_id=client_id, _external=True)))
File "/srv/www/stg.us.truenth.org/portal/env/local/lib/python2.7/site-packages/flask/helpers.py", line 333, in url_for
return appctx.app.handle_url_build_error(error, endpoint, values)
File "/srv/www/stg.us.truenth.org/portal/env/local/lib/python2.7/site-packages/flask/app.py", line 1805, in handle_url_build_error
File …
```

Fix bug in service token watchdog

---

portal/config/eproms/Organization.json
portal/config/gil/Organization.json
portal/config/model_persistence.py
tests/test_model_persistence.py

I was very careful to not modify anything, but simply to remove all of the default values from the organization.json files.
The process included generating database dumps of the affected tables before and after each step, and comparing results, using this script:
```
pg_dump --no-owner --table public.organizations > org.sql
pg_dump --no-owner --table public.organization_identifiers > org_ids.sql
pg_dump --no-owner --table public.organization_addresses > org_addresses.sql
pg_dump --no-owner --table public.organization_locales > org_locales.sql
pg_dump --no-owner --table public.organization_research_protocols > org_rps.sql
```
Also for reference, this is what a default org with nothing but the name set looks like:
```
{
"language": null, 
"identifier": [], 
"name": "Homer's Hospital", …
```

TN-829 cleanup org persistence

---

portal/models/next_step.py
portal/views/portal.py

Abort if given a `next_step` that's unavailable to the user.
Improve logging as well when capturing the `next` target.

TN-847 capture access/next-step abuse

---

portal/factories/app.py

* Hack to fix SQLA `InvalidRequestError` error, caused by a model not being imported explicitly
* Importing model explicitly would cause cyclic import errors

Add hack to fix cyclic imports

---

docker/docker-compose.yaml

* Wait for `web` container to be ready before starting celery beat
* Set DB env vars for celerybeat to use
* Todo: investigate why celerybeat connection to DB connection failed silently

TN-360 Fix celery beat in docker-compose

---

portal/config/eproms/Organization.json

all orgs (at all levels) currently have a default language set (via "language"). Not clear whether they can simply inherit from the parent or not... This commit changes that of some children to match their parent's (which I changed yesterday).

TN-543-suborg-locale-match-parent

---

portal/static/js/main.js
portal/templates/initial_queries_macros.html

I stumbled upon this issue when I was testing in eproms - I think this stemmed from refactoring of initial queries template - I found that the terms checkbox is checked even though not all items had been agreed upon
- put in the check to checking checkbox only if all terms items are agreed upon
another issue found when testing was reset password email get sent twice 
- add fix to stop event bubbling up to parent element 
Tested this in both eproms and truenth to make sure everything is copacetic
*for this release*
@ivan-c  ivan, FYI

bug fix - initial queries fix for eproms

---

portal/static/js/initialQueries.js
portal/static/js/main.js
portal/templates/initial_queries_macros.html

did some clean-up of initial queries code
- remove unnecessary code
- add check to prevent duplicate submission of tou consent
- use config variable instead of role of patient to display subject specific element

initial queries code clean-up

---

.travis.yml
bin/docker-build.sh
docker/Dockerfile.build
docker/docker-compose.build.yaml
docs/source/docker.rst
tox.ini

* Do not explicitly set branch to build docker artifacts from
* Fix for branch/remote error for "pr" builds of pull-requests
* Fail build if build-artifacts job fails

Use current branch for building docker artifacts

---

portal/config/config.py
portal/migrations/versions/bd9a3f60b2c3_.py
portal/models/user.py
portal/views/auth.py
tests/test_user.py

Add `is_registered` method to user class for easier & consistent handling of pre-registered roles.
Capture user password change event and remove special pre-registered roles.

TN-513, TN-957, TN-955

---

portal/views/portal.py

@ivan-c you'll now be able to call `/api/settings/PRE_REGISTERED_ROLES` if you want to keep the code in sync, that checks for user roles to determine if they have registered.  Presence of any of those returned in the user's roles (in `/api/demographics`) means they have *NOT* yet registered.
Example return:
```
{
"PRE_REGISTERED_ROLES": [
"access_on_verify", 
"write_only", 
"promote_without_identity_challenge"
]
}
```

TN-565 Extend api/settings to include PRE_REGISTERED_ROLES

---

docker/Dockerfile.build

* Workaround current [issue with pip >= 10](https://github.com/pypa/pip/issues/5240)

Don't upgrade system-installed version of pip

---

portal/static/js/i18next-config.js
portal/templates/patients_by_org.html
portal/templates/staff_by_org.html

-add lookup function to i18next config to allow frontend to lookup translated text for missing key
-load sourceData to sessionStorage for lookup
-add missing translation tags ("row per page" in pagination) on patients/staff list

add lookup for text in i18next config, fix missing translation tags

---

portal/views/portal.py

The newer string format, when passed to gettext left the variable in place, i.e. `{org_name}`, which lead to app_text errors.

TN-994 gettext can't handle newer string format - revert to old syntax.

---

portal/gil/views.py

This corrects the error log emails such as:
```
Exception on /privacy [GET]
File "/srv/www/us.truenth.org/portal/env/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
File "/srv/www/us.truenth.org/portal/env/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
File "/srv/www/us.truenth.org/portal/env/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
File "/srv/www/us.truenth.org/portal/env/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File …
```

TN-1022 Safeguard /privacy for anonymous viewers

---

portal/models/communication.py

"Unexpected exception in `send_queued_communications` on 5 : https://stg-lr7.us.truenth.org/c/portal/truenth/asset/mail?version=2.4&uuid=2c837970-71e3-d736-9d2f-626f417bbbad&languageId=de_CH contains unknown varables: First_name,Last_name"

TN-1020 Fix - error text now includes `languageId`:

---

docs/source/code.rst

* Add Open API documentation background
* Add schema reuse example
[More good examples](https://swagger.io/docs/specification/using-ref/)

Add schema/ref Open API example

---

portal/factories/app.py
portal/views/identifier.py
tests/test_identifier.py

As a workaround to PUT /api/demographics, this PR enables POSTing additional identifiers on user.

TN-1036 GET/POST identifier API

---

docs/source/configuration.rst
portal/factories/app.py

* Check for `base.cfg` inside `instance/` and load if present
* Allow config management software to set deployment-specific infrastructure defaults (eg `SERVER_NAME`, `EMAIL_`)

Add base config

---

portal/config/config.py

We should then remove any custom values in `application.cfg` and other .env files unless it *needs* customization.

Plug in new default for ERROR_SENDTO_EMAIL (the local cirg list)

---

portal/static/js/main.js

use session storage orgs list when possible - for performance - this will also be included in the JS refactor

use session storage when retrieve orgs list

---

portal/static/js/main.js

remove unencoded single/double quote from message sent to report-error api

fix frontend reporting error

---

portal/models/i18n.py

Strangely, the standard test for a key in a container isn't working on a redis session on the second call.  (as if the first lookup adds the key, sorta...)
Adding a safeguard test to confirm we get back a value to avoid the key error.

Protect null access in session variable.

---

portal/migrations/versions/0f1576a4e220_.py
portal/views/client.py

Remove WRITE_ONLY from service users.  This will enable service token renewal, again.

TN-1087 Hotfix/service users no special roles

---

portal/static/js/main.js

address TN-1126  https://jira.movember.com/browse/TN-1126
remove i18next tag from items from questionnaire json response - i18next mangled numeric text.  My guess is that it is related to the fact that i18next is treating text to be translated as a key, and it is using that key to find corresponding matching value - having a numeric value (e.g. 100, 150) as a key can therefore have unexpected results - because it is treated now as a index to an array, not key.

TN-1126 fix q responses rendering

---

debian/rules

* Don't use newest version of pip when building `portal` debian package
* Newer versions of pip (10+) prefer installing portal as wheel over egg (see below)
* `pkginfo` reads version metadata from egg (`portal.egg-info/PKG-INFO`)
* `pkginfo` can't read wheel package metadata (`dist-info` directory?)
Todo: 
* Figure out wheel packaging
* `python setup.py bdist_wheel`
[Pip 10.0 changelog](https://pip.pypa.io/en/stable/news/#id5)
>Installing from a local directory or a VCS URL now builds a wheel to install, rather than running setup.py install. Wheels from these sources are not cached. (#4501)

Pin pip version when building debian package

---

portal/config/eproms/AppText.json

Removes the following TNUSA content from ePROMs config:
* [Terms and conditions](https://stg-lr7.us.truenth.org/c/portal/truenth/asset/detailed?version=latest&uuid=68af03b7-813c-d93e-06d1-9702686744c8&editorUrl=true)
* [Privacy/legal](https://stg-lr7.us.truenth.org/c/portal/truenth/asset/detailed?version=latest&uuid=f2ea71f5-d47a-1a5c-130b-830b9bd785cf&editorUrl=true)
* [About Movember](https://stg-lr7.us.truenth.org/c/portal/truenth/asset/detailed?version=latest&uuid=abaa79be-6106-8409-d499-51a3f35c1dc5&editorUrl=true)
* [Terms of use](https://stg-lr7.us.truenth.org/c/portal/truenth/asset/detailed?version=latest&uuid=cbe17d0d-f25d-27fb-0d92-c22bc687bb0f&editorUrl=true)

Remove TNUSA content items from ePROMs

---

debian/rules
portal/__init__.py
portal/factories/app.py

* Define `__version__` attribute for `portal` module from [Distribution](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#distribution-objects) (using `pkg_resources`)
* [setuptools-scm example](https://github.com/pypa/setuptools_scm#setuppy-usage)
* Allow newest version of pip (10+) for dh-virtualenv
Todo:
* Fix remaining metadata supplied by `pkginfo`, but not by `pkg_resources` (eg summary, authors etc)

Get project version from distribution data

---

portal/models/organization.py

I'd like to capture more details and replace a failing assertion in response to a few error emails we've seen, such as:
```
Exception on /gil-interventions-items/10056 [GET]
File "/srv/www/stg.us.truenth.org/portal/env/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
File "/srv/www/stg.us.truenth.org/portal/env/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
File "/srv/www/stg.us.truenth.org/portal/env/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
File "/srv/www/stg.us.truenth.org/portal/env/local/lib/python2.7/site-packages/flask/app.py", line 1813, …
```

Replace failing assertion with exception including details

---

portal/static/js/sessionMonitor.js
portal/templates/portal_wrapper.html

found issue with reading cookie(s) from document.cookie in portal wrapper - it is not returning all cookies, due to this I think: https://stackoverflow.com/questions/1022112/why-doesnt-document-cookie-show-all-the-cookie-for-the-site
add the workaround so the cookie value will be used when present

portal wrapper - timeout cookie read fix

---

portal/views/auth.py

As per https://tools.ietf.org/html/rfc6749#section-3.3 , although one may request, use, require multiple "scopes", the argument/parameter is always passed in singular `scope` form.
NB - this DOES create a slight backwards incompatibility for partners consuming and parsing the `/oauth/token-status` results, as the returned JSON is now compliant, returning the list of scopes in the `scope` attribute.

TN-1153 use singular form of `scope` - resolve inconsistencies 

---

portal/models/user.py
portal/views/user.py
tests/test_auth.py
tests/test_user.py

Now confirming target user is `email_ready()` before sending them down a registration path they can't complete.

TN-1157 guard /api/user/register-now from invalid use

---

portal/static/js/profile.js
portal/templates/profile/profile_macros.html

Followup fix to https://jira.movember.com/browse/TN-1107:
Display reason/message for when send email buttons are disabled (reason provided from API)

TN-1107 display reason for not email ready status

---

portal/static/js/sessionMonitor.js

found this issue while testing:
session storage should be cleared when the session timed out on its own.

clear session storage if session timed out on its own

---

portal/models/assessment_status.py
portal/models/questionnaire_bank.py
tests/test_assessment_status.py

With a treatment date much older than the consent date, we hit an error due to a well hidden bug.
Now checking the trigger_date for each questionnaire bank as it's being processed, as they don't all use the same trigger_date logic (baseline vs. recurring, for example).

TN-1195 tx trigger date older than consent

---

portal/views/patient.py
tests/test_patient.py

overlooked a db.session.commit()
also added audit entries for both birthDate and deceased POSTs

TN-1104 hotfix birthDate POST

---

portal/models/research_protocol.py
tests/test_research_protocol.py

No front end use at this time, but at least we can now acquire the display version of the research protocol from the db for translation tables.

TN-1176 Add display_name property to research protocol.

---

requirements.txt

This resolves the warning seen lately when pulling requirements - I think developers should pull down these additional tools themselves if needed - not really project dependencies.

Remove dependencies added for debugging purposes.

---

requirements.txt

* Use python3-enabled [flask-dogpile-cache fork](https://bitbucket.org/SlippingAway/flask-dogpile-cache)
* Forked to [uwcirg and tagged](https://github.com/uwcirg/flask-dogpile-cache)

py3 flask dogpile cache fork

---

portal/config/model_persistence.py
portal/csrf.py
portal/dict_tools.py
portal/models/app_text.py
portal/models/client.py
portal/models/i18n.py
portal/models/lazy.py
portal/models/user.py
portal/views/client.py
portal/views/coredata.py
portal/views/reporting.py

* Rewrite imports to use py3 versions of modules
* `libfuturize.fixes.fix_future_standard_library` fixer
* Use `future` module until transition to py3 complete

Imports for py3 forward-compatibility

---

portal/views/patch_flask_user.py
tests/test_patch_flask_user.py

In 2to3 we picked up a buggy version of urlunsplit, that compares the type of the first arg with each successive arg in urlunsplit.  Work around this bug by using empty strings (same type as args returned from urlsplit) rather than None for clearing scheme and hostname from a URL.

Resolve error introduced in 2to3 urllib.parse.urlunsplit

---

portal/config/model_persistence.py
portal/csrf.py
portal/models/app_text.py
portal/models/client.py
portal/models/i18n.py
portal/models/lazy.py
portal/models/user.py
portal/views/client.py
portal/views/coredata.py
portal/views/patch_flask_user.py
portal/views/reporting.py

Add `isort` ignore directive to future imports to prevent re-sorting

Ignore future module in import sorting

---

portal/models/role.py

Correct error from PR #2244 
@ivan-c this was noticed on stg by @achen2401 - we're currently locked out of any view decorated with `@roles_required(ALL_BUT_WRITE_ONLY)`

ALL_BUT_WRITE_ONLY should simply be a list of role strings.

---

bin/deploy-docker.sh
docker/docker-compose.prod.yaml
docker/docker-compose.yaml

* Limit celery-worker CPU usage to .3 CPUs
* Prevent CPU spike and system alarm after deployment

Limit celery-worker CPU usage

---

portal/models/assessment_status.py
portal/models/intervention_strategies.py
portal/models/questionnaire_bank.py
portal/models/reporting.py
portal/views/reporting.py
tests/test_assessment_status.py
tests/test_questionnaire_bank.py

Modified several functions used in calculating assessment status on QuestionnaireBanks.  The QuestionnaireBank alone lacks details needed for recurring QBs - therefore the named tuple QBD is now being used to capture vital details.  (QBD was in use previously, but not consistently)

TN-1246 - always include iteration & recurs in QB calculations

---

.editorconfig
.travis.yml
portal/config/exclusion_persistence.py
portal/config/model_persistence.py
portal/config/site_persistence.py
portal/models/app_text.py
portal/models/client.py
portal/models/communication.py
portal/models/i18n.py
portal/models/lazy.py
portal/models/login.py
portal/models/user.py
portal/views/client.py
portal/views/coredata.py
portal/views/patch_flask_user.py
portal/views/reporting.py
tests/test_app_text.py
tests/test_date_tools.py
tests/test_exclusion_persistence.py

* Re-sort imports
* Combine `as` imports on same line, add configuration for `isort`
* Add directives to ignore py3 shims from linting/sorting

Fixup imports

---

tests/conftest.py
tests/test_date_tools.py
tests/test_integration.py
tox.ini

* Use `py.test` as the test runner for all tox environments except default (py27)
* Don't run selenium tests (tox `ui` environment) without `--include-ui-testing` option

Partially migrate test runner to py.test

---

portal/static/js/profile.js

found this runtime error in initial queries when testing:
check the existence of orgs in returned API before setting user orgs property

initial queries runtime error fix

---

portal/static/js/profile.js

address demo data caching issue on profile page 
as seen in a MedidataRave patient whose data is updated in one session

fix demo caching issue in profile page

---

portal/static/js/profile.js
portal/templates/profile/profile_macros.html

https://jira.movember.com/browse/TN-1265
Fixes are:
disabling send invite button until user selects a email type
disabling email type selector when user is not "email ready" e.g. no email address, dob, etc.

TN-1265 patient invite email button UI fix

---

portal/views/organization.py
tests/test_organization.py

As needed by Medidata/RAVE, extend `POST /api/user/<user_id>/organization` to enable mapping an organization's defaults for timezone and language to a user.

TN-1275 extend user/org api to copy org's timezone, language to user

---

.travis.yml
setup.cfg
tox.ini

* Start celery from TravisCI, outside of tox
* Filter warnings about using `localhost` as a domain for cookies during testing

Cleanup py.test

---

.travis.yml
portal/config/config.py
tox.ini

* Implement supporting configuration for parallel testing
* Configure worker database based on [worker name/index](https://github.com/pytest-dev/pytest-xdist#identifying-the-worker-process-during-a-test) (eg `gw0`, `gw1`)
* Read from `PYTEST_XDIST_WORKER` env var
* NB: a pre-existing DB is required for each worker
* Run using `--dist=loadscope` or `--dist=loadfile` to group tests sent to workers ([see docs](https://github.com/pytest-dev/pytest-xdist#speed-up-test-runs-by-sending-tests-to-multiple-cpus))
Full example invocation:
```
createdb portal_unit_tests0
createdb portal_unit_tests1
pip install pytest-xdist
py.test -n 2 --dist=loadfile
```

Parallel Testing WIP

---

portal/views/identifier.py

Now leaving the appropriate audit log:
```[2018-07-02 13:27:48,229] AUDIT in audit: performed by 956 on 1185: user: Added Identifier secondary http://us.truenth.org/identity-codes/external-study-id 146-01-05```
which also shows in patient's profile.

TN-1301 Audit generated on identifier POST

---

portal/views/organization.py

Now audits are being created on a call such as
```
curl -H "Authorization: Bearer $my_token" -H 'Content-Type: application/json' -X POST -d @${file} ${origin}/api/user/${user_id}/organization
```
with
```
{"organizations":[{"reference": "api/organization/11000"}]}
```

TN-1302 Audit generated on user organization POST

---

requirements.txt

Reverts uwcirg/true_nth_usa_portal#2393
@ivan-c I'm reverting this as it looks to have caused an error in `build-artifacts` that needs your attention.

Revert "Update pytest to 3.6.3"
