portal/config/eproms/AccessStrategy.json
PSA Tracker strategy now checks:
```
TNG Patient & ((Men with a positive PCa_localized) OR (Men without a positive PCa_diag))
```
=> TN-197 third round of access strategy check:

portal/static/js/main.js
Followup fixes to this story:
https://jira.movember.com/browse/TN-1284
- remove putClinical API function code as it is not used by frontend (use postClinical uniformly now)
- add clinical code enum for global access
=> TN-1269 followup fix and remove unused code

portal/config/eproms/Organization.json
…nter Northwestern University"
This is preventing Medidata from associating patients with either org that had the accidental duplicate ID.
=> TN-1329 Correct pcctc identifier for "Robert H..."

portal/eproms/static/js/resources.js, portal/eproms/templates/eproms/resources.html
followup fix to this story:  https://jira.movember.com/browse/TN-1259
dynamically set tab content container height based on content (e.g. video)
=> TN-1258 tab content height fix

.travis.yml, tox.ini
* Allow testing of any version of python3 installed (eg `tox -e py3`), instead of python 3.4 only
* Run tests against python 3.6 on TravisCI
=> Fixup py3 versioning in tox/TravisCI

portal/static/js/main.js
address clinical data submission error:
sending in string instead of integer for clinical code
=> hotfix: send string instead of integers for clinical data

portal/models/coding.py, tests/test_clinical.py
coerce to string for db varchar requirement.  this will resolve errors seen such as:
```
ProgrammingError: (psycopg2.ProgrammingError) operator does not exist: character varying = integer
LINE 3: WHERE codings.code = 111 AND codings.system = 'http://us.tru...
^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
[SQL: 'SELECT codings.id AS codings_id, codings.system AS codings_system, codings.code AS codings_code, codings.display AS codings_display \nFROM codings \nWHERE codings.code = %(code_1)s AND codings.system = %(system_1)s \n LIMIT %(param_1)s'] [parameters: {'code_1': 111, 'system_1': u'http://us.truenth.org/clinical-codes', 'param_1': 1}] (Background on this error at: http://sqlalche.me/e/f405)
```
=> sanely handle observations with int values

portal/views/user.py, tests/test_consent.py
Makes sense to do as a hotfix, just to prevent Medidata from repeating the error.
=> TN-1347 Don't allow future dates in consent API.

portal/models/assessment_status.py, portal/models/communication.py, portal/models/communication_request.py, portal/models/intervention_strategies.py, portal/models/organization.py, portal/models/questionnaire_bank.py, portal/models/user.py, portal/tasks.py, portal/views/assessment_engine.py, portal/views/user.py, tests/__init__.py, tests/test_assessment_status.py, tests/test_communication.py, tests/test_organization.py, tests/test_procedure.py, tests/test_reporting.py
This PR includes fixes for the following sub-tasks:
TN-1039 consult consent status before sending reminders
TN-1353 Extend assessment_status.overall_status to hand out `Withdrawn`
TN-1354 Extend intervention_strategies.update_card_html_on_completion for Withdrawn
TN-1355 handle `withdrawn` in /api/present-needed
=> TN-1033 & TN-1285 withdrawn patients

portal/static/js/initialQueries.js
saw this issue while test this story:  https://jira.movember.com/browse/TN-1328 in stg.us.
- seeing brief blank page during initial queries when registering as new patient
Fix is to hiding loading indicator until incomplete fields are checked and content displayed
=> fix brief blank screen issue during initial queries

portal/static/css/orgTreeView.css
followup styling fixes to this story:
https://jira.movember.com/browse/TN-1324
add padding to each individual org label
underline json link for readability
remove restriction on org containing element width
=> TN-1324 followup styling fixes

portal/models/assessment_status.py, portal/models/organization.py, portal/models/reporting.py, portal/models/user.py, portal/views/reporting.py, tests/test_organization.py
Refactored OrgTree().find_top_level_orgs() to return a set (resolves duplicate problem) and param for obtaining first item.
=> TN-1366 multiple orgs in same branch of tree raise errors

portal/factories/app.py, portal/views/patch_flask_user.py
TN-1376 replace flask_user's default send_email function with one that stores messages and uses consistent protocols as the rest of the system.
=> TN-1110 Flask User emails not in audit log

tests/test_recur.py
The workarounds added to `pytest.approx` calls (via PR https://github.com/uwcirg/true_nth_usa_portal/pull/2544) aren't necessary, as in this case, exact dates can be compared.
=> Test for exact dates rather than use `pytest.approx`

portal/views/user.py
Include time in start and expiry comparisons when looking up questionnaires for a user at `/api/user/{user_id}/questionnaire_bank`
=> TN-1410 Remove the `.date()` lookup when comparing as_of_date w/ QB dates

portal/eproms/views.py
address 500 server error generated when viewing resources page in EPROMS in this story:
https://jira.movember.com/browse/TN-1402
I think it is related to this change to simply LR request generation:
https://github.com/uwcirg/true_nth_usa_portal/commit/5c50698c0ea0bde17149ce22315bcddfcbb1a869#diff-9e0de5e6c307fdaa25d641fa8198feec
I made the corresponding fix to simply retrieving json result.
I think this fix is correct as I have tested it but I do appreciate feedback on this fix
=> TN-1402 fix json decoding error related to resources page

portal/config/eproms/AppText.json
* Remove `Data Sharing with UCSF Medical Center (DEPRECATED)` content item reference from ePROMs
* `$ORG consent URL` may have been partially replaced with `$ORG website consent URL`
=> TN-1392 Remove deprecated LR content

portal/templates/initial_queries_macros.html
issue raised related to this story:  https://jira.movember.com/browse/TN-1408
remove check for role as still needed terms core data items are determined via API.
=> TN-1408 remove check for role for terms requirements in initial queries

portal/static/js/sessionMonitor.js
followup fix to this story:  https://jira.movember.com/browse/TN-662
fix untranslated text by using placeholder element for default html display - onus is placed on the consumer to provide default content.
=> TN-662 translation fix - use placeholder element in session monitor js

docs/source/provider_authentication.rst, portal/models/flaskdanceprovider.py, portal/views/auth.py, tests/test_auth.py
ACTUAL:
Facebook auth fails when a user hides their birthdate or gender
EXPECTED:
Auth succeeds when birthdate or gender are hidden.
Change Summary:
- Moved parsing logic to common function
- Added tests for failing scenarios
- Updated documentation
Before these changes, Facebook and Google json were parsed in separate functions. I checked for birthdate and gender properly in Google's parser, but didn't do so in Facebook's (oops). In addition, neither parser was tested because they were hard to test. These changes move parsing logic to a common function which minimizes provider specific code and allows me to test parse logic using a mock. This should also make new providers easier to add in the future.
=> OAuth: Auth should succeed when birthdate and gender are not returned by providers

portal/static/js/admin.js, portal/views/patients.py
Followup fixes for story, TN-1252:
-fix server error related to retrieving assessment status for deleted user
-add reset view of table after deactivating/reactivating a patient account (i.e. reset rows displayed)
-re-init row event on search/filtering
-remove unnecessary else statement based on feedback from last PR
=> TN-1252 followup fixes including server error fix

portal/models/user.py, portal/views/auth.py, portal/views/extend_flask_user.py, tests/test_auth.py
Off by two, actually.  Zero index and strictly less than comparison.  Note, the failure is bumped AFTER the check if the current attempt is bad.
=> TN-977 correct off by one error

portal/config/eproms/AppText.json
address this story:  https://jira.movember.com/browse/TN-1459
fix eproms app text url reference to patient reminder email for TNGR
tested and worked in my instance
note the item existed in Liferay previously (content was last updated 6 months ago), the url reference just wasn't updated on the portal side
=> TN-1459 eproms reminder email LR url fix

portal/static/js/profile.js
address issue found when multiple ajax call to consent API is made upon no organization selection
- simply code for removing existing consent upon no org element selection - removing all valid consents via call to get valid consents instead of checking valid consent for each org individually
- remove extraneous ajax call to set email ready status (i.e. applicable only in profile)
=> no organization event binding fix

portal/config/config.py, portal/config/eproms/ScheduledJob.json, portal/config/gil/ScheduledJob.json, portal/models/assessment_status.py, portal/models/reporting.py
Dramatic cut back in frequency of scheduled jobs, to reduce the thrashing on stg*.
Bumped assessment cache to 2 hours.
Bumped reporting cache to 12 hours.
Eproms runs on the even hour:
:05 assessment cache update
:35 prepare communication
:55 send communication
9:00 (am & pm) reporting cache update
TrueNTH runs on the odd hour:
:05 assessment cache update
:35 prepare communication
:55 send communication
11:00 (am & pm) reporting cache update
=> TN-1485 Less frequent scheduled jobs

portal/config/config.py, portal/models/user.py, portal/views/auth.py, tests/test_user.py
https://jira.movember.com/browse/TN-1408
Problem:
When a patient is registered it's possible for their account to be promoted to a power user account (e.g. staff, admin, ect...)
Repo Steps:
Login as a staff member
Navigate to /patients (or use the menu and select the Patients menu item)
Create a new patient
Send that patient and invitation
Open the new patient's email and click the "verify account" button
Verify the patient's identity by entering in their name and DOB and clicking the verify button
Critical Step instead of registering the new patient, login as a staff member
 
ACTUAL BEHAVIOR:
Temp account created by the staff member is promoted to power user and the staff member's account is deleted
 
EXPECTED BEHAVIOR:
Failure - 400. Temp account should not be promoted to power user …
=> TN-1408 Prevent promoting a temporary account with a power user account

portal/views/portal.py, tests/test_portal.py
* Allow front-end access to /api/settings without being logged in
* Add test to prevent secrets from being exposed
=> Allow unauthenticated access to /api/settings

portal/models/identifier.py, tests/test_identifier.py
Fix problem noticed when a user w/ non-ascii chars in email address caused server error.
=> Sanely handle non-ascii identifier values.

portal/static/js/initialQueries.js, portal/static/js/main.js, portal/static/js/profile.js, portal/templates/initial_queries_macros.html, portal/templates/profile/profile_macros.html
followup fixes for this story:  https://jira.movember.com/browse/TN-1447
- add missing saving loading indicator (i.e. for clinics)
- simply code/ remove unused code
- allow orgs to be updated prior to submitting consent
=> TN-1447 saving loading indicator fix, clinical questions fix

portal/views/user.py, tests/test_user.py
The /unique_email API asserts when it finds more than one match for an email address. This throws a 500. Because the UI calling the API doesn't get a direct response, it allows the staff member to create a  patient with the duplicate email address.
These changes fail gracefully, returning False which allows the UI to pop up an error message that prevents a new user from being created.
This, however, is not a complete fix for TN-1418. It only prevents the UI from proceeding, but does not prevent a user from being created through the /account API. That work is fixed in this [PR](https://github.com/uwcirg/true_nth_usa_portal/pull/2629).
=> TN-1418: Handle multiple unique emails gracefully

tests/test_user.py
This single test ensures that example_@gmail.com is considered different from example-@gmail.com
[TN-1472](https://jira.movember.com/browse/TN-1472) was opened because underscores and dashes in emails were thought to be treated as the same character. I was not able to repro that issue and wanted to add this unit test in as a sanity check to make sure we catch this issue if it ever comes back.
=> TN-1472 Add test to ensure _ and - in emails are treated uniquely

portal/static/js/admin.js
noting this when I was testing - 
Admin table was referencing wrong field name when adjusting visibility of checkbox field (e.g. 'deactivatedstatus')
related to this story:  https://jira.movember.com/browse/TN-1253
=> fix wrong field reference in admin.js

portal/static/js/accountCreation.js
In account creation page, when ajax call to get orgs for UI population failed, it displayed error message, as I have tested.  This fix is to display error message for cases where no indication of error is returned (e.g. mixed up sessionStorage data) and UI is not populated.
=> display error on account creation when orgs UI is not populated

portal/static/js/profile.js
address feedback for this story:
https://jira.movember.com/browse/TN-1498
allow consent date for a patient to be editable in Test environment (applies to both IRONMAN and TNGR) as before for testing purposes
=> TN-1498 allow consent date be editable in Test environment as before

requirements.txt, tests/test_patch_flask_user.py
Flask-User performs case INsensitive lookups using the sql LIKE clause which uses ```_``` as a wildcard. In effect, searching for ```user_@example.com``` will find ```user1@example.com```. This not only causes unexpected behavior, it is also a potential security risk. I opened [this bug](https://github.com/lingthio/Flask-User/issues/234) to track this issue in the Flask-User repo.
I updated our fork of flask-user to properly do case INsensitive lookups with ```func.lower()``` in [this](https://github.com/uwcirg/Flask-User/commit/e316779b4ab331c00812878fcc9092cec0fa297b) change. The changes in this PR pull in the patch when ```pip install -r requirements.txt``` is run.
Once this PR is merged I'll submit a PR to flask-user.
=> TN-1472: Do not use '_' as a wildcard when looking up emails

portal/static/js/initialQueries.js
In initial queries - display error to user if agreement url or organization id is missing when submitting terms data
=> Initial queries add missing information check

portal/static/js/profile.js, portal/templates/profile/profile_macros.html
Found this issue while testing:
duplicate invite messages and loading indicators were being displayed while sending out invite for unregistered Music patient
Fix is to display only indicator/message for the specific email type being sent
=> invite email loading indicator/message display fix in profile

portal/migrations/versions/883fd1095361_.py
Helps to set current value of `uc` prior to use.
=> TN-1601 hopefully for the last time!

portal/config/exclusion_persistence.py
Discovered in testing eproms-test -> stg-eproms flow.  Any previously deleted service users would trigger on import:
> ValueError: can not update first_name on deleted user <id>
=> Do NOT included deleted service users in exclusion export.

portal/views/crossdomain.py
* Add `OPTIONS` to view `required_methods`
* See [*Small fix by Audrius Kažukauskas*](http://flask.pocoo.org/snippets/56/)
* Adapted from [flask-cors](https://github.com/corydolphin/flask-cors/blob/master/flask_cors/decorator.py#L117-L119)
NB: the `cross_domain()` decorator MUST come after the `route()` decorator otherwise it cannot modify the view function to add `OPTIONS` support
=> Fixup CORS Automatic OPTIONS Handling

portal/views/auth.py
Currently, when a user logs in through a provider our audit logs don't capture enough details. Specifically, we are not granular enough about user data that is changing. This PR provides more details in these audit logs by adding the following information.
- The information that was used to create a new user account when a user is logging in for the first time.
- The new image url that is used for the user after a successful login
Jira story: https://jira.movember.com/browse/TN-1595?filter=-1
=> [TN-1595] Update audit logs on provider login

docker/docker-compose.yaml
* Allow configuration of postgres image tag (ie version) by environment variable
* Set default postgres version (tag) to `10`
=> Pin postgres version; allow configuration by env var

portal/views/portal.py
Observed this behavior when sending out invite email to patient:
Error is displayed to user even though invite email **has been** sent. Tracing back and found that error occurred during the redirect call at the end of invite function.
Fix is to invoke the invite_sent function directly instead of invoking a redirect to the associated endpoint
=> fix timeout error occurred after email invite has been sent

portal/factories/app.py, portal/views/healthcheck.py, tests/test_healthcheck.py
These changes return a 200 status code when a successful JSON response is returned from the healthcheck API, despite if one of our dependencies is down.
Healthcheck by default returns a 500 when one of the dependent services is down. The 500 status code should be reserved for cases when "the server encountered an unexpected condition that prevented it from fulfilling the request" ([citation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500)). While one of our dependencies going down is not good, it does not mean the /healthcheck API was unable to fulfill the request. As long as we successfully process the request, despite the health of our dependencies, we should return a 200.
I considered submitting a pull request to Healthcheck since I think the default behavior is …
=> Always return 200 from /healthcheck

docker/docker-compose.yaml, manage.py
/healthcheck returns false until celery beat starts, which doesn't happen until after the web service starts. These changes ping the celery beat health check endpoint while celery beat is starting up to "trick" /healthcheck into thinking celery beat is running. In effect, this delays warnings a few minuets (based on LAST_CELERY_BEAT_PING_EXPIRATION_TIME).
=> TN-1642 Delay celery beat healthcheck warnings/errors

manage.py, portal/views/healthcheck.py, portal/views/portal.py, tests/test_healthcheck.py
PROBLEMS:
1) The celery health check returns true when celery failed to process jobs
2) Responses were not standardized which makes monitor code cumbersome
AFTER THESE CHANGES:
1) The celery health checks the result of a job using the celery_test API
2) Responses are standardized to make monitoring easier
=> Update celery health check and standardize responses

portal/static/js/utility.js
Saw this while testing - was seeing unnecessary ajax calls for configuration being sent off in system outage message rendering function in authenticated pages
- Fix is to add check for the presence of system outage element before sending off ajax call to get configuration variables
=> TN-1234 followup fix - fix call for config

portal/static/js/initialQueries.js
stumbled on this edge case when testing:  When self-registering as a patient affiliated with one of the Michigan clinics (MUSIC clinics), the next button does not display if **there is** still needed required core data.
Fix is to allow patient to continue via window reload as next button is not displayed by default in continue to next work flow.
https://jira.movember.com/browse/TN-1654 @mcjustin Justin, FYI
=> fix button not displayed issue for self-registered music patient

docker/docker-compose.flower.yaml
* Add optional docker-compose file for Flower
* Add to [`COMPOSE_FILE` env var](https://docs.docker.com/compose/reference/envvars#compose_file) in `.env` to enable
=> Add Flower Celery Monitor

portal/eproms/static/js/landing.js, portal/gil/static/js/index.js, portal/static/js/main.js, portal/static/js/utility.js
address: https://jira.movember.com/browse/TN-1503
The frontend fix is to prevent users from accessing cached pages in browser via Back button by manipulating the JS History object - clicking on the Back button will result in user staying on the current page
Changes' scope is narrowed to landing pages for eproms and truenth USA, respectively.  These are the pages the users land on upon logging out.
I myself have tested the fix in Chrome, Firefox, Safari and IE.
**History is cleared in the onclick event of logout button - narrowing down the scope further here**
=> TN-1503 prevent user from access cached pages - landing pages only

tox.ini
* Check for absence of `TRAVIS_PULL_REQUEST` env var before uploading extracted strings
* TravisCI runs a build of how the destination branch will appear after merging (`continuous-integration/travis-ci/pr`), where `TRAVIS_BRANCH` is correctly `develop`
TODO:
* Add flag to control whether or not upload actually occurs
=> Don't upload translations outside of develop branch

portal/static/js/flask_user/register.js
Found this while testing:
submit button remained disabled after re-typing correct password upon validation error  - the button is only enabled after removing focusing from the password field.
The fix is to check password validation on keyup - this will enable submit button immediately if the password is entered without validation error.
=> add event handler to check password validity on key up

portal/tasks.py
It's there if we want it, but we'd need to handle the exception rather than just let it lock up the service, as it interrupts any process when the timeout is exceeded.
=> Removed the soft_time_limit that causes nothing but thrashing.

docker/Dockerfile
* Expose gunicorn worker timeout as env var
* Remove pointless [keepalive option (ignored with sync workers)](http://docs.gunicorn.org/en/stable/settings.html#keepalive)
=> Expose gunicorn request timeout configuration as env var

portal/config/model_persistence.py, portal/models/app_text.py, portal/models/organization.py, portal/models/qb_status.py, portal/models/research_protocol.py, portal/views/reporting.py
Call any site persistence class implementing `invalidation_hook()` when a change is noticed on import.
Only use ATM is for an organization - resets any affected user rows in the qb_timeline as a form of invalidation.
Also cleaned up superfluous log noise on site persistence import - *finally* looks to be only reporting actual changes.
NB: we'd do well to merge this BEFORE #2842 (which is already merged into master).
=> TN-1735 Mechanism to reset cache on research protocol change

portal/models/qb_status.py, portal/views/patient.py, portal/views/reporting.py
See bug for details - as we add the `completed` status after the `due` row to qb_timeline, adding a second `order_by` criteria (qb_timeline.id) makes this case deterministic.
(Thanks @ivan-c for the idea!)
=> TN-1753 address status qb_timeline.at collision

portal/config/eproms/Organization.json
... for both 14701 "CHU de Quebec - Universite Laval", and 14669 "Tygerberg Hospital"
=> TN-1737-fix-language-syntax

portal/config/eproms/Coding.json
The organization_locale associations introduced in TN-1737 must be named in coding.json, or subsequent persistence runs will fail.
=> Add new South African language codes to `Coding.json`.

bin/gulp-wrapper.sh, debian/rules, docker/Dockerfile.build
* during package building process...
* Build and include front-end files
* Compile PO to MO files
* Remove progress bars when installing Python and NodeJS dependencies
* Remove changes to unneeded tracked files caused by `make-deb`
=> TN-1763 Build frontend translation files into debian package

tests/integration_tests/__init__.py, tox.ini
* If Sauce Lab settings present, run on Sauce Labs infra
* If `DISPLAY` environment variable set, run using current X session
* If `DISPLAY` environment variable missing, attempt to run in headless mode
=> Allow integration tests to run in graphical mode

docker/Dockerfile, docker/remap_envvars.py, tox.ini
* Make locale explicit ([fixes click issue](https://click.palletsprojects.com/en/7.x/python3/))
* Add py3k wrappers for scripts
Cut-over changes to py3k will remain in #2868
=> TN-1765 remaining py2/py3k compatibility

docker/docker-compose.yaml, portal/tasks.py, portal/views/healthcheck.py
* Set celerybeat health directly through redis (no http)
* Set celerybeat healthy as soon as redis available
=> Quicker celerybeat healthy

.travis.yml, bin/deploy-docker.sh, docker/docker-compose.build.yaml, docker/docker-compose.prod.yaml, docker/docker-compose.yaml, portal/factories/app.py, tox.ini
* Add healthcheck to docker-compose production override
* Do not (error) log healthcheck failures
* Log level is not configurable with [healthcheck module](https://github.com/Runscope/healthcheck/blob/1.2.0/healthcheck/__init__.py#L110-L112)
* Errors can be collected and reported to other, less severe channels
* Allows continuous probing of health (even when app starting) without flooding logs
* Start `web` service and check health before uploading artifacts, as part of CI
=> TN-1774 Add healthcheck to Dockerfile

tests/integration_tests/__init__.py
See 
[Debugging Tests with JavaScript Console Logs and HAR Files (Extended Debugging)](https://wiki.saucelabs.com/pages/viewpage.action?pageId=70072943)
=> Add extended logging on Sauce Labs

docker/docker-compose.yaml, docker/portal.env.default, tox.ini
* Remove unintentional env var overrides (`SERVER_NAME`, `SECRET_KEY`, `PERSISTENCE_DIR`) override from `docker-compose.yaml`
* Values in docker-compose.yaml files override `.env` files (ie `portal.env`) ([but not THE `.env` file](https://docs.docker.com/compose/environment-variables/#the-env-file))
* Create temporary `portal.env` file during testing
* Add docs
---
*Environment variable precedence*
> Compose file
> Shell environment variables
> Environment file
> Dockerfile
> Variable is not defined
See 
[Environment variables in Compose](https://docs.docker.com/compose/environment-variables/)
=> Fix docker-compose environmental variable precedence

README.rst, debian/rules, requirements.dev.txt, requirements.txt, setup.cfg, tox.ini
* Separate dev dependencies
* Move abstract dependencies to separate `dev` section in `extras_require`
* Move concrete dependencies to separate `requirements.dev.txt` file
* Remove nosetest
* Remove packaging workaround
See [setup.py vs requirements.txt](https://caremad.io/posts/2013/07/setup-vs-requirement/) for context
Todo
=> Separate dev dependencies

portal/static/js/src/admin.js, portal/static/js/src/modules/Global.js, portal/static/js/src/modules/Utility.js, portal/static/js/src/profile.js
address issue updating email in IE as reported by user:
The email field was relying on bootstrap library validator to validate input value - it will trigger update of email address if the value entered is valid.
However, when testing in IE,  I found that, at times, after a fresh page load of profile page, inputting an email value did not trigger validation - and therefore update.  The occurrence of issue isn't consistent enough that makes me wonder if it is a bootstraping issue (e.g. validator not attached to the element on page load) or simply a bug in the bootstrap validator.  
Attaching validation/update action code to the on change event directly to the email element solves the issue.  Issue only seems to be happening in IE.
Also changes include fixes for runtime error I saw in …
=> TN-1769 IE followup fixes

portal/templates/flask_user/emails/eproms_password_changed_message.txt
The password changed email text was still looking up the `count()` of what is now an already joined query.
=> TN-1830 error in password changed email generaion

portal/config/gil/Organization.json
TN-1838-unc-parent-tz (was undefined prev so defaulted to utc)
=> TN-1838-unc-parent-tz

portal/static/js/flask_user/register.js
Found this issue while testing another story:
When clearing error message related to custom validation for email input field, error display css class remained.
Fix is to remove the associated css class upon clearing error message.
=> registeration bug fix, remove has-error class for email input field when error message for has been cleared

portal/views/user.py, tests/test_user.py
We'll now catch "duplicates" in the unique email check, even if they're stuck in the __invited__ state.
=> TN-1799 - Invited user IDs not considered in unique email check

debian/control, docker/Dockerfile.build
* Fixup version generation
* Mask superfluous local changes (`debian/changelog`) causing `dYYMMDD` suffix in version
* Fixup checkout pattern
* Only list files needed from `make-deb` invocation
=> Fixup version generation; cleanup build process

portal/static/js/flask_user/register.js
Found this issue while testing:
noting that has error css class didn't disappear when re-entering value in input fields on registration page
Fix is to remove the error css class when value of input field changes via user action
=> registration JS bug fix

portal/models/qb_status.py, portal/models/qb_timeline.py, portal/views/patient.py, tests/test_assessment_status.py
This is very likely the source of the problem reported in https://jira.movember.com/browse/TN-1847  (can't reproduce to confirm, but I believe all of the queries adjusted *should* have this fix).
=> TN-1847 add QBT.id to queries ordered by QBT.at, due to collisions

portal/static/js/src/initialQueries.js, portal/static/js/src/modules/CONSENT_ENUM.js, portal/static/js/src/modules/Consent.js, portal/static/js/src/modules/OrgTool.js, portal/static/js/src/modules/Utility.js, portal/static/js/src/profile.js, portal/templates/profile/profile_macros.html
extracting out consent, orgs specific code from profile.js to be re-usable by others (e.g. initial queries JS)
- moving consent specific code to individual modules
- move org specific code from profile.js to OrgTool module
note, content of the code remains relatively the same, just moving around pieces
=> TN-1751 followup cleanup to Consent/orgs js code

portal/config/eproms/Organization.json
I'm quite sure that the default IRONMAN protocol is v3, but I did include that explicitly in the new org, and added it to the existing CA org that I'm editing here, for clarity.
=> TN-1843 IRONMAN: new org in CA; mod existing CA org

portal/static/less/portal.less
Found these issues when testing:
in Truenth USA:
select element for birthday field and that for biopsy date field have disproportioned font-size compared to others.
made styling fixes to address.
=> fix font-size styling issue of select element in initial queries in

portal/config/eproms/Organization.json
I'd missed this step at https://github.com/uwcirg/true_nth_usa_portal/pull/2971
=> TN-1843 remove PLACEHOLDER from org system ID URI

docker/Dockerfile, portal/config/config.py, portal/config/model_persistence.py, tests/test_site_persistence.py
* Move env var configs to flask configs
* Move defaults to `config.py`
* Use TrueNTH USA as default config (`PERSISTENCE_DIR`)
NB: `PERSISTENCE_DIR=eproms` is required to maintain an ePROMs configuration
=> Fixup project/product config

portal/static/js/src/initialQueries.js, portal/static/js/src/modules/Utility.js, portal/templates/initial_queries.html
found this issue while testing another:  at Initial Queries during registration, one was presented with a blank page before content faded in.
Fix includes:
delay fading out of loading indicator (by adding callback class on document body to indicate as such) to allow loading of body content on callback
create a Utility dedicated function for delayed removing loading indicator
=> initial queries - fix initial blank page display on loading

portal/static/js/src/profile.js
noting this issue when testing:
Organizations display was not updated in profile when user org(s) has been updated.  
Fix includes:
Refresh orgs display on callback when user orgs are updated.
=> in profile: update orgs display view when user org(s) have been updated

portal/static/js/src/admin.js
found this while investigating another issue:
a function call to obsolete method was generating runtime JS error
=> remove call to obsolete method in admin JS

portal/config/eproms/Organization.json
TN-1888-TN-1893-new-orgs-protocol explicitly set to v3 (note that these were never at v2, except for on dev&test (errantly) )
=> TN-1888-TN-1893-new-orgs-protocol

README.rst, requirements.dev.txt, tox.ini
Noticed this trick in another example.  Should mean any devs keeping their local builds up via `pip` are down to a single step: `pip install -r requirements.dev.txt`
=> pull base requirements.txt file as dev dependency.

README.rst, app.json, docker/Dockerfile.build, docs/source/contributing.rst, docs/source/docker.rst, portal/eproms/templates/eproms/about.html, portal/gil/templates/gil/base.html, setup.cfg
@ivan-c this should be all obsolete references *except* those I see in `portal/translations`.  I didn't update those, assuming that's a symptom - how is the repo string landing within?
=> Update source code repository URL to current value.

portal/config/eproms/CommunicationRequest.json
This replaces just the 3 month 3rd reminder (day of) for rp2 and rp3.  Open questions in https://jira.movember.com/browse/TN-703 should this be expanded to other cycles.
=> TN-703 replace content UUID for day of reminder on 3 month QB.

requirements.txt
* Revert billiard version to match one installed by celery
Currently `billiard` version `3.6.0` is listed in [`requirements.txt`](https://github.com/uwcirg/truenth-portal/blob/v19.2.25/requirements.txt#L14), but `celery` (installed from [`setup.cfg` abstract requirements](https://github.com/uwcirg/truenth-portal/blob/develop/setup.cfg#L42)) requires `billiard` be at least `3.5.0.5` ([see build log](https://travis-ci.org/uwcirg/truenth-portal/jobs/500511926#L1557))
=> Revert billiard update to version actually installed

requirements.txt
* Update to oldest version supported by our dependencies
NB: This will likely require re-testing OAuth setup on a deployment with it configured
Currently `oauthlib` version `1.1.2` is installed (see below), but `flask-dance` and `requests-oauthlib` require `oauthlib` be at least `2.1.0` ([see build log](https://travis-ci.org/uwcirg/truenth-portal/jobs/500511926#L1557))
```
$ docker-compose exec web pip freeze | grep oauthlib
oauthlib==1.1.2
```
=> Remove pin on oauthlib

docker/docker-compose.dev.yaml, docs/source/docker.rst
* Add `docker-compose.dev.yaml` (Add to `COMPOSE_FILE` (in `.env` ) to enable)
* Use flask dev server, enable debugging
* Mount git checkout into container as volume to allow auto-reloading development
* Add docs
=> Add docker-compose development overrides

portal/static/js/src/components/PsaTracker.vue, portal/static/less/psaTracker.less
https://jira.movember.com/browse/TN-1945
address the issue where data points were drawn beyond visual area.
changes include: 
- since the graph is drawn in log scale, need to account for value(s), e.g. < 0.1 that caused invalid log value  - in which case use the minimum allowable log value (0.1)
- grid line needs to be capped at maximum allowable range for PSA tracker values (10000) (otherwise seeing extra line drawn)
- allow edit of treatment date only if it is possible (the section is only shown in profile, where treatment is edited, in Truenth USA)
=> TN-1945 Psa Tracker Graph bug fixes

tests/test_scheduled_job.py
See test fail log:
```
=================================== FAILURES ===================================
____________________ TestScheduledJob.test_random_schedule _____________________
self = <tests.test_scheduled_job.TestScheduledJob testMethod=test_random_schedule>
def test_random_schedule(self):
schedule = "r * * * *"
sj = ScheduledJob(
name="rando", task="test", schedule=schedule, active=True)
sjc = sj.crontab_schedule()
assert len(sjc.minute) == 1
>       assert sjc.minute.pop() in range(0, 59)
E       AssertionError: assert 59 in range(0, 59)
E        +  where 59 = <built-in method pop of set object at 0x7f35dacbd3c8>()
E        +    where <built-in method pop of set object at 0x7f35dacbd3c8> = set().pop
E        +      where set() = <crontab: 59 * * * * (m/h/d/dM/MY)>.minute
E …
```
=> Fix off-by-one error in scheduled job test

bin/utils.sh, docker/Dockerfile.build, docker/docker-compose.build.yaml, docker/docker-compose.flower.yaml, docker/docker-compose.yaml
* Remove shell-style defaults (see below) from docker-compose files
* Shell-style defaults allow overrides via `.env` and `portal.env` (env files)
* Now only overrideable via `portal.env`
* Still necessary for some settings that cannot be set from `portal.env`
* eg `volumes`, `ports`
Shell-style defaults:
```
${FOO:-default value of FOO if not set}
```
=> Simplify docker-compose syntax

portal/views/portal.py
Most ePROMs reminder email templates require a QB, but not true for TNTH USA.  The lack of one would prevent staff from being able to send a reminder to a patient w/o a pending QB.
=> TN-1915 don't prevent reminder email for templates not needing a QB

portal/migrations/versions/55469bdd181f_.py, portal/models/intervention.py, portal/models/organization.py, portal/models/questionnaire_response.py, portal/models/user.py, portal/static/js/src/admin.js, portal/templates/admin/admin_base.html, portal/views/patients.py, portal/views/reporting.py, portal/views/staff.py, tests/test_organization.py
Another, and better, refactor of patient queries.  Should now in a more uniform manner, across clients including /patients /reports and /api/patients/assessment , stick to common rules for behavior by ROLE and apply the RCT constraints as defined in TN-1835.
Resulted in moving detailed query code from views into respective models and elimination of several duplicate functions.
=> TN-1931 Exclude test users from /reports

portal/views/user.py, tests/test_consent.py
This will enable users of `/api/user/<int:user_id>/consent/withdraw` to suspend a consent at any point in time prior to utcnow().
=> TN-1967 acceptance_date now accepted in the withdraw API

portal/models/qb_timeline.py, tests/test_qb_timeline.py
New data structure added to maintain order of list by attribute `at` field, named `AtOrderedList`.
The `append` method on `AtOrderedList` enforces order on insertion.
Use when building user's qb_timeline rows to prevent order errors, such as those demonstrated in TN-1975.
NB - no migration yet to seek out any qb_timeline rows needing to be reprocessed.  Waiting to see if another issue's migration during same sprint will cover.
=> TN-1975 always preserve order of QBT.at values inserting QB_Timeline

portal/static/css/orgTreeView.css
stumbled on this when testing this story:
https://jira.movember.com/browse/TN-408
Fix the rendering of single parent organizations from API, after adding legend for each:
/api/organization?tree_view=True
=> TN-408 fix rendering of tree view for single parent organization

portal/static/css/orgTreeView.css, portal/static/js/src/modules/OrgTool.js
Followup fix to this story:
https://jira.movember.com/browse/TN-408
still seeing issues with the way org tree is being rendered (see /api/organization?tree_view=True):
adding helper css class to distinguish child organizations
styling fixes for sub group of organizations (including single item organization)
=> TN-408 followfix - child org rendering

portal/migrations/versions/ede15dcea777_.py, portal/models/qb_timeline.py, portal/models/user_consent.py
Confronts a bug introduced in PR #3053.  Reworked ``latest_consent`` to only return valid, current consent, and extended ``consent_withdrawal_dates`` to correctly handle the withdrawn scenario, and use to work with building history of withdrawn cases.
@ivan-c this PR may need a migration to purge potentially incorrect qb_timeline rows as well.  Pushing now for test run.
=> TN-1995 correct consent lookup bug generated in fixing TN-1947

docker/docker-compose.prod.yaml
* Respawn celery workers after 10 tasks to prevent potential memory leaks
=> Set celery worker prod default

portal/views/portal.py
Fix 500 error generated (i.e. 'list' object has no attribute 'split') when filtering organization(s) on admin list.
Fix is to remove code that attempt to perform string split on orgs list preference object variable
note: orgs list filtering preference is now saved as a list instead of a comma-delimited string (see PR: https://github.com/uwcirg/truenth-portal/pull/3041)
=> fix error generated when filtering org(s) on admin list

portal/models/qb_status.py
Remove obsolete check for withdrawn users in `current_qbd`, as it's needed for display of history.
=> Withdrawn users need access to "current" QBD for correct history 

portal/models/qb_status.py
Reverts Withdrawn users need access to "current" QBD for correct history display. (#3156)
This reverts commit 6eab46a8063424f7fa68909d31ddb748e8c2dff8
See comments on TN-1947
=> Revert Withdrawn user QBD view change

portal/templates/profile/profile_macros.html
add missing sao paulo timezone to dropdown list.  note: the list is currently hard-coded.  A story has been created to dynamically generate this list:  https://jira.movember.com/browse/TN-2024
=> TN-1932 add missing America/Sao_Paulo time zone

portal/models/qb_status.py, portal/views/reporting.py
Fixes report when patient's withdrawal date coincided with "current" QB cycle.
Corrects first attempt that inadvertently opened the door for assessments beyond a patient's withdrawal date.
=> TN-2021 current_qbd gains `even_if_withdrawn` parameter

portal/static/less/eproms.less
found this while testing in EPROMS:
add margin to set apart password reset button and password reset sent message on patient profile UI (one was closely on top of the other)
=> add margin between reset passowrd button and message on patient profile

portal/static/js/src/profile.js
Address issue found for https://jira.movember.com/browse/TN-1965
Issue arose for a newly created patient account whose consent date falls on current date/time (today's datetime of patient timezone)
Instead of defaulting to current date/time, completion date should be set to using consent date/time **IF** they are the same.
=> TN-1965 set completion date to consent date/time if occurs on current

portal/config/eproms/Organization.json
the migration would write them out, then persistence would promptly remove them
=> TN-1941 Need additional identifiers in Organization.json

portal/models/qb_timeline.py
We obtain a "lock" from redis when updating a user's qb_timeline, so multiple processes (celery, other requests) don't interfere with one another.
After seeing a number of redis timeouts leading to process interruption, opted to work in a retry loop, as well as a sane error message rather than allowing the exception to bubble up.
=> Don't allow redis timeouts to halt processing requests

portal/views/reporting.py
Temp fix for below exception:
```
File "/srv/www/eproms.cirg.washington.edu/portal/env/local/lib/python2.7/site-packages/werkzeug/wsgi.py", line 870, in __next__
return self._next()
File "/srv/www/eproms.cirg.washington.edu/portal/env/local/lib/python2.7/site-packages/werkzeug/wrappers.py", line 82, in _iter_encoded
for item in iterable:
File "/srv/www/eproms.cirg.washington.edu/portal/portal/views/reporting.py", line 308, in gen
writer.writerow(desired_order)
TypeError: unicode argument expected, got 'str'
```
=> Hotfix original CSV generator function

debian/postinst, debian/rules
* Remove old `dh-virtualenv` workaround
* Fix loading of package defaults for `FILE_UPLOAD_DIR`, `PERSISTENCE_EXCLUSIONS_DIR`
=> Simplify/Clean-up Build Process

portal/static/js/src/gil.js
address error message reported when portal wrapper failed to load in GIL: 
`Received error {u'actor': u'user 12392',
 u'message': u'In GIL, error loading nav elements from portal - undefined' ...`
Fix: Provide error status code if response text is not available
=> GIL - portal wrapper loading error message fix

docker/docker-compose.prod.yaml
See
[How do I avoid Gunicorn excessively blocking in os.fchmod?](http://docs.gunicorn.org/en/stable/faq.html#how-do-i-avoid-gunicorn-excessively-blocking-in-os-fchmod)
[Docker is different: configuring Gunicorn for containers](https://pythonspeed.com/articles/gunicorn-in-docker/)
=> Prevent gunicorn from blocking on disk access

portal/models/reporting.py
Without `entry_method` in CSV column headers, that column was excluded from the report.
=> TN-1983 add missing `entry_method` header to CSV format

portal/eproms/templates/eproms/base.html
address part of this story: 
https://jira.movember.com/browse/TN-483
there are a few others but trickier to remove, .e.g portal-wrapper and footer.  will look more in-depth later
=> TN-483 remove inline js from eproms base html file

portal/models/i18n.py, portal/models/i18n_utils.py
* Rewrite POT file generation to idiomatic code, with `polib`
* Fix POT file reference format for static & DB strings
* Use available object metadata as gettext references (translation context)
=> Cleanup string extraction tooling

portal/models/organization.py, portal/views/organization.py
to handle mixed unicode & strings in python2, need `unicode_literals` for audit, as some org names now contain unicode.
=> TN-2092 Handle unicode org names correctly

.gitlab-ci.yml, .travis.yml, portal/models/i18n_utils.py, tox.ini
* Split Gitlab build process into stages
* Separate i18n extraction (`test`) and upload process (`deploy`)
* Only upload (from develop branch) if all prerequisite jobs pass
* Move i18n extraction testing & upload to GitlabCI
* Cleanup test setup
* Move defaults into testing setup, from CI config
=> TN-2090 Move i18n Uploads to GitlabCI

portal/static/js/vendor/bootstrap_datatables_extension.js
address https://jira.movember.com/browse/TN-2094
fix JS runtime error raised when sorting was attempted on consent date field of the patient list - specifically on rows containing empty consent date
specific error thrown `admin.js:78 Error thrown:  Error: TypeError: a.replace is not a function`
The runtime error halted subsequent JS executions.
Fix made: added falsy checks on date variables being compared  before performing string-related operation on each
=> TN-2094 fix JS runtime error when sorting null consentdate on patient

portal/models/questionnaire_response.py
logic inversion error when looking up current QB and short circuiting out if walked off end.
Discovered after Warren's testing of TN-2069
=> TN-2069 correct logic error exposed in testing

portal/config/eproms/Organization.json
`python -c 'import pytz; print pytz.all_timezones' | grep -i --color Europe` showed Europe/Dublin, it's GMT -1.
=> TN-2091 IRONMAN add Ireland and Irish org

portal/static/js/src/profile.js
stumbled on this error while working in my instance:
Runtime JS error, i.e. URI error, malformed URI, generated in audit log display of some user accounts in profile:
example audit entry that throws error: 
`... by SELECT performers.id AS performers_id, performers.reference_txt AS performers_reference_txt, performers.codeable_concept_id AS performers_codeable_concept_id 
FROM performers, observation_performers 
WHERE **%(param_1)s** = observation_performers.observation_id AND performers.id = observation_performers.performer_id with status`  
**%(** when decodeURIComponent function is applied (to decode escaped characters) to it generates the error
try and catch statement is added to catch such error
=> Audit Log runtime JS error fix

portal/static/js/src/modules/Global.js, portal/static/less/eproms.less
https://jira.movember.com/browse/TN-2138
Fix copyright year in footer to correctly reflect that set by configuration
Fix incorrect interpretation of object key set via variable by browser (object key set by variable was interpreted literally as string)
=> TN-2138 fix copyright year to correctly reflect that set by configuration

.gitignore
Fixes [TN-2143](https://jira.movember.com/browse/TN-2143): currently exercise and diet page is not styled in Production
* remove `.gitignore` (ie [generated `.dockerignore` rule](https://github.com/uwcirg/truenth-portal/blob/develop/.gitignore#L38-L40)) rule
=> TN-2143 exercise and diet fix unapplied stylesheet issue

portal/static/js/src/modules/TnthDate.js, portal/static/js/src/modules/Utility.js
https://jira.movember.com/browse/TN-2137
- use **end date** of system maintenance window to allow system maintenance message to display until the end of the window (currently the message goes away when the start date of the maintenance window hits).
- added support for entries of other ISO 8601 formats, e.g. 2018-06-09T16:00:00Z, 2019-07-09T22:30:00-7:00, 2019-05-24T15:54:14.876Z
- add invalid date check for start/end date entries for the system maintenance window
=> fix system message display til the end date of the maintenance window

portal/static/js/src/modules/TnthDate.js, portal/templates/initial_queries_macros.html
It was found that entering future date during initial queries doesn't allow user to continue but no error message is displayed to indicate as such.
Fixes include:
allow error message to display when birthday validation failed by removing css class that hides the error message container
allow message for validation error against future date to display (after entering 4 digits)
=> initial queries birthday validation fix

portal/migrations/versions/c242e22f5a47_.py
Minor extension to the migration for TN-2110, now removing any associated auth_provider rows to close Google & FB backdoor.
NB - it migration c242e22f5a47 was already run, downgrade first to up pick this change.
=> TN-2110 SR RCT patients & partners, remove associated auth_providers

.gitlab-ci.yml, debian/control, debian/rules, docker/Dockerfile, manage.py, portal/models/questionnaire_response.py, portal/models/user.py, portal/models/value_quantity.py, portal/views/crossdomain.py, tests/test_portal.py
* Use `venv` module with [dh-virtualenv](https://github.com/spotify/dh-virtualenv) to create debian-packaged virtual environment
* currently uses `virtualenv` binary
* Switch to new debian (buster) images
* work around pip bootstrapping issues (see #3201)
* Remove py2/3 compatibility code(`past.basestring`)
* Assume local repo trusted when installing portal debian package
=> Use python3 venv module for packaging

portal/views/assessment_engine.py
Force a qb_timeline cache update on a assessment PUT.
=> TN-2163 user's QB timeline requires invalidation on assessment update.

portal/templates/admin/patients_by_org.html
unnoticed till py3, we were including nulls in the sort filter used to determine if a user_document came from ST or DS.
add another filter so only the user_documents with a defined intervention_id are included for comparison.
=> TN-2177 filter out user_documents w/o intervention_id

portal/models/client.py
Due to this error, any logout's that would trigger a client.notify() would error and prevent subsequent action, such as /api/complete-assessment
=> TN-2192 hmac and b64encode require byte arrays in py3

portal/logs.py
This change should enable us to see error emails again.
=> TN-2197 py3 version of SMTPHandler renamed attribute `timeout`.

portal/models/questionnaire_response.py
check for `request_context` before attempting to use, in stack frequently called from celery (where no such request context exists).
=> TN-2200 celery report generation doesn't have a request context.

portal/models/questionnaire_response.py
Any attempt to index the results of a dict.keys() call fails on py3 with:
```TypeError: 'dict_keys' object does not support indexing```
Fix by casting any `dict_keys` result to a `list` before attempting an index.
=> TN-2202 in py3, dict.keys() returns a non-index-able type.

portal/static/js/src/components/AssessmentReport.vue, portal/static/js/src/modules/TnthDate.js
Found issue in IE when displaying assessment date:
allow IE to display assessment authored date as is without re-formatting if parsing error occurred
Fixes include:
- let TnthDate date module returns date string as is instead of an empty string when parsing of date string failed
- display assessment report date string as is if parsing error occurred
=> Assessment List/Report: Fix date display issue in IE

portal/models/questionnaire_response.py
Overlooked a `values()` call, applied the same fix as used for the `keys()` side.
=> TN-2202 in py3, dict.values() returns a non-index-able type.

portal/models/client.py
* Add missing `.decode()` call on bytearray
* Rename variables for consistency
=> Fix Event Callback Signature Format

portal/models/user_document.py
Binary files, such as PDF documents should be opened with the binary flag.  Switching to python3 uncovered this oversight.
=> TN-2216 open user_documents in binary mode

manage.py
Given the repeated need to correct the `authored` date on a QNR - added a CLI utility method to do so.  It also handles the questionnaire bank association updates and qb_timeline invalidation.
Sample invocation:
```flask update-qnr-authored --actor pbugni@gmail.com --qnr_id 5847 --authored "2019-04-09 15:14:43"```
=> TN-2244 new CLI utility to update the `authored` value of a QNR

portal/static/js/src/profile.js
address JS error related to display audit log records.  example stack: 
`Received error {'actor': 'user 10518',
'message': 'Error generated in JS - malformed URI '
'sequenceinitAuditLogSection/</<@https://truenth-test.cirg.washington.edu/static/js/dist/profile.bundle.js:1:157564\n'
'initAuditLogSection/<@https://truenth-test.cirg.washington.edu/static/js/dist/profile.bundle.js:1:157322\n'
'auditLog/<@https://truenth-test.cirg.washington.edu/static/js/dist/profile.bundle.js:1:22962\n'
'sendRequest/<@https://truenth-test.cirg.washington.edu/static/js/dist/profile.bundle.js:1:1987\n'
'r.prototype.initWorker/<@https://truenth-test.cirg.washington.edu/static/js/dist/profile.bundle.js:1:36647\n',
'page_url': '/api/user/11121/audit',
'subject_id': '11121'}` 
Issue stemmed from frontend code …
=> fix JS error related to display of audit records

portal/models/questionnaire_response.py
csv exports were failing from QNRs w/o an identifier or author attributes defined.
NB, the identifier in question is used to uniquely identify a QNR - say with an assessment engine session ID, not the questionnaire association as incorrectly assumed in the parent story
=> TN-2277 handle QNRs w/o identifiers

portal/static/js/src/profile.js
address JS runtime error as seen when parsing audit log.  Example:  https://truenth-test.cirg.washington.edu/patients/patient_profile/11764
Followup fix to this fix:
https://github.com/uwcirg/truenth-portal/commit/1a15e8672bf3
=> fix JS error when parsing audit log (followup fix)

portal/gil/static/js/lived_experience.js, portal/static/less/gil.less
Per latest feedback to this story:
https://jira.movember.com/browse/TN-2298
- remove "READ OTHER STORIES" link from LE main page
- styling fix of button layout
=> TN-2298 remove other story link from LE main page

portal/models/user.py
Probably inaccessible with front end fix in place (TN-1883) but add validation step to confirm we don't double promote a temporary, registered account.
=> TN-1885 don't allow double promotion of temporary account.

portal/migrations/versions/677b8b841cb3_.py, portal/models/message.py, portal/views/user.py
The list of email messages shown in a user's profile was relying on the current email address.  This would omit any messages sent to the user prior to an email address change.
Now tracking the `email_message.recipient_id` for any emails sent to a user.  PR includes migration to pick up all the old.
=> TN-1034 add recipient_id to email_message for tracking over address change

portal/static/js/src/modules/Validator.js, portal/static/js/src/profile.js, portal/static/less/portal.less, portal/templates/profile/profile_macros.html
https://jira.movember.com/browse/TN-2322
Noting here that these changes **only** apply to the email field on the profile page
Fix includes:
- Disable text fields on the profile page initially (thus prevents LastPass plugin from autofilling the field on page load) and re-enable them only when Edit button on each section is clicked.
- Fix bug associated with ajax post call being fired off even when validation occurred due to duplicate email address input.
Tested this on Firefox and Chrome with LastPass plugin activated - although I myself have not been able to reproduce auto submission of email address even **before** these changes( I did see email address being auto-filled though) so it'd be good to have someone else try out these changes.
=> TN-2322 prevent lastpass plugin from autofilling email field in profile

.gitlab-ci.yml, tests/conftest.py, tests/test_celery.py, tox.ini
Add tox environment and GitlabCI job for tests requiring celery running in background during tests
=> Split celery fixtured/unfixtured jobs

.gitlab-ci.yml, docker/docker-compose.yaml, portal/tasks.py, requirements.dev.txt, setup.cfg, tests/conftest.py, tests/test_celery.py, tox.ini
Adds a second celery worker, dedicated to the "low_priroty" queue (namely, any celery tasks that are not directly user or health check related).
=> TN-2314 add second "low_priority" celery worker queue

portal/models/questionnaire_response.py
questionnaire_response.authored must be used when calculating the visit (timepoint) - encounter.start_time doesn't typically match in paper entry scenarios.
=> TN-2340 use questionnaire_response.authored in timepoint calculation

portal/views/auth.py
Found a path where an existing account with only case differences in email from the value at an external IdP (i.e. FB or Google) would generate an error.
Look for existing email match in case insensitive manner.
=> TN-2012 look for existing account emails w/o case for external IdP

portal/static/js/src/profile.js, portal/templates/profile/profile_macros.html
Address a bug introduced when text input fields on profile page are disabled upon page load to prevent auto-populating from Last Pass plugin.  Text fields are enabled when in edit view (on clicking of edit button).  However, input fields in certain sections (e.g. manual entry modal) should remain editable.
Fix is to add indicator on a text input field, i.e. field attribute, that prevents it from being disabled automatically
=> Bug fix: exempt input fields in manual entry modal from disabling

requirements.dev.txt, tests/test_date_tools.py, tests/test_organization.py
update the requirement.dev.txt to reflect the latest pytest version
update the deprecated usage for error message in test_date_tools.py
update the deprecated usage for error message in test_organization.pyw
=> Resolve Pytest Conflicts

portal/views/client.py, requirements.txt, tests/test_auth.py
update the requirement.txt to reflect the latest validators version
remove the deprecated attribute require_tld in validators.url() for portal/views/client.py
remove the deprecated test require_tld for test_auth.py
=> Resolve Validators Conflict

portal/views/patient.py, portal/views/user.py
Extend /timeline?purge=all to also remove and therefore force re-eval of QNR->QB associations.
Do the same on a consent deletion.
=> TN-2408, TN-2409 force qnr association re-eval

portal/views/user.py, tests/test_consent.py
Found problems with QNR->QB associations for accounts with withdrawals predating the current acceptance date.
=> TN-2410 don't allow predated suspension

portal/package.json
Add `core-js-compat` to [fix babel build errors](https://stackoverflow.com/questions/59145601/module-build-failed-from-node-modules-babel-loader-lib-index-js-error-cann)
=> Add library to fix build errors

portal/static/js/src/accountCreation.js, portal/static/js/src/gil.js, portal/static/js/src/modules/TnthAjax.js
trying to get more detailed information for this type of error related to calling organization API: `Received error {'actor': 'user 10980',
'message': 'Error generated in JS - no detail available',
'page_url': '/api/organization',
'subject_id': '10980'}`
- in GIL, switch to use common ajax function for calling API, so as to get more detail about the call, e.g. retry attempts, parameters sent.
- delay calling organization API on account creation page to allow current user object to finish initialization
- reset ajax call attempts **after** reporting error so we know how many attempts have been made
=> fix error reporting for calling organization api to report more detail

portal/static/js/src/profile.js, portal/static/less/eproms.less, portal/templates/profile/profile_macros.html
Address https://jira.movember.com/browse/TN-2287
Issue: 
In entering completion date for Paper Prom, submission button still remained disabled **after** correcting an invalid date entry.
Changes include
- clear error message after incorrect date entry has been corrected
- add bootstrap error css class to input validation
- remove redundant code for validating date
=> TN-2287 correct date validation handling for manual entry

portal/models/questionnaire_response.py
Hopefully a temporary workaround, run a second query for the entire json document if the query for the json path field fails.
=> TN-2417 provide ugly workaround to failed query

portal/models/qb_timeline.py, portal/models/qbd.py, portal/models/questionnaire_response.py, portal/set_tools.py, tests/test_qb_timeline.py
Extended logic to handle more than two research protocols using generators.
Caught details previously overlooked for transitioning during protocol change if user had started but only completed questionnaires belonging to both RPs for the applicable visit.
=> TN-2405 Handle more than two Research Protocols

portal/static/js/src/profile.js, portal/templates/profile/profile_macros.html
Followup fixes for this story:  https://jira.movember.com/browse/TN-2287
Noting where testing that when completion date entered was not within expected window,  error message **did not** display as would have expected - only seeing submission button being disabled, which can be confusing to user.
Fixes include:
-  display error message when completion date for paper manual entry is not entered within a valid PROM window
- remove loading indicator when there is error
- reset error message to null instead of empty string when clearing error, fix based on previous feedback
=> TN-2287 followup fixes - display error when completion date is not within window

portal/models/qb_timeline.py, portal/models/questionnaire_response.py
no value in returning QNRs that don't apply to current RP Questionnaire Banks when determining transition timing.  mostly simplifies it for the human, but also restricts passing unwanted results about.
=> Noticed an easy optimization when debugging

portal/models/qb_timeline.py
raising exceptions too aggressive given existing test data.  log error when multiple RPs for the same visit are found for a user.
=> sane mgms for user's with multiple RPs on a visit

portal/views/patient.py, portal/views/user.py
found 2 remaining exception catching blocks looking for the exception message in the python 2 syntax - which generates server errors in python 3.
=> Access to exception message requires python 3 syntax.

portal/config/eproms/Organization.json, portal/models/qb_timeline.py
Now handling two edge cases previously overlooked:
1. if the RP being replaced doesn't include all the "visits" found in the next RP, extend logic to look ahead and step back when appropriate.
2. if the RP being replaced runs dry before the next RP starts, force a transition and pick up the new.
Also added another Test organization with all 3 IRONMAN RPs defined, with old retirement dates so we can test additional scenarios.
=> More edge cases handled in Research Protocol advancement

portal/config/eproms/Organization.json
https://jira.movember.com/browse/TN-2441 
Adds 146-131 (Sheffield), and adds a missing secondary identifier to Lancashire 146-124
=> TN-2441-Add-IRONMAN-org-fix-another

portal/models/qb_timeline.py
Found a number of production users with Questionnaire Responses for the indefinite QB on **both** research protocol v2 and v3.  Rather than delete any prod data, accept this scenario, log a warning, and move to the newer RP.
=> tolerate QNRs from two RPs on same visit

portal/static/js/src/profile.js
address this story: https://jira.movember.com/browse/TN-2444
Address IE specific JS Vue runtime error that occurred when an invalid manual entry date is submitted. The runtime JS error halted subsequent execution of JS code - re-entry of valid date was therefore not allowed to continue.
Fixes included:
* assign value to manual entry error message via computed property
* reset errors on re-opening of manual entry modal window
=> TN-2444 fix IE runtime error when invalid manual entry date is entered

portal/models/qb_timeline.py, tests/test_qb_timeline.py
in case of multiple RPs that were retired before a user's initial trigger, need to advance RPs multiple times in the transition process.
=> TN-2464 multi RP transitions pre start

tests/conftest.py
configure conftest to use TestConfig instead of default environment
=> bugfix/conftest-not using-testconfig

portal/eproms/templates/eproms/landing.html, portal/gil/templates/gil/base.html
The login-as timeout wasn't getting reverted on subsequent login, as our custom login templates didn't include the necessary flask-user expected "next" form field.
Now, logins using our front end forms will also redirect to /next-after-login as designed and intended.
=> TN-2470 include desired "next" after login within our custom templates

.gitlab-ci.yml, docs/source/conf.py
Intermittent build failures seem to be increasing for the documentation werkzeug link.
Found a possibly better supported redirect target to obtain the latest werkzeug documentation URL.
If this doesn't work, we'll need to use the direct link, which is less attractive as it's version specific.
=> try updated intersphinx link for werkzeug

portal/models/flaskdanceprovider.py, portal/models/user.py, portal/views/auth.py
FB has added additional permission barriers for attributes like user_birthdate and user_gender.
As suggested in the comments of TN-2447, reduce the request to external IdPs - no longer request either birthdate or gender.
=> TN-2447 reduce fields requested from external IdPs

portal/models/message.py
There's a comment in the code:
```            # This should never happen, alert if it does ```
generating emails with the following useless content:
```Unable to generate audit log for email <class 'flask_mail.Message'>```
Although `format()` is documented to automatically call an object's __str__ method, it doesn't look to be functioning from the log statement.  Force the call to improve our visibility on this situation.
=> Force str(Message) in logging to eliminate bogus error log text.

portal/static/js/src/profile.js
https://jira.movember.com/browse/TN-2506
Followup bugfix:
Fix faulty logic involving check for ignore_preference parameter.
- check for the presence of ignore_preference before disabling/enabling send/receive emails capacity (check for the absence is not reliable as it can be the parameter is completely absent or false).
- remove extra check, i.e. whether user has an email address,  for validity of email readiness - relying on API results as source of trueth
=> TN-2038 followup bugfix

portal/config/eproms/AppText.json, portal/migrations/versions/d4517f61aaed_.py
An app text value incorrectly linked TNGR orgs with the University of Washington consent.
Correct this error and correct existing records via a migration.
=> TN-1940 use stock consent for TNGR organization consent

portal/models/questionnaire_response.py
* Replace static check with state machine
* If `valueCoding` follows `valueString`, always treat as single response
=> Fixup CSV Export

portal/models/qb_timeline.py
As RP v5 shifted start dates back a couple weeks, need to accommodate in the look ahead logic when determining if it's time to transition to the next RP.
=> Allow for slightly mismatched RP schedules

portal/config/eproms/QuestionnaireBank.json
https://jira.movember.com/browse/TN-2556
See also https://github.com/uwcirg/truenth-portal/pull/3657.
Note: the primary goal here was to adjust 'overdue', as we were entering that state too early. But, I did also reduce the gap between QB's by a day for v5 via 'expired', as it seemed like we had an extra day of buffer there which could be trimmed.
=> TN-2556-v5-shift-QB-refinement

portal/views/portal.py
Need to redirect to appropriate blueprint, eproms/home or gil/home
=> Obsolete redirect if logged in user attempts /go

portal/models/user.py
as `get_user()` occasionally takes the user_id from a request path or query_string, coerce to integer to avoid problems in comparison.  added assertion to catch any similar problems.
=> TN-2628 confirm only int values are passed to check_role

portal/eproms/templates/eproms/base.html, portal/views/assessment_engine.py
A followup bug fix for this story: https://jira.movember.com/browse/TN-2628
**Issue**: Once a url-authenticated user has confirmed identity as survey taker, the ensuing URL the user was redirected was missing required parameters (e.g. resume instrument id, etc.)
**Fix**: to properly encode URL that is being passed as a query string to the confirm identity view
Also added text change per communication from Cam: https://jira.movember.com/browse/TN-2659
=> TN-2628 followup fix - address issue where redirect url was truncated

portal/templates/portal_wrapper.html
Per feedback from this story: https://jira.movember.com/browse/TN-2645:
Address issue where an url-authenticated user can access the profile link without signing in first from the assessment engine
Fix includes:
Previously, href attribute for the profile link in the portal wrapper, in the context of url-authentication, was updated dynamically via JS.  That worked in the portal.  However, it won't work in Assessment Engine, as the JS code sits on the portal side only.
To address that, the **template** code for the portal wrapper is updated so that the href for the profile link is assigned based on the auth method of user's encounter.
=> Tn-2645 bugfix related to profile link

portal/extensions.py, portal/models/encounter.py, portal/models/login.py, portal/models/procedure.py, portal/models/user.py, portal/views/assessment_engine.py, portal/views/auth.py, portal/views/clinical.py, portal/views/demographics.py, portal/views/intervention.py, portal/views/notification.py, portal/views/organization.py, portal/views/procedure.py, portal/views/role.py, portal/views/user.py, tests/test_encounter.py, tests/test_fhir.py
Due to oauth initiation happening via API invocation, many of the fail safe calls to `login()` needlessly generate a new encounter, and previously occasionally included the incorrect assumption on `auth_method`.
Now reusing the current_encounter for a user on a call to login, if it's found to be valid and of the requested auth_method.
Should also resolve a bug in the `url_authenticated` flow, where any oauth protected API call from an external intervention (i.e. the AssessmentEngine) incorrectly promoted the auth_method.
=> Reuse valid encounters during login flow, if found

portal/models/message.py
Correct typo in word `message` - lower, not upper case.
This will provide what we want, in place of current emails such as:
```
TrueNTH <noreply@us.truenth.org> | TrueNTH <noreply@us.truenth.org> | Aug 1, 2020, 8:37 AM (2 days ago)
-- | -- | --
TrueNTH <noreply@us.truenth.org>
Unable to generate audit log for email: <class 'flask_mail.Message'>```
=> Log details of the failing message, not the class!

portal/migrations/versions/1977c23a53c8_.py
given bootstrap problem (multiple PRs altered development order of operations), add placeholder row rather than relying on site_persistence run in migration.
=> add required research_studies row in migration

portal/models/extension.py, portal/models/organization.py, portal/views/organization.py, tests/conftest.py, tests/fixtures/organization.py, tests/test_organization.py
The /api/organization/<org_id> endpoint now takes a query string parameter to include inherited information, such as a research protocol defined not at the requested org level, but somewhere up the org tree.
Research Protocols now include research_study_id in their serialized form.
Together, the front end can now call `/api/organization/<org_id>?include_inherited_attributes=true` to check for research study enrollment at any level.
=> TN-2768 extend organization API for research study needs

portal/models/organization.py, portal/models/qb_timeline.py, portal/models/questionnaire_bank.py, portal/models/research_protocol.py, portal/models/research_study.py, tests/test_model_persistence.py, tests/test_organization.py, tests/test_research_protocol.py
TN-2769 Oversight from #3771 - need to filter on research_study_id when looking up research_protocols in many cases.
=> looking up research_protocol must often be limited by research_study

portal/templates/admin/patients_substudy.html, portal/views/clinician.py, portal/views/patients.py
The patient query for sub-study patients now populates a `user.clinician` attribute.    It will have a value of `None` when the patient does not have an assigned clinician.
=> TN-2773 clinician name in patient list

portal/config/eproms/Questionnaire.json
TN-2669
Add extension for [SDC Observation-based extraction](http://build.fhir.org/ig/HL7/sdc/StructureDefinition-sdc-questionnaire-observationExtract.html) to Ironman substudy questionnaire
NB: This extension can be applied to individual `item`s (questions) if not all questions need extraction
=> TN-2669 SDC Extraction Extension

portal/models/qb_timeline.py, portal/models/qbd.py, portal/models/reporting.py
Complicated situation discovered thanks to an assertion in the reporting code.
If a user happens to have posted QNRs that deterministically tie them to the older RP (say they completed `ironmisc` on v3 versus `ironmisc_v5`) AND the timing is such that the older protocol (say v3) didn't include a visit (such as month 33), do NOT insert that skipped visit into their timeline, as we can't move back and forth between protocols.
=> TN-2794 don't insert skipped visits if posted results tie user to older RP

portal/config/eproms/QuestionnaireBank.json, portal/models/qb_status.py, portal/models/qb_timeline.py, portal/models/questionnaire_bank.py, portal/models/research_study.py
Since this QB is blocking the ability to administer the empro patient questionnaire and thus test things like trigger evaluation, our temporary approach for this story is to make the empro patient QB contingent on the empro consent date only (removing the complex requirement to also factor in the state of the ironman global QB).
=> TN-2541-empro-qb-for-patient-temp

portal/config/eproms/QuestionnaireBank.json
correct off by one error - baseline plus 11 months of recurring for a total of 12.
Correction for error in PR #3803
=> TN-2541 should be a total of 12 visits for EMPRO 

portal/eproms/templates/eproms/resources.html, portal/eproms/views.py
address  https://jira.movember.com/browse/TN-2813
Links in EPROMS resources page link to incorrect LR content
Issue stems from code relying on getting the topic tag for the work instruction based on its index within the asset tags array - the index can change however, as tags in the array can change its order
Fix includes:
-  filter for only topic tag in the asset tags array so that the template can use the correct tag to build the url that displays the LR content
=> Bug fix for eproms staff resources page links

.dockerignore, bin/docker-build.sh, docker/Dockerfile, setup.cfg
Merges into #3713 
* Build substudy content as isolated docker stage
* Use nodejs docker image as base
* Reduce scripting complexity, add `.dockerignore`
=> Substudy Docker Build

docker/Dockerfile
Add substudy files directly to installed package directory (instead of inserting before debian package is built)
=> Fix Substudy App Build

portal/eproms/templates/eproms/assessment_engine.html, portal/eproms/templates/eproms/assessment_engine/ae_complete.html, portal/eproms/templates/eproms/assessment_engine/ae_due.html, portal/eproms/templates/eproms/assessment_engine/ae_indefinite_due.html, portal/eproms/templates/eproms/assessment_engine/ae_macros.html, portal/static/js/src/empro.js, portal/static/less/eproms.less
Addresses: 
https://jira.movember.com/browse/TN-2786
https://jira.movember.com/browse/TN-2644
update patient home page for a sub-study subject based on latest content and design changes
- Verbiage updates to sub-study tiles
- update layout for when both main study and sub-study questionnaires are completed
- update sub-study thank you modal based on latest design and content changes
- fix tile text for when **both** sub-study and main-study tiles are present
- put back text for the main study questionnaire completed tile
- remove un-needed extra HTML tags from assessment_engine.html
=> Latest updates to the patient home page for a sub-study subject

portal/static/js/src/admin.js, portal/static/js/src/modules/OrgTool.js, portal/templates/admin/patients_substudy.html
Address part of https://jira.movember.com/browse/TN-2771
Update column names for sub-study patient list based on latest specs.
In addition, fixes were made:
- fix export of report data on the sub-study patient list page, i.e. passed in research study ID so data by research study will be exported
- fix organization filter selector to sub-study organization(s) on the sub-study patient list
- fix patient list toggle UI so that clicking on the label will also be able to switch view
=> Substudy patient list updates

portal/eproms/templates/eproms/assessment_engine/ae_due.html, portal/eproms/templates/eproms/assessment_engine/ae_indefinite_due.html, portal/eproms/templates/eproms/assessment_engine/ae_macros.html, portal/static/js/src/empro.js, portal/static/less/eproms.less
Issues found while testing  https://jira.movember.com/browse/TN-2786
Fixes include:
- Title update for **completed** PROM tiles - needing to differentiate between main and sub-study tiles, i.e. IRONMAN Questionnaire vs EMPRO Questionnaire
- Display completed EMPRO tiles where possible, e.g. main study has pending work, but subject could have completed EMPRO Questionnaire
- minor styling updates per specs
- link to sub-study tailored content page should open in the same browser tab
=> TN-2786 follow-up bug fixes for EMPRO patient home page

portal/config/eproms/AppText.json, portal/models/app_text.py, portal/static/js/src/modules/TnthAjax.js, portal/static/js/src/profile.js, portal/static/less/eproms.less, portal/templates/profile/patient_profile.html, portal/templates/profile/profile_macros.html, portal/views/patients.py, portal/views/portal.py
Address https://jira.movember.com/browse/TN-2711
- Adding sub-study welcome email option to select dropdown list
- Allow sub-study welcome email option to be available only if there is a valid user email and user has an assigned treating clinician as per specs
- Present sub-study welcome email option only when sub-study assessment is ready.
Note, pending: clean-up of the sub-study welcome email content in LR.
=> Allow sending substudy welcome email from patient profile page

portal/eproms_substudy_tailored_content/src/js/Base.js, portal/eproms_substudy_tailored_content/src/style/app.less
Bug found when testing - 
sub-study tailored content landing page is not presented based on subject's triggers
Fix include:
- update content based on trigger(s) only when it is ready, i.e. ajax call is finished
=> TN-2787 bugfix  - filter content based on triggers on when it is ready

portal/static/js/src/modules/Consent.js
Remove date range constraint on the allowable dates to be selected from date picker for consent date.
Note again: datepicker for consent date is only available in the test environment
=> remove date range restriction for consent datepicker

portal/static/js/src/empro.js, portal/static/less/eproms.less
address https://jira.movember.com/browse/TN-2644
allow user to land on the sub-study thank you modal upon completion of sub-study questionnaire.
- add check for when sub-study completion is done, IF completed today (which means the user has come from the questionnaire), then pops open the thank you modal automatically
- the modal will only automatically open **once**, any subsequent navigation back to the patient home page won't automatically invoke the modal (unless there are triggers)
- fix call the trigger API only when sub-study assessment is completed
- styling fixes
=> substudy thank you modal - presents it upon user's completion of sub-study assessment

portal/static/js/src/empro.js, portal/static/less/eproms.less
Found bug when testing:  sub-study thank you modal is popping up when substudy assessment hasn't been done yet.
Fix is to pass the correct parameter to disable thank you modal popup
=> bugfix - substudy thankyou modal shouldn't popup when assessment hasn't

portal/eproms/views.py, portal/models/qb_status.py, portal/models/qb_timeline.py, portal/models/research_study.py, portal/trigger_states/empro_states.py, portal/views/patients.py, portal/views/research_study.py, tests/test_trigger_states.py
Determine patient's research study eligibility in consistent manner.
Prevent qb_timeline row additions prior to patient's eligibility.
Provide bootstrap safe lookup.
Previously, sub-study qb_timeline rows were erroneously added for patients w/o a clinician.  This should be run on test dbs after merge.  (No, not worth a migration IMO)
`delete from qb_timeline where user_id in (select id from users where clinician_id is null and id in (select distinct(user_id) from qb_timeline where research_study_id = 1));`
=> Refactor / clean-up sub-study eligibility checks

portal/eproms/views.py, portal/models/qb_status.py, portal/trigger_states/empro_domains.py, portal/trigger_states/views.py, portal/views/assessment_engine.py, portal/views/patients.py, tests/test_trigger_states.py
Added `authored` field to triggers['source'].
Added new view `/api/user/<int:user_id>/trigger_history` to return list of user's trigger states and details.  Example result:
```json
[
{
"state": "due",
"timestamp": "2020-12-01T19:10:55+00:00",
"user_id": 3160
},
{
"state": "inprocess",
"timestamp": "2020-12-01T19:10:55+00:00",
"user_id": 3160
},
{
"state": "processed",
"timestamp": "2020-12-01T19:10:59+00:00",
"triggers": {
"domain": {
"anxious": {},
"discouraged": {},
"fatigue": {},
"general_pain": {},
"insomnia": {},
"joint_pain": {},
"sad": {},
"social_isolation": {}
},
"source": {
"qb_id": 114,
"qb_iteration": null,
"qnr_id": 2579
}
},
"user_id": 3160
}
]
```
Extended assessment API to obtain a QNR by id.  Example use:
`/api/patient/3160/questionnaire_response/2579`
=> TN-2859 extend trigger api

portal/models/qb_status.py, portal/models/qb_timeline.py, portal/models/questionnaire_bank.py, portal/models/questionnaire_response.py, portal/views/patient.py, portal/views/user.py, tests/test_qb_timeline.py, tests/test_questionnaire_bank.py, tests/test_reporting.py
The `trigger_date` (nothing to do w/ EMPRO triggers, but the old term for the initial trigger to start a QB) for EMPRO is now delayed until a "recent" (must be within 4 weeks of consent, or we wait for subsequent) global study QB is on file as `completed`.
=> TN-2780 delay EMPRO start date till completion of global study w/i four weeks. 

portal/eproms/templates/eproms/assessment_engine/ae_complete.html, portal/eproms/templates/eproms/assessment_engine/ae_due.html, portal/eproms/templates/eproms/assessment_engine/ae_indefinite_due.html, portal/eproms/templates/eproms/assessment_engine/ae_macros.html, portal/eproms/views.py, portal/static/less/eproms.less, portal/templates/admin/patients_substudy.html
fix for https://jira.movember.com/browse/TN-2803 and
fix for of https://jira.movember.com/browse/TN-2689
Fixes include:
- For sub-study subject, display any error message, e.g. no clinician,  if sub-study questionnaire due tile is disabled even when global study questionnaire has been completed
- For **URL-authenticated** user, accessing the sub-study longitudinal report on the patient home page requires logging in first. Fix is to add check for user authentication method and add `portal-weak-auth-disabled` to report link where applicable. Frontend code is already in place that will check for any link with `portal-weak-auth-disabled` css class and prompts user to login first via a modal, see previous relevant commit here:  https://github.com/uwcirg/truenth-portal/pull/3724
- code clean …
=> Substudy patient home followup fixes

portal/eproms_substudy_tailored_content/src/js/Base.js, portal/static/js/src/profile.js, portal/static/less/eproms.less
Fix in response to issue found in https://jira.movember.com/browse/TN-2811
tailored content for external resources was not loaded for users in Australia
Fix include:
- load default resources content if content for a specific country code is not found
- also minor styling fix for display of post intervention questionnaire response
=> TN-2811 retrieval of resources content by country code fix

portal/config/config.py, portal/extensions.py, portal/session.py, requirements.dev.txt, requirements.txt
TN-2577
* Add flask-session override class ([base class](https://github.com/fengsp/flask-session/blob/0.3.2/flask_session/sessions.py))
* Include cookies in cross-site requests (eg portal banner) with [`SameSite=None`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#None)
* Update dependencies as necessary
=> TN-2577 Add flask-session override for SameSite cookie settings

portal/models/qb_timeline.py, portal/views/patients.py
Address feedback when testing:  https://jira.movember.com/browse/TN-2771
See Diana's comment: https://mo-programs.slack.com/archives/GV6K6SURW/p1608247980052500
Fixes include:
- Fix post intervention questionnaire status to "**not applicable**" when EPRO questionnaire has yet started, i.e. due.
- Capitalize first letter in post intervention questionnaire status when displayed in patient list
- Fix runtime patient list error related to missing position argument, i.e. research_study_id, for **calc_and_adjust_expired** function in qb_timeline.py
=> TN-2771 post tx status display fix

manage.py, portal/models/qb_timeline.py, portal/views/patient.py
Found yet more special cases, some of which broke with previous hotfix (#3886)
Added a `pre_loop_trasition` to catch RPs up to the current or one previous so loop can correctly determine if it's time to transition RPs, or if the user has already submitted results associating the user with the older RP.
Also found a bug in `update_qnr_authored()`.  Once this PR is live on prod, this command should be run to clean up a bogus authored date:
```flask update-qnr-authored --actor pbugni@gmail.com --authored '20109-14 16:00:00' --qnr_id 5353```
=> TN-2869 RP advancement issues

portal/views/patient.py
fixes bug noticed in error email:
```
File "/opt/venvs/portal/lib/python3.7/site-packages/portal/views/patient.py", line 513, in patient_timewarp
for email in triggers['actions']['email']:
KeyError: 'actions'
```
=> add missing guard for early triggers missing `actions`.

portal/models/qb_status.py
Couldn't generate an acceptance report due to a single user's mis-filed QNRs.
Generate an error log, don't halt the process via exception.
=> Withdrawn sanity check should log error, not halt process

portal/models/qb_timeline.py, portal/static/js/src/modules/TnthAjax.js, portal/static/js/src/profile.js, portal/static/less/eproms.less, portal/templates/profile/patient_profile.html, portal/templates/profile/profile_macros.html, portal/trigger_states/empro_states.py, portal/views/assessment_engine.py, portal/views/patient.py
Clinicians/staff can submit the post intervention QB even beyond the point at which a patient can take the next month's EMPRO.
In the patient/substudy view, the 'clinician action status` should show results/status from the last submitted EMPRO.
The patient_profile view should allow clinician/staff to fill out post-intervention QB until a subsequent visit has been posted by the patient.
=> TN-2885 Intervention QB remains available till next post

portal/trigger_states/empro_states.py, portal/trigger_states/views.py
Found a critical where clause missing on the query to mark previous post-intervention QB as `missed`.
When using the reprocess_qnr_id flag (debugging), clean up the trigger_state history.
=> TN-2748 bugfix and reprocess cleanup

portal/eproms_substudy_tailored_content/src/js/Base.js, portal/static/js/src/components/LongitudinalReport.vue, portal/static/js/src/modules/TnthAjax.js, portal/trigger_states/views.py, tests/test_trigger_states.py
make trigger APIs more consistent with other APIs like /timeline
=> correct trigger APIs to follow `/api/patient` pattern 

portal/eproms_substudy_tailored_content/src/components/Header.vue, portal/eproms_substudy_tailored_content/src/js/Base.js, portal/eproms_substudy_tailored_content/src/js/Utility.js, portal/eproms_substudy_tailored_content/src/style/app.less, portal/eproms_substudy_tailored_content/webpack.config.js, portal/static/js/src/admin.js, portal/static/js/src/modules/OrgTool.js, portal/static/js/src/profile.js, portal/static/less/eproms.less
story: https://jira.movember.com/browse/TN-2762
Fixes for sub-study tailored content
- Allow collapsible UI element including its child element(s) to react to click event  and add polyfill for IE
- Allow empro substudy content menu to show in the context of sub-study tailored content
Also minor fixes to address:
- validation for missing role or organization selection
- display warning text related to assigned clinician (when clinician is not from one of the sub-study sites)
- styling updates
=> TN-2762 sub-study tailored content related fixes

portal/models/communication.py
As were now getting elast alerts from the celery jobs, this one keeps happening, and I can't make sense of it (as user 2907 most certainly has a valid QB looking at their timeline).
Adding more info to the exception text to help sleuth out the error.
Example elast alert: ```raised unexpected: NoCurrentQB('no applicable QB for user 2907')```
=> Adding additional query info to exception text seen on prod.

portal/trigger_states/empro_states.py, portal/trigger_states/models.py, tests/test_trigger_states.py
Found several issues resulting in emails being sent to EMPRO clinicians/staff where the user had NOT generated hard triggers in their EMPRO submission.
NB - existing trigger_states rows in the db may continue to display bad behavior, but all new patients are expected to work correctly.
=> TN-2902 clinician email on hard trigger only

portal/models/qb_timeline.py
when a user doesn't finish a QB, but only posts some of the contained Questionnaires, at the conclusion of the "visit" (say 3 month), a "partially_completed" row is saved to the users qb_timeline.  as some QBs overlap, the check for existing posted results needs to consider not the date of "partial completion", but rather when results were actually posted.
The fix here is to look back for the time of the posted QNR and move the partially completed date just before the start of the next so we don't generate overlapping QBs in the user's timeline.
**Please note**:  once this is live, we should reprocess the following patients.  `purge=True` is adequate, `purge=all` will generate more audit noise:
- 570
- 594
- 1170
- 1862
=> TN-2894 don't skip visits on Partially Completed state.

portal/migrations/versions/481d8266a4c0_tn_2899_merge_authored_dates.py
Migration to pick best authored value based on criteria in TN-2899, set the other to match such that following this migration, for all questionnaire_responses: authored == document->'authored'
=> TN-2899 Migration to select best authored 

portal/eproms/views.py, portal/models/qb_status.py, portal/models/research_study.py, portal/static/js/src/mixins/CurrentUser.js, portal/static/js/src/modules/Global.js, portal/static/js/src/modules/TnthAjax.js, portal/static/js/src/modules/Utility.js, portal/static/js/src/profile.js, portal/static/less/eproms.less, portal/templates/portal_wrapper.html, portal/templates/profile/patient_profile.html, portal/templates/profile/profile_macros.html, portal/views/patients.py, portal/views/research_study.py
The results returned by `/api/user/<id>/research_study` were both inadequate (in the patient's case) and confusing.
Branched into two APIs for the respective needs:
- `/api/staff/<id>/research_study` continues to return the list of research studies (as before) assigned to the organizations in common with the staff user
- `/api/patient/<id>/research_study` was enhanced to return more details about each research study assigned to the patient, such as `ready` and `error` status.
- Frontend code updates to consume new API, adjust presentation sub-study UI based on returned data from API, i.e. taking into consideration of whether subject is eligible and or ready for the sub-study
=> TN-2798 currate research_study apis

portal/eproms/templates/eproms/assessment_engine/ae_complete.html, portal/eproms/templates/eproms/assessment_engine/ae_macros.html, portal/static/js/flask_user/urlAuthenticatedModal.js, portal/static/js/src/portal.js, portal/static/js/src/profile.js, portal/templates/profile/user_profile.html
feedback from testing https://jira.movember.com/browse/TN-2786
Issue: When accessing patient home page via url-authenticated link in the email - clicking on "**View Previous Questionnaire**" button on the patient home page, which _requires_ login before accessing the resource,  didn't present the URL authenticated modal directing user to login, as it should.
Fixes include:
- Add missing css class to the button that frontend code identifies as element(s) that invokes the authentication modal.
- prevents default on-click event from firing if the authentication modal is to be presented.
=> TN-2786 bugfix to present URL authentication modal in patient home page

portal/static/js/src/modules/TnthAjax.js
In general, we use 3 attempts from front-end requests, should there be a blip that prevents an API request from responding.
When debugging code, this can be a hassle, as multiple threads concurrently hit breakpoints confusing the user.
Adding an obvious constant to make temporary changes to the number of attempts easy to adjust for dev purposes.
=> create global for MAX_ATTEMPTS to simplify debugging

portal/static/js/src/components/LongitudinalReport.vue, portal/static/js/src/data/common/AssessmentReportData.js, portal/static/js/src/profile.js, portal/static/less/eproms.less, portal/templates/profile/profile_macros.html
Followup changes to https://jira.movember.com/browse/TN-2835
- indicates as such, e.g. as a legend, when an assessment is **in progress** in both longitudinal report and post intervention questionnaire UI for clarity
- do not present "no high stress area found" verbiage on the UI in post intervention questionnaire section when the note is still in progress
- display an action status of Missed when occurs in the post intervention questionnaire for clarity
=> UI updates Longitudinal report & post intervention questionnaire

portal/static/js/src/components/LongitudinalReport.vue, portal/static/js/src/empro.js, portal/static/js/src/profile.js
Per testing feedback from https://jira.movember.com/browse/TN-2644
Issue:
EMPRO thank you modal **didn't** automatically pop up right after completion of a EMPRO questionnaire of visit beyond baseline.  Example patients in EPROMS-TEST: IDs, 3404 and 3437
Fix includes:
- Identify whether a thank you modal should display based on a key that includes assessment date
Other changes:
- remove debugging console statement
- minor fix to sort TOU items on consent history table in profile by acceptance date
=> TN-2644 EMPRO thank you modal - pop up on questionnaire completion fix

portal/config/eproms/QuestionnaireBank.json, portal/eproms/views.py, portal/models/qb_status.py, portal/templates/site_overdue_table.html
Long history with the confusion between `start/available` and `due` dates for a QB.  The current implementation treats them ambiguously, maintaining both a `start` and `due` value on the QB itself, but calling the `start/available` date as `due` in the QB timeline and within all status checks.
TN-2468 addresses the confusion this creates for users, as they might get a reminder email for a 3 month prom that suggests it's `due` when it first becomes `available`.
At this point, this PR corrects:
- all EMPRO patient QBs, to have a due date 2 weeks after the start.
- all recurring IRONMAN QBs, to have a due date such that the original "visit" date is respected.  For example, a v3 3 month that first recurs at "3 months -15 days" now has a due of 15 days.
- the `due_date` variables used by the …
=> TN-2468 correct QBs due date to reflect desired `target_date`

portal/static/js/src/admin.js
Adherence report UI on patient list:
Issue:  Currently, the UI doesn't display error detail and dialog disappears promptly when error happens in the process of exporting.
Fix: display and _persist_ more discrete error detail from the ajax call to export adherence report data when it fails.
=> adherence report UI on patient list - export error display fix

manage.py
Renamed branch - same PR as 3980, but no longer named as a `hotfix`:
Add new CLI preview-site-update to present expected changes for patients on a Research Protocol change.
Example run:
flask preview-site-update --retired "2021-02-01 13:00:00" --org_id 146102
Results from said example available on parent Jira issue: https://jira.movember.com/secure/attachment/99896/APC-RPv5-changes.txt
Not intended to be run on prod - checks config to confirm.
=> TN-2919 preview site update

portal/eproms_substudy_tailored_content/src/js/Base.js
fix based on feedback here:  https://jira.movember.com/browse/TN-2762
Issue clicking on resources tile in sub-study tailored content does open up the resource link
Cause - stemming from the fact that the content is dynamically generated
Fix - initiating tile on click event **after** the content has been populated
=> TN-2762 tailored content tile click event fix

portal/date_tools.py, portal/trigger_states/models.py, tests/test_date_tools.py, tests/test_trigger_states.py
When calculating if it's time to send a reminder email to staff for EMPRO triggered patient follow ups, we need to exclude weekends.
Added new date_tools utility function `weekday_delta()` to calculate time delta between two dates, omitting weekend days.
=> TN-2924 exclude weekends for EMPRO reminder schedules.

portal/config/config.py, portal/views/auth.py, portal/views/portal.py, portal/views/reporting.py
Clinicians were blocked from accessing `/api/report/questionnaire_status` (an easy fix) but this was difficult to track as we didn't have a `USER_UNAUTHORIZED_ENDPOINT` configured, and would therefore simply redirect to '' and return a 301 status rather than a 401 as needed for the front end to be aware of the error situation.
=> Add critical USER_UNAUTHORIZED_ENDPOINT and enable clinicians to generate adherence reports

portal/models/user.py
On a system with zero consented users, the query intended to include only consented users must consider the empty set.
=> Zero consented patients query safeguard

portal/migrations/versions/481d8266a4c0_tn_2899_merge_authored_dates.py, portal/migrations/versions/68a25f790d27_.py
Potential fix on truenth-demo where the `T` separating date & time in `document->>'authored'` (as specified by ISO 8601) is killing the SQL `TO_TIMESTAMP` parse.
=> Add `T` to datetime format string in failing migration on truenth-demo

portal/static/js/src/profile.js
Address story:  https://jira.movember.com/browse/TN-2933
- Issue:  An ajax call is fired off to the **patient** research study API on a **staff** profile page, resulting in a 400 error, i.e. incorrect role.
- Background for the ajax api call:  The call to the research study api is mainly relevant in the context of the patient profile page where certain UI elements can only be seen by the EMPRO patients.
- Fix:  Correctly call the research study API for staff on a staff profile page if it is determined that the subject is not a patient.
Implemented as a hot fix.
=> TN-2933 call the correct research study api on a staff profile page

requirements.txt, tox.ini
* Remove deprecated `pip` resolver flag
* Update pinned dependencies to resolve conflicts between dependencies
* pip now considers dependencies of dependencies when choosing versions to install
=> TN-2877 Remove Deprecated Dependency Resolver

portal/models/user.py, portal/views/assessment_engine.py
generate a fresh encounter if a new QuestionnaireResponse comes in, and the user's current_encounter() already belongs to an existing QuestionnaireResponse.
=> TN-2941 one QNR per encounter

portal/models/app_text.py, portal/models/organization.py, portal/models/reporting.py
Overlooked single clinician assumption in adherence report.  Fixed and finally caught the simple case of org tree breaking behind `/api/research_study` -- only mystery is why this was hard to reproduce.
=> Allow multiple clinicians in adherence report

portal/eproms_substudy_tailored_content/src/js/Base.js, portal/eproms_substudy_tailored_content/src/js/Utility.js, portal/models/audit.py, portal/views/truenth.py
https://jira.movember.com/browse/TN-2952
Logging sub-study **content** domain accessed.
example logged entry in audit table: `remote message: GET /substudy-tailored-content#/mood_changes`
=> Audit logging viewing of sub-study tailored content

portal/trigger_states/empro_states.py
The visit_month state check only functions after the trigger_state is added to the db, as the default value comes from a database fired default.
=> TN-2954 fix auto invite for EMPRO

portal/models/qb_status.py, portal/models/reporting.py, tests/test_qb_timeline.py
Regression issue: need to capture the `current QBD` even if patient is withdrawn, for accurate reporting of withdrawn visit info.
=> TN-2950 restore withdrawn visit in adherence report

portal/migrations/versions/1a84c56e6abc_.py, portal/models/qb_status.py
A few error emails started rolling in since we merged #4019 on truenth-test.
Hardened the code to avoid this edge case, and added a migration to fix the handful of problem users.  (simply deletes their qb_timeline so it'll get constructed on next pass)
=> Correct `withdrawn` timeline rows

portal/trigger_states/empro_states.py
`current_app.logger.error` isn't plural!
=> typo exposed in recent log watch emails.  

portal/trigger_states/empro_messages.py
NB, will only function once liferay templates are updated to use {study_id} - see https://jira.movember.com/browse/TN-2968
=> TN-2963 use study ID in EMPRO trigger emails to staff.

requirements.dev.txt, tox.ini
* Add 1 hour timeout limit to celery tests
* If timeout exceeded, dump stack
* Changed Gitlab CI timeout from 1 hour to 2 hours [via web UI](https://docs.gitlab.com/ee/ci/pipelines/settings.html#timeout)
=> Add timeout limit to tests

portal/models/qbd.py, portal/models/reporting.py, portal/views/patient.py
Number of fixes, enhancements on adherence reports.
- Withdrawn users now include consent dates
- EMPRO columns added for triggers and access (TN-2854)
- Timewarp adjusts audits tracking access (TN-2972)
=> TN-2854, TN-2955, TN-2972: Adherence reports

portal/factories/app.py, portal/factories/celery.py
* Use the same module-global variable as `json_logging` ([`_current_framework`](https://github.com/bobbui/json-logging-python/blob/master/json_logging/__init__.py#L29)) to detect logging initialization
* Read celery loglevel from flask app, or `celery` CLI option
=> JSON Logging Fixups

portal/models/login.py, portal/models/user.py, portal/static/js/flask_user/2fa.js, portal/static/less/eproms.less, portal/templates/flask_user/second_factor.html, portal/views/auth.py, portal/views/patch_flask_user.py
2FA was being thwarted by unauthenticated request to restricted resources.  Difficult to wire in with flask-user, but found a way by patching the `make_safe_url()` function of flask-user.
Replaced the `token` term with `code` as suggested in parent story TN-2974
=> TN-2989 correctly manage 'next' in 2FA

manage.py, portal/factories/app.py, portal/models/qb_timeline.py, portal/models/questionnaire_bank.py, portal/models/questionnaire_response.py
Eliminate overlapping QB problems by shifting the expiration date of the previous QB to be just before the start of the next QB.
- Click task `find-overlaps()` will seek out and report all overlapping QBs in the active patients, and optionally correct.
- Any overlaps found while building up a user's timeline are eliminated by moving the expiration date, provided QNRs or other events won't be clobbered.
- Additional safeguards added to the timeline build process, to confirm we don't insert new rows containing overlaps.
=> TN-2994 correct QB visit date overlaps

portal/config/eproms/Organization.json, portal/views/patient.py
Was a hotfix, reverted to standard flow as time allows for this to go out with the current sprint.
=> TN-2998 allow timewarp on demo systems.

portal/config/config.py
As was, an environment var setting such as: `ENABLE_2FA=False` would evaluate as true, being a string.
=> Interpret false strings as boolean False value for `ENABLE_2FA`

portal/models/login.py
We do call login() as part of any oauth request that includes a bearer token, to pick up flask-user roles, etc.  BUT this should not included the 2FA logout / email / verify loop, as that was already done in obtaining the bearer token.
=> TN-3026 login() calls during oauth client don't require 2FA 

portal/eproms/views.py
The privacy policy options on EPROMs are limited to:
```
- IRONMAN patient privacy URL
- IRONMAN staff privacy URL
- TrueNTH Global Registry patient privacy URL
- TrueNTH Global Registry staff privacy URL
```
for users other than patients, default to the staff version.
=> TN-3045 default to staff role for all but patients for privacy URL

portal/models/user.py
We continue to see these on a rare basis.  No action is needed.  Just noise in our INBOXes - turning down.
Example message that was being generated:
```
{"written_at": "2021-06-08T09:38:24.736Z", "written_ts": 1623145104736012000, "msg": "Failed to locate in-progress encounter for <redacted id>; generate failsafe", "type": "log", "logger": "flask.app", "thread": "MainThread", "level": "ERROR", "module": "user", "line_no": 466, "correlation_id": "454300fc-c83d-11eb-8f14-0242ac120008"}
```
=> Quiet benign and seemingly worthless error which requires no action.

portal/templates/portal_wrapper.html
Followup bug fix to this story:
https://jira.movember.com/browse/TN-3046
Bug found:
User with both staff and clinician roles will wind up have two `Patients` menu items in the menu
Fix include:
update the conditional statement
=> TN-3046 followup bugfix

portal/models/questionnaire_response.py, portal/views/reporting.py
- restore "online" default to entry method (when not paper, interview assisted or staff authenticated)
- add entry method `staff_authenticated` for the login as patient scenario
- calculate all the entry methods for all questionnaire responses on a given visit and when more than one exists, return the one most frequently used and a ratio of that one to all, i.e. `paper 4:5`
=> TN-3027 Adherence report entry method work

portal/models/qb_status.py, portal/static/js/src/profile.js, portal/templates/profile/profile_macros.html, portal/views/research_study.py
Front end was erroneously disabling the control for a staff follow up on EMPRO trigger, once the patient has subsequent global study work pending.
The `/api/patient/<>/research_study` API now includes an additional `staff_eligible` boolean.  Only when that is false does the control for staff follow up need to be disabled.
=> TN-3048 /api/patient/<>/research_study extended for `staff_eligible`

portal/views/user.py
When deleting EMPRO consent, audit message now makes that clear:
``` Deleted EMPRO consent agreement```
=> TN-3056 audit message clarity when deleting EMPRO consent

portal/views/portal.py
Server error was being generated when users returned to bookmarked /initial-queries outside of a valid session.
Confirm we have a valid user and redirect to force login.
=> TN-2755 Check for bookmarked scenario, without `current_user()` 

portal/static/js/src/profile.js
https://jira.movember.com/browse/TN-3100
Allow editing of EMPRO consent for a test patient account if logged-in user has role as specified in`CONSENT_EDIT_PERMISSIBLE_ROLES`
=> TN-3100 allow empro consent to be editable for test patient in prod

portal/static/js/src/profile.js, portal/static/less/eproms.less
https://jira.movember.com/browse/TN-3099
Fix includes:
When a new role is checked/removed from the roles UI, an existing set of roles is queried first via API to ensure freshness before role(s) are updated.
=> TN-3099 UI roles update bugfix

portal/static/js/src/profile.js
Followup bug fix to this story:
https://jira.movember.com/browse/TN-3099
Found and address two issues when testing:
- when calling API for current roles, need to make sure that they are not coming from cache, or cached storage (e.g. sessionStorage)
- need to check/uncheck roles on the UI to reflect true current roles of the user
=> TN-3099 followup bugfix

portal/models/qb_timeline.py, portal/models/reporting.py
For EMPRO patients, specifically those shown in the /substudy list, use a default status of "Not yet available" rather than the global study default "expired".
Note - this is intended to go out as a hotfix.
=> TN-3101 correct default (prior to initiation) status for EMPRO questionnaires

portal/models/user_consent.py, tests/test_consent.py
Now raising 400 with sane message, rather than generating a 500 server error when consent API was given a bogus `status` value.
=> TN-1939 validate optional `status` param sent to consent API

portal/views/patch_flask_user.py
PR #4145 introduced this regression - just noticed in error logs today, and fixed.
Require user to look for pre-registered roles.
=> TN-3114 check for user before checking for roles

portal/static/js/src/admin.js, portal/static/less/eproms.less, portal/templates/admin/admin_base.html, portal/templates/admin/patients_by_org.html
https://jira.movember.com/browse/TN-3120
- address progress popup disappearing by remove code that hid the export popup on window re-size
- abort/clean up pending export ajax requests on error and prior to each new export
- abort export request if export status stays in PENDING status for more than 1 minute  (shouldn't be in PENDING that long, no?)
- allow access to the most recent export (as a link) (see screenshot):
=> TN-3120 Adherence report - improve usability

portal/development_gulpfile.js, portal/i18next_gulpfile.js, portal/package-lock.json, portal/package.json, portal/webpack.development.js, portal/webpack.production.js
- updates frontend libraries, `del`, `acorn` and `webpack-merge` as per recommendations by dependabot
- made necessary changes in weback and gulp files affected by changes introduced by the updates
=> update frontend libs, del, acorn and webpack-merge to latest versions

portal/eproms_substudy_tailored_content/package-lock.json
ran `npm audit fix` to address, where possible, security vulnerability issues raised by the dependabot in the frontend libs used by the empro sub-study project content/resources page.
=> address vulnerability issues raised by dependabot

portal/views/assessment_engine.py
for use exclusively when outside assessment was completed outside visit date boundaries.
=> TN-3118 consume and pass on `actual` date assessment was completed

portal/static/js/src/modules/TnthAjax.js, portal/static/js/src/modules/TnthDate.js, portal/static/js/src/profile.js, portal/static/less/eproms.less, portal/templates/profile/profile_macros.html
https://jira.movember.com/browse/TN-3117
- a new required Visit field is added to the manual entry modal
- If the entered questionnaire completion date is not within the time window of the selected visit, a warning message will appear and tell user as such.  However, the user **will not** be prevented to continue. Dates displayed to the user will be in **local** date/time (down to the minutes)
- a new `actual` (date actually completed) query string is passed on to the backend api when applicable 
- `actual` date is determined if the date comes after the visit starts, the end date of the visit minus one day is passed along; if the date comes before the visit starts, the start date of the visit is passed along
example url that will be passed on from the frontend: ` …
=> TN-3117 out of window proms UI changes

portal/views/assessment_engine.py
The pre-existing assertion (present as the storage of our internal extensions was destructive) was preventing the necessary use of extensions in QuestionnaireResponse for out-of-band submissions.
Now checking for presence of `extension`s and extending with internal data rather than replace.
=> Allow pre-existing extension(s) in questionnaire responses.

portal/static/js/src/profile.js, portal/static/less/eproms.less, portal/templates/profile/profile_macros.html
As per feedback from https://jira.movember.com/browse/TN-3117
- remove code that pre-populates manual entry completion input date fields with today's date
- fix mobile layout for visit selector and text as per feedback
- fix issue where date validation error message is not being displayed
=> remove pre-population of today's date in the manual entry completion date fields

portal/models/questionnaire_response.py
double quotes within QuestionnaireResponse answer valueStrings break CSV parsing on exports.
Quote via a second double quote, found to be the only reliable way to preserve:
> RFC-4180, paragraph "If double-quotes are used to enclose fields, then a double-quote appearing inside a field must be escaped by preceding it with another double quote.
=> TN-3119 quote any double quotes within QNR answer strings

manage.py, portal/models/qb_timeline.py, portal/models/questionnaire_response.py
As per support story IRONN-45, questionnaire responses submitted beyond the visit when a user is withdrawn need to be deleted from the system.
A rather delicate, complicated process, new CLI function `remove-post-withdrawn-qnrs` does just that, including an audit row to track the change.
=> IRONN-45 add CLI to delete post withdrawn qnrs

portal/models/user.py
#IRONN-52 symptom fix.
Regression introduced with #TN-3008, confirm a study id isn't already associated with another user before masking it as deleted.
=> #IRONN-52 Don't mask identifiers as deleted if still in use

portal/config/eproms/ScheduledJob.json
up schedule to run EMPRO trigger job 2x per day, to avoid potential extra day between events.
=> TN-3151 increase job frequency for EMPRO triggers

portal/trigger_states/empro_messages.py
query for staff & clinicians to receive trigger emails didn't exclude deleted users.
=> TN-3145  EMPRO trigger emails sent to deleted staff

portal/static/js/flask_user/CsrfTokenChecker.js
Follow up fix to this story:
https://jira.movember.com/browse/TN-3137
- In addition to checking whether CSRF token has expired, a check should also be made about whether a CSRF token **is present** before an ajax request is made (if absent and ajax request is made, error manifested in `404 error: The CSRF token is missing` )
=> TN-3137 follow up fix - check for empty CSRF token

portal/models/user.py, tests/conftest.py, tests/test_coredata.py, tests/test_demographics.py, tests/test_trigger_states.py
Needed to move to a SQLAlchemy @hybrid_property in order to filter out any related clinicians that have been deleted.
=> TN-3150 user.clinicians should not include deleted

portal/models/qb_status.py, portal/models/reporting.py
TN-3150 (don't include deleted clinicians) required a change in access to user.clinicians; no longer a simple relationship but now a hybrid property.
Found 3 overlooked refactor points.  All of these cause a server error when hit.
=> TN-3150 continued - found overlooked changes needed.

portal/trigger_states/empro_states.py, portal/trigger_states/models.py, tests/test_trigger_states.py
TN-3157 happened due to a failure to persist the correct visit month in a trigger_states transition.
This PR includes a one line code change (shifting the `db.session.commit()` out of a first month only clause in `initiate_trigger()`, so we always persist new or changed trigger_states rows from that function), as they should always be saved, and may potentially be the source bug behind the issue.
All other changes are to better capture trigger_states transitions and persistence in a manner that should be easier to locate in the logs, should the problem persist.
=> TN-3157 potential fix; enhance trigger states logging

portal/factories/app.py, portal/tasks.py, portal/trigger_states/empro_states.py
The log statement isn't nested w/i the for loop, but one level out at the point of commit, causing these errors seen in the docker logs:
```
celeryworkerslow_1  | {"written_at": "2022-05-23T16:01:00.019Z", "written_ts": 1653321660019708000, "msg": "Task portal.tasks.process_triggers_task[a274233b-17a6-455d-80dd-a4a72cf353b7] succeeded in 0.014829255640506744s: 'Unexpected exception in `process_triggers_task` on 148 : local variable \\'ts\\' referenced before assignment'", "type": "log", "logger": "celery.app.trace", "thread": "MainThread", "level": "INFO", "module": "trace", "line_no": 124, "correlation_id": "d10db52c-d896-11ec-9b28-0242ac120006"}
```
Was a bit of a mystery as to why this didn't get picked up in our log watcher - presumably as the log level shows as INFO - which doesn't …
=> scope error on logging statement, interrupting EMPRO trigger task

portal/models/user_consent.py
TN-3161 displays a symptom of an overlooked bug in `consent_withdrawal_dates()`.  In the case of no current consent, the lookup for a previous row with status `suspended` did NOT consider the research_study_id.
This thwarted the check to see if a patient should be included in a given adherence report, as it was incorrectly returning withdrawn dates from the global study, when evaluating the EMPRO study.
=> TN-3161 erroneous inclusion of global withdrawn patients in EMPRO adherence

portal/config/eproms/CommunicationRequest.json
Previously only had a single set of `CommunicationRequests` established for the recurring EMPRO (sub-study) questionnaire bank - namely for iteration 0.
As the calculations used to determine if a patient has been sent or is due to receive a reminder (`CommunitationRequest`) rely on unique identifiers, we must include individual config blocks for every desired iteration.  This PR covers months 3-12, matching up with the questionnaire bank `ironman_ss_recurring_monthly_pattern` iterations 1-10.
=> TN-3163  EMPRO (sub-study) email reminders for months 3-12

portal/factories/app.py, portal/tasks.py
Resorting celery task logger imports, in an attempt to see if this may restore celerybeat health.
(yes, this is a wild guess at the moment, but the only obvious change since updates to the scheduled_jobs stopped functioning and celerybeat started reporting errors)
=> Resorting celery task logger imports

portal/tasks.py, portal/timeout_lock.py, portal/trigger_states/empro_states.py, portal/trigger_states/models.py, portal/trigger_states/views.py, tests/test_trigger_states.py
Reworked the asynchronous locks to more reliably prevent interruption or race conditions when updating a user's trigger_stats from various threads (jobs, user actions, etc).
Caught another incorrect visit_month scenario with enhanced logging, in the act.  Almost certain the source is behind the trigger_states.insert(from_copy=True) calls, which makes use of SQLAlchemy's `make_transient()` method.
Using `make_transient()` coupled with `db.session.commit()` can lead to unexpected loss of object results.
Now intentionally reloading after any such calls.
See also https://github.com/sqlalchemy/sqlalchemy/issues/3640
=> TN-3157 found a more plausible reason for losing track of visit_month

portal/config/config.py, portal/views/healthcheck.py
testing exposed down services (such as redis or celery) generate exceptions (which do effectively trigger alerts and log filters) but fail to return accurate health lead additional exception handling within healthchecks to capture and return state when redis is down.
worth noting, when celery is down, healthcheck hangs, but monitoring services such as icinga would catch such a deadlock.
=> TN-3164 enhance healthcheck

portal/eproms_substudy_tailored_content/src/js/Base.js
bug found when testing https://jira.movember.com/browse/TN-3175
LF expect locales delimited by `_` as opposed to `-`
see convo [here](https://mo-programs.slack.com/archives/GV6K6SURW/p1658334965733719)
Fix include:
-  fix the locale code passed to LR to retrieve sub-study content
=> TN-3175 fix locale code passed to LR to retrieve sub-study content

portal/models/qb_status.py, tests/test_assessment_status.py, tests/test_qb_timeline.py
Now that we allow future consent dates, need to prevent the "special" indefinite QB from being started prior to the passage of the consent moment.
=> TN-3178 don't start indef prior to consent

portal/models/qb_status.py, portal/static/js/src/profile.js, portal/templates/profile/profile_macros.html
address https://jira.movember.com/browse/TN-3188
Use `intervention_qnr_eligible` flag returned from `/api/patient/[id]/research_study` to determine whether to display error(s) in the clinician intervention questionnaire section of the patient profile page.
**Note** the flag is TRUE even if there is pending work in base study.  See example [here](https://eproms-test.cirg.washington.edu/api/patient/3982/research_study).  So that specific error will not display on the UI.
=> TN-3188 hide "pending work in base study" error in clinician intervention questionnaire

portal/views/patients.py
Although primarily a symptom of fake test data (due to outdated assignment of plain staff as clinicians), clean up how deleted clinicians are displayed in the `/patients/substudy` list.
1. without a current clinician, use empty string, not `<deleted>`.
2. Include text should we ever again find a clinician w/o a "name in map", as picked up from test-only data on test system.
=> TN-3190 correct display of <deleted> clinicians

portal/static/js/src/admin.js
Address https://jira.movember.com/browse/TN-3195
Behavior observed in Production:
Select organization(s) from the _Filter List By Site_  on the patient list does not result in filtered list on refresh.  Another refresh is needed to see it.
Possible Cause:
The timing is so that the patient list is served up by the backend prior to the filter preference having completed saving.
Fix:
Code updated to ensure that the frontend Ajax call to set the table filter preference should complete **before** refreshing the patient list.  This so that the backend can present the patient list based on that saved filter preference.
=> bugfix: TN-3195  Filter list by site org filter bug

portal/templates/profile/profile_macros.html
Follow up to https://jira.movember.com/browse/TN-3198
Issue found:
User can still delete PI in the Treating Clinician section even though the delete icon isn't showing for UI element.
Cause:
The **on click** event to delete a clinician is attached to the the parent UI element that contains the delete icon. So clicking anywhere on it will invoke the delete clinician event even if the delete icon isn't showing.
Fix:
Attach on click event to delete clinician to the delete icon button itself
=> UI bug - PI deletion on treating clinician section in profile

docker/docker-compose.static-ingress.yaml, docker/docker-compose.traefik-ingress.yaml, docker/docker-compose.yaml
- Add docker-compose override to allow config via Traefik
- Set `SERVER_NAME` in `.env` to match DNS Hostname (eg `eproms.ubu.ivanc.dev.cirg.uw.edu`)
- Add docker-compose override for exposing port (current apache deploy method)
- `ports:` section will be removed from docker-compose.yaml at a later date
=> Traefik Ingress

portal/models/reporting.py
due to recent change in report generation (to support different studies) we exposed a SQLAlchemy issue where a filter on `IN` fails if the parameter contains a single item and isn't structured as a list.
the query being patched was used to locate all staff who should receive emails for the weekly summary report on the global studies.  it was returning 0 users every time due to the failing/bogus `role.name IN ()` clause.
=> IRONN-132 patch failing staff user query

portal/migrations/versions/17060aa3c9d6_.py, portal/models/user.py
the use of user_consents.expired is not being managed and erroneously hiding consent rows.  delete checks against this column as hot fix for now.
note, this PR replaces #4277 which unintentionally picked up another change in develop, not wanted on a hotfix.
=> default 5 year expiration on user_consents coming into play

portal/static/js/src/accountCreation.js, portal/static/js/src/data/common/consts.js, portal/static/js/src/profile.js
https://jira.movember.com/browse/TN-3217
Description of the changes:
- When the role of Primary Investigator is checked - in account creation page or profile page, the UI will display warning about other required role(s), e.g. Staff, Admin Staff, and Clinician (see example screenshot).
- The user will be prevented from continuing unless ONE of those required roles is checked.
Example screenshot:
=> TN-3217 PI role account creation - prevent invalid role combo

portal/config/eproms/Organization.json
1. Moves "Instituto Valenciano de Oncologia" (146-146) to v5 effective 2020-10-21T23:00:00Z . This will need a dry-run @pbugni .
2. Switches "Hospital Universitario Miguel Servet (Zaragoza)" (146-180) to v5, effective for all time (this was a new site added March '22 - they accidentally asked for v3 at that time).
3. Removes a redundant org config for "Hospital Universitario Virgen de la Victoria". The removed config is at v3, which is incorrect. The remaining config has the valid transition to v5; this config was later in the file, and it appears that it overrode the prior/bad config, fortunately (at least, as I read https://eproms.truenth.org/api/organization?tree_view=true today).
https://jira.movember.com/browse/IRONN-130
=> IRONN-130-Spain-v5-all-orgs

manage.py, portal/models/questionnaire_response.py
example use follows.  to view current value for a requested linkId within the given QuestionnaireResponse.id, include the `--noop` flag:
```
$  flask update-qnr --qnr_id 19490 --link_id irondemog_v3.27 --actor pbugni@gmail.com --noop
'{"text": "Are you Hispanic or Latino?", "answer": [{"valueString": "No"}, {"valueCoding": {"code": "irondemog_v3.27.2", "system": "https://eproms.truenth.org/api/codings/assessment"}}], "linkId": "irondemog_v3.27"}'
```
scrape and edit the above result, and include with the `--replacement` flag, to update the record:
```
$ flask update-qnr --qnr_id 19490 --link_id irondemog_v3.27 --actor pbugni@gmail.com --replacement 
'{"text": "Are you Hispanic or Latino?", "answer": [{"valueString": "Yes"}, {"valueCoding": {"code": "irondemog_v3.27.1", "system": …
```
=> TN-3205 new CLI `update-qnr` to manually correct a QNR

portal/static/js/src/profile.js, portal/templates/profile/profile_macros.html
Per convo with Sie-ce: see [here](https://cirg.slack.com/archives/C5TVC8KQE/p1678483156811069)
- Made fix so that the appearance the time warp UI is not dependent on the completion of a questionnaire response
- Make the time warp input field to be a number field and without limiting the number of digits one can enter (currently one can only enter 2 digits).
=> time warp UI fix - should be present regardless of QR completion

portal/trigger_states/empro_states.py, portal/trigger_states/views.py
API at: `/api/questionnaire_response/<int:qnr_id>/$rescore`
only available to users with `admin` role.
=> IRONN-172 new API to rescore an interrupted scoring on any given QNR

docker/docker-compose.prod.yaml
- Auto-restart `sdc` container, if not explicitly stopped (eg on reboot)
=> TN-3229 Add sdc restart policy

portal/config/eproms/ScheduledJob.json, portal/tasks.py
NB, this job is not scheduled, but can be manually triggered anytime we need to verify handling and routing of errors.
=> TN-3226 new celery job to intentionally raise exceptions

manage.py, portal/models/qb_timeline.py, portal/models/questionnaire_response.py
Assigning questionnaire responses to the correct visit (questionnaire_bank and iteration) includes considering research protocol change by the patient's organization.
This PR corrects a situation where the overlapping and additional visits added by v5 coincide with the organizations transition date and a patient's questionnaire response authored date.  For protocol v3, month 30 precedes month 36.  In v5 additional visits month 33 and month 39 were added.
When a questionnaire response authored date lands near the protocol change, it must be determined which protocol was being fulfilled when assigning the visit to the questionnaire response.  The code was looking ahead but not far enough, due to the additional visits in the new protocol.  The case in question had an authored date that fit …
=> TN-3231 look further ahead with protocol changes

portal/models/user.py, portal/views/auth.py
Immediately attempt to use code before emailing out - regenerate if it doesn't work.
I'll note, via unit testing I could NOT find a reliable way to get this to break before or after changing, despite many attempts and huge iteration counts.  Therefore, I can't be certain this fixes the issue, but I was able to verify by hand that some of the codes emailed out do NOT work against the otp_secret saved.  This has a good chance of being the problem.
=> TN-3097 confront random failures with 2FA tokens.

manage.py, portal/models/questionnaire_response.py
Further extended `preview-site-update` to detail the visit and questionnaire for each respective questionnaire response that loses its association when transitioning research protocols.
Example run:
```
flask preview-site-update --org_id=146146 --retired="2020-10-21T23:00:00Z"
[...]
173 QuestionnaireResponses for all patients in organization 146146
Instituto Valenciano de Oncologia
Patients in organization: 34
Patients negatively affected by change: 13
Number of those QNRs assigned to a QB before RP change: 173
Number of those QNRs assigned to a QB after RP change: 150
Number of QuestionnaireBanks completed before RP change: 40
Number of QuestionnaireBanks completed after RP change: 20
Details of patients having lost a QuestionnaireResponse association:
Patient 3733
visit: Month 3 …
```
=> site preview qnr details for affected patients

portal/migrations/versions/2f125954b69a_.py
Followup to #4297
Fixup string formatting when there is only a single problematic result
See eproms-test `web` output:
```
File "/opt/venvs/portal/lib/python3.7/site-packages/portal/migrations/versions/2f125954b69a_.py", line 152, in upgrade
conn.execute(f"delete from questionnaire_responses where id in {tuple(purge_ids)}")
File "/opt/venvs/portal/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 976, in execute
return self._execute_text(object_, multiparams, params)
File "/opt/venvs/portal/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1149, in _execute_text
parameters,
File "/opt/venvs/portal/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
e, statement, parameters, cursor, context
File …
```
=> Fixup delete query, for single entry

portal/trigger_states/models.py
Hit an edge when a user is near the end of their study, thus the call to initialize a variable was never being hit and causing a stack in `celery_worker_slow`
=> Edge found on last month of EMPRO study, requires initialization.

portal/static/js/portal_wrapper/SessionMonitor.js
address https://jira.movember.com/browse/IRONN-176
and follow up to meeting, see [slack convo](https://cirg.slack.com/archives/C5EU4L7PF/p1682532067179999)
I believe the current behavior is:
- Frontend receives when session will`expires_in` information from the backend.
- Frontend calculates the session lifetime.
- Frontend pops up a warning a minute before the session expires.
- Frontend logs out the user when the session expires.
This change to add extra check, in case for some reason, the previous steps fail to ensure session freshness, via call to `/api/me`.  If the API call returns `401` unauthorized status code - the user will be logged out
=> add check to ensure user is still authorized to prevent stale session

portal/timeout_lock.py
intended to prevent the following, and thereby generate a useful error to help track down the real issue:
```
celeryworkerslow_1  | {"written_at": "2023-06-08T04:01:00.370Z", "written_ts": 1686196860370567000, "msg": "<class 'TypeError'>: argument of type 'NoneType' is not iterable; <traceback object at 0x7f960c4d5488>", "type": "log", "logger": "flask.app", "thread": "MainThread", "level": "ERROR", "module": "timeout_lock", "line_no": 65, "correlation_id": "145320d6-05b1-11ee-9893-0242ac130006"}
```
=> wrap error message generation with checks, avoid stack observed in log

tox.ini
Fixup `sh` consistency in `command`s and `allowlist_externals`
=> Fixup Testrunner Config

portal/models/organization.py, portal/views/reporting.py, tests/__init__.py, tests/test_reporting.py
Site codes were not working in most places, as we were looking for an identifier that matched:
```
current_app.config.get('REPORTING_IDENTIFIER_SYSTEMS')
```
that happens to be a list, not a string on most systems.  now handling either input type.
The error preventing weekly reports from going out stems from an orgtree node being treated like an Organization instance.
=> TN-3223; IRONN-196; patch sitecode errors and lookup.

portal/tasks.py, portal/views/portal.py
needing to see differences between background and portal's config settings, added a task and view to see what celery has for `current_app.config` values
=> adding an admin accessible only /celery-settings view

docker/docker-compose.dev.yaml, docker/docker-compose.prod.yaml, docker/docker-compose.yaml, manage.py, portal/factories/app.py
The site_persistence machinery generates a site specific (eproms vs USA) config file for consumption on start-up.
Previously, only the `web` service was executing `flask sync` which generates this file for consumption.
New `generate-site-cfg` CLI included in the respective `celery` launch commands does exactly that, so the jobs have the same configuration as the web service.
=> generate `site.cfg` for celery workers

portal/views/user.py
Strange behavior observed multiple times on prod.  A relatively new check for a valid token, from the front-end to the `/api/me` view hits:
```if user.current_encounter().auth_method == 'url_authenticated':```
the error stack from the alerts indicate `current_encounter()` is returning `None`.  given the default behavior within `current_encounter` of generating a fallback encounter if none is found, this would be seemingly impossible!!
as this check is only being used to lookup the `auth_method` for the current user, and the fallback encounter will always have a different level auth, the code has been made more "robust" by not attempting to generate this fallback encounter and handle the lack of a  `current_encounter` in `/api/me`
=> TN-3255 status check from front-end to /me raising unexpected errors

portal/static/js/src/components/ExportInstruments.vue, portal/static/js/src/components/asyncExportDataLoader.vue
Address story: [TN-3259](https://movember.atlassian.net/browse/TN-3259?atlOrigin=eyJpIjoiM2Q1MzQ2ZjE0YzY1NDBjMDk0OTM2OWMxMWMzMTc3ODAiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
See also Slack convo [here](https://cirg.slack.com/archives/C5EU4L7PF/p1694733386101599)
- Whenever an data export is initiated on the UI, the frontend will cache the celery task URL associated with the export
- Address the scenario where the export is left running in the background, e.g. as when user switches to a different browser tab - when data export window receives focus again, e.g. as when the user comes back from a different browser tab, the frontend will now check if the download has finished by calling the celery task URL cached from the previous step and update the download link on UI if it has …
=> TN-3259 research data export - UI not showing the most current download link

docker/Dockerfile
- Update debian base image from oldoldstable (buster) to oldstable (bullseye)
- current stable (bookworm) fails to build
We'll probably want to switch to our general (simpler) approach for building python images and remove [`dh-virtualenv`](https://github.com/spotify/dh-virtualenv), instead of upgrading to bookworm
=> Fixup Docker Image Building

portal/eproms/templates/eproms/assessment_engine/ae_complete.html, portal/eproms/templates/eproms/assessment_engine/ae_due.html, portal/eproms/templates/eproms/assessment_engine/ae_indefinite_due.html, portal/eproms/templates/eproms/assessment_engine/ae_macros.html, portal/models/qb_status.py, portal/models/questionnaire_response.py, portal/models/reporting.py, portal/static/js/src/components/ExportInstruments.vue, portal/static/js/src/components/asyncExportDataLoader.vue, portal/views/assessment_engine.py, tests/test_assessment_engine.py
The view used to determine which questionnaires (assessments) a given patient needs to submit, was incorrectly comparing an `OverallStatus` instance with the string `Withdrawn`.  Thus, patients withdrawn from a given study would incorrectly be administered assessments.
Extending this hotfix to include exclusion of questionnaire responses after withdrawn visits - actually now excluding ALL questionnaire responses that aren't associated with a valid questionnaire bank (i.e. a visit).
=> TN-3250, incorrect type in check for withdrawn from study

portal/models/questionnaire_response.py
Correct typo/bug: include all questions as they were, replacing only the matching link_id.
As it was, replaced every question with the target answer intended for just a single link_id.
=> TN-3205 Fix for `update_qnr` 

portal/views/user.py, tests/test_consent.py
This change allows for an update to an existing withdrawn consent.  Previously, a 404 was generated if the user didn't have a valid matching consent when a withdrawal was requested.
It is required that the requested withdrawal date is:
- greater than the last valid consent for the research study
- less than 1 day in the future (to allow for any timezone details)
=> IRONN-210 allow for change of withdrawal dates

debian/portal.triggers, docker/Dockerfile
- Update version-specific python3 paths to bookworm release of python3
- fixes #4342
=> Fixup python3 path

portal/views/assessment_engine.py
If a withdrawn user returns via access mail with next_step to present_needed, the user would see a 400:
Adjusted to log event and redirect home.
=> TN-3250 Possible a withdrawn user returns via access email

portal/views/user.py
The withdrawal API (at /api/user/<id>/consent/withdraw) didn't cast incoming JSON `research_study_id` value to an int.  This had previously worked fine in SQL queries, but the change introduced in PR #4343 requires an int to match research studies in looking for old consents.
=> TN-3268 withdrawal API, incorrect type for `research_study_id`

portal/eproms/templates/eproms/assessment_engine/ae_complete.html, portal/eproms/templates/eproms/assessment_engine/ae_indefinite_due.html
address Error stack:
```
File \"/opt/venvs/portal/lib/python3.9/site-packages/portal/eproms/templates/eproms/assessment_engine/ae_complete.html\", line 42, in block \"body\"\n    {{empro_expired(\njinja2.exceptions.UndefinedError: 'empro_expired' is undefined\n"
```
stemming from `empro_expired` template macro not included in the `include` statement
The scenario that will likely hits this 500 error is when a subject has completed the main study questionnaire but the EMPRO questionnaire has expired.
bug from [front end changes here](https://github.com/uwcirg/truenth-portal/pull/4338)
=> add missing includes for empro expired macro

portal/config/eproms/Organization.json
https://movember.atlassian.net/browse/IRONN-223
This org doesn't have any patients (and likely won't ever), it's used as an umbrella for 3 sites that were transitioned to v5 3 years ago. This change simply switches this parent to v5 with the same effective date as the children, as a precaution in case staff do add patients here.
=> IRONN-223 Change a parent org to v5 (no impact)

portal/config/eproms/Organization.json
Only Groote Schuur Hospital has been using it to date.  https://movember.atlassian.net/browse/TN-3267 .
See the description at that story, we actually removed Zulu in 2021 but earlier this year were asked to use it for Groote Schuur. 
I think we'll need a migration to switch any user from Zulu to English, like we did for orgs in 2021 https://github.com/uwcirg/truenth-portal/pull/4086 (and we'll need to run that existing migration again)
=> TN-3267 Remove Zulu

portal/migrations/versions/66368e673005_.py, portal/models/questionnaire_response.py, portal/models/reporting.py, portal/timeout_lock.py, portal/views/patient.py
fix for https://movember.atlassian.net/browse/IRONN-225
EMPRO qb_status expired status is ambiguous - can mean "not yet available" or "expired".  Added comparison with consent to correct in adherence report.
=> IRONN-225 EMPRO month 12 expired vs. not available

portal/timeout_lock.py
When an exception is raised from any code during the use of a TimeoutLock, it propagates to the `TimeoutLock.__exit__()` method, which must catch and disband the exception, less it'll remain in a potential deadlock state.
But, the code attempting to log the exception text was incorrectly accessing the attributes from the stack.  This PR corrects to generate a stack in the log file, and move on.
This is an old issue, and has been hiding errors raised behind TimeoutLocks from the log files for some time.  Is also probably the reason celery will occasionally behave as if it's in a locked state.
Finally found a reproduction (while working on #4343 regression issues), and found a solution!
I should add, the code in our system protected by TimeoutLocks is SIGNIFICANT - most all questionnaire …
=> TimeoutLock.__exit__() fixed to correctly generate a stack in the log

portal/models/message.py, portal/trigger_states/empro_states.py
Generate a reasonable error if EMPRO patient can't receive email at time of generation.
(shouldn't ever happen in production, but makes a mess of the logs in dev/testing)
=> logger.error on empro message sans email

portal/config/config.py, portal/factories/redis.py, portal/models/qb_timeline.py, portal/tasks.py, portal/timeout_lock.py, portal/views/healthcheck.py, tests/test_healthcheck.py
This started as an attempt to mock redis for consistent testing outside of normal behavior.
That attempt failed thus far, but to capture all redis session initialization behind a single function still seems of value, for future work and easier debugging.
This PR includes a fence around the cache clearing redis communication necessary in a patient's timeline rebuild, to only hit redis when not under test.  Necessary as otherwise, we experience a deadlock situation where tables can't be dropped between test runs, as postgres believes a deadlock condition exists.
=> move all redis session creation to factory

portal/models/message.py, portal/trigger_states/empro_messages.py
found additional cases where test system may be attempting to send EMPRO alert emails to user's w/o a valid email address (staff).
added detailed logging where failure is occurring, as well.
=> confirm staff have valid email before attempt to send

portal/models/qb_status.py
the following was recently found on elk:
```
File "/opt/venvs/portal/lib/python3.9/site-packages/portal/models/qb_status.py", line 102, in _sync_timeline
if cur_index > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```
pencil tracing the code, can't think of a logical explanation for the combination of variables that would cause this.  modified code to stop raising exceptions, be more robust and log an error if this happens again with more detail.
=> log missing cur_qbd situation

portal/models/qb_timeline.py
between protocol v3 and v5, additional months were added, i.e. month 33.
if v3 month 36 didn't have any committed work and it's time to change protocols for the user, v5 month 33 should follow v3 month 30.
the code looking for this case had an extra check which prevented the above from functioning, in the rare case where v3 month 30 ended before v5 month 33 starts.
this was discovered with the new withdrawal handling in adherence data, as the insertion of the withdrawal row could not predictably insert before the time point just after withdrawal, when the timeline was found to have such an overlap.
=> bug found in qb_timeline overlap check

portal/tasks.py
Due to change in keeping timeline info beyond withdrawal dates, must now check withdrawn status before sending notifications
=> safeguard withdrawn patients from notification emails

portal/models/qb_timeline.py
another bug introduced with extending timeline beyond the user's point of withdrawal.
now looking specifically for withdrawn status in /patients list, as it was still assuming the timeline terminated at the point of withdrawal as it used to.
=> correct withdrawn patient status in /patients

portal/models/qb_status.py
observed a few errors in the log since latest hotfix rollout.  the situation no longer deserves error alert status, as the withdrawn users will legitimately raise this error.  dialed back to a `logger.warning` just in case it helps with future debugging.
not critical to push live, unless the alerts are overwhelming.
example of error it was generating:
```
celeryworkerslow_1  | {"written_at": "2024-03-27T14:30:02.073Z", "written_ts": 1711549802073935000, "msg": "patient 5357 w/o cur_qbd??", "type": "log", "logger": "flask.app", "thread": "MainThread", "level": "ERROR", "module": "qb_status", "line_no": 99, "correlation_id": "7f2f63ac-ec46-11ee-b0e1-0242ac190006"}
celeryworkerslow_1  | 2024-03-27 14:30:02,073: patient 5357 w/o cur_qbd??
```
=> remove logger.error noise

portal/config/eproms/Coding.json, portal/models/clinical_constants.py, portal/models/code_systems/v3-Ethnicity.cs.json, portal/models/code_systems/v3-Race.cs.json
The previously available value sets for ethnicity and race, hosted at hl7.org, are no longer available for automated download.
Dumped contents to filesystem for a reliable import on deploy.
=> Pull ethnicity and race coding from filesystem

portal/static/js/src/components/LongitudinalReport.vue, portal/static/js/src/modules/TnthAjax.js, portal/static/less/eproms.less
Address [TN-3242 story](https://movember.atlassian.net/browse/TN-3242?atlOrigin=eyJpIjoiOTE5YzI5Y2E1OTM5NDg4YWI4NTU2MWQ1NDljMTNkNzciLCJwIjoiaiJ9)
Changes:
- An opted out hard trigger now has one asterisk only – indicating ‘Support needed
- hide navigation buttons when there is only responses for one date
- de-bouncing window resize event call
- general report styling fixes
Example screenshot after fixes:
=> longitudinal report opt out changes

portal/eproms/templates/eproms/assessment_engine/ae_macros.html
https://movember.atlassian.net/browse/TN-3306
restore "X" for closing the OPT OUT modal
screenshot after change:
=> TN-3306 EMPRO OPT OUT re-store X

.gitlab-ci.yml, requirements.dev.txt, requirements.txt, setup.cfg, tox.ini
- Upgrade celery & dependencies to next major version
- Modified `setup.cfg` and used `pip-compile` to generate a new set of dependencies
- Upgrade version of python used for testing to match container
=> Upgrade Celery

portal/models/qb_status.py, portal/models/questionnaire_response.py
the special case to handle assignment of questionnaire response to the trigger_state row (for the post EMPRO clinician follow-up QNR) failed to set the correct research study.  this resulted in missing updates on the adherence report after clinicians took action.
=> TN-3305 substudy clinician follow-up doesn't update adherence cache

portal/models/adherence_data.py
Add a check for existing row before attempted insert, to prevent race case observed in logs.  See [TN-3313](https://movember.atlassian.net/browse/TN-3313) for details.
=> TN-3313 Robustly handle race case of an updating adherence_row 

requirements.dev.txt
Workaround error during tests `TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'`
=> Update test dependency

portal/templates/admin/patients_by_org.html, portal/templates/admin/patients_substudy.html
Address https://movember.atlassian.net/browse/TN-3318
remove patient list export button on the patient list page for users with Researcher role (note: the button will still be present for users that have Admin role and have Researcher role as well)
Screenshot for a non-admin user with Researcher role:
Screenshot for a user without Researcher role:
The patient list export button, 
is removed for non-admin users with Researcher role
=> TN-3318 remove patient-list-export button for researchers

portal/static/js/src/admin.js
https://movember.atlassian.net/browse/TN-3319?atlOrigin=eyJpIjoiOTYwODgxZDM5MTBhNGRkODhlNGViYTRhNDJiMjQwYzQiLCJwIjoiaiJ9
- increase wait time for celery task to start (progressing from PENDING status) from 1 minute to 5 minutes.
- log as error if waiting for more than 5 minutes.
screenshot for when 5 minutes have reached:
=> TN-3319 extend wait time for adherence report export task

portal/models/research_data.py
wrap research_data row addition in critical section, keyed on unique constraint, as we do rarely experience asynchronous collisions.
this is intended to prevent exceptions such as the following, seen once during the initial population of 100K rows:
```
Unexpected exception in `cache_research_data_task` on 231 : (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "ix_research_data_questionnaire_response_id"
DETAIL:  Key (questionnaire_response_id)=(97480) already exists.
```
=> wrap research_data row addition in critical section

portal/static/js/src/admin.js, portal/static/js/src/modules/TnthAjax.js, portal/templates/admin/admin_base.html, portal/templates/admin/patients_by_org.html
part of  https://movember.atlassian.net/browse/TN-3324
Currently UI is a blank screen when the ajax call to retrieve patient list data encounters error:
Added fix to error handling with error displaying on screen and allowing user to change/clear filters on the UI if need to
=> fix frontend error handing of patient list ajax error

portal/models/reporting.py, portal/views/demographics.py
Updates to a user's study-id via a PUT to /demographics would leave old adherence data rows with the old study-id.
We now force a recalculation of a user's adherence data when PUT /demographics is called.
=> IRONN-242 update adherence cache on any patient demographics changes.

portal/models/questionnaire_response.py
Fresh error log details lead to discovering this long outstanding symptom.  Users leaving an unfinished, `in-progress` indefinite QNR from an older research protocol, then returning after their organization has transitioned protocols would raise an exception, as the lookup was too specific.
=> TN-2747 look for indefinite QNR in both v3 and v5.

portal/models/organization.py
Hotfix:
Found a significant number of timeout exceptions raised looking to acquire the OrgTree-LOCK (used by any process needing to build the in-memory organization tree on first request).
The default timeout of 10 seconds is clearly inadequate.  Increasing to same value (300 or 5 mins) used for the expiration of this lock (to catch any hung processes holding on to the lock).
=> real timeout org tree lock

portal/static/js/src/profile.js, portal/static/less/eproms.less, portal/templates/profile/profile_macros.html, portal/views/portal.py
TN-3331 describes symptoms as we didn't previously confirm a reminder email was appropriate to send, if requested by staff.
No longer generating email content, or sending email, unless the user has outstanding work, when the user (staff) requests to send a reminder email.
=> TN-3331 prevent staff users from sending bogus reminder emails

requirements.txt, setup.cfg
Build artifact errors depending on yanked version of `python-levenshtein`.  Attempt to upgrade to latest.
Error seen in CI build log:
```
#20 87.47 WARNING: The candidate selected for download or install is a yanked version: 'python-levenshtein' candidate (version 0.12.0 at https://files.pythonhosted.org/packages/42/a9/d1785c85ebf9b7dfacd08938dd028209c34a0ea3b1bcdb895208bd40a67d/python-Levenshtein-0.12.0.tar.gz#sha256=033a11de5e3d19ea25c9302d11224e1a1898fe5abd23c61c7c360c25195e3eb1 (from https://pypi.org/simple/python-levenshtein/))
#20 87.47 Reason for being yanked: Insecure, upgrade to 0.12.1
```
=> upgrade python-levenshtein as old version was yanked.

portal/views/patients.py
As a hotfix, do not include deleted patients in the patient lists, at both /patients and /patients/substudy
Fix for [TN-3342](https://movember.atlassian.net/browse/TN-3342)
=> TN-3342 exclude deleted patients from patient lists.

portal/templates/admin/patients_by_org.html
Remove search box from patient list as it is currently not functional.
Per Slack [convo](https://cirg.slack.com/archives/C5TVC8KQE/p1746730199065269)
story: https://movember.atlassian.net/browse/TN-3345?focusedCommentId=334852
Verified in my own instance that search box is now gone:
=> disable search on patient list

portal/trigger_states/adherence_cache_validation.py
Patch for PR #4443 - hardcoded ID for baseline_ss questionnaire bank didn't work on eproms.test.  Look up the value.
=> QuestionnaireBank IDs not consistent on test vs. prod.

portal/static/js/src/modules/TnthAjax.js
see [Slack convo](https://cirg.slack.com/archives/C5EU4L7PF/p1753460068004999)
- catch unauthorized or CSRF token related error before re-attempting an ajax request
=> Add frontend handling of  auth/csrf token errors in request

portal/static/js/src/admin.js, portal/static/js/src/modules/TnthAjax.js, portal/static/js/src/profile.js
Fixes in response to several (hundreds) request errors seen in email:
`Received error {'actor': 'user 9179',_ 'message': 'Error generated in JS - [Error occurred processing request]  '_            'status - request timed out/network error, response text - no '_            'response text returned from server [data sent]: '_            '{type:PUT,url:/api/user/9179/table_preferences/patientList,attempts:1,max_attempts:1,contentType:application/json; '_            'charset=utf-8,dataType:json,sync:false,timeout:5000,data:{\\\\sort_field\\\\:\\\\lastname\\\\,\\\\sort_order\\\\:\\\\asc\\\\,\\\\filters\\\\:{\\\\questionnaire_status\\\\:\\\\Overdue\\\\,\\\\visit\\\\:\\\\Baseline\\\\,\\\\orgs_filter_control\\\\:[14644],\\\\column_selections\\\\:[\\\\userid\\\\,\\\\firstname\\\\,\\\\lastname\\\\,\\ …
=> fix request retry logic related to setting table preferences
