uwcirg/truenth-portal

portal/app.py
portal/views/portal.py

Don't duplicate the exception - framework already logs exception.

Correct 'from' address to use configured value.

---

bin/deploy.sh

Here's my first pass at a deployment script, please don't hesitate to offer any critique or suggestions.
Notes:
- Runnable from any directory (pass git repo path with `-p`)
- Rudimentary detection of changes requiring:
- Python package installation
- Database seeding, migration
- Webserver restart

Push-button deployment script

---

bin/deploy.sh

This adds a "force" option to the deployment script to force all conditional deployment processes (eg update dependencies, DB).

Add "force" option to deployment script

---

portal/templates/layout.html
portal/templates/portal_wrapper.html
portal/views/crossdomain.py
portal/views/truenth.py
tests/test_truenth.py

Aligning behavior of protected and portal-header-wrapper.  Now identical
except that protected-portal-header-wrapper uses CORS.

Plugging security hole in login_url

---

manage.py
portal/app.py
portal/models/coredata.py
portal/models/organization.py
portal/static/js/main.js
portal/views/portal.py
tests/__init__.py
tests/test_coredata.py
tests/test_organization.py
tests/test_portal.py

if a user has already supplied all the upfront data.

Implementation for story #119865471 - flexible system for checking

---

docs/source/conf.py

Let me know if this seems like a bad idea!

Use project metadata for populating documentation boilerplate

---

portal/views/auth.py
portal/views/portal.py

as a state machine, to determine where to go after each stage including
logging in, gathering initial queries (data) and resuming interrupted
intervention OAuth token requests.

Refactored initial login flow.  Using the next_after_login() function

---

portal/app.py
portal/models/audit.py
portal/views/audit.py
tests/test_audit.py

this time.  Part of the solution for issue #131453777

Adding simple api to GET audit data for user - open to admins only at

---

portal/config.py
portal/templates/portal.html

TrueNTH" card, as it's hidden in the ePROMs-demo.

Adding config "SHOW_EXPLORE" to enable config control of "Explore

---

portal/templates/portal_wrapper.html
portal/views/portal.py
requirements.txt

Don't allow WRITE_ONLY users into /profile (NB - required extending

---

portal/static/css/eproms.css
portal/static/less/eproms.less

Fixing banner disappearing issue in Firefox.

fix banner disppearing issue in Firefox

---

portal/static/css/portal.css
portal/static/js/tnth.js
portal/static/less/portal.less

Update portal.less/portal.css to include css for added features, i.e. audit table and assessment profile tables in profile page.  In addition, add styling css for new layout for new layout in profile.html.  Additional media queries are also added.  Fix FOUC seen in portal wrapper.

Truenth css stylesheet updates and fix FOUC

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/challenge_identity.html
portal/views/portal.py

Fix the datepicker browser incompatibility issue - use boostrap datepicker object for all browsers since native date input type is not recognized by all
Add responsive styling to the challenge form

fix datepicker browser incompatibility issue in challenge form

---

docs/source/organizations.txt
portal/templates/shortcut_alias.html
portal/views/organization.py
portal/views/portal.py

As per #116993873 - clinic shortcuts now at /go - also now includes a

---

bin/deploy.sh

@ivan-c can you please review?  This is needed to react on commits to the site-persistence repos, as mentioned: https://www.pivotaltracker.com/n/projects/1225464/stories/133316477

Adding deploy switch to run seed.

---

requirements.txt

Reverts uwcirg/true_nth_usa_portal#149
Some kind of compatibility issue between celery/kombu:
[`python manage db seed` output](https://github.com/uwcirg/true_nth_usa_portal/files/567112/db_seed.log.txt)

Revert "Update kombu to 4.0.0"

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/initial_queries.html

- Fixed disabled button issue with checked org
- Fixed stylings in initial queries html
- Remove console.log code in JS in initial queries (some of which are from main.js)
- minor css fix for profile page

Fixes involving initial queries

---

portal/static/js/main.js
portal/templates/profile.html
portal/templates/profile_macros.html

Adding locale dropdown to user profile, allowing users to easily configure their own locales (default = site default locale)

Adding locale dropdown to profile

---

portal/static/js/main.js
portal/templates/profile_create.html
portal/templates/profile_macros.html

- Changes in response to story:
https://www.pivotaltracker.com/story/show/134750129
- Remove default check(s) on organizations based on staff affiliation(s)
- Default checking "None of the above" option for organization/affiliation(s)

staff creation of account - default checking none of the above option for organization/affiliation

---

portal/app.py
portal/views/auth.py
portal/views/extend_flask_user.py
portal/views/portal.py

Refactor challenge view to handle multiple needs (p/w change, invite,
etc.)

Prompt user to verify name and DOB on p/w change

---

portal/templates/profile_macros.html

After switching locales on profile screen, wait 1s then reload the screen (so that profile text will display in new language).

Reload page after switching locale

---

portal/static/js/main.js
portal/templates/profile.html
portal/templates/profile_macros.html

- invoking  call to validate form fields in profile to include name, birthday and email fields - appeared not to be invoked previously
- adjust validation check on email field to update field only after ajax call to check unique email address is done
- remove obsolete code from profile.html
- fixed hard coded instrument id code in assessment session list section to get it dynamically from api

invoking validation check on form fields in profile

---

portal/templates/profile.html

- presenting user with dialog when clicking on login-as-patient button
- clicking on OK in the dialog will redirect and login user as patient
- clicking on Cancel will dismiss the dialog

present confirming dialog as on-click-event for login-as-patient button

---

portal/models/intervention_strategies.py
portal/views/assessment_engine.py

* Allow multiple instruments to be queued for the Assessment Engine at once
* Instrument code path-parameter now accepts CSVs for instrument code

Multi-instrument queuing

---

portal/templates/profile.html
portal/templates/profile_create.html
portal/templates/profile_macros.html

- Add new clinical question, pcal localized, to account creation page
- Layout fix to profile page

new clinical question in profile account creation page

---

portal/views/patients.py

- addressing this story: https://www.pivotaltracker.com/story/show/135261361
- in patients.py - storing and assigning users from all child organizations belonging to a parent organization for displaying purpose
- the patient list for parent organization should contain users from all children organizations
Paul - let me know if you see any issue with this change.

patient list - top org table will include users from all child orgs

---

portal/views/extend_flask_user.py
portal/views/portal.py

Fix for #135344259 - hide challenge parameters for security and fix

---

portal/templates/challenge_identity.html

- made the fix to allow 1 digit for day of birthday
- toggle validation to display validation error when invalid entries are entered in the fields

validation fixes in challenge form 

---

portal/models/user.py
tests/test_audit.py

Reverts uwcirg/true_nth_usa_portal#275

Revert "Feature/provider consent check"

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/flask_user/_macros.html
portal/templates/flask_user/login.html

- Add reminder text in login page for user to use email address instead of username for login
- Text visible in Truenth, hidden in Eproms
- mobile css fixes for login page

adding reminder text to user in login page to use email address, Truenth ONLY

---

portal/models/intervention_strategies.py

https://www.pivotaltracker.com/n/projects/1225464/stories/135181653/comments/157464859
Minor design changes pending.

Near full implementation for

---

portal/templates/initial_queries.html
portal/templates/profile.html
portal/templates/profile_macros.html

- Adding pca_localized section in patient profile
- Visible in Eproms Only ( "pca_localized" must be  included in the show_macros variable in persistent file) 
- UI modification to uncheck diagnosis, cancer localized and treatment if biopsy question is answered no

adding pca_localized clinical question to patient profile -  EPROMS specific

---

portal/templates/landing.html

Reverts uwcirg/true_nth_usa_portal#287

Revert "add maintenance notice to landing page"

---

portal/app.py
portal/views/patient.py
tests/test_patient.py

(only search on email functional at this time)

Implement patient search in a FHIR compliant manner.

---

portal/templates/landing.html
portal/templates/portal_wrapper.html
portal/views/auth.py
portal/views/portal.py

- only start timeout session when user is logged in
- display timeout message as such if user is logged out due to timeout

portal wrapper timeout fixes

---

portal/static/js/main.js
portal/static/js/procedures.js
portal/templates/coredata.html
portal/templates/profile.html
portal/templates/profile_macros.html

- prevent ajax call from being sent when _custom_ validation errors occur on birthday and email fields (working on native errors - ajax update is already prevented)
- fix validation on procedure date (prevent year before 1900)
- user object property value assignments - assignment occurs only if property and object are present

front-end custom validation fixes in profile

---

portal/templates/initial_queries.html
portal/templates/initial_queries_macros.html

- scrolling fix - allowing browser scrolling to any next item in display - was missing from some items previously
-birthday field validation fixes - enhanced displayed error message and prevent ajax updates until all required birthday fields are filled.
- some layout css fixes on the initial queries page

initial queries refinements

---

portal/static/css/eproms.css
portal/static/less/eproms.less
portal/templates/flask_user/_macros.html
portal/templates/flask_user/register.html

- improve password validation message based on pattern, i.e. at least one lower case letter, one upper case letter and one number
- fix information message field id by dynamically populating it using input field id

front-end password field refinement fixes

---

portal/templates/profile_create.html

- Add write only role for new account - this should fix the invite email issue

add write-only role for newly created account

---

portal/models/auth.py

This change adds all of the context passed to the event callback `notify()` to the debugging log

Improve Event Callback Logging

---

portal/models/fhir.py
portal/models/procedure_codes.py
portal/views/procedure.py
tests/__init__.py

caused incorrect codings for procedures to land in the respective
codeable concepts.
This commit may cause server failures as it's erroring noisily if bad
data is found in the db.  Don't revert the commit - fix the db!

Bug in codeable concept insertion (comparing id's prior to commit)

---

portal/models/coredata.py
portal/templates/initial_queries.html

-  change in the logic so a user who is specified as a caregiver will not be prompted for further questions

initial queries fix to skip questions for caregiver user

---

portal/views/extend_flask_user.py

defined values for birthdate, first_name and last_name.

Provide backdoor for p/w change w/o challenge if user doesn't have

---

portal/views/auth.py
portal/views/portal.py

Fix for #135964191 - redirect to home if logged in user attempts /go or

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/profile.html
portal/templates/profile_create.html
portal/templates/profile_macros.html

- add consent history (to include deleted and expired consents also) section to profile
- fix ajax call to set consent only when no valid consent is present (not counting deleted and expired one(s)
- minor styling and text formatting fixes in profile creation page, found while testing

add consent history section to profile page

---

portal/static/js/main.js
portal/templates/profile_macros.html

- prevent submission of blank email address when updating demographics
- add error message in custom birthday field validations to prompt for missing date, year and/or month if missing
- fix ajax call for consent so it is not cached
- fix deletion of consent(s) to include all for the same parent org
- fix insertion of loading div - insert only if it does not already exists

general bug fixes in profile

---

portal/templates/initial_queries.html
portal/templates/initial_queries_macros.html

- address edge cases from story:https://www.pivotaltracker.com/story/show/135991095
- disable submit button on unselecting answer(s) on required fields
- automate code to include skipped questions
- remove hard-coded code where applied

initial queries fixes

---

portal/static/js/main.js

- dynamically populates organization name(s) in consent list in profile instead of relying on the existing org UI

fix org names for consent list in profile

---

portal/templates/initial_queries.html
portal/templates/initial_queries_macros.html

- prevent user from continuing if field (e.g. birthday) has invalid value
- add check to make sure all field are completed upon checking the organization before enabling the submit button

initial queries - field validations fixes

---

portal/views/auth.py
tests/test_auth.py

Added missing functions for broken and working case on
/oauth/token_status

Patching error seen in logs - don't crash w/o token on token_status

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/profile_create.html
portal/templates/profile_macros.html

- Add edit (e.g. delete) feature to consent list in profile to allow provider/admin to edit it
- minor fixes to issues found during testing in profile creation page to remove error messages related to org and pca_localized questions respectively once they are selected

allowing consent list in profile be editable by provider/admin

---

portal/models/user.py
portal/static/js/main.js
portal/templates/profile_macros.html

- add deceased status/date section to patient profile, viewable and editable only for provider
Paul - to give you a heads up, I found and fixed an issue I encountered while updating deceasedBoolean (see user.py, it seems that the "else" clause had one more indent than it should be).  Let me know if you see any issue with that.

add deceased status/date section to patient profile

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/profile.html
portal/templates/profile_macros.html

- button css and text fixes in consent List in profile
- display warning message in popover on withdraw consent button
- found during testing, minor bug fix to add loading div to gender field (to display update text)

consent UI fixes

---

portal/models/fhir.py
portal/models/intervention_strategies.py

Small refactor - moving general purpose methods to models.fhir from

---

portal/models/fhir.py
tests/test_assessment_status.py

https://www.pivotaltracker.com/n/projects/1225464/stories/135853115

Implementaion of assessment_status as per

---

portal/templates/profile.html
portal/templates/profile_macros.html
portal/views/patients.py

- pre-populate assessment button and modal based on pre-existing pcal localized status
- dynamically set button/modal if pca localized status changed in profile

front-end fixes for assessment button/modal in profile based on pca_localized question

---

portal/views/extend_flask_user.py

new user flow.  Put this feature on config "NO_CHALLENGE_WO_DATA"

The backdoor to let old users change passwords w/o challenge broke

---

portal/templates/patients_by_org.html
portal/views/patients.py

- adding consent date to patients list
- change "download" text to "export" in button and modal where applicable
- make username field invisible on first display, still selectable in columns selector

adding consent date to patients list and other fixes to patients list

---

portal/templates/profile.html

- fix escaped ampersand link in assessment links in profile

unescape ampersand character in assessment links

---

portal/templates/portal.html

- remove modal for registration button on home page
- add url redirect to registration button on home page

home page registration button fix

---

portal/models/intervention_strategies.py

https://www.pivotaltracker.com/n/projects/1225464/stories/137123227

Reflect assessment_status at /home cards - implementation for #137123227

---

manage.py
portal/site_persistence.py
tests/__init__.py

New flag for site persistence when unmentioned data is needed for

---

portal/static/js/main.js
portal/static/js/procedures.js
portal/templates/initial_queries.html
portal/templates/initial_queries_macros.html
portal/templates/profile_macros.html

Addressing this story: https://www.pivotaltracker.com/story/show/137033845
- Adding cancer treatment question back to initial queries page on the UI
- updating cancer treatment using procedure API, i.e. adding code for ajax calls in main.js
- consolidating loading div code in main.js (e.g. removing repetitive code)

adding cancer treatment question back to initial queries page

---

portal/templates/about.html

- remove unnecessary block from about page

ready document ready block from about page

---

portal/templates/gil/base.html

- add forget password link to login modal in GIL
- add validations to login and password fields in login modal in GIL, i.e. to prevent submission of empty form

add forget password link to login modal

---

portal/static/js/main.js

- fix the issue of ajax call to get wrapper HTML not working in IE9 by using javascript native XMLHTTPRequest object
- fix JS error in main.js encountered when testing in IE9

fix portal wrapper not rendering issue in IE9

---

portal/models/user_document.py
portal/views/user.py
tests/test_user_document.py

Adding an API endpoint allowing for downloading a specific user document. Returns that user doc's file contents.
Includes tests.

User Doc Download API endpoint

---

portal/templates/profile_macros.html

- remove cancer treatment question from Clinical Questions section in profile
this is to address this story: https://www.pivotaltracker.com/story/show/137643955

remove treatment question from profile page

---

portal/templates/gil/base.html
portal/templates/gil/contact.html
portal/templates/gil/decision-support.html
portal/templates/gil/index.html
portal/templates/gil/symptom-tracker.html

- add href attribute to links where applicable
- prevent loading div from displaying on contact page

Fix GIL links not working on IOS devices issue

---

portal/templates/gil/base.html
portal/templates/gil/index.html
portal/views/portal.py

- invoke modal on GIL home page when user is redirected back to with with redirect_uri request parameter
addressing this story: 
https://www.pivotaltracker.com/story/show/138007509

add modal for the presence of redirect_uri request parameter for GIL home page

---

portal/config.py

minor config change to start using the LR7 dev instance.

bind SS dev to CMS dev instead of stg

---

portal/static/js/main.js
portal/static/js/procedures.js
portal/templates/coredata.html
portal/templates/profile_macros.html

- verbiage changes (e.g. treatment to management option)
- add add button to allow user to change inputs if needed
- remove duplicate code from coredata.html (use common template from profile_macros.html instead)
- remove commented out code where applicable in profile_macros.html

front-end procedures section fixes

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/less/eproms.less
portal/static/less/portal.less

this is the css fix for the send email button in profile page

css fix for send email button

---

portal/static/js/main.js
portal/templates/challenge_identity.html
portal/templates/flask_user/change_password.html
portal/templates/flask_user/flask_user_base.html
portal/templates/flask_user/forgot_password.html
portal/templates/flask_user/member_base.html
portal/templates/profile_create.html

this applies to fields in forms where applicable.

trim text input field values before submitting data to back-end

---

portal/templates/profile_macros.html

this will apply to both Eproms and Truenth

In profile, UI fix to not allow staff to edit their own orgs

---

portal/views/auth.py

Assert we're getting an email back from the IdP, as the accounts being
created without one are invalid.

Handle IdP CancellationError in a sane manner (redirect home)

---

portal/templates/profile_create.html

added user_id in the parameters submitted to set consent via ajax for new user account.

submit user id in ajax request to set consent in account creation page

---

portal/static/css/topnav.css
portal/static/less/topnav.less
portal/templates/portal_wrapper.html

the portal wrapper layout changes affect both Eproms and Truenth
addressing this story: https://www.pivotaltracker.com/story/show/138376527

swap dropdown menu and logo on portal wrapper and css fixes

---

portal/templates/gil/about.html
portal/templates/gil/base.html
portal/templates/gil/contact.html
portal/templates/gil/decision-support.html
portal/templates/gil/index.html
portal/templates/gil/symptom-tracker.html
portal/templates/gil/what-is-prostate-cancer.html

Addressing this story:  https://www.pivotaltracker.com/story/show/138387791
- add code to close "sign up with us" upper banner once the user has closed it. applies to current browser session only.

GIL upper banner fix

---

portal/static/js/main.js
portal/templates/profile_macros.html

- added roles restrictions so that consent UI is viewable in patient's or patient partner's profile.
- minor orgs UI css fix

add roles restrictions to view consents ui in profile

---

portal/templates/gil/404.html
portal/templates/gil/500.html
portal/views/portal.py

adding custom 404 and 505 error pages for GIL,  visible in Truenth only

add custom GIL error pages, Truenth only

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/profile.html
portal/templates/profile_macros.html

- custom patient detail section to include login-as patient, send email to user, start assessment.
- see story: https://www.pivotaltracker.com/story/show/138535229
- the changes should only apply to Eproms

add custom patient details to patient profile, EPROMS only

---

portal/static/css/eproms.css
portal/static/css/gil.css
portal/static/css/portal.css
portal/static/css/topnav.css
portal/static/less/eproms.less
portal/static/less/gil.less
portal/static/less/portal.less
portal/static/less/topnav.less
portal/templates/gil/about.html
portal/templates/gil/base.html
portal/templates/gil/contact.html
portal/templates/gil/decision-support.html
portal/templates/gil/index.html
portal/templates/gil/portal.html
portal/templates/gil/symptom-tracker.html
portal/templates/gil/what-is-prostate-cancer.html

- fixed GIL menu when seen by logged-in patient
- layout fixes for GIL portal page
- css fixes for portal wrapper

GIL UI layout and menu fixes

---

portal/templates/profile_macros.html

- fix button and heading texts and login-as content in custom-patient-detail section

text fixes in custom patient details section in profile

---

portal/models/intervention_strategies.py
portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/profile_macros.html

This will apply to both Eproms and Truenth

add registration status in profile

---

portal/static/js/main.js

address this story: 
https://www.pivotaltracker.com/story/show/138527235

fixed signed date label in consents table UI

---

portal/static/css/gil.css
portal/static/less/gil.less
portal/templates/gil/base.html

- add access code field to GIL Join Us modal to allow user to enter access code
- general GIL links fixes to disable intervention links (e.g. decision support) if relevant interventions aren't enabled

modify GIL Join Us Modal to include access code field, general GIL link fixes

---

portal/templates/profile_create.html

- fix code to send in additional parameters (e.g. orgs, consent) per change in accounts api
- remove code that is no longer used

fix account creation issues

---

portal/templates/gil/base.html
portal/templates/layout.html
portal/templates/profile.html
portal/templates/profile_macros.html

addressing this story: https://www.pivotaltracker.com/story/show/138123523
- prevent browser from caching sensitive patient data
- prevent user from going back in browser history when logged in as patient
Paul, this might have a conflict with PR #506.  I will resolve the conflict after #506 is reviewed and merged.

add front end code to prevent user logged in as patient to go back in browser

---

portal/templates/profile_macros.html

thank you for catching that, Paul.  I have removed the clause.

remove redundant if clause from send email form macro in profile

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/profile.html
portal/templates/profile_macros.html

- add UI in profile to allow user to select their timezone
- convert time field(s) in profile based on user time zone

add frontend code for timezone conversion

---

portal/templates/profile_macros.html

- passing the correct authored date for each listed report in assessment section
- display no report message as needed

pro assessment section in profile fixes

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/less/eproms.less
portal/static/less/portal.less

fixed styling of orgs UI in both Eproms and Truenth.

orgs UI css fixes

---

portal/templates/initial_queries.html
portal/templates/layout.html

- removed extra white space  in initial queries page
- remove unwanted code from layout.html

minor css fixes in initial queries page

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/profile.html
portal/templates/profile_macros.html

The UI should only be visible in Eproms.  Using css to hide it in Truenth.

add study ID UI to profile

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/profile_create.html
portal/templates/profile_macros.html

- Add "user has no email checkbox" to allow no email be entered
- pass "__no_email__" value for email to the backend when no email is entered
- css fixes for the email field

add UI fix to account creation page to allow no email be entered

---

portal/models/user.py
tests/test_demographics.py

`__no_email__` that prefix is given a unique value for db stability, but
all request for the email as a string will return None.

Support users w/o email.  If demographics receives special value

---

portal/templates/profile_macros.html

disable send email select box if no email address is available

---

portal/audit.py
portal/migrations/versions/4b1e5b7b69eb_.py
portal/models/audit.py
portal/models/user.py
portal/views/assessment_engine.py
portal/views/auth.py
portal/views/clinical.py
portal/views/demographics.py
portal/views/group.py
portal/views/intervention.py
portal/views/organization.py
portal/views/patient.py
portal/views/portal.py
portal/views/procedure.py
portal/views/tou.py
portal/views/truenth.py
portal/views/user.py
setup.py
tests/__init__.py
tests/test_assessment_status.py
tests/test_audit.py
tests/test_clinical.py
tests/test_consent.py
tests/test_intervention.py
tests/test_site_persistence.py
tests/test_tou.py
tests/test_user.py

* Added subject_id field to audit
* Migration will populate with affected user from audit.comment (if it can be found), otherwise will copy over user_id
* Modified all existing audit creations and auditable_event() calls to include subject_id
* Added tests for subject_id to audit tests

Add subject_id to audit

---

portal/static/js/main.js
portal/static/js/tnth.js
portal/templates/portal_wrapper.html

- retry loading portal wrapper if ajax call failed the first time
- delayed showing wrapper to prevent appearance of unstyled content

frontend portal wrapper fixes

---

portal/models/reference.py
portal/static/js/main.js
portal/templates/profile.html

address this story:https://www.pivotaltracker.com/story/show/138527235
- not showing agreement column based on whether the consent was with parent org
- organization column should show parent organization
- bug fixes while testing - prevent session storage addition in private mode, fix 500 server error in reference.py when trying to cast int of NoneType, remove unnecessary if statement in showWrapper function in main.js

consent UI restrict viewing of columns for eproms, bug fixes

---

portal/static/js/main.js

- add back code that was accidentally removed - which will fix getOrgName call JS error
- add fixes for Firefox (e.g. only support UTC timezone, wrapper visibility fixes)

org name fix and fixes for firefox

---

portal/static/css/portal.css
portal/static/js/main.js
portal/static/less/portal.less
portal/templates/profile.html
portal/templates/profile_create.html
portal/templates/profile_macros.html

- remove Study Id field from patient's view of profile
- hide Study Id field in Truenth
- display error message when timezone conversion failed (and do not reload the page)

Frontend Study Id fixes, timezone error checking fixes

---

portal/static/css/gil.css
portal/static/js/gil.js
portal/static/js/main.js
portal/static/less/gil.less
portal/templates/gil/base.html
portal/templates/gil/index.html
portal/templates/initial_queries_macros.html
portal/templates/layout.html
portal/views/portal.py

Addressing this story: https://www.pivotaltracker.com/story/show/134455509
- fixed verbiage on the modal
- css fixes to make the modal responsive to browser sizes
- fixed ajax updates
- remove unnecessary code
- popstate event listener fix (back history)

GIL organizations modal fixes - ajax updates fixes, css fixes

---

portal/templates/initial_queries.html

- display pre-selected organization in initial queries (accessed via access code)
- update user role if needed

orgs UI fixes in initial queries

---

portal/static/css/gil.css
portal/static/js/main.js
portal/static/less/gil.less
portal/templates/gil/base.html
portal/templates/profile.html
portal/templates/profile_macros.html

- GIL organizations modal css fixes
- dismiss modal for the current browser session if presented once
- set organization ID = 0 if unselecting all organizations
- bug fixes in profile, add error checking to timezone conversion, remove custom code (for assessment) from profile .html to profile_macro.html

UI Fixes for GIL organizations modal

---

portal/templates/portal_wrapper.html

- fix portal wrapper visibility issue

portal wrapper visibility fix

---

portal/templates/profile_macros.html
portal/views/user.py
tests/test_user_document.py

Adds a list of patient reports to the user profile (section only appears if user has user documents, otherwise is hidden). List includes download button for each file.
Change includes adding optional parameter to userdoc GET api, allowing for filtering by doc_type.
Also includes tests for said new parameter.

Display patient reports

---

portal/static/css/portal.css
portal/static/less/portal.less
portal/templates/profile_macros.html

add css class to reduce white space, responsive to browser size

removing white space in profile for Truenth

---

portal/templates/gil/index.html

Intro text fix per request from Kellie

truenth intro text fix

---

portal/models/user.py
portal/static/css/eproms.css
portal/static/js/admin.js
portal/static/js/main.js
portal/static/less/eproms.less
portal/templates/patients_by_org.html
portal/templates/profile_create.html
portal/templates/profile_macros.html
portal/views/patients.py

address this story:https://www.pivotaltracker.com/story/show/139249273
- add widget on patients list page to allow patients list be filtered by orgs based on those of provider's
- refactor code in patients_by_org.html by moving utility js code to standalone admin.js file
- css fixes

add frontend feature to allow patients list be filtered by org(s)

---

portal/templates/patients_by_org.html

To address the issue that filter by orgs of patients list feature should only be seen in Eproms

add check for config variable to show filter by orgs UI

---

portal/static/css/topnav.css
portal/static/less/topnav.less

- centered the Truenth logo correctly in portal wrapper
- removed unnecessary media query css

tnth logo in portal wrapper positioning css fixes

---

portal/static/js/gil.js
portal/templates/flask_user/flask_user_base.html
portal/templates/flask_user/login.html

- In GIL, trim text field(s) before submitting responses
- trim text fields on paste event

front end trim text field fixes

---

portal/static/css/eproms.css
portal/static/js/admin.js
portal/static/js/main.js
portal/static/less/eproms.less
portal/templates/patients_by_org.html
portal/templates/profile_macros.html
portal/views/patients.py

- made the fix so the user can select from any org (parent and leave orgs) accessible to the user
- add clear/select all buttons to the dropdown
- bug fixes (in profile, fix timezone section error message display) and css fixes

Filter by Orgs in Patients List Fixes

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/admin.js
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/patients_by_org.html

- enable filter by orgs feature for truenth
- css fixes
- minor tweaks of UI

filters by org on patients list UI fixes

---

portal/static/css/gil.css
portal/static/js/gil.js
portal/static/less/gil.less
portal/templates/gil/base.html
portal/templates/gil/decision-support.html
portal/templates/gil/exercise-and-diet.html
portal/templates/gil/lived-experience.html
portal/templates/gil/symptom-tracker.html
portal/views/portal.py

- fix login/register modal layout
- add placeholder html pages for exercise-and-diet and lived-experience links
- add validation for access code in register modal
- refactor js code (moved some to gil.js)

another round of GIL UI revisions

---

portal/templates/initial_queries.html
portal/templates/initial_queries_macros.html

- remove code that was for debugging purpose, but should be removed

removing old code, console.log code from initial queries

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/flask_user/register.html

- apply GIL-style css to registration page
- re-format registration page layout
- retain color theme for Eproms

re-style registration page

---

portal/views/assessment_engine.py

* Pass instruments to be resumed from SS to AE through similar querystring param

Pass Resumed Assessments to AE

---

portal/static/css/eproms.css
portal/static/css/gil.css
portal/static/css/portal.css
portal/static/js/gil.js
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/gil.less
portal/static/less/portal.less
portal/templates/gil/base.html
portal/templates/gil/decision-support.html
portal/templates/gil/symptom-tracker.html
portal/templates/initial_queries.html
portal/templates/initial_queries_macros.html
portal/templates/profile_macros.html

addressing the following stories:
https://www.pivotaltracker.com/story/show/139500667
https://www.pivotaltracker.com/story/show/139494689
https://www.pivotaltracker.com/story/show/139711439
https://www.pivotaltracker.com/story/show/139485009
- provide access code validation feedback to user in GIL modal, delay redirect after a successful entry
- limit patients to enter one org (changing UI to radio button for patient)
- filter orgs for patients
- css fixes of orgs UI
- bug fixes of GIL links - direct user user to decision support link after registration (if starting point is decision support page)

front-end orgs related fixes

---

portal/static/css/gil.css
portal/static/less/gil.less
portal/templates/gil/base.html
portal/templates/patients_by_org.html
portal/templates/profile_macros.html

https://www.pivotaltracker.com/story/show/139763053
https://www.pivotaltracker.com/story/show/139763627
- change "assessment" text to "questionnaire text where applicable in UI 
- tentatively remove procedures section from profile in anticipation of rule(s) changes
- css fixes to GIL access code modal UI, add capture of paste event for access code entry

Frontend assessment and procedure UI fixes

---

tests/test_site_persistence.py

expectations (in this case, the latest).

Update the known_good_persistence_file to a version matching test

---

portal/templates/profile_macros.html

this should apply to Truenth only as patients can edit orgs in Truenth

fix orgs UI label for when editable by patient

---

portal/static/css/gil.css
portal/static/js/gil.js
portal/static/less/gil.less
portal/templates/gil/base.html

- display loading div when re-directing to intervention URL
- fix URL check to include checking full URL
- css fix of loading div

GIL redirect url fixes

---

portal/models/coredata.py
portal/static/js/main.js
portal/templates/initial_queries.html
portal/templates/initial_queries_macros.html
portal/templates/profile.html
portal/templates/profile_create.html
portal/templates/profile_macros.html
portal/views/patients.py

addressing this story: 
https://www.pivotaltracker.com/story/show/138544113
- remove pca_localized question where applicable
- remove unused code

remove pca_localized question

---

portal/static/js/admin.js
portal/static/js/main.js
portal/templates/patients_by_org.html

- add reset view listener to admin table to update row data (needed as some data are being updated via ajax now)

fix row data not updated issue in patients list

---

portal/models/fhir.py

(not if the string evaluates true!)
Fix for https://www.pivotaltracker.com/n/projects/1225464/stories/139958777

Corrected typo - test if 'completed' is in the details 

---

portal/static/css/gil.css
portal/static/js/gil.js
portal/static/less/gil.less
portal/templates/gil/base.html

https://www.pivotaltracker.com/story/show/139952665
styling fixes for login and other css fixes for GIL menu and modals
fixed bug to delay redirect after access code is entered in register modal

fix login button styling in Gil, delay access code redirect bug fix

---

portal/static/css/gil.css
portal/static/less/gil.less

- Fix scrollbar and overflow css issue in GIL home page

fix card container height and overflow issue in GIL/home page

---

portal/static/js/main.js
portal/templates/initial_queries.html

- fix the pre-select clinic check in initial queries
-fix time zone conversion check for browser support

bug fix in initial queries and timezone conversion check fix

---

portal/templates/initial_queries.html

address issue raised in this story:  https://www.pivotaltracker.com/story/show/139985955
- remove code as it is not needed

remove put role code from initial queries

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/portal.html

ridding extra white space seen in portal.html
and minor layout adjustment

portal.html layout fixes

---

portal/static/js/main.js

Paul - the is the fix for the study ID update issue I mentioned to you.  Do you mind reviewing this when you have a minute?  Thank you.

front end study ID update fix

---

portal/static/css/eproms.css
portal/static/css/gil.css
portal/static/css/portal.css
portal/static/js/gil.js
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/gil.less
portal/static/less/portal.less
portal/templates/gil/base.html
portal/templates/profile_create.html

- re-factor GIL js code, i.e. modularize the code as others
- GIL modal css fixes
- create profile page css fixes
- minor fixes in profile, e.g. error message display fixes, removed unused code

GIL js re-factoring css fixes, profile bug and css fixes

---

portal/models/fhir.py
portal/templates/profile_macros.html
tests/test_assessment_status.py
tests/test_intervention.py

Added to both cards and "Enter manually" (assess-as)

Add hpfs instrument to Ironman sequence

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/admin.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/patients_by_org.html

- sort patients list by id in descending order
- css fixes of filter by menu
- allow appearance of filter by menu when there is no patients result

patients list fixes

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/admin.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/patients_by_org.html

- fix css of filter menu (e.g. height of menu, button css)
- attach event to button to clear checkboxes
- update row data when switching to card view of patients list
- add error message display if rows update fails

patients list filter menu and card-view fixes

---

portal/views/auth.py

This enables interventions such as Sexual Recovery to direct users
to our site for registration, and then redirect them back to the
given 'next' target on the intervention site prior to obtaining any
outstanding data.

Add support to 'suspend_initial_queries' on account registration.

---

portal/static/js/main.js
portal/templates/profile_macros.html

- display procedures section based on show_macros procedures config variable
- add error display message for failed ajax calls for treatments

add procedures section back for truenth

---

docs/source/organizations.txt

https://www.pivotaltracker.com/story/show/139052395
Updating documentation to include information on the new race/ethnicity/indigenous coding options, including inheritance logic and the relevant user display property

Updating org docs with r/e/i coding option info

---

portal/models/coredata.py
portal/models/intervention.py

Fix for [SR and CP users shouldn't see some parts of initial-queries, eg clinic selection.](https://www.pivotaltracker.com/n/projects/1225464/stories/130776783)

Give SR users a pass on all core data.

---

portal/static/css/gil.css
portal/static/less/gil.less
portal/templates/flask_user/_macros.html
portal/templates/gil/base.html
portal/templates/gil/legal.html
portal/templates/gil/portal.html
portal/templates/gil/terms-and-conditions.html
portal/views/portal.py

addressing this story: 
https://www.pivotaltracker.com/story/show/140455791
- fix GIL legal and terms-of-use pages to get content from LR
- add copy right information in GIL header and footer of SS pages
- change display of legal to privacy
- css fixes

GIL content fixes

---

portal/models/app_text.py
portal/templates/gil/terms-and-conditions.html
portal/views/portal.py

add reference of GIL terms of condition to reference new LR item

reference GIL terms of conditions page to new LR item

---

portal/templates/initial_queries.html
portal/templates/initial_queries_macros.html

per discussion with Justin, change verbiage for checkbox for terms-of-use checkbox

change verbiage for tou checkbox in initial queries

---

portal/static/js/admin.js

- display withdrawn status for users with suspended consent status
- taking into consideration of deleted consent (don't display consent date etc. for this)
addressing this story: https://www.pivotaltracker.com/story/show/140371935
needed for tomorrow, not today's production release

patients list status display fixes

---

portal/static/css/gil.css
portal/static/less/gil.less
portal/templates/gil/base.html

per conversation with Justin (and conversation between Justin and Tony) - made the fix so the copyright text in GIL is now in the common footer area, not header.

place GIL copyright text in the footer instead of header

---

portal/models/fhir.py
portal/templates/profile_macros.html
tests/test_assessment_status.py
tests/test_intervention.py

* Add Ironman demographics instrument to sequence, last, after PREMS

Add Ironman demographics

---

portal/static/js/admin.js
portal/templates/patients_by_org.html

addressing this story:  https://www.pivotaltracker.com/story/show/140371935
- fix assessment status display in patients list
- refactor admin.js code, hastily written now coming around to clean it up (e.g. assign methods as prototype methods of class object, remove some unused code)
- remove redundant event listeners for updating patients list dynamically generated data (e.g. status consentdate)

refactor admin.js code, fix status display in patients list

---

portal/views/auth.py

This should have been part of PR #616 - overlooked due to haste
Fixes [Registration status as visible to staff (based on roles) - very confusing](https://www.pivotaltracker.com/n/projects/1225464/stories/139916119) by no longer swapping user identifiers, at least from the perspective of the invited user.

Finish up refactor to merge new registered account back into the invited user (weakly auth'd) one.

---

portal/config.py
portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/css/topnav.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/static/less/topnav.less
portal/templates/flask_user/login.html
portal/templates/landing.html
portal/templates/portal_wrapper.html

addressing this story:  https://www.pivotaltracker.com/story/show/140188597
- add banner in wrapper displaying system version
- banner is absolutely positioned, overlaying the wrapper, so does not change the layout of wrapper
- banner is displayed based on system config variable, "SYSTEM_TYPE".  This is done similar to how CPRO has done:  
Possible system type:
Staging | Development | Demonstration | Production
I welcome suggestion(s) of alternative way of doing this.

add banner displaying system version in portal wrapper

---

portal/models/fhir.py
portal/views/assessment_engine.py
tests/test_assessment_engine.py

* Adds `format` querystring parameter, allowing csv to be specified
* Generates a CSV file with a row for every FHIR `answer`
* Fields:
* identifier (inline JSON)
* patient_identifiers (inline JSON)
* authored
* instrument
* question_code
* answer_type
* answer
See [PT#139422745](https://www.pivotaltracker.com/story/show/139422745)

QuestionnaireResponse CSV Output

---

portal/templates/gil/terms-and-conditions.html
portal/views/portal.py

- correct assignment of value returned from tuple to get terms-and-conditions content

fix backend error for terms-and-conditions page

---

portal/static/css/gil.css
portal/static/less/gil.less
portal/templates/gil/base.html

addressing this story:  https://www.pivotaltracker.com/story/show/140188597
- add system type banner to GIL

add system type banner to GIL

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/css/topnav.css
portal/static/less/eproms.less
portal/static/less/portal.less
portal/static/less/topnav.less
portal/templates/flask_user/_macros.html
portal/templates/profile.html
portal/templates/profile_macros.html

minor layout fixes to sections in profile - in particular the communications section 
add sticky menu fixes - add code to dynamically determine its height, change glyphicon icons in sticky menu
add responsive styling fixes to sticky menu
per story: https://www.pivotaltracker.com/story/show/140188597  - change system type banner background color

minor layout fixes to profile page

---

portal/static/css/eproms.css
portal/static/css/gil.css
portal/static/css/portal.css
portal/static/css/topnav.css
portal/static/less/eproms.less
portal/static/less/gil.less
portal/static/less/portal.less
portal/static/less/topnav.less

per conversation with Justin, fixing the banner background color and text color as similar to that in CRPO

css fixes for system type banner

---

portal/templates/flask_user/login.html
portal/templates/landing.html
portal/templates/profile_macros.html

per stories:
https://www.pivotaltracker.com/story/show/140809905
https://www.pivotaltracker.com/story/show/140188597
- add system type banner to login and landing pages in EPROMs
- add additional items to sticky menu in profile in EPROMs

minor EPROMs specific fixes for banner and profile

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/css/topnav.css
portal/static/less/topnav.less
portal/templates/flask_user/login.html
portal/templates/landing.html
portal/templates/profile.html

address system banner disappearing issue in smaller browser sizes found by Justin
add anchor tag in sticky menu item so user can go to the url directly or see the url upon hovering (issue raised by Ivan today)

minor ui fixes

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/flask_user/_macros.html
portal/templates/patients_by_org.html
portal/templates/profile.html

addressing this story:  https://www.pivotaltracker.com/story/show/140979621
- add CSV as one of the download options in patients list page
- responsive styling fixes for profile page
@ivan-c 
Ivan, if you can help me test this to see if csv download works for you, I'd appreciate it.

add csv download option in patients list, styling fixes in profile

---

portal/templates/flask_user/_macros.html
portal/templates/profile.html

fix the overlapping content in footer section issue in profile 
- add media queries for footer to respond to different browser sizes

profile footer styling fixes

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/flask_user/_macros.html
portal/templates/profile.html
portal/templates/profile_macros.html

- add responsive css to fix issue of fields in profile being cut off in smaller browser sizes (e.g. name, birthday fields and footer)
- add async attribute to ajax calls in timezone section, deceased status section, a slight performance boost

Profile fields styling fixes

---

portal/static/css/topnav.css
portal/static/js/main.js
portal/static/less/topnav.less
portal/templates/portal_wrapper.html
portal/templates/profile_macros.html

address this story: https://www.pivotaltracker.com/story/show/141197631
- fix menu not appearing in portal wrapper in IE by not caching the ajax call to get portal wrapper HTML
- fix ul element list style issue in IE by adding inline styling and media queries

IE UI portal wrapper fixes

---

portal/views/assessment_engine.py
tests/test_assessment_engine.py

* Use HTTP PUT to update an existing QNR
* Will only update a single existing QNR that matches the given identifier exactly

Update partial questionnaire responses

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/flask_user/login.html

https://www.pivotaltracker.com/story/show/141240605
re-design login page affecting both Truenth & Eproms

redesign login page

---

portal/static/css/gil.css
portal/static/less/gil.less
portal/templates/gil/base.html
portal/templates/gil/portal.html

https://www.pivotaltracker.com/story/show/141247241
- add fixes to visibility of items based on user role as specified in the specs provided in the story
- styling fixes to registration button in GIL portal.html

GIL menu and button fixes

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/patients_by_org.html
portal/templates/profile.html

- fix column width styling issues in patients list
- add styling fixes for footer in profile (i.e. fixed overlapping content)
-add global variables in less files and re-compile portal.css and eproms.css for consistent font-size and color for common elements, e.g. button, link, input fields

styling fixes for profile and patients list pages

---

portal/templates/flask_user/register.html

https://www.pivotaltracker.com/story/show/141460037
- add custom registration texts for Eproms and Truenth respectively
**Note**  these changes are dependent on changes in following persistence file PRs:
https://github.com/uwcirg/TrueNTH-USA-site-config/pull/27
https://github.com/uwcirg/ePROMs-site-config/pull/18

custom text changes in registration page

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/profile.html
portal/templates/profile_macros.html

- fixed profile image position in profile page
- use flexbox css to display sub-sections of profile sections (e.g. responsive layout)
- general layout fixes

profile layout fixes

---

docker/Dockerfile
docker/docker-compose.yaml
portal/app.py
portal/config.py

* Use Redis config URLs directly with `redis.from_url()`
* Remove docker-compose env var defaults from Dockerfile
* Make Docker Apache port configurable by env var

Config Cleanup

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/main.js
portal/static/less/eproms.css
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/patients_by_org.html
portal/templates/profile.html
portal/templates/profile_create.html
portal/templates/profile_macros.html

- fix UI layout issues in smaller mobile devices
- fix link texts to be consistent (e.g. capitalize first letter)

ui responsive styling fixes

---

portal/models/user.py
tests/test_user.py

Final piece for https://www.pivotaltracker.com/story/show/137497435

Extend check_role for staff_admin needs.

---

portal/templates/profile_macros.html

https://www.pivotaltracker.com/story/show/141197667
- modify title for intervention reports and assessment sections
- add error checking for patient reports section

profile section titles changes

---

.travis.yml
app.json
docker/Dockerfile
portal/config.py

* Deploys Docker images created on TravisCI to Heroku, if configured (`HEROKU_APP`, `HEROKU_USERNAME`, `HEROKU_API_KEY`)
* Uses Heroku env vars (`PORT`, `REDIS_URL`, `DATABASE_URL`) to automatically configure Shared Services
* Not entirely functional yet, but good test-bed for Docker
* Later work could add a [Heroku button](https://devcenter.heroku.com/articles/heroku-button) to allow anyone to deploy Shared Services (if they sign up for a free Heroku account)

Heroku Continuous Deployment

---

portal/static/css/portal.css
portal/static/js/admin.js
portal/static/less/portal.less
portal/templates/layout.html
portal/templates/patients_by_org.html
portal/templates/profile.html
portal/templates/profile_macros.html

fixes made while doing rounds of testing: 
- adjust styling of send email UI in truenth
- fix send email UI to not allow sending email if email address is blank
- allow footer be a customizable template block in layout.html
- display error message for audit log (if error occurred)
- in patients list, hide export data button if there is no patient listed
- remove footer media queries from profile page, used customized footer instead

ui bug fixes

---

manage.py

* Fixes Docker bootstrapping issue

Always include interventions when initializing database

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/profile.html
portal/templates/profile_macros.html

doing one last round of checking of UI before demo update tomorrow
- fix input and button styling to be consistent (especial those in the procedures section in profile)
- styling fixes of ui on mobile devices, e.g. input fields

UI refinements

---

portal/models/organization.py
portal/system_uri.py
portal/views/organization.py
tests/test_organization.py

Backend solution for https://www.pivotaltracker.com/story/show/141769661

Implement organization search by state.

---

portal/templates/profile_macros.html
portal/views/user.py
tests/test_user.py

https://www.pivotaltracker.com/story/show/141435785
* Added API endpoint for resetting passwords
* Triggering user must have editing permissions over target user
* Sends password reset email to target user (using target user's email)
* Creates audit entry for password reset trigger
* Added div+button on profile page to call password reset endpoint
* div only visible if current user is not the profile user
* Added test for API endpoint method

Reset password functionality

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/initial_queries.html
portal/templates/initial_queries_macros.html
portal/templates/profile_macros.html

address this story: https://www.pivotaltracker.com/story/show/141769661
changes applied only to Truenth
- add custom clinics selector for patient in both initial queries and profile pages
- changes also include css fixes and some re-factorings of code in main.js

Clinics selector for patient

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/less/eproms.less
portal/static/less/portal.less

fix content overflow issue in profile page on smaller mobile device (i.e. iphone)

ui mobile fixes

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/patients_by_org.html

styling fixes of patients list to be responsive to smaller device sizes

minor responsive styling fixes to patients list

---

portal/models/fhir.py

* Update code set URLs to match changes on FHIR website (`.cs` added before `.json` suffix)
* Should probably switch to a snapshot we control (See [PT#142261201](https://www.pivotaltracker.com/story/show/142261201))
* Copy kept in repo
* Copy kept in another repo or gist

Valueset URL

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/less/eproms.less
portal/static/less/portal.less

minor styling adjustments made while testing
- align buttons and text 
- adjust button and input font-size and placement
- put back gradient class that was removed when styling sheet was re-factored and re-compiled

minor styling fixes in patient lists page

---

portal/static/css/portal.css
portal/static/less/portal.less
portal/templates/profile.html
portal/templates/profile_macros.html
portal/views/patients.py

address this story: https://www.pivotaltracker.com/story/show/142112811
- allow intervention staff to see the list of interventions with which the patient is associated in patient profile

add interventions list to patient profile

---

portal/templates/profile_macros.html

add show macro filter to interventions section 
see Truenth persistence file PR:  https://github.com/uwcirg/TrueNTH-USA-site-config/pull/30
This will allow the section to display in Truenth for now

add show macro filter to interventions section in profile

---

portal/static/js/main.js
portal/templates/profile_macros.html

- remove code that spun off ajax call when it shouldn't
- defer executing script for clinics selector and clinical questions

clinics selector fix

---

portal/templates/profile_macros.html

Ivan, my big apology in advance.  This fix was left out from last commit.  My mistake.  I accidentally removed it when I removed my debugging code last time.

add biopsy date fix that was left out from last commit

---

portal/static/css/eproms.css
portal/static/less/eproms.less
portal/templates/profile_create.html

address this story: https://www.pivotaltracker.com/story/show/142404551

default check org if only one present in create profile page

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/portal_wrapper.html

This is **not** to be included in the current release to Production
- fix the flash of un-styled content issue in portal wrapper by using combo of css and javascript fix - hiding content (via javascript) until it is rendered (via moving script code after html)
- remove white space in portal wrapper code to aid loading speed

fix flash of unstyled content issue in portal wrapper

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/admin.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/patients_by_org.html
portal/templates/profile_macros.html
portal/templates/sessionReport.html

address these stories related to instruments-related UI fixes:
https://www.pivotaltracker.com/story/show/142540331
https://www.pivotaltracker.com/story/show/142547801
- using code for question text if text is unavailable in instrument
- filter export data list in patients list based on user parent organization (e.g. CRV, Ironman)
- styling fixes of export data modal and assessment report

Instruments-related UI fixes

---

portal/templates/profile_macros.html

addressing this story one more time:
https://www.pivotaltracker.com/story/show/142540331
- rendering question based on code or linkId if text isn't available
- looping through the answer array instead of hard-coding the index to get at corresponding text for question and answer

fix instrument question text based on code if no text

---

portal/templates/flask_user/register.html

address this story: https://www.pivotaltracker.com/story/show/142739413
- move the password hints to be content of popover so user can see it first
- provide feedback to user as to whether the user's password has met requirements

Password hints UI fixes

---

portal/models/app_text.py
portal/static/css/eproms.css
portal/static/css/gil.css
portal/static/css/portal.css
portal/static/js/gil.js
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/gil.less
portal/static/less/portal.less
portal/templates/about.html
portal/templates/gil/base.html
portal/templates/gil/privacy.html
portal/templates/gil/terms-and-conditions.html
portal/templates/initial_queries_macros.html
portal/templates/privacy.html
portal/templates/profile_macros.html
portal/templates/terms-and-conditions.html
portal/views/patients.py
portal/views/portal.py
portal/views/tou.py
tests/test_app_text.py

https://www.pivotaltracker.com/story/show/139492813
- allow user with role of content manager to access LR editor link to edit LR content
**Note** these changes are dependent on PRs for persistence files for Eproms and Truenth

LR edit link addition in UI

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/initial_queries.html
portal/templates/portal.html

address this story:  https://www.pivotaltracker.com/story/show/142739533
- display loading indicator after user clicking on submit button on UI.  This applies to initial queries and home pages.

add loading indicator for submit buttons on UI

---

portal/templates/flask_user/register.html
portal/templates/profile_macros.html

- add feedback for unmatched criteria
- prevent user from submitting form without re-typing the password
- add one fix for IE for birthday date match (in profile)

Fixes for email hints popover

---

portal/static/css/gil.css
portal/static/less/gil.less
portal/templates/gil/about.html
portal/templates/gil/base.html
portal/templates/gil/what-is-prostate-cancer.html

address a number of stories here:
https://www.pivotaltracker.com/story/show/142862071
https://www.pivotaltracker.com/story/show/142861769
https://www.pivotaltracker.com/story/show/142861737
Fix GIL header location in logged-in state
add missing header info in PC Facts and  About pages

GIL header fixes

---

portal/views/assessment_engine.py

Update QNR status on submission

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/gil.js
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/flask_user/_macros.html
portal/templates/flask_user/register.html
portal/templates/gil/base.html
portal/templates/initial_queries.html
portal/templates/initial_queries_macros.html
portal/templates/patients_by_org.html
portal/templates/portal_wrapper.html
portal/templates/profile.html
portal/templates/profile_create.html
portal/templates/profile_macros.html
portal/views/portal.py

address a number of stories relating to registration flow changes and bug fixes:
https://www.pivotaltracker.com/story/show/142862151
https://www.pivotaltracker.com/story/show/142864339
https://www.pivotaltracker.com/story/show/142860527
https://www.pivotaltracker.com/story/show/143012227
https://www.pivotaltracker.com/story/show/143011941
main changes:
- various UI changes of initial queries page based on specs specified:
https://promowiki.movember.com/pages/viewpage.action?spaceKey=TU&title=User+Profile+%28Patient+or+Caregiver%29+Review+6+March+2017
- prevent user from leaving terms & conditions unless agreed
- eproms no email validation display fix
- eproms consent saving fix (address the js error that occurred in IE)

truenth registration flow changes and eproms registration bug fixes

---

portal/templates/profile_macros.html
portal/views/patients.py

Use the assessment_engine link_url for the staff link to enter manually.

Fix for https://www.pivotaltracker.com/story/show/139240057

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/main.js
portal/static/js/procedures.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/flask_user/login.html
portal/templates/flask_user/register.html
portal/templates/initial_queries.html
portal/templates/initial_queries_macros.html
portal/templates/landing.html
portal/templates/profile.html
portal/templates/profile_create.html
portal/templates/profile_macros.html

address profile UI and registration related changes in the stories:
https://www.pivotaltracker.com/story/show/142862373
as documented here: https://promowiki.movember.com/display/TU/User+Profile+%28Patient+or+Caregiver%29+Review+6+March+2017#UserProfile(PatientorCaregiver)Review6March2017-UserProfile
https://www.pivotaltracker.com/story/show/143212197
https://www.pivotaltracker.com/story/show/142862625
- numerous changes in profile page and registration related changes
- initial queries bug fix

Profile UI changes 

---

portal/static/js/admin.js
portal/static/js/main.js
portal/templates/profile_create.html
portal/templates/profile_macros.html

- remove checkbox attribute from orgs selector in account creation page
- orgs UI fix - to not display modal if the consent has been given with parent org

account creation and orgs UI bug fixes

---

Procfile
app.json
requirements.txt
setup.py

* Use `app.json` to specify how to deploy to Heroku:
* Deploy using URL from [Heroku button](https://devcenter.heroku.com/articles/heroku-button)
* `https://dashboard.heroku.com/new?template=https%3A%2F%2Fgithub.com%2Fuwcirg%2Ftrue_nth_usa_portal%2Ftree%2F$BRANCH_NAME`
* Required environmental variables, default values
* "Addons" (backing services)
* Redis
* PostgreSQL
Todo:

Heroku Deployment

---

portal/templates/profile.html
portal/templates/profile_macros.html

fix event propagation issue for login-as button to allow correct login-as behavior

fix login-as UI redirect issue

---

portal/static/css/eproms.css
portal/static/css/gil.css
portal/static/css/portal.css
portal/static/js/gil.js
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/coredata.html
portal/templates/initial_queries.html
portal/templates/patient_profile_create.html
portal/templates/profile_macros.html
portal/templates/staff_profile_create.html
portal/views/coredata.py

address ui-related issues, mostly organizations-related  in this story:
https://www.pivotaltracker.com/story/show/143523337
- fix orgs UI to prevent staff from editing it
- allow top level org to be saved for user(s) having top-level-org afiliation
- css fixes
- makes all editable sections in profile view-only with edit button
- fix email field placeholder text

profile ui fixes

---

portal/static/js/main.js

minor fix to save organization affiliation as none only when there is no existing cllinic affiliation (including top-level org(s))

no organization fix

---

portal/static/css/eproms.css
portal/static/less/eproms.less
portal/templates/initial_queries.html
portal/templates/patient_profile_create.html
portal/templates/profile_macros.html

address stories:
https://www.pivotaltracker.com/story/show/143599725
https://www.pivotaltracker.com/story/show/143602641
https://www.pivotaltracker.com/story/show/143603341
- center complete registration and continue button in initial queries page
- make sure disabled class is removed from email button when its attribute, disabled, is removed
- verbiage fix from "user" to "patient" in patient creation page

UI buttons fixes

---

portal/templates/profile_macros.html

noticed the send email event wasn't firing. Fixed but placing the script code in the correct shared template.

invite email events fix

---

portal/static/css/eproms.css
portal/static/less/eproms.less
portal/templates/profile_macros.html
portal/views/patients.py

https://www.pivotaltracker.com/story/show/143608927
- disabled enter manually button and display message when patient has completed all questionnaires

display manually entered button appropriatedly in profile

---

portal/static/js/gil.js
portal/templates/gil/base.html

adjust GIL header position before content fading in to prevent appearance of jumpiness

GIL header position fix

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/profile.html
portal/templates/profile_macros.html

fix inconsistent display of text (e.g. date string, no data), button in profile

fix inconsistent display in UI

---

.travis.yml

* Let build pass if UI/selenium testing fails (`TOXENV=ui`)

Allow UI tests to fail without failing build

---

.travis.yml
portal/config.py
tox.ini

Fix accidental consequence from commit 3ea3586271006dd690bf98585d458faf0025a8b0

Restore running tests on test db on systems with SQL environment variables

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/profile_macros.html
portal/templates/staff_by_org.html
portal/templates/staff_profile_create.html
portal/views/portal.py
portal/views/user.py

this should address issues raised by story:
https://www.pivotaltracker.com/story/show/143217817
- staff list for admin staff user will now exclude user(s) of admin or admin_staff role from the same org as the user
- allow staff admin user to create account of staff user of all orgs (not just leave orgs) of the user
- allow staff to send registration email for newly created user

staff admin page fixes

---

portal/config.py

Change default Liferay Origin

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/initial_queries.html
portal/templates/initial_queries_macros.html
portal/templates/profile.html
portal/templates/profile_macros.html
portal/views/patients.py
portal/views/portal.py

address story: https://www.pivotaltracker.com/story/show/143463375
- add display of TOU information to the consent list table
- handle pre-selected clinic to prompt user for consent, instead of implicitly adding the consent
- fix LR consent edit button display based on role

consent display fixes

---

portal/templates/initial_queries.html
portal/templates/initial_queries_macros.html

https://www.pivotaltracker.com/story/show/144045511
add focus to biopsy date field when biopsy yes radio is selected

biopsydate focus fix

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/profile.html
portal/templates/profile_macros.html

address story: 
https://www.pivotaltracker.com/story/show/143463375
add fix to display general terms if no consent is found for the patient
add orgs permission fixes
css fixes

general terms consent display fixes

---

portal/static/js/main.js
portal/templates/initial_queries.html
portal/templates/profile_macros.html
portal/views/portal.py

* Update develop with bugfixes from release/v17.4.22

Bugfix develop

---

portal/static/js/main.js
portal/templates/profile_macros.html

address minor text changes in this story:
https://www.pivotaltracker.com/story/show/144248419
@ivan-c 
Ivan, I think it would be good to include these minor text changes in the upcoming release.

minor text changes, including intervention report title

---

portal/views/patients.py

made the fix to filter patients list by consented users.

filter patients list by consented users

---

app.json
bin/deploy.sh
docker/Dockerfile
manage.py

Fixes as per https://www.pivotaltracker.com/story/show/134463297

initdb is now safe to call on existing dbs, and stamps the migration

---

.catalyze/post-build

* Run database migrations on Datica after build

Run database migrations after build on Datica

---

portal/views/patients.py

needed to do this fix after rounds of testing:
fix the query to include consented patients from child org(s) of current user orgs in the patients list, previously had excluded them

patients list child orgs fixes

---

manage.py
portal/models/organization.py
portal/models/user.py
setup.py

Reverts uwcirg/true_nth_usa_portal#838

Revert "Replace Flask-Script with builtin Flask.cli"

---

.catalyze/post-build
app.json
bin/deploy.sh
docker/Dockerfile
manage.py
portal/config.py
portal/models/organization.py
portal/models/role.py
portal/models/user.py
setup.py

* Second attempt of #838
* Fixed issues with calling seed() and Click decorators

Replace Flask-Script with Flask CLI

---

portal/static/css/gil.css
portal/static/less/gil.less
portal/templates/gil/base.html

https://www.pivotaltracker.com/story/show/141278441
additional links include: facebook, twitter and contact us links

Additional links in GIL footer

---

portal/templates/profile_macros.html

found this bug while testing in eproms 
fix view-only rendering of organizations for patient
minor verbiage fix for birthdate validation

eproms patients orgs view fix, minor verbiage fix for birthday validation text

---

portal/static/js/main.js
portal/templates/profile_macros.html

- allow consent date for consent agreement be editable for patient with the role of TEST.
@pbugni  Paul, I'd appreciate it if you can take a look at these changes as discussed.

Edit consent date UI changes for test patient

---

portal/views/patients.py

found this bug while testing - 
exclude patient with no affiliation from patients list

exclude patients with no affiliation from patients list

---

portal/views/portal.py

Disables search engine indexing on non-production, non-demo systems (eg staging, development)

Add robots.txt

---

portal/templates/profile_macros.html

* changing the profile phone field text on the pre-Edit screen from 'Phone' to 'Cell' (with localization) - same as it appears in the Edit screen

Correcting the pre-Edit phone field text

---

portal/models/intervention_strategies.py

fix server error due to null due date returned for questionnaire

null due date fix in intervention strategies py

---

portal/static/css/eproms.css
portal/static/less/eproms.less

fix styling issues especially in smaller browser sizes and mobile devices for eproms patient home page

styling fixes for eproms patient home page

---

portal/static/css/gil.css
portal/static/less/gil.less

GIL Lived experience page styling fixes to include:
button placements in footer in smaller browser sizes
video container placement fixes
layout fixes

LE page footer style fix, and other css fixes

---

portal/views/demographics.py

Resolution for problem reported by Martin.

Another user error warning for /api/demographics

---

manage.py
portal/site_persistence.py
tests/test_site_persistence.py

Invert logic - user now must take action to exclude_interventions on

---

portal/static/css/gil.css
portal/static/less/gil.less

found this while testing:
fixing styling of home dashboard for user with partner role
- align buttons correctly
- fix style of buttons to be more GIL-like
would be nice to also include this in the release as it corrects the styling of dashboard for partner user(s)

truenth partner user home page styling fixes

---

portal/templates/gil/lived-experience.html

text fix for LE page as requested by MO.
needed for this release.

minor text change in LE page

---

portal/templates/gil/alonzo_mccann_story.html
portal/templates/gil/hirsch_brothers_story.html

fix the title for LE stories from objective No 1 to objective No 2
Needed for this release

title text changes for LE story pages

---

portal/static/js/main.js
portal/templates/profile_macros.html

https://www.pivotaltracker.com/story/show/145231443
Add prostate cancer localized question in clinical questions section in profile

add pca localized question in clinical questions section in profile

---

portal/templates/gil/david_andrew_story.html

change title objective 1 to object 2 in LE story page

text fix in LE story page

---

portal/templates/flask_user/_macros.html
portal/templates/portal.html
portal/templates/profile.html

- remove duplicate code for rendering footer and extend common footer template for flexibility for different layout and different logo image

remove duplicate code for footer in UI, extend common footer template

---

portal/static/css/eproms.css
portal/static/less/eproms.less
portal/templates/patients_by_org.html

Found while testing in eproms:
Fix display of study Id in patients list and profile
remove inline styling from patients list
not for this release. can be merged into develop upon review.

fix display of study Id in patients list and profile

---

portal/static/js/main.js
portal/templates/profile_macros.html

address this issue:
https://www.pivotaltracker.com/story/show/145567539
display correct selected timezone after changing it in view 
display locale only when available in the locale selection box

fix selected timezone display issue

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/flask_user/register.html

address this story: https://www.pivotaltracker.com/story/show/145725667
place create password label just above password field

fix password label location on registration form

---

portal/static/css/eproms.css
portal/static/less/eproms.less
portal/templates/profile_macros.html
portal/views/assessment_engine.py

address this story: 
https://www.pivotaltracker.com/story/show/142322617
-  allow user to set method for manual entry for questionnaires
- pass set entry method to assessment engine

add modal for manual entry button, pass manual entry method to AE

---

.travis.yml
portal/config.py
tox.ini

* Upload strings for translation in new `translations` TravisCI job/tox env
* Only upload from `develop` branch

Smartling CI upload

---

portal/models/user_document.py
portal/views/user.py

* changing language of patient report -related descriptions to be less specific to WiserCare
* modified some line layouts to fit pep8 standards

Rewrite patient_report description to be more generalized

---

portal/templates/profile_macros.html

https://www.pivotaltracker.com/story/show/144718977

fix assessment report date display

---

portal/static/js/main.js
portal/templates/profile_macros.html

made fixes to issues found while testing:
- provide text display when no data is shown in patient detail section
- remove optional class from indigenous section

provide indication in patient detail when no data is displayed

---

portal/models/user.py
portal/templates/patients_by_org.html

* add UserDocuments of doctype 'PatientReport' to the Reports column on the /patients list
* includes helper method on User model
* docs are displayed by filename, and are clickable download links for that doc

Add UserDocument PatientReports to reports column

---

portal/models/assessment_status.py
tests/test_assessment_status.py

Bug in AssessmentStatus.overall_status() for in-progress vs partially
completed.
Improved comments to help understand the complexity of the method.

Fix for https://www.pivotaltracker.com/story/show/145972087

---

portal/templates/patient_profile_create.html
portal/templates/staff_profile_create.html

address this story:  https://www.pivotaltracker.com/story/show/145959201
save default consent if consent agreement is missing for the assigned organization at account creation.

consent fix for patient/staff account creation

---

portal/models/fhir.py

See [PT#142574099](https://www.pivotaltracker.com/n/projects/1225464/stories/142574099)
* Adds fields to CSV and JSON QNR exports
* Org name
* QNR.status

Expose QNR fields in JSON/CSV export

---

.pep8speaks.yml

* Add comments about PEP8 styling during pull requests

Add PEP8 Speaks config

---

portal/templates/profile_macros.html

made fixes for issue found while testing - not able to send email invite to new staff
also wrapping email text in translation tags

staff invite email fixes

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/coredata.html

address this story: 
https://www.pivotaltracker.com/story/show/146120339
- add GIL footer to acquire data form via API call to get portal footer HTML
- add css fixes to acquire data form and procedures section

add GIL footer to acquire data form

---

portal/views/portal.py

@achen2401 will this work for sending in errors from front end code?

Adding endpoint for front end error reports.

---

portal/static/js/main.js
portal/templates/patient_profile_create.html
portal/templates/staff_profile_create.html

client side error reporting via ajax call to API, see PR #978

add client side generated server error reporting via ajax

---

portal/static/js/gil.js
portal/templates/gil/base.html
portal/templates/gil/portal.html

I have been meaning to do this, finally gotten around to do it
- refactor GIL js code.   The code should function the same way.  The changes including modularizing the function code (e.g. filterMenu function, moving it from template to js file) so it belongs to a class (for scope protection); minimizing crowding of global scope by removing unnecessary global functions (e.g. invoking via event of an element) and making declared variables private; separate out event invocation code from gil.js file (put it in base template instead) for organization purpose; remove unnecessary class declaration code;

refactor GIL JS code, including modularizing functional code

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/coredata.html

https://www.pivotaltracker.com/story/show/146120339
https://www.pivotaltracker.com/story/show/146386713
fix broken button issue, minor styling fixes

acquired data page fixes

---

.travis.yml
portal/config.py
portal/models/i18n.py

* Move Smartling project_id to each persistence file
* Upload translations for each project

Smartling ePROMs upload

---

portal/templates/coredata.html

- add loading indicator to give indication of redirection of url
- add error checking if redirect url is invalid

add loading indicator and error checking to acquire data page

---

portal/models/intervention_strategies.py

https://www.pivotaltracker.com/story/show/144303371
minor verbiage fix and move logout button location

add s at the end of completed questionnaire heading

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/templates/initial_queries.html
portal/templates/profile.html
portal/templates/profile_macros.html

https://www.pivotaltracker.com/story/show/146494723
https://www.pivotaltracker.com/story/show/146494631
remove left navigation panel from profile page, fix layout in profile, minor text change in treatments section and refactoring of code in profile page (e.g. removed redundant calls, etc.)
Note, keeping code for left navigation panel commented out so can put it back later if needed again
fix styling issue in initial queries page - progress bar is now drawn in proportion, and fix footer layout issue

UI layout changes and profile page re-factoring

---

portal/views/portal.py

address this story: https://www.pivotaltracker.com/story/show/146635611
For Eproms only, prevents privacy policy page from publicly viewable

made privacy policy page unavailable for EPROMs

---

portal/models/app_text.py
portal/models/organization.py
portal/templates/flask_user/_macros.html
portal/templates/privacy.html
portal/templates/terms.html
portal/views/portal.py

address stories:
https://www.pivotaltracker.com/story/show/146483197
https://www.pivotaltracker.com/story/show/146637257
add new privacy and terms link based on user role and organization
**NOTE**  This is dependent on the EPROMs persistence file changes in this PR: https://github.com/uwcirg/ePROMs-site-config/pull/34

links app text changes

---

portal/models/intervention_strategies.py

https://www.pivotaltracker.com/story/show/144304907
fix text in patient's dashboard when patient has completed the questionnaires

remove date and text fixes in patient's dashboard

---

portal/templates/initial_queries.html

found this while working on the file -
add else statement for getting needed data
otherwise the needed data resulted from ajax call will be overridden

add neglected else statement to if statement for getting needed data

---

portal/templates/patient_profile_create.html

- add error message display when a required field is not filled out in account creation page upon data submission

add better error message indication in account creation page

---

bin/deploy.sh

Prevents bootstrap issue caused by flask CLI using old config values

Remove old site configuration before downloading new one

---

portal/templates/profile_macros.html

https://www.pivotaltracker.com/story/show/146344059
made fix to allow multiple responses to a question in the questionnaire be rendered
@ivan-c Ivan, FYI

fix multiple responses rendering in questionnaire response

---

portal/templates/patients_by_org.html

address this story: https://www.pivotaltracker.com/story/show/146902661
fix report link style in patients list

fix button style on patients list

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/initial_queries.html
portal/templates/initial_queries_macros.html
portal/templates/profile_macros.html
portal/templates/website_consent_script.html
portal/views/coredata.py
portal/views/portal.py

https://www.pivotaltracker.com/story/show/146638933
https://www.pivotaltracker.com/story/show/146639099
add website consent flow for Eproms

Web consent and  tou front-end changes

---

portal/models/user.py
portal/views/portal.py

refactored out common and deep if;then;else trees in common lookup
for user's first_top_organization().

Allow anonymous view of /privacy

---

portal/templates/patients_by_org.html

* modified 'PatientReport' column of /patients list
* display based on intervention name
* if Symptom Tracker, display 'ST'; otherwise, display 'DS'
* only list buttons for distinct interventions

Modify PatientReport column display in /patients list

---

portal/models/app_text.py
portal/views/portal.py

This enables hiding the patient oriented content from staff users.

Add role descrimination to WebsiteConsentByOrg_ATMA.

---

portal/templates/patient_profile_create.html

- fix error message generated when account creation failed - indicating no user id created when applicable
- removed hard-coded code (i.e. field names) for clearing fields after account created

account creation error message fix

---

portal/static/css/portal.css
portal/static/less/portal.less
portal/templates/patients_by_org.html

https://www.pivotaltracker.com/story/show/146902661
- fix styling of buttons in patients list

add styling fixes to reports buttons on patients list

---

portal/models/app_text.py
portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/initial_queries.html
portal/templates/initial_queries_macros.html
portal/views/portal.py

address these issues related to initial queries page:
https://www.pivotaltracker.com/story/show/147461653
https://www.pivotaltracker.com/story/show/147371649
- refactor UI code
- hide terms intro terms as needed (for eproms)
- refactor portal.py code for getting terms app text

initial queries ui code bug fixes and refactoring

---

portal/static/css/portal.css
portal/static/less/portal.less

saw this while testing, made minor styling fix for buttons for reports in patients list (allows slight margins between buttons)

fix buttons styling for reports in patients list

---

portal/static/js/main.js
portal/templates/flask_user/_macros.html
portal/templates/initial_queries.html
portal/templates/profile.html
portal/templates/profile_macros.html
portal/views/patients.py

- mostly re-factoring of code by removing unnecessary/unneeded/repetitive code related to consents
- add comments to allow reminders of what the code does
- indent code when needed
** Not needed for this release**

refactor consents UI code

---

portal/views/user.py

* added logging for 500 errors on PatientReports, for easier debugging

Log PatientReport POST 500 errors

---

portal/templates/landing.html
portal/templates/patient_profile_create.html
portal/templates/patients_by_org.html
portal/templates/profile_macros.html

add missing translation tags in portal templates

add missing translation tags in portal templates

---

portal/templates/profile_macros.html

https://www.pivotaltracker.com/story/show/147655861
- UI fix to disable study ID field in patient view of profile

UI fix to prevent patient from editing study Id field

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/initial_queries.html
portal/templates/initial_queries_macros.html
portal/templates/profile_macros.html

https://www.pivotaltracker.com/story/show/147777315
- remove datepicker from biopsy date field
- add month, day year fields for the biopsy date
- css fixes

biopsy date UI changes

---

portal/templates/profile_macros.html

https://www.pivotaltracker.com/story/show/144248401
- add patient reports section in patient's view of profile
- was previously misplaced in the wrong section of template

add patient reports for in patient's view of profile

---

portal/static/css/portal.css
portal/static/less/portal.less
portal/templates/initial_queries.html
portal/templates/initial_queries_macros.html

found some of these issues when testing:
- fix biopsy date field styling in different browser sizes.
- slowed the scroll to the next field.  
- fix UI issue when localized returned as still needed data
- remove unused code

initial queries UI fixes/refinements

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/patients_by_org.html

https://www.pivotaltracker.com/story/show/147878139
add TrueNTH specific ID label for ID column in patients list

patients list id label fix

---

portal/static/css/topnav.css
portal/static/less/topnav.less
portal/templates/portal_wrapper.html

address this story: https://www.pivotaltracker.com/story/show/147781111
fix styling issues for branded logo in portal wrapper

branded logo e.g. wisercare logo css fixes

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/patient_profile_create.html
portal/templates/profile_macros.html

https://www.pivotaltracker.com/story/show/147878139
add site ID field in account creation and profile pages for TrueNTH
**NOTE** changes are dependent on this PR:
https://github.com/uwcirg/true_nth_usa_portal/pull/1067

external site ID UI changes

---

portal/static/js/main.js
portal/templates/initial_queries.html

addressing this story:
https://www.pivotaltracker.com/story/show/147655653
front-end fixes for adding/displaying organization associated with terms of use
**NOTE**  Changes are depending on this PR: https://github.com/uwcirg/true_nth_usa_portal/pull/1071

organization ID in terms - EPROMs 

---

tests/test_assessment_status.py

reported in https://www.pivotaltracker.com/story/show/147880043

Adding boundary date tests to confirm we handle edge cases as

---

portal/models/app_text.py
portal/templates/initial_queries_macros.html
portal/templates/website_consent_script.html
portal/views/portal.py

per chat with Diana and updates in this documentation:  https://promowiki.movember.com/pages/viewpage.action?pageId=18812800
- update text in terms presented to user during manual entry
- add new LR items for website declaration form, one for CRV and one for IRONMAN
**NOTE** this is dependent on changes in EPROMs persistence file: https://github.com/uwcirg/ePROMs-site-config/pull/46

update verbiage and declaration form for manual entry in EPROMs

---

portal/static/js/main.js
portal/templates/patient_profile_create.html
portal/templates/profile_macros.html

Found this while testing in Truenth - state associated with the organization for the newly created patient account was not selected on the UI
Fix is to add front-end code to submit state information for organization

submit state information in Account creation

---

portal/templates/initial_queries_macros.html
portal/templates/website_consent_script.html

When reviewing the content documentation : https://promowiki.movember.com/pages/viewpage.action?pageId=18812800
noticed that I neglected to fix the intro text that includes organization name

fix intro text for manual entry

---

portal/templates/initial_queries_macros.html

correcting text discrepancies when reviewing documentation:https://promowiki.movember.com/pages/viewpage.action?pageId=18812800

checkbox text fix for IRONMAN interview-asisted checkbox

---

portal/static/css/gil.css
portal/static/less/gil.less
portal/templates/gil/base.html

found this while testing in Truenth:
remove teal css class from login button as it has a different color theme

remove teal css class from GIL login button

---

portal/static/css/portal.css
portal/static/less/portal.less

minor styling fix of site id field in account creation page (for TrueNTH)

fix site id styling in account creation page

---

portal/models/role.py
portal/static/css/portal.css
portal/static/less/portal.less
portal/templates/portal_wrapper.html
portal/templates/reporting_dashboard.html
portal/views/portal.py

https://www.pivotaltracker.com/story/show/147783817
* created initial version of reporting dashboard
* accessible to 'admin' and 'analyst' roles
* api endpoint + html template
*includes User Stats and Institution Stats section (no graphs yet, just counts)
* for full definitions of sections, see PT story
* created 'analyst' role, which only has access to reporting (no PHI)
* added new page to dropdown menu (if user has appropriate roles)

Initial version of reporting dashboard

---

portal/models/auth.py

* fixing issue of deleting clients that are referenced by grants, by adding a relationship to Grants in the Client model, and including a delete cascade

Client deletion bug fix

---

portal/templates/gil/base.html

address this story: https://www.pivotaltracker.com/story/show/147480971
add reporting dashboard item to GIL menu

add reporting dashboard item to GIL menu

---

portal/app.py
portal/config.py
portal/extensions.py
portal/templates/contact.html
portal/templates/gil/contact.html
portal/views/portal.py
requirements.txt
setup.py

https://www.pivotaltracker.com/story/show/148387559
* adding flask-recaptcha to app
* added config values for captcha (connects to `bob25mary@gmail.com` admin panel) - should get pulled from `os.environ`
* adding recaptcha to `/contact` page
* only appears (and subsequently checks) if user is not logged in, and proper configs are set
* if recaptcha cannot be verified on submit, reloads `/contact` page instead of attempting to send a contact message

Recaptcha for contact form

---

portal/views/portal.py
tests/test_portal.py

as per https://www.pivotaltracker.com/story/show/147150023

move settings/KEY under the common api/ request path

---

portal/views/auth.py

Fix for https://www.pivotaltracker.com/story/show/148614995

Don't error on un-known oauth providers - generate 404.

---

portal/views/auth.py

* on oauth login:
* explicitly check that the given `provider_name` is valid given our enum `providers_list`
* explicitly check that we have the correct configurations (`CONSUMER_KEY` and `CONSUMER_SECRET`) for the given provider.

Check oauth config during oauth login

---

portal/templates/profile_macros.html

https://www.pivotaltracker.com/story/show/147878139
not display site id or study id field in patient's view of profile

not rendering site id/study id field in patient's view of his profile

---

portal/models/assessment_status.py
tests/test_assessment_status.py

Fix for https://www.pivotaltracker.com/story/show/146631689

Bugfix for expired questionnaires that were in-progress

---

portal/views/auth.py

Fix for https://www.pivotaltracker.com/story/show/142914901

After promoting registered user to invited, set local user var!

---

portal/static/js/main.js
portal/templates/initial_queries.html
portal/templates/initial_queries_macros.html
portal/templates/profile_macros.html

found error message display issues today during prolonged periods of attempts to connect to instances (e.g. stg.eproms).  Some errors were not displayed because they were overridden by others.
- made fixes to display errors specific to types (e.g. GET, PUT, DELETE ajax requests)

fix error message display on the UI

---

portal/static/js/main.js

found this while testing:
- not requiring data in consent hour/minute/second fields while editing
- set default values for hour/minute/second consent fields

add default values for h/m/s for consent date field

---

portal/static/css/eproms.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/templates/initial_queries.html

per conversation with Justin and address this story: https://www.pivotaltracker.com/story/show/147655653
make subject website consent terms link to LR consent item in profile
fix disabled links in menu
needed for this release

Eproms terms link fixes

---

portal/templates/gil/base.html

found this while testing in stg.us:
fix styling of login button in login/register modal for GIL

add button--teal css class back to login-register button

---

portal/views/portal.py

Fix for https://www.pivotaltracker.com/story/show/148716703

Raise 400 on missing data rather than assertion.

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/flask_user/login.html
portal/templates/flask_user/register.html
portal/templates/patients_by_org.html

add missing translation tags to portal templates during translation tags review
add minor styling fixes to profile page

add missing translation tags, minor profile page styling fixes

---

portal/config.py

Default LR_GROUP id changed - fix for functionailty on systems

---

portal/models/user.py

* added additional checks (w/ aborts) for blank email & duplicate email during `User.update_from_fhir()` (called via demographics PUT)

Additional checks on email during demographics PUT

---

portal/static/js/main.js
portal/templates/patient_profile_create.html

Follow up on account creation error messages stemming from request timing out/network issues
- remove static functions and change them to methods of an object that also handle retries of ajax calls for account creation
- remove unused code

account creation retry changes

---

portal/views/portal.py

https://www.pivotaltracker.com/story/show/149025755
* additional data checks in `/contact POST` endpoint
* must provide sender email (which must include '@')
* must provide email body

Check for body & sender email in contact post

---

portal/static/css/eproms.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/templates/profile_macros.html

found these issues while test:
-  made fix to not draw orgs UI elements again if they have been drawn already
-  made fix to draw orgs UI elements that do not have state/region specified
- css fixes

orgs by state selector fixes

---

portal/views/auth.py
tests/test_encounter.py

Fix for https://www.pivotaltracker.com/story/show/149105827

login-as restricted to patients and partners.

---

portal/templates/contact.html

https://www.pivotaltracker.com/story/show/149135619
- verbiage change in eproms contact page
**Note**  This is needed for this week's release.  This should go out in tandem of a change in persistence file.  PR: https://github.com/uwcirg/ePROMs-site-config/pull/47

eproms contact page intro text change

---

portal/templates/contact.html
portal/templates/gil/base.html

per issue found by Sie-ce -
add missing csrf token field to forms that need them

add missing csrf header in UI forms

---

portal/static/js/main.js
portal/templates/profile_macros.html

https://www.pivotaltracker.com/story/show/149043645
* created `escapeHtml()` js function, to escape out HTML special characters
* applied new escape function to specific fields in `#profilePatientReportTable` and `#profileAuditLogTable`, to prevent any XSS attacks via user-editable text fields.

Prevent XSS Attacks (display-side)

---

portal/static/css/eproms.css
portal/static/less/eproms.less
portal/templates/initial_queries_macros.html
portal/templates/website_consent_script.html
portal/views/portal.py

found this while testing:
- fix error received (i.e. unable to validate client origin) when attempting to complete assessment via manual entry mode
- css fixes of website consent script page

website consent script page fixes

---

tests/test_portal.py

* updating `test_portal.test_redirect_validation()` to reflect changes in https://github.com/uwcirg/true_nth_usa_portal/pull/1156

Update tests for changes to website-consent-script API

---

portal/models/app_text.py
portal/models/message.py
portal/static/js/main.js
portal/templates/profile_macros.html
portal/views/portal.py
tests/test_portal.py

address this story:  https://www.pivotaltracker.com/story/show/149178933
- update staff registration email content for EPROMs
**Note**  This should go out in tandem of persistence file change, https://github.com/uwcirg/ePROMs-site-config/pull/50
@ivan-c  Ivan, this is the change that MO needs for this release, so this will need to be a hotfix.  Please review at your convenience.  Thank you very much in advance.

eproms registration staff email changes

---

portal/models/intervention_strategies.py
portal/static/css/eproms.css
portal/static/less/eproms.less
tests/test_portal.py

per chat with Justin and defect found by Diana:
remove duplicate logout button from completed assessment dashboard
**NOTE** needed for this release
@ivan-c   Ivan, another hotfix for this release.  Please review at your convenience.  Thank you!

remove duplicate logout button from completed assessment dashboard

---

portal/static/js/main.js
portal/templates/patient_profile_create.html
portal/templates/profile_macros.html

address this issue:
https://www.pivotaltracker.com/story/show/149407045
can't reliably replicate the issue, seems to be happening only in IE. validation timing might be at issue.  Hope this will take.

birthdate validation fixes

---

portal/static/js/gil.js

address this story:  https://www.pivotaltracker.com/story/show/149316745

fix validation of access code to ignore case

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/admin.js
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/patient_profile_create.html
portal/templates/patients_by_org.html
portal/templates/profile_macros.html

https://www.pivotaltracker.com/story/show/149439247
https://www.pivotaltracker.com/story/show/149439243
- hide ID field in patients list via config variable
- modify study ID label (i.e. IRONMAN subject ID) based on top level organization (modification is visible only for IRONMAN patient)
**NOTE**  This needs to go out in tandem with persistence file change.  see PR:  https://github.com/uwcirg/ePROMs-site-config/pull/51

hide ID field and modify study id label (IRONMAN) for Eproms

---

portal/views/tou.py

https://www.pivotaltracker.com/story/show/148703713
* added additional check to `/tou/accepted` API, to validate `tou_type` value

Check for valid tou_type value

---

portal/templates/profile_macros.html
portal/views/assessment_engine.py
portal/views/patients.py

per standup regarding of loading of profile page, first step towards improving the performance.
- removing the passage of assessment status to the template in the backend
- instead, retrieving the assessment status via api call
that seems to improve the loading time
@pbugni and @ivan-c Paul and Ivan, let me know if see any problem with these changes

get assessment status via ajax

---

portal/static/js/admin.js
portal/templates/patients_by_org.html
portal/views/patients.py

address story: https://www.pivotaltracker.com/story/show/149615045
- remove code to load assessment status in the backend and retrieve the data via ajax instead
assessment statuses on the visible rows will be retrieved first
then the rest will be retrieved via a series of ajax calls (15 each) separated by a mili-seconds 
separation  
- fix frontend sorting column issue
- add helper methods to admin tool
hope this will take.  tested in different browsers

eproms patients list performance fix

---

portal/static/js/admin.js
portal/templates/patients_by_org.html

fix blank patients list issue seen only in IE
- limit the number of ajax call (e.g. 10)
- delay updating of patient row until it is ready using bootstrap's update row method (seems to lock up the browser if there is no delay)

Patients list IE fixes

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/profile_macros.html

add some frontend fixes to safeguard against xss data insert:
- add input validation check against < and > characters (only for now) 
- based on Content Security Policy documentation, https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP, remove string from setTimeout calls.

add input validation for < & > characters, remove string from settimeout calls

---

portal/models/user.py

* modified `User.display_name()` to only apply `escape()` to non-null `name` values

Handle name=None case in display_name()

---

portal/static/js/admin.js
portal/templates/patients_by_org.html

Fixes include - 
reducing the size of each ajax request
reducing the number of rows rendered each time (e.g. render each row as the data comes back now, instead of delayed rendering)

fix patients performance issue

---

portal/templates/gil/index.html

per chat with Justin and at standup, hotfix for this release related to this story:
https://www.pivotaltracker.com/story/show/149024499
check user agent before invoking kiosk pro function
**Needed** for this release

check ipad/webkit in user agent before calling kioskpro method

---

portal/static/css/portal.css
portal/static/less/portal.less
portal/templates/patients_by_org.html

styling fix for reports column
**Needed** for this release

Patients list reports column fix

---

portal/static/js/admin.js

fading loading spinner for one time request

fade loading spinner for one time request on patients list

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/admin.js
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/patients_by_org.html

general admin js clean-up
- add  descriptive comments
- remove unused code (e.g. arrData is not used)
- remove unnecessary calls to function (e.g. remove fadeLoader call as it is already called on page load)
- add check for null values in parameters in methods

admin js cleanup

---

portal/views/portal.py

https://www.pivotaltracker.com/story/show/150063689
* split reporting data collection into separate function
* added hourly dogpile cache to new function

Cache Reporting Dashboard data

---

portal/models/i18n.py
portal/translations/messages.pot

* Fix paths in POT file to point to project URL instead of checkout-specific paths
* Add available project metadata

Fix POT file refs

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/admin.js
portal/static/js/bootstrap-table-filter-control.js
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/layout.html
portal/templates/patients_by_org.html

https://www.pivotaltracker.com/story/show/150112248
- add filtering feature to patients list
- display loading indicator for status column before it is ready for filtering, otherwise filtering won't work correctly
- fix sorting issue for consent date, was not sorted numerically
- hide ID column for EPROMS (still selectable in side menu), see story:
https://www.pivotaltracker.com/story/show/149439243

add filtering feature to patients list

---

portal/models/role.py
portal/static/js/admin.js
portal/templates/gil/base.html
portal/templates/patients_by_org.html
portal/templates/portal_wrapper.html
portal/templates/research.html
portal/views/assessment_engine.py
portal/views/portal.py

https://www.pivotaltracker.com/story/show/150112113
* added new Researcher role
* added new Research Dashboard ('/research')
* only available to those with Researcher role
* includes header/gil links to new page, for those with the role
* moved 'Export Questionnaire Data' functionality to new /research page
* moved data export population logic into admin.js

Researcher role + dashboard

---

portal/models/questionnaire.py
portal/models/questionnaire_bank.py
portal/views/assessment_engine.py
tests/test_questionnaire_bank.py

* added GET endpoints for Questionnaires (list + single) & QuestionnaireBanks (list)
* added unit tests

Questionnaire query APIs

---

.travis.yml
docker/docker-compose.yaml
portal/config.py
tox.ini

Harmonize postgres env var configuration- only use [PG* environmental variables](https://www.postgresql.org/docs/9.6/static/libpq-envars.html)

Cleanup env settings

---

portal/static/js/admin.js
portal/static/js/main.js

as per earlier conversation with Adam - remove hard-coded instruments list for each parent organization and generate it via call to API.

generate UI instruments list by org via api

---

bin/deploy.sh

* Remove partial conditional deploy logic (all steps run with each invocation now)
* Exit on first error
* Remove verbose/force options

Cleanup deploy script

---

portal/models/organization.py

Reload the org tree when an existing organization can't be found
in the lookup_table.

Fix for https://www.pivotaltracker.com/story/show/150305706

---

portal/templates/profile_macros.html
portal/views/audit.py

https://www.pivotaltracker.com/story/show/150303132
giving intervention staff access to audit table

giving audit log access to intervention staff

---

portal/static/css/eproms.css
portal/static/css/portal.css
portal/static/js/main.js
portal/static/less/eproms.less
portal/static/less/portal.less
portal/templates/profile.html

patient profile title changes, address this story: 
https://www.pivotaltracker.com/story/show/150118632
for patient profile title:
- use name if available, otherwise use email
- css fixes
- fix email saving (for no email)

profile title changes, css fixes

---

portal/models/fhir.py

* Report skipped questions as CSV rows without answer_code/answer
See [PT#149439763](https://www.pivotaltracker.com/story/show/149439763)

Report skipped questions in CSV export

---

portal/models/fhir.py

* Rename `subject_id` to `truenth_subject_id` in QNR CSV export
See [PT#149439547](https://www.pivotaltracker.com/story/show/149439547)

Rename subject_id column in CSV export

---

tests/test_intervention.py

https://www.pivotaltracker.com/story/show/150532380
* added new unit test for TrueNTH's SymptomTracker (aka self_management) AccessStrategy
* includes new Biopsy check

Test for TrueNTH ST AccessStrategy

---

portal/app.py
portal/models/app_text.py

Add logging when LR takes too long to serve requests.

Bump request-cache from 10 to 1000 seconds to work around LR delays

---

portal/templates/patient_profile_create.html
portal/templates/profile_macros.html
portal/templates/staff_profile_create.html

per standup and related to this story: https://www.pivotaltracker.com/story/show/150690136
retry and display error message if loading of clinics data failed.

Orgs loading error display

---

portal/static/js/main.js

https://www.pivotaltracker.com/story/show/150698194
needed for this release

change eproms consent date label

---

portal/templates/flask_user/emails/eproms_base_message.html

https://www.pivotaltracker.com/story/show/150718346

Adding thank you footer to eproms emails as per

---

portal/views/patients.py
portal/views/portal.py

* fixed invite link in CRV/IRONMAN invite emails to be an actual html link

Fix ePROMs invite link html

---

portal/models/fhir.py

* Rename `answer` column to `other_text` - [PT#150156866](https://www.pivotaltracker.com/story/show/150156866)
* Add `option_text` column for radio/checkbox questions [PT#150157034](https://www.pivotaltracker.com/story/show/150157034)
* Strip HTML from `option_text`

CSV Option text

---

portal/models/assessment_status.py

Small refactor to better describe function's role.

refactor most_recent_survey -> recent_qnr_status for clarity

---

portal/static/js/main.js
portal/templates/admin.html
portal/templates/patients_by_org.html
portal/templates/staff_by_org.html

* modified options to use custom filenames for Staff, Admin, and Patient list exports
* custom filename is `<table_object>List_<datetimestamp` (e.g. `StaffList_08092017150707.csv`)

Custom export filenames

---

portal/templates/layout.html

found this when testing - 
remove extra > character from layout.html

remove errand character > in layout.html

---

portal/models/reference.py
tests/test_reference.py

Correct issue found in Reference for Interventions.

---

portal/models/questionnaire_bank.py
tests/test_communication.py

As per https://www.pivotaltracker.com/story/show/134315063

ST QBs don't currently apply to metastatic patients

---

portal/app.py

Fix version generation when `portal` module installed outside of git checkout

Fix version generation

---

portal/static/js/main.js
portal/templates/flask_user/_macros.html
portal/templates/initial_queries.html
portal/templates/layout.html
portal/templates/patients_by_org.html
portal/templates/profile.html
portal/templates/profile_macros.html

fixes made on issues while testing:
initial queries page -
did a bit of clean-up
- remove timeout call to get incomplete fields, call is made on ajax callback to get as needed fields
- add required attribute to terms checkbox only if relevant items(e.g. website terms of use) are returned from as needed ajax call
profile page - 
- remove commented out code
- delayed function calls to re-paint UI elements (e.g. footer, loading divs) - to allow page to render first
- remove synchronous ajax call (i.e. populate checked orgs on call back)

initial queries & profile pages ui fixes

---

portal/templates/gil/base.html

saw this while testing - 
remove html tags that were seen in the timeout message

GIL timeout popup message fix

---

portal/templates/layout.html
portal/templates/research.html

was encountering JS error when going to /research page due to refactoring of script inclusions in the layout template
- allow additional script inclusion as in the case of /research page

js script error fix for research page

---

portal/migrations/versions/8ffec90e68a7_.py
portal/models/assessment_status.py
portal/models/questionnaire_bank.py
portal/models/recur.py
portal/views/assessment_engine.py

https://www.pivotaltracker.com/story/show/150859216
* modified `QuestionnaireBank.most_current_qb()`, `QuestionnaireBank.calculated_start()`, `Recur.active_interval_start` to properly accept/handle `as_of_date` param
* updated existing calls
* added migration to updated existing QuestionnaireResponses with `questionnaire_bank_id` and `qb_iteration` values

QNR to QB/IC association migration

---

tests/test_questionnaire_bank.py

Should fix failing test.  Errant " found in test data.

Correct typo in test data.

---

portal/models/communication_request.py
portal/tasks.py

Adding exception handling and enhanced logging in tracking down celery

---

portal/templates/profile_macros.html

per slack chat with Justin related to questionnaire responses sent by Care Plan:
questionnaire id should populate question column
answer code should populate the answer column

fix answer display for questionnaire response that doesn't have answer

---

portal/tasks.py
portal/views/portal.py

Not well tested!  Should work to find a user ready for email and send it via
`/communicate/<users_email>`

Quick attempt at API to send messages to one user.

---

portal/models/questionnaire_bank.py
portal/views/patients.py
tests/test_questionnaire_bank.py

* moved QB visit name construction code to separate function (in QB module)
* added check for `qbd.questionnaire_bank` value
* created unit tests for QB visit name, for baseline and recurring scenarios

Move visit_name to separate function, add tests

---

docker/docker-compose.yaml

* Add celery and celery beat services

Add Celery Services

---

portal/static/js/procedures.js

per slack with Justin, fixed issue found by Robert - 
display treatment after previous procedure has been deleted

fix treatment not displayed issue in procedures section

---

portal/models/communication.py
tests/test_communication.py

Fix for https://www.pivotaltracker.com/story/show/151416781

Add missing lookup functions for email template variables

---

portal/templates/profile_macros.html

fixed the comment for orgs selector, add additional text to make it more clear

fix comment for orgs selector UI

---

portal/models/communication_request.py
tests/test_communication.py

Fix for https://www.pivotaltracker.com/story/show/151459530

Only send the latest reminder if a user qualifies for multiple

---

portal/factories/celery.py

Remove SQLAlchemy session after task completes
See [celery, flask sqlalchemy: DatabaseError: (DatabaseError) SSL error: decryption failed or bad record mac](https://github.com/celery/celery/issues/3238#issuecomment-227831231)

Remove DB session after task

---

portal/views/patients.py

Found this while testing - fix styling for the button in registration invite email for eproms
**FOR THIS RELEASE**

styling fix for button in registration invite email for eproms

---

portal/views/audit.py

https://www.pivotaltracker.com/story/show/151111342
* added audits where `audit.subject_id == patient.id` to patient profile audit table

Expanding profile audit table

---

portal/config.py
portal/factories/celery.py

* Fix celery backend configuration

Configure redis backend from existing values

---

portal/models/communication.py
portal/views/patients.py
portal/views/portal.py

This looks to solve the current stg* problems - where patient/profile and invites are blocked.

Use `load_template_args` for all MailResource needs.

---

portal/config.py
portal/factories/celery.py
portal/tasks.py

See [Configuration and defaults](http://docs.celeryproject.org/en/latest/userguide/configuration.html#new-lowercase-settings)

Use standard celery config names

---

docker/Dockerfile.build

* Update `builder` (docker image for building debian packages) to use stretch
* Remove backport cruft

Cleanup deb-builder

---

docker/Dockerfile
wsgi.py

* Use debian stretch for portal docker image
* Use debian-packaged version of `wait-for-it`
* Cleanup env vars/paths

Update docker image

---

docker/docker-compose.build.yaml
docker/docker-compose.yaml
docs/source/docker.rst

* Fix process for building docker images locally (and update documentation)
* Add missing celery beat config parameters
* Increase log level of celery/beat
Todo: harmonize docker documentation for ease of use (more walk-through-like)

Fix docker build process

---

docker/Dockerfile
docker/docker-compose.yaml

* Automatically run envvar-remapping script for every docker command (move script into image)

Auto-run env var remapping

---

portal/tasks.py

* add exception handling and detailed status message to `send_queued_communications()`
* log stack trace during exception for all tasks

Improve task exception handling & logging

---

portal/models/message.py

More unicode fun - the audit message was failing on unicode in recipients

fix unicode errors in email audit

---

portal/static/js/main.js

general clean-up
-remove string from setTimeout code, use anonymous function and closure for scope instead.
-also remove unused variables

fix settimeout code to not use string in consent/orgs js code

---

bin/deploy.sh

* Allow branch to be set by environmental variable (`BRANCH`)
* Invoke as: `$ export BRANCH=release/release-name update-$VHOST`
* Remove unnecessary conditions/functions
* Switch to bourne shell (from bourne-again shell)

Pass-through branch to deployment script

---

portal/static/js/main.js
portal/templates/initial_queries_macros.html

observed these issues in firefox when testing:
- fix cursor jumping issue when selecting biopsy month
- upon page re-loading, return biopsy question radio input field to unchecked state if biopsy date is not entered.

fix ui issues with biopsy question fields in firefox

---

portal/static/js/main.js
portal/templates/profile_macros.html

add frontend error logging for failed ajax calls
- refactor code to have a common ajax call function which:
1.  will log error (via ajax call to server) if the ajax call fails.
2.  allows callback upon ajax success or failure
**Not for this release**
can be merged to the develop branch after this is reviewed.

frontend error logging changes

---

manage.py

**NB: This will merge into RC**
* Call `FLUSHDB` on configured redis DB (`REDIS_URL`) before updating database

Flush redis before updating DB

---

portal/static/js/main.js

https://www.pivotaltracker.com/n/projects/1225464/stories/150859450/comments/180740197
* modified table export filename, to only include the date (not the time)

Remove HHMMSS from table export filename

---

.travis.yml
README.rst
bin/deploy-docker.sh
docker/Dockerfile.build
docker/default.env
docker/portal.env.default
docker/remap_envvars.py
docs/source/docker.rst

* Update docker docs with deployment-specific information

Update docker docs

---

portal/models/message.py

* Fix a bug introduced in #1488

Fix accidentally deleted "sender" attribute

---

portal/models/message.py

Reverts uwcirg/true_nth_usa_portal#1496

Revert "Fix accidentally deleted "sender" attribute"

---

.travis.yml

* Do not allow build job to fail on TravisCI
* Allow UI job to fail

Do not allow build job to fail on TravisCI

---

.travis.yml

* Move envvars defined during execution to specific envvar block

Cleanup TravisCI envvars

---

.travis.yml
docker/docker-compose.yaml
docs/source/docker.rst

* Fix tagging docker images with multiple tags
* Rename env vars for clarity (prefix with `DOCKER`)
* Allow empty `DOCKER_REPOSITORY` for local builds

Fix docker image tagging

---

portal/static/js/main.js

found this issue while testing in stg.us:
- add check for all required terms item before checking checkbox for terms
- simplify the logic for finding the checkbox

fix logic related to checking terms checkbox

---

.travis.yml
bin/deploy-docker.sh
bin/docker-login.sh
bin/docker-push.sh
bin/utils.sh

* Move more TravisCI steps into script functions (metadata tagging)
* Refactor env vars to allow loose coupling
* Switch to internal names in scripts
* Remap TravisCI env vars to ones expected by scripts

TravisCI cleanup

---

.travis.yml
bin/docker-build.sh
tox.ini

* Move docker image-building into separate script
* Call aforementioned script with tox directly

Add proper job for docker image-building

---

portal/config.py
portal/factories/app.py

* Default value should appear in /settings now
* Updated value on prod to 8 hours

Move request cache duration to formal config

---

portal/static/js/admin.js
portal/static/js/bootstrap-table-filter-control.js
portal/templates/patients_by_org.html

found this issue when testing - user interaction with the filtering list (on the patient list toolbar) should reset user preference for filtering

fix filtering preference on patients list, UI only

---

portal/models/message.py
portal/views/user.py
tests/test_user.py

https://jira.movember.com/browse/TN-297
* added `as_json()` method for EmailMessages
* added GET API endpoint for messages sent to a given user (`/api/user/<user_id>/messages`)
* only accessible by those who should see the table in the UI - that is, Staff, InterventionStaff, and Admins
* added unit tests for above endpoint

TN-236 TN-297 User EmailMessages API

---

portal/gil/templates/gil/about.html

fix broken exercise and diet link in GIL About page

fix exercse and diet link in GIL about page

---

.travis.yml
tox.ini

* Generate XML coverage report after nosetest run
* Upload report to Codacy

Report coverage to codacy

---

.travis.yml
tox.ini

Reverts uwcirg/true_nth_usa_portal#1548

Revert "Report coverage to codacy"

---

portal/templates/reporting_dashboard.html

found this while testing - add filtering to usage stats table in reporting dashboard

add filtering capacity to usage table in reporting dashboard

---

portal/static/js/gil.js

address story https://jira.movember.com/browse/TN-278

TN-278 User sidebar menu should read "Exercise and Diet" instead of "Exercise Diet"

---

portal/templates/profile_macros.html

found this issue while testing - invite_email parameter was not being passed in to communications macro resulting in no invite being sent.
Code here is due for re-factoring but putting in a patch here for now.

pass invite_email parameter to new communication template macro

---

portal/static/js/admin.js

address issue found in TN-105 https://jira.movember.com/browse/TN-105
- check for undefined type (contributor field) and exclude it from being displayed in popup.

handle undefined patient report type inmodal popup in patients list

---

portal/gil/templates/gil/about.html

fi x exercis e and diet link on gil s about p age

fix exercise and diet link on about page

---

portal/eproms/templates/eproms/contact.html
portal/gil/templates/gil/contact.html

https://jira.movember.com/browse/TN-156
* minor fix to change the default contact enquiry type name from 'Other' to 'Not sure'

TN-156 Change default enquiry type name string

---

portal/models/questionnaire_bank.py
portal/tasks.py

https://jira.movember.com/browse/TN-136
* add explicit check for `user.email` (for cases when `user._email=<just a prefix>`, so `user.email=None`)
* change 'multiple QB' error logging to warning logging (so we're not spammed with emails about it)

TN-136 Minor fixes for site summary email

---

portal/static/js/admin.js
portal/templates/patients_by_org.html
portal/views/patients.py

fixes per conversation with Justin and address issues found related to this story: https://jira.movember.com/browse/TN-124
- **remove** select filter for organization column
- preserve filters based on selection(s) from filter list control
@OptimusRhine Adam, it would be nice if you can have a look and see if my changes in patients.py are okay?  I figure it is easier to get filtered rows for selected organization(s) from the server side rather than client side

orgs filtering fix in patients list

---

portal/static/js/admin.js
portal/views/patients.py

did some rounds of testing, fixed couple issues I found:
- make sure checkbox is checked before selecting child org(s) of parent org
- no need for backend to check for here below orgs as the front end is already doing it

patients list filter minor fixes

---

portal/models/user.py
portal/static/js/main.js

responding to feedback from Diana in this story:  https://jira.movember.com/browse/TN-131
- sort consent history by last updated date
- add acting actor (i.e. who modified the consent) column for clarity 
@OptimusRhine @ivan-c 
Adam and Ivan, it would be nice if you can look over my changes. I updated the user that modified the consent to **current user** to accommodate the fact that, in EPROMS, the person updating the consent is not the patient himself but the staff member(s).  I did look over the associated tests. I don't think they need to be updated with the change. But let me know if you think otherwise.

add actor column to consent history, sort consent history by last

---

portal/factories/app.py

* Move `MAIL_DEFAULT_SENDER` back to string (from tuple) config
See https://github.com/mattupstate/flask-mail/issues/61

Fix flask-mail email config

---

portal/static/js/main.js

per Diana's comment - in https://jira.movember.com/browse/TN-131
remove action column from consent history

remove action column from consent history

---

.travis.yml
tox.ini

Allow build jobs to fail until I can figure the best way to clone to an exact commit

Allow build jobs to fail

---

portal/gil/templates/gil/lived_experience_base.html

https://jira.movember.com/browse/TN-277
add "join us" button to GIL lived experience page when user has logged out -  the button was previously missing

add "join us" button to GIL LE page when user logged out

---

portal/templates/profile_macros.html

a followup to the last fix to this story:
https://jira.movember.com/browse/TN-247
- add check for top level org that does not have any child org

add check for top level org(s) without children in orgs state selector

---

docs/source/development.rst
docs/source/index.rst
docs/source/internationalization.rst
portal/models/i18n.py
tox.ini

* Push new strings with same `tox` `translations` job
* Use `nodeenv` to install frontend dependencies (thanks @achen2401 !)

Auto-push frontend strings to Smartling

---

portal/static/js/admin.js

filter orgs UI when no patient present
address jquery :visible selector issue - add check for org elements with css property of display: none so they don't get selected

orgs filter hotfix

---

portal/static/js/main.js
portal/templates/admin.html
portal/templates/patients_by_org.html
portal/templates/profile_macros.html
portal/templates/staff_profile_create.html

address story: https://jira.movember.com/browse/TN-353
- makes email an optional field for patient in profile page
- replace single quote with double quote
- remove unreferenced email macro from staff creation page

TN-353 ePROMS - Unable to delete email address from a patient profile

---

portal/tasks.py

* added `SMTPRecipientsRefused` exception error handling to site summary email task
* job no longer completely fails from just one invalid email
* job status message includes list of erroneous email addresses (if errors found)
* add audit row for user if email fails (for easier tracking from front-end)

TN-369 Handle RecipientRefused errors in site summary email

---

portal/config/gil/site_persistence_file.json
portal/gil/views.py
portal/models/app_text.py

https://jira.movember.com/browse/TN-280
* updated `Terms_ATMA()` to accept just a role param
* updated `/terms [GET]` to pass user role (if 'patient' or 'staff') when generating content from `Terms_ATMA()`
* added new AppText entries to TNUSA site persistence file for patient & staff roles

TN-280 Role-based terms for TNUSA

---

portal/models/assessment_status.py
portal/models/intervention_strategies.py

https://jira.movember.com/browse/TN-401
* added `top_organization` property to AssessmentStatus
* updated InterventionStrategy questionnaire-related verbiage
* populate variables with `AS.top_organization.name` instead of `AS.organization.name`
* remove "registry study"

TN-401 Fix registry verbiage

---

portal/static/js/main.js
portal/templates/initial_queries_macros.html
portal/templates/profile_macros.html

found this issue while testing - terms checkbox remained unchecked on page reload of website script page
- add necessary class for UI to pickup the checkbox
- remove unused code

fix website terms script checkbox issue

---

portal/static/js/procedures.js

in treatment selection - only delete other procedure(s) if the corresponding element(s) exists

add check for existence of other elements in procedure

---

portal/static/js/main.js

fix for found date-related issue in IE related to this story:  https://jira.movember.com/browse/TN-417

IE date check fix

---

tests/test_reporting.py

https://jira.movember.com/browse/TN-396
* Fixing unit test issue introduced in #1641

TN-396 Fixing reporting ostats test

---

portal/static/js/main.js

@ivan-c Ivan, this addressed https://jira.movember.com/browse/TN-220
I will need to look at TN-421 to see if that is the same story.  I will comment on the story if they are.

remove code text from questionnaire response

---

portal/config/config_persistence.py
portal/config/eproms/Coding.json
portal/config/eproms/site_persistence_file.json
portal/config/gil/Coding.json
portal/config/model_persistence.py
portal/config/site_persistence.py
portal/models/fhir.py
tests/test_model_persistence.py

Same as https://github.com/uwcirg/true_nth_usa_portal/pull/1645 - but with the RC as the merge target as intended.

Codings in site persistence

---

portal/templates/profile_macros.html

found when testing, wrong spelling of "instrument"

fix spelling error

---

portal/templates/profile_macros.html

Remove errand character

---

portal/static/js/admin.js
portal/templates/staff_by_org.html

As per request in https://jira.movember.com/browse/TN-138

Label controls "Deactivate" rather than "Delete" for staff admins.

---

portal/static/js/main.js

tn-333 fix 'NaN' display in date string in questionnaire list section

fix questionnaire list date display

---

portal/models/questionnaire_bank.py
tests/test_communication.py

Need to include as_of_date when calculating expiry and due dates as

---

portal/config/site_persistence.py
portal/models/codeable_concept.py
portal/models/coding.py
portal/models/encounter.py
portal/models/extension.py
portal/models/fhir.py
portal/models/intervention_strategies.py
portal/models/locale.py
portal/models/organization.py
portal/models/performer.py
portal/models/procedure.py
portal/models/procedure_codes.py
portal/models/user.py
portal/system_uri.py
portal/views/patients.py
tests/__init__.py
tests/test_clinical.py
tests/test_fhir.py
tests/test_model_persistence.py
tests/test_organization.py
tests/test_user.py

Also added IETF_LANGUAGE_TAG and LocaleConstants for consistent use.

Moved Coding and CodeableConcept to their own modules

---

portal/gil/templates/gil/base.html

use in ter po lation for a cc es alias cod e in fo te xt.

use interpolation for access code info text

---

portal/views/portal.py

* fixing minor issue with `dump_trace()` call in /settings POST

Fix minor issue in settings POST

---

portal/views/portal.py

Reverts uwcirg/true_nth_usa_portal#1675

Revert "Fix minor issue in settings POST"

---

portal/static/js/main.js
portal/templates/profile_macros.html

https://jira.movember.com/browse/TN-467
https://jira.movember.com/browse/TN-466
https://jira.movember.com/browse/TN-469
https://jira.movember.com/browse/TN-472
https://jira.movember.com/browse/TN-471
frontend translation text fixes:
fix ty po and terms o f  us e te xt

front end translation text fixes

---

portal/views/portal.py

Move trace imports to top of file where they belong.

---

portal/templates/initial_queries_macros.html

https://jira.movember.com/browse/TN-473
correct misunderstood change -  show terms for staff in trueNTH USA

TN-473 display terms for staff in TNUSA

---

portal/models/communication.py

Fix for https://jira.movember.com/browse/TN-434

Email reminders get dynamic lookup link `present_needed`.

---

portal/models/fhir.py
portal/views/assessment_engine.py
tests/test_assessment_status.py

Correct path w/i json questionnaire response documents for the identifier.

More bugs found and fixed

---

portal/static/js/initialQueries.js

follow up fix to story:  https://jira.movember.com/browse/TN-142
re-align next button when hiding continue to finish button

TN-140 align initial queries buttons follow-up fix

---

portal/views/patients.py
portal/views/staff.py

https://jira.movember.com/browse/TN-317
* added filter to /staff and /patients lists, to remove users with the Test role (if the `current_user()` does not have the Admin role)

TN-317 Only show Test Patients/Staff to Admins

---

portal/static/js/initialQueries.js
portal/static/js/main.js
portal/templates/profile_macros.html

more fixes for TN-442: https://jira.movember.com/browse/TN-442
re-indent text
fixed order of orgs
fixed a bug in initial queries.js (fixed the self reference)

TN-442 orgs display fixes

---

portal/models/reporting.py
tests/test_reporting.py

https://jira.movember.com/browse/TN-393
* added filter of 'Decision Support P3P' from 'interventions' reporting only (_not_ 'interventions doc' reporting)
* added more interventions reporting unit tests

TN-393 Filter DSP3p from intervention /reporting

---

portal/templates/profile_macros.html
portal/views/patients.py

Simplify url building for "Enter Manually" - several special cases no longer apply with the `/present-needed` API.
This should resolve symptom found in https://jira.movember.com/browse/TN-485

Bug fix for TN-485

---

portal/config/eproms/Coding.json
portal/config/eproms/Organization.json
portal/config/site_persistence.py
portal/models/coding.py

Add ePROMs languages

---

portal/models/user.py
portal/templates/profile_macros.html
tests/test_user.py

* change `locale_display_options()` to return locale codes and full names
* Add `DEFAULT_LOCALE` to list returned by `locale_display_options()`
* List all available organization-specific locales in locale selector

List all locales in locale selector

---

portal/config/eproms/CommunicationRequest.json
portal/migrations/versions/cea9fbdd98f9_.py
portal/models/communication_request.py

Fix for https://jira.movember.com/browse/TN-500

Correct iteration number on IRONMAN 6 month reminders.

---

portal/static/js/main.js
portal/templates/profile_macros.html

fix bugs raised by
https://jira.movember.com/browse/TN-522
https://jira.movember.com/browse/TN-514

TN-514 & TN-522

---

portal/models/intervention.py
portal/models/organization.py
portal/models/telecom.py
portal/models/user.py
portal/views/demographics.py
portal/views/intervention.py
portal/views/organization.py
tests/test_demographics.py
tests/test_intervention.py

`organization`, `demographics` and `intervention` APIs are now fully compliant with the improved PUT model.

Implementing clean PUT model for partial updates on orgs and users

---

portal/static/js/vendor.js

references to non-existent js source maps were causing 404 errors

remove references to non-existent js source maps

---

portal/models/user.py
tests/test_user.py

Remove config default locale (`DEFAULT_LOCALE`) from locale list

Remove default locale from locale list

---

portal/exercise_diet/static/js/exercise_diet.js

fix generic reference of element that caused submission to YMCA on login failure on exercise and die t p a g e.

TN-222 fix exercise diet input submit function
